import type { Dict } from '../../i18n'
import { withOrg } from '../org/strings'

const page: Dict = {
  en: {
    'teams.tree': 'Hierarchy',
    'teams.new': 'New team',
    'teams.search': 'Search teams or leads',
    'teams.none': 'There are no teams yet.',
    'teams.none.edit': 'There are no teams yet. Create the first top-level team, then add child teams to it.',
    'teams.pick': 'Select a team in the hierarchy.',
    'teams.path': 'Parent teams',
    'teams.name': 'Name',
    'teams.description': 'Description',
    'teams.email': 'Team mailbox',
    'teams.telegram': 'Team Telegram chat',
    'teams.channel.hint': 'With a mailbox or chat, backup notification goes there and to the lead instead of every member.',
    'teams.telegram.hint': 'Chat ID of a group with the Umbrella bot, for example -1001234567890.',
    'err.invalid_telegram': 'The Telegram chat ID is invalid.',
    'teams.optional': 'optional',
    'teams.parent': 'Parent team',
    'teams.parent.none': '— Top level —',
    'teams.parent.hint': 'Names are unique among teams with the same parent. Up to {n} levels.',
    'teams.lead': 'Lead',
    'teams.lead.none': '— No lead —',
    'teams.lead.of': 'Lead: {name}',
    'teams.save': 'Save',
    'teams.saved': 'Team saved.',
    'teams.discard': 'Discard',
    'teams.addChild': 'Add child team',
    'teams.delete': 'Delete',
    'teams.create': 'Create',
    'teams.create.root': 'New top-level team',
    'teams.create.child': 'New child team',
    'teams.members': 'Members',
    'teams.members.title': 'Members ({n})',
    'teams.members.add': 'Add members',
    'teams.members.addTo': 'Add members to “{team}”',
    'teams.members.confirm': 'Add to the team',
    'teams.members.from': 'also in {team}',
    'teams.members.empty': 'The team has no members. A person can be in several teams; adding keeps their other teams.',
    'teams.members.remove': 'Remove {name} from the team',
    'teams.children': 'Child teams',
    'teams.children.title': 'Child teams ({n})',
    'teams.children.empty': 'No child teams.',
    'teams.delete.title': 'Delete team',
    'teams.delete.text': 'The team “{name}” will be deleted. This cannot be undone.',
    'teams.delete.children': 'Its {n} child team(s) move up to “{parent}” together with their own child teams.',
    'teams.delete.childrenRoot': 'Its {n} child team(s) become top-level teams together with their own child teams.',
    'teams.delete.noChildren': 'It has no child teams.',
    'teams.delete.members': 'Its {n} member(s) are left without a team. Members of child teams keep their teams.',
    'teams.delete.noMembers': 'It has no members.',
    'teams.delete.services': 'Business services stop referring to it as their owner or participant.',
    'err.team_name_taken': 'A team with this name already exists under the same parent.',
    'err.team_child_conflict': 'A child team has the same name as a team under the parent it would move to. Rename one of them first.',
    'err.team_cycle': 'A team cannot be placed under itself or under one of its child teams.',
    'err.team_too_deep': 'The hierarchy cannot be deeper than 8 levels.',
    'err.invalid_team_name': 'Team name: 1–80 characters.',
    'err.unknown_parent': 'The parent team no longer exists. Reload the page.',
    'err.unknown_lead': 'The selected lead no longer exists. Reload the page.',
  },
  ru: {
    'teams.tree': 'Иерархия',
    'teams.new': 'Новая команда',
    'teams.search': 'Поиск команд или руководителей',
    'teams.none': 'Команд пока нет.',
    'teams.none.edit': 'Команд пока нет. Создайте первую команду верхнего уровня, затем добавьте в неё дочерние.',
    'teams.pick': 'Выберите команду в иерархии.',
    'teams.path': 'Родительские команды',
    'teams.name': 'Название',
    'teams.description': 'Описание',
    'teams.email': 'Почтовый ящик команды',
    'teams.telegram': 'Чат команды в Telegram',
    'teams.channel.hint': 'Если задан ящик или чат, резервное оповещение уходит туда и руководителю, а не каждому участнику.',
    'teams.telegram.hint': 'ID группового чата с ботом Umbrella, например -1001234567890.',
    'err.invalid_telegram': 'Неверный ID чата Telegram.',
    'teams.optional': 'необязательно',
    'teams.parent': 'Родительская команда',
    'teams.parent.none': '— Верхний уровень —',
    'teams.parent.hint': 'Названия уникальны среди команд с одним родителем. Не больше {n} уровней.',
    'teams.lead': 'Руководитель',
    'teams.lead.none': '— Без руководителя —',
    'teams.lead.of': 'Руководитель: {name}',
    'teams.save': 'Сохранить',
    'teams.saved': 'Команда сохранена.',
    'teams.discard': 'Отменить',
    'teams.addChild': 'Добавить дочернюю',
    'teams.delete': 'Удалить',
    'teams.create': 'Создать',
    'teams.create.root': 'Новая команда верхнего уровня',
    'teams.create.child': 'Новая дочерняя команда',
    'teams.members': 'Участники',
    'teams.members.title': 'Участники ({n})',
    'teams.members.add': 'Добавить участников',
    'teams.members.addTo': 'Добавить участников в «{team}»',
    'teams.members.confirm': 'Добавить в команду',
    'teams.members.from': 'также в {team}',
    'teams.members.empty': 'В команде нет участников. Человек может состоять в нескольких командах; добавление не убирает его из других.',
    'teams.members.remove': 'Убрать {name} из команды',
    'teams.children': 'Дочерние команды',
    'teams.children.title': 'Дочерние команды ({n})',
    'teams.children.empty': 'Дочерних команд нет.',
    'teams.delete.title': 'Удаление команды',
    'teams.delete.text': 'Команда «{name}» будет удалена. Отменить это нельзя.',
    'teams.delete.children': 'Её дочерние команды ({n}) поднимутся в «{parent}» вместе со своими дочерними.',
    'teams.delete.childrenRoot': 'Её дочерние команды ({n}) станут командами верхнего уровня вместе со своими дочерними.',
    'teams.delete.noChildren': 'Дочерних команд нет.',
    'teams.delete.members': 'Её участники ({n}) останутся без команды. Участники дочерних команд остаются в своих командах.',
    'teams.delete.noMembers': 'Участников нет.',
    'teams.delete.services': 'Бизнес-сервисы перестанут ссылаться на неё как на владельца или участника.',
    'err.team_name_taken': 'Команда с таким названием уже есть у этого родителя.',
    'err.team_child_conflict': 'У дочерней команды то же название, что у команды на уровне, куда она переместится. Сначала переименуйте одну из них.',
    'err.team_cycle': 'Команду нельзя поместить в саму себя или в её дочернюю команду.',
    'err.team_too_deep': 'Иерархия не может быть глубже 8 уровней.',
    'err.invalid_team_name': 'Название команды: от 1 до 80 символов.',
    'err.unknown_parent': 'Родительской команды больше нет. Обновите страницу.',
    'err.unknown_lead': 'Выбранного руководителя больше нет. Обновите страницу.',
  },
}

export const strings: Dict = withOrg(page)
