import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'map.search': 'Find a service or item',
    'map.view': 'Show',
    'map.view.all': 'Everything',
    'map.view.problems': 'Problems only',
    'map.cis': 'Configuration items',
    'map.refresh': 'Refresh',
    'map.updated': 'Updated {time}',
    'map.loading': 'Loading the map…',
    'map.empty': 'No business services yet. Create services in Overview → Business services and bind their configuration items.',
    'map.empty.problems': 'No problems: every service and item is healthy or not judged.',
    'map.services': 'Services',
    'map.level.critical': 'Critical',
    'map.level.warning': 'Warning',
    'map.level.ok': 'Healthy',
    'map.level.unknown': 'Unknown',
    'map.basis.title': 'What health is based on',
    'map.basis.ci': 'Item: its status (failed or offline is critical, decommissioning a warning, planned and staged unknown), the domain controller check from the NetBox sync (missing or disabled computer is a warning) and the active incidents of the item, from connectors and RED/USE rules.',
    'map.basis.service': 'Service: the worst of its items; a service it depends on that is in trouble makes it a warning. Planned and retired services, and services without judged items, are unknown.',
    'map.basis.events': 'Active incidents are taken into account: open and acknowledged ones; incidents under a maintenance window are shown but do not make the item worse.',
    'map.basis.noEvents': 'Incidents are not taken into account: {reason}',
    'map.basis.noEvents.db': 'incidents are kept only with PostgreSQL.',
    'map.close': 'Close',
    'map.kind.service': 'Business service',
    'map.field.health': 'Health',
    'map.field.criticality': 'Criticality',
    'map.field.status': 'Status',
    'map.field.owner': 'Owner team',
    'map.field.kind': 'Type',
    'map.field.ips': 'IP addresses',
    'map.field.services': 'Business services',
    'map.field.dependsOn': 'Depends on',
    'map.field.usedBy': 'Used by',
    'map.field.cis': 'Configuration items',
    'map.field.events': 'Active incidents',
    'map.field.directory': 'Domain controller',
    'map.dir.matched': 'Computer found',
    'map.dir.missing': 'No computer object',
    'map.dir.disabled': 'Computer disabled',
    'map.netbox': 'Open in NetBox',
    'map.none': 'None',
    'map.reasons.none': 'Nothing to report.',
    'map.events.counts': 'P1: {critical}, P2: {error}, P3: {warning}, P4: {low}, P5: {info}',
    'map.events.maintenance': ', under maintenance: {count}',
    'map.events.suppressed': 'maintenance',
    'map.events.status.open': 'open',
    'map.events.status.acknowledged': 'acknowledged',
    'map.reason.status_failed': 'Status is “failed”',
    'map.reason.status_offline': 'Status is “offline”',
    'map.reason.status_decommissioning': 'Being decommissioned',
    'map.reason.status_planned': 'Planned, not in service yet',
    'map.reason.status_staged': 'Staged, not in service yet',
    'map.reason.directory_missing': 'No computer object in the domain controller',
    'map.reason.directory_disabled': 'Computer object is disabled in the domain controller',
    'map.reason.events_critical': '{count} critical or error incidents active',
    'map.reason.events_warning': '{count} warning incidents active',
    'map.reason.events_maintenance': '{count} incidents under a maintenance window',
    'map.reason.ci_critical': 'Item {detail} is critical',
    'map.reason.ci_warning': 'Item {detail} has warnings',
    'map.reason.dependency_critical': 'Depends on {detail}, which is critical',
    'map.reason.dependency_warning': 'Depends on {detail}, which has warnings',
    'map.reason.service_planned': 'Service is planned',
    'map.reason.service_retired': 'Service is retired',
    'map.reason.no_cis': 'No configuration items are bound',
    'map.reason.cis_unknown': 'None of its items can be judged',
    'map.crit.critical': 'Critical',
    'map.crit.high': 'High',
    'map.crit.medium': 'Medium',
    'map.crit.low': 'Low',
    'map.svc.active': 'Active',
    'map.svc.planned': 'Planned',
    'map.svc.retired': 'Retired',
    'map.ci.device': 'Device',
    'map.ci.vm': 'Virtual machine',
    'map.ci.service': 'Service',
    'map.ci.other': 'Other',
  },
  ru: {
    'map.search': 'Найти сервис или КЕ',
    'map.view': 'Показать',
    'map.view.all': 'Всё',
    'map.view.problems': 'Только проблемы',
    'map.cis': 'КЕ',
    'map.refresh': 'Обновить',
    'map.updated': 'Обновлено {time}',
    'map.loading': 'Загрузка карты…',
    'map.empty': 'Бизнес-сервисов пока нет. Создайте сервисы в разделе Обзор → Бизнес-сервисы и привяжите к ним КЕ.',
    'map.empty.problems': 'Проблем нет: все сервисы и КЕ в порядке или их состояние неизвестно.',
    'map.services': 'Сервисы',
    'map.level.critical': 'Критично',
    'map.level.warning': 'Предупреждение',
    'map.level.ok': 'В порядке',
    'map.level.unknown': 'Неизвестно',
    'map.basis.title': 'На чём основано состояние',
    'map.basis.ci': 'КЕ: её статус (неисправна или выключена — критично, выводится из эксплуатации — предупреждение, запланирована или подготовлена — неизвестно), сверка с контроллером домена при синхронизации с NetBox (нет компьютера или он отключён — предупреждение) и активные инциденты по этой КЕ из коннекторов и правил RED/USE.',
    'map.basis.service': 'Сервис: худшее состояние его КЕ; проблемный сервис, от которого он зависит, даёт предупреждение. Запланированные и выведенные сервисы, а также сервисы без оценённых КЕ — неизвестно.',
    'map.basis.events': 'Учитываются активные инциденты: открытые и подтверждённые; инциденты в сервисном окне показаны, но не ухудшают состояние КЕ.',
    'map.basis.noEvents': 'Инциденты не учитываются: {reason}',
    'map.basis.noEvents.db': 'инциденты хранятся только при подключённом PostgreSQL.',
    'map.close': 'Закрыть',
    'map.kind.service': 'Бизнес-сервис',
    'map.field.health': 'Состояние',
    'map.field.criticality': 'Критичность',
    'map.field.status': 'Статус',
    'map.field.owner': 'Команда-владелец',
    'map.field.kind': 'Тип',
    'map.field.ips': 'IP-адреса',
    'map.field.services': 'Бизнес-сервисы',
    'map.field.dependsOn': 'Зависит от',
    'map.field.usedBy': 'Используется',
    'map.field.cis': 'КЕ',
    'map.field.events': 'Активные инциденты',
    'map.field.directory': 'Контроллер домена',
    'map.dir.matched': 'Компьютер найден',
    'map.dir.missing': 'Нет объекта компьютера',
    'map.dir.disabled': 'Компьютер отключён',
    'map.netbox': 'Открыть в NetBox',
    'map.none': 'Нет',
    'map.reasons.none': 'Замечаний нет.',
    'map.events.counts': 'P1: {critical}, P2: {error}, P3: {warning}, P4: {low}, P5: {info}',
    'map.events.maintenance': ', в сервисном окне: {count}',
    'map.events.suppressed': 'сервисное окно',
    'map.events.status.open': 'открыт',
    'map.events.status.acknowledged': 'подтверждён',
    'map.reason.status_failed': 'Статус «неисправна»',
    'map.reason.status_offline': 'Статус «выключена»',
    'map.reason.status_decommissioning': 'Выводится из эксплуатации',
    'map.reason.status_planned': 'Запланирована, ещё не работает',
    'map.reason.status_staged': 'Подготовлена, ещё не работает',
    'map.reason.directory_missing': 'Нет объекта компьютера в контроллере домена',
    'map.reason.directory_disabled': 'Объект компьютера отключён в контроллере домена',
    'map.reason.events_critical': 'Активных критичных инцидентов и ошибок: {count}',
    'map.reason.events_warning': 'Активных предупреждений: {count}',
    'map.reason.events_maintenance': 'Инцидентов в сервисном окне: {count}',
    'map.reason.ci_critical': 'КЕ {detail} в критичном состоянии',
    'map.reason.ci_warning': 'У КЕ {detail} есть предупреждения',
    'map.reason.dependency_critical': 'Зависит от {detail}, который в критичном состоянии',
    'map.reason.dependency_warning': 'Зависит от {detail}, у которого есть предупреждения',
    'map.reason.service_planned': 'Сервис запланирован',
    'map.reason.service_retired': 'Сервис выведен из эксплуатации',
    'map.reason.no_cis': 'К сервису не привязаны КЕ',
    'map.reason.cis_unknown': 'Состояние его КЕ оценить нельзя',
    'map.crit.critical': 'Критическая',
    'map.crit.high': 'Высокая',
    'map.crit.medium': 'Средняя',
    'map.crit.low': 'Низкая',
    'map.svc.active': 'Работает',
    'map.svc.planned': 'Планируется',
    'map.svc.retired': 'Выведен',
    'map.ci.device': 'Устройство',
    'map.ci.vm': 'Виртуальная машина',
    'map.ci.service': 'Сервис',
    'map.ci.other': 'Другое',
  },
}
