import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'ci.search': 'Search by name, IP address, owner, site…',
    'ci.create': 'New configuration item',
    'ci.new': 'New configuration item',
    'ci.edit.title': 'Change {name}',
    'ci.count': '{shown} of {total}',
    'ci.empty': 'There are no configuration items yet.',
    'ci.empty.edit': 'Connect NetBox in Automation → NetBox to import them, or create one by hand.',
    'ci.empty.filtered': 'Nothing matches the filters.',
    'ci.readonly': 'You can view configuration items but not change them.',
    'ci.tile.total': 'All items',
    'ci.tile.netbox': 'From NetBox',
    'ci.tile.local': 'Created here',
    'ci.tile.registered': '{n} also in NetBox',
    'ci.tile.no_owners': 'Without responsible people',
    'ci.tile.directory_missing': 'Not in the domain',
    'ci.filter.kind': 'Type',
    'ci.filter.status': 'Status',
    'ci.filter.source': 'Source',
    'ci.filter.any': 'Any',
    'ci.filter.reset': 'Reset filters',
    'ci.col.name': 'Name',
    'ci.col.kind': 'Type',
    'ci.col.status': 'Status',
    'ci.col.ips': 'IP addresses',
    'ci.col.owners': 'Responsible',
    'ci.col.source': 'Source',
    'ci.kind.device': 'Device',
    'ci.kind.vm': 'Virtual machine',
    'ci.kind.service': 'Service',
    'ci.kind.other': 'Other',
    'ci.status.active': 'Active',
    'ci.status.planned': 'Planned',
    'ci.status.staged': 'Staged',
    'ci.status.offline': 'Offline',
    'ci.status.failed': 'Failed',
    'ci.status.decommissioning': 'Decommissioning',
    'ci.status.inventory': 'Inventory',
    'ci.source.netbox': 'NetBox',
    'ci.source.local': 'Umbrella',
    'ci.source.local.registered': 'Umbrella + NetBox',
    'ci.field.name': 'Name',
    'ci.field.kind': 'Type',
    'ci.field.status': 'Status',
    'ci.field.description': 'Description',
    'ci.field.owners': 'Responsible people',
    'ci.field.owners.add': 'Add a person…',
    'ci.field.ips': 'IP addresses',
    'ci.field.ips.hint': 'Separate addresses with spaces or commas.',
    'ci.field.tags': 'Tags',
    'ci.field.register': 'Register in NetBox',
    'ci.field.register.hint': 'The item is created in NetBox with the defaults from Automation → NetBox and stays linked: changes and deletion go to NetBox too.',
    'ci.field.register.kind': 'Only devices and virtual machines can be registered in NetBox.',
    'ci.field.site': 'Site',
    'ci.field.role': 'Role',
    'ci.field.device_type': 'Device type',
    'ci.field.cluster': 'Cluster',
    'ci.field.tenant': 'Tenant',
    'ci.field.platform': 'Platform',
    'ci.field.parent': 'Runs on',
    'ci.field.ports': 'Ports',
    'ci.field.serial': 'Serial number',
    'ci.field.netbox': 'NetBox',
    'ci.field.directory': 'Domain controller',
    'ci.field.id': 'ID',
    'ci.field.created': 'Created',
    'ci.field.updated': 'Changed',
    'ci.field.synced': 'Synchronized',
    'ci.netbox.open': 'Open in NetBox',
    'ci.netbox.none': 'Not registered',
    'ci.dir.matched': 'Found',
    'ci.dir.missing': 'No computer object with this name',
    'ci.dir.disabled': 'Account disabled',
    'ci.dir.os': 'OS',
    'ci.dir.dns': 'DNS name',
    'ci.dir.logon': 'Last logon',
    'ci.dir.dn': 'Object',
    'ci.owner.deleted': 'Deleted account',
    'ci.owner.default': 'Responsible',
    'ci.imported': 'Imported from NetBox. Change it in NetBox; the next synchronization brings the changes here.',
    'ci.none': '—',
    'ci.edit': 'Change',
    'ci.delete': 'Delete',
    'ci.register': 'Register in NetBox',
    'ci.close': 'Close',
    'ci.cancel': 'Cancel',
    'ci.save': 'Save',
    'ci.delete.title': 'Delete configuration item',
    'ci.delete.text': 'Delete {name}?',
    'ci.delete.netbox': 'The object is also deleted in NetBox ({kind} #{id}).',
    'ci.delete.confirm': 'Delete',
    'err.invalid_ci_name': 'The name is empty or too long.',
    'err.invalid_ci_description': 'The description is too long.',
    'err.invalid_ci_kind': 'Unknown type.',
    'err.invalid_ci_status': 'Unknown status.',
    'err.invalid_ip': 'One of the IP addresses is invalid.',
    'err.too_many_ips': 'Too many IP addresses.',
    'err.too_many_owners': 'Too many responsible people.',
    'err.unknown_user': 'One of the people no longer exists.',
    'err.invalid_tag': 'Tags: up to 40 characters without spaces or commas.',
    'err.too_many_tags': 'Too many tags.',
    'err.ci_imported': 'The item is imported from NetBox and changes only there.',
    'err.ci_registered': 'The item is already in NetBox.',
    'err.ci_not_registrable': 'Only devices and virtual machines can be registered in NetBox.',
    'err.ci_kind_fixed': 'The type of an item registered in NetBox cannot change.',
    'err.netbox_off': 'NetBox is not connected. Connect it in Automation → NetBox.',
    'err.netbox_defaults': 'Choose the values for new objects in Automation → NetBox.',
    'err.netbox_failed': 'NetBox refused the request.',
  },
  ru: {
    'ci.search': 'Поиск по имени, IP-адресу, ответственному, площадке…',
    'ci.create': 'Новая КЕ',
    'ci.new': 'Новая конфигурационная единица',
    'ci.edit.title': 'Изменение {name}',
    'ci.count': '{shown} из {total}',
    'ci.empty': 'Конфигурационных единиц пока нет.',
    'ci.empty.edit': 'Подключите NetBox в разделе Автоматизация → NetBox, чтобы загрузить их, или создайте КЕ вручную.',
    'ci.empty.filtered': 'Под фильтры ничего не подходит.',
    'ci.readonly': 'Вы можете просматривать КЕ, но не изменять их.',
    'ci.tile.total': 'Всего КЕ',
    'ci.tile.netbox': 'Из NetBox',
    'ci.tile.local': 'Созданы здесь',
    'ci.tile.registered': 'из них в NetBox: {n}',
    'ci.tile.no_owners': 'Без ответственных',
    'ci.tile.directory_missing': 'Нет в домене',
    'ci.filter.kind': 'Тип',
    'ci.filter.status': 'Статус',
    'ci.filter.source': 'Источник',
    'ci.filter.any': 'Любой',
    'ci.filter.reset': 'Сбросить фильтры',
    'ci.col.name': 'Имя',
    'ci.col.kind': 'Тип',
    'ci.col.status': 'Статус',
    'ci.col.ips': 'IP-адреса',
    'ci.col.owners': 'Ответственные',
    'ci.col.source': 'Источник',
    'ci.kind.device': 'Устройство',
    'ci.kind.vm': 'Виртуальная машина',
    'ci.kind.service': 'Сервис',
    'ci.kind.other': 'Другое',
    'ci.status.active': 'Работает',
    'ci.status.planned': 'Запланирована',
    'ci.status.staged': 'Подготовлена',
    'ci.status.offline': 'Выключена',
    'ci.status.failed': 'Неисправна',
    'ci.status.decommissioning': 'Выводится',
    'ci.status.inventory': 'На складе',
    'ci.source.netbox': 'NetBox',
    'ci.source.local': 'Umbrella',
    'ci.source.local.registered': 'Umbrella + NetBox',
    'ci.field.name': 'Имя',
    'ci.field.kind': 'Тип',
    'ci.field.status': 'Статус',
    'ci.field.description': 'Описание',
    'ci.field.owners': 'Ответственные',
    'ci.field.owners.add': 'Добавить человека…',
    'ci.field.ips': 'IP-адреса',
    'ci.field.ips.hint': 'Адреса через пробел или запятую.',
    'ci.field.tags': 'Метки',
    'ci.field.register': 'Зарегистрировать в NetBox',
    'ci.field.register.hint':
      'КЕ создаётся в NetBox со значениями из раздела Автоматизация → NetBox и остаётся связанной: изменения и удаление тоже уходят в NetBox.',
    'ci.field.register.kind': 'В NetBox регистрируются только устройства и виртуальные машины.',
    'ci.field.site': 'Площадка',
    'ci.field.role': 'Роль',
    'ci.field.device_type': 'Тип устройства',
    'ci.field.cluster': 'Кластер',
    'ci.field.tenant': 'Арендатор',
    'ci.field.platform': 'Платформа',
    'ci.field.parent': 'Работает на',
    'ci.field.ports': 'Порты',
    'ci.field.serial': 'Серийный номер',
    'ci.field.netbox': 'NetBox',
    'ci.field.directory': 'Контроллер домена',
    'ci.field.id': 'ID',
    'ci.field.created': 'Создана',
    'ci.field.updated': 'Изменена',
    'ci.field.synced': 'Синхронизирована',
    'ci.netbox.open': 'Открыть в NetBox',
    'ci.netbox.none': 'Не зарегистрирована',
    'ci.dir.matched': 'Найден',
    'ci.dir.missing': 'Компьютера с таким именем нет',
    'ci.dir.disabled': 'Учётная запись отключена',
    'ci.dir.os': 'ОС',
    'ci.dir.dns': 'DNS-имя',
    'ci.dir.logon': 'Последний вход',
    'ci.dir.dn': 'Объект',
    'ci.owner.deleted': 'Удалённая учётная запись',
    'ci.owner.default': 'Ответственный',
    'ci.imported': 'Загружена из NetBox. Изменяйте её в NetBox: следующая синхронизация принесёт изменения сюда.',
    'ci.none': '—',
    'ci.edit': 'Изменить',
    'ci.delete': 'Удалить',
    'ci.register': 'Зарегистрировать в NetBox',
    'ci.close': 'Закрыть',
    'ci.cancel': 'Отмена',
    'ci.save': 'Сохранить',
    'ci.delete.title': 'Удаление КЕ',
    'ci.delete.text': 'Удалить {name}?',
    'ci.delete.netbox': 'Объект будет удалён и в NetBox ({kind} #{id}).',
    'ci.delete.confirm': 'Удалить',
    'err.invalid_ci_name': 'Имя пустое или слишком длинное.',
    'err.invalid_ci_description': 'Слишком длинное описание.',
    'err.invalid_ci_kind': 'Неизвестный тип.',
    'err.invalid_ci_status': 'Неизвестный статус.',
    'err.invalid_ip': 'Один из IP-адресов некорректен.',
    'err.too_many_ips': 'Слишком много IP-адресов.',
    'err.too_many_owners': 'Слишком много ответственных.',
    'err.unknown_user': 'Одного из людей больше нет.',
    'err.invalid_tag': 'Метки: до 40 символов без пробелов и запятых.',
    'err.too_many_tags': 'Слишком много меток.',
    'err.ci_imported': 'КЕ загружена из NetBox и изменяется только там.',
    'err.ci_registered': 'КЕ уже есть в NetBox.',
    'err.ci_not_registrable': 'В NetBox регистрируются только устройства и виртуальные машины.',
    'err.ci_kind_fixed': 'Тип КЕ, зарегистрированной в NetBox, изменить нельзя.',
    'err.netbox_off': 'NetBox не подключён. Подключите его в разделе Автоматизация → NetBox.',
    'err.netbox_defaults': 'Выберите значения для новых объектов в разделе Автоматизация → NetBox.',
    'err.netbox_failed': 'NetBox отклонил запрос.',
  },
}
