import type { Dict } from '../i18n'

export const navStrings: Dict = {
  en: {
    'nav.label': 'Sections',
    'group.automation': 'Automation',
    'group.org': 'Organization',
    'group.settings': 'Settings',
    'page.status': 'System status',
    'page.connectors': 'Connectors',
    'page.credentials': 'Credentials',
    'page.credentials.subtitle': 'Tokens, passwords and keys that connectors use to check incoming requests. Secrets are stored in OpenBao and never shown again.',
    'page.users': 'Users',
    'page.users.subtitle': 'Local and directory accounts, their roles, teams and access.',
    'page.roles': 'Roles',
    'page.roles.subtitle': 'Access to pages and functions. Every user has exactly one role.',
    'page.teams': 'Teams',
    'page.teams.subtitle': 'Team hierarchy and membership.',
    'page.services': 'Business services',
    'page.services.subtitle': 'Business services and the teams responsible for them.',
    'page.settings.postgres': 'PostgreSQL',
    'page.settings.openbao': 'OpenBao',
    'page.settings.ldap': 'LDAP / AD / Entra ID',
    'page.settings.policy': 'Password policy',
    'page.settings.subtitle': 'Connections and security of this Umbrella installation.',
  },
  ru: {
    'nav.label': 'Разделы',
    'group.automation': 'Автоматизация',
    'group.org': 'Организация',
    'group.settings': 'Настройки',
    'page.status': 'Состояние системы',
    'page.connectors': 'Коннекторы',
    'page.credentials': 'Учётные данные',
    'page.credentials.subtitle': 'Токены, пароли и ключи, которыми коннекторы проверяют входящие запросы. Секреты хранятся в OpenBao и больше не показываются.',
    'page.users': 'Пользователи',
    'page.users.subtitle': 'Локальные учётные записи и учётные записи каталога, их роли, команды и доступ.',
    'page.roles': 'Роли',
    'page.roles.subtitle': 'Доступ к страницам и функциям. У каждого пользователя ровно одна роль.',
    'page.teams': 'Команды',
    'page.teams.subtitle': 'Иерархия команд и их участники.',
    'page.services': 'Бизнес-сервисы',
    'page.services.subtitle': 'Бизнес-сервисы и ответственные за них команды.',
    'page.settings.postgres': 'PostgreSQL',
    'page.settings.openbao': 'OpenBao',
    'page.settings.ldap': 'LDAP / AD / Entra ID',
    'page.settings.policy': 'Парольная политика',
    'page.settings.subtitle': 'Подключения и безопасность этой установки Umbrella.',
  },
}
