import type { Dict } from '../i18n'

export const navStrings: Dict = {
  en: {
    'nav.label': 'Sections',
    'group.overview': 'Overview',
    'group.automation': 'Automation',
    'group.org': 'Organization',
    'group.settings': 'Settings',
    'page.status': 'System status',
    'page.incidents': 'Incidents',
    'page.incidents.subtitle': 'Alerts folded by configuration item and signal, routed to the owning team and sent to PagerDuty.',
    'page.connectors': 'Connectors',
    'page.credentials': 'Credentials',
    'page.credentials.subtitle': 'Tokens, passwords and keys that connectors use to check incoming requests. Secrets are stored in OpenBao and never shown again.',
    'page.cis': 'Configuration items',
    'page.cis.subtitle': 'Devices, virtual machines and services monitoring refers to, with the people responsible for them.',
    'page.netbox': 'NetBox',
    'page.netbox.subtitle': 'Import of configuration items and responsible people from NetBox, registration of new items there and matching with the domain controller.',
    'page.users': 'Users',
    'page.users.subtitle': 'Local and directory accounts, their roles, teams and access.',
    'page.roles': 'Roles',
    'page.roles.subtitle': 'Access to pages and functions. Every user has exactly one role.',
    'page.teams': 'Teams',
    'page.teams.subtitle': 'Team hierarchy and membership.',
    'page.services': 'Business services',
    'page.services.subtitle': 'Business services, the teams responsible for them, the configuration items they run on and their link to NetBox.',
    'page.cmdb': 'CMDB map',
    'page.cmdb.subtitle': 'Business services, their dependencies and configuration items with the health of each.',
    'page.settings.postgres': 'PostgreSQL',
    'page.settings.openbao': 'OpenBao',
    'page.settings.ldap': 'LDAP / AD / Entra ID',
    'page.settings.policy': 'Password policy',
    'page.settings.alerting': 'Alerting',
    'page.maintenance': 'Maintenance windows',
    'page.maintenance.subtitle': 'Planned works: incidents of the covered services and CIs are kept but not sent to PagerDuty or by backup notification.',
    'page.settings.alerting.subtitle': 'PagerDuty, backup notification by mail and Telegram.',
    'page.settings.subtitle': 'Connections and security of this Umbrella installation.',
  },
  ru: {
    'nav.label': 'Разделы',
    'group.overview': 'Обзор',
    'group.automation': 'Автоматизация',
    'group.org': 'Организация',
    'group.settings': 'Настройки',
    'page.status': 'Состояние системы',
    'page.incidents': 'Инциденты',
    'page.incidents.subtitle': 'Тревоги, схлопнутые по КЕ и сигналу, направленные команде-владельцу и отправленные в PagerDuty.',
    'page.connectors': 'Коннекторы',
    'page.credentials': 'Учётные данные',
    'page.credentials.subtitle': 'Токены, пароли и ключи, которыми коннекторы проверяют входящие запросы. Секреты хранятся в OpenBao и больше не показываются.',
    'page.cis': 'Каталог КЕ',
    'page.cis.subtitle': 'Устройства, виртуальные машины и сервисы, к которым привязан мониторинг, и ответственные за них.',
    'page.netbox': 'NetBox',
    'page.netbox.subtitle': 'Загрузка КЕ и ответственных из NetBox, регистрация новых КЕ в NetBox и сверка с контроллером домена.',
    'page.users': 'Пользователи',
    'page.users.subtitle': 'Локальные учётные записи и учётные записи каталога, их роли, команды и доступ.',
    'page.roles': 'Роли',
    'page.roles.subtitle': 'Доступ к страницам и функциям. У каждого пользователя ровно одна роль.',
    'page.teams': 'Команды',
    'page.teams.subtitle': 'Иерархия команд и их участники.',
    'page.services': 'Бизнес-сервисы',
    'page.services.subtitle': 'Бизнес-сервисы, ответственные команды, КЕ, на которых работают сервисы, и связь с NetBox.',
    'page.cmdb': 'Карта CMDB',
    'page.cmdb.subtitle': 'Бизнес-сервисы, их зависимости и КЕ с состоянием каждого элемента.',
    'page.settings.postgres': 'PostgreSQL',
    'page.settings.openbao': 'OpenBao',
    'page.settings.ldap': 'LDAP / AD / Entra ID',
    'page.settings.policy': 'Парольная политика',
    'page.settings.alerting': 'Оповещения',
    'page.maintenance': 'Сервисные окна',
    'page.maintenance.subtitle': 'Плановые работы: инциденты затронутых сервисов и КЕ сохраняются, но не уходят в PagerDuty и резервное оповещение.',
    'page.settings.alerting.subtitle': 'PagerDuty и резервное оповещение по почте и в Telegram.',
    'page.settings.subtitle': 'Подключения и безопасность этой установки Umbrella.',
  },
}
