import type { Dict } from '../i18n'

export const statusStrings: Dict = {
  en: {
    'status.subtitle': 'Version, runtime, connections, intake and recent errors of this Umbrella installation',
    'status.checkedAt': 'Checked at {at}',
    'status.allOk': 'All systems are working',
    'status.problems': 'Problems found: {n}',
    'state.warn': 'Attention',
    'state.ready': 'Running',
    'card.app': 'Application',
    'card.runtime': 'Process and memory',
    'card.entra': 'Microsoft Entra ID',
    'card.intake': 'Connector intake',
    'card.inventory': 'Objects',
    'card.logs': 'Recent warnings and errors',
    'field.commit': 'Commit',
    'field.commit.modified': 'with local changes',
    'field.builtAt': 'Built at',
    'field.go': 'Go',
    'field.platform': 'Platform',
    'field.startedAt': 'Started at',
    'field.uptime': 'Uptime',
    'field.host': 'Host',
    'field.pid': 'Process ID',
    'field.cpus': 'CPUs (GOMAXPROCS)',
    'field.goroutines': 'Goroutines',
    'field.memAlloc': 'Heap in use',
    'field.memSys': 'Memory from the OS',
    'field.gc': 'Garbage collections',
    'field.gc.value': '{n}, total pause {ms} ms',
    'field.lastGC': 'Last collection',
    'field.latency': 'Response time',
    'field.namespace': 'Namespace',
    'field.cluster': 'Cluster',
    'field.sealed': 'Sealed',
    'field.renewable': 'Token renewable',
    'field.lastError': 'Last error',
    'field.dbUser': 'User',
    'field.dbSize': 'Database size',
    'field.pgStarted': 'Server started',
    'field.connections': 'Server connections',
    'field.connections.value': '{n} of {max}',
    'field.ssl': 'SSL',
    'field.pool': 'Umbrella pool',
    'field.pool.value': '{total} of {max} open, {acquired} busy, {idle} idle',
    'field.poolWait': 'Waits for a free connection',
    'field.poolWait.value': '{waits} of {acquires}, average {ms} ms',
    'field.persist': 'Saving the configuration',
    'field.persist.pending': 'Changes are waiting to be saved',
    'field.persist.ok': 'Saved',
    'field.cloud': 'Cloud',
    'field.tenant': 'Tenant',
    'field.clientId': 'Application (client) ID',
    'field.redirect': 'Redirect URI',
    'field.issuer': 'Issuer',
    'field.secret': 'Client secret',
    'field.secret.ok': 'Valid',
    'field.secret.bad': 'Not accepted',
    'field.userGroup': 'Allowed users group',
    'entra.off': 'Sign-in with Microsoft Entra ID is not configured.',
    'field.connectors': 'Connectors',
    'field.connectors.value': '{total} (published {published}, with errors {invalid})',
    'field.queue': 'Waiting in the queue',
    'field.oldest': 'Oldest waiting since',
    'field.openFailures': 'Unresolved failures',
    'field.received': 'Received in 24 h',
    'field.received.value': '{received}, rejected {rejected}, failed {failed}, duplicates {duplicates}',
    'field.events': 'Events in 24 h',
    'field.procLatency': 'Processing time',
    'field.procLatency.value': 'average {avg} ms, maximum {max} ms',
    'field.lastReceived': 'Last request',
    'intake.notReady': 'The intake is not running: the PostgreSQL tables are not ready yet.',
    'field.disabledUsers': 'Disabled users',
    'field.sessions': 'Open sessions',
    'field.sessions.value': '{sessions} ({users} users)',
    'field.roles': 'Roles',
    'field.teams': 'Teams',
    'field.services': 'Business services',
    'field.credentials': 'Connector credentials',
    'field.audit': 'Audit log entries',
    'logs.counts': 'Since the start: {errors} errors, {warnings} warnings. The latest {n} are kept in memory.',
    'logs.none': 'No warnings or errors since the start.',
    'logs.level.error': 'Error',
    'logs.level.warn': 'Warning',
    yes: 'Yes',
    no: 'No',
    'unit.d': 'd',
    'unit.h': 'h',
    'unit.min': 'min',
    'unit.s': 's',
    'unit.ms': 'ms',
    'cloud.global': 'Global',
    'cloud.usgov': 'US Government',
    'cloud.china': 'China (21Vianet)',
  },
  ru: {
    'status.subtitle': 'Версия, среда выполнения, подключения, приём данных и последние ошибки этой установки Umbrella',
    'status.checkedAt': 'Проверено {at}',
    'status.allOk': 'Все системы работают',
    'status.problems': 'Найдено проблем: {n}',
    'state.warn': 'Внимание',
    'state.ready': 'Работает',
    'card.app': 'Приложение',
    'card.runtime': 'Процесс и память',
    'card.entra': 'Microsoft Entra ID',
    'card.intake': 'Приём данных коннекторами',
    'card.inventory': 'Объекты',
    'card.logs': 'Последние предупреждения и ошибки',
    'field.commit': 'Коммит',
    'field.commit.modified': 'с локальными изменениями',
    'field.builtAt': 'Дата сборки',
    'field.go': 'Go',
    'field.platform': 'Платформа',
    'field.startedAt': 'Запущено',
    'field.uptime': 'Время работы',
    'field.host': 'Хост',
    'field.pid': 'ID процесса',
    'field.cpus': 'Процессоры (GOMAXPROCS)',
    'field.goroutines': 'Горутины',
    'field.memAlloc': 'Используемая куча',
    'field.memSys': 'Память от ОС',
    'field.gc': 'Сборки мусора',
    'field.gc.value': '{n}, суммарная пауза {ms} мс',
    'field.lastGC': 'Последняя сборка',
    'field.latency': 'Время ответа',
    'field.namespace': 'Пространство имён',
    'field.cluster': 'Кластер',
    'field.sealed': 'Запечатан',
    'field.renewable': 'Продление токена',
    'field.lastError': 'Последняя ошибка',
    'field.dbUser': 'Пользователь',
    'field.dbSize': 'Размер базы',
    'field.pgStarted': 'Сервер запущен',
    'field.connections': 'Подключения к серверу',
    'field.connections.value': '{n} из {max}',
    'field.ssl': 'SSL',
    'field.pool': 'Пул Umbrella',
    'field.pool.value': 'открыто {total} из {max}, занято {acquired}, свободно {idle}',
    'field.poolWait': 'Ожидания свободного подключения',
    'field.poolWait.value': '{waits} из {acquires}, в среднем {ms} мс',
    'field.persist': 'Сохранение конфигурации',
    'field.persist.pending': 'Изменения ждут сохранения',
    'field.persist.ok': 'Сохранено',
    'field.cloud': 'Облако',
    'field.tenant': 'Клиент (tenant)',
    'field.clientId': 'ID приложения (client ID)',
    'field.redirect': 'URI перенаправления',
    'field.issuer': 'Издатель',
    'field.secret': 'Секрет клиента',
    'field.secret.ok': 'Действителен',
    'field.secret.bad': 'Не принят',
    'field.userGroup': 'Группа разрешённых пользователей',
    'entra.off': 'Вход через Microsoft Entra ID не настроен.',
    'field.connectors': 'Коннекторы',
    'field.connectors.value': '{total} (опубликовано {published}, с ошибками {invalid})',
    'field.queue': 'Ожидают в очереди',
    'field.oldest': 'Самый старый ожидает с',
    'field.openFailures': 'Неразобранные сбои',
    'field.received': 'Получено за 24 ч',
    'field.received.value': '{received}, отклонено {rejected}, со сбоем {failed}, повторов {duplicates}',
    'field.events': 'Событий за 24 ч',
    'field.procLatency': 'Время обработки',
    'field.procLatency.value': 'в среднем {avg} мс, максимум {max} мс',
    'field.lastReceived': 'Последний запрос',
    'intake.notReady': 'Приём данных не запущен: таблицы в PostgreSQL ещё не готовы.',
    'field.disabledUsers': 'Отключённые пользователи',
    'field.sessions': 'Открытые сеансы',
    'field.sessions.value': '{sessions} (пользователей: {users})',
    'field.roles': 'Роли',
    'field.teams': 'Команды',
    'field.services': 'Бизнес-сервисы',
    'field.credentials': 'Учётные данные коннекторов',
    'field.audit': 'Записей в журнале аудита',
    'logs.counts': 'С момента запуска: ошибок {errors}, предупреждений {warnings}. В памяти хранятся последние {n}.',
    'logs.none': 'С момента запуска предупреждений и ошибок не было.',
    'logs.level.error': 'Ошибка',
    'logs.level.warn': 'Предупреждение',
    yes: 'Да',
    no: 'Нет',
    'unit.d': 'д',
    'unit.h': 'ч',
    'unit.min': 'мин',
    'unit.s': 'с',
    'unit.ms': 'мс',
    'cloud.global': 'Глобальное',
    'cloud.usgov': 'US Government',
    'cloud.china': 'Китай (21Vianet)',
  },
}
