import type { Dict } from '../i18n'
import { policyStrings } from '../policy'

const base: Dict = {
  en: {
    'nav.label': 'Sections',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'menu.open': 'User menu',
    'menu.language': 'Language',
    'menu.theme': 'Theme',
    'profile.personal': 'Personal data',
    'profile.password': 'Password',
    'profile.account': 'Account',
    'prefs.tz.saved': 'Time zone saved.',
    'prefs.tg.title': 'Telegram',
    'prefs.tg.field': 'Telegram chat ID',
    'prefs.tg.hint': 'Backup notification about incidents of your team comes here when PagerDuty does not take them. Press «Link Telegram» to link it through the Umbrella bot, or enter your numeric ID by hand.',
    'prefs.tg.saved': 'Telegram chat saved.',
    'prefs.tg.link': 'Link Telegram',
    'prefs.tg.link.opened': 'A chat with the bot opened in Telegram: press Start there. The link works for 15 minutes.',
    'prefs.tg.link.manual': 'If Telegram did not open:',
    'err.bot_off': 'The Telegram bot is off: an administrator turns it on in Settings → Alerting.',
    'err.invalid_telegram': 'A chat ID is a number (negative for groups) or @channel_name.',
    'signin.title': 'Sign in',
    'field.last_name': 'Last name',
    'field.first_name': 'First name',
    'field.middle_name': 'Middle name',
    'field.title': 'Job title',
    'field.department': 'Department',
    'field.manager': 'Manager',
    'field.passwordPolicy': 'Password policy',
    optional: 'optional',
    'prefs.saved': 'Profile saved.',
    'prefs.directory': 'Profile data comes from the directory (LDAP / AD) and updates at every sign-in.',
    'prefs.avatar.upload': 'Upload photo',
    'prefs.avatar.remove': 'Remove',
    'prefs.avatar.saved': 'Photo updated.',
    'prefs.avatar.own': 'Your uploaded photo. PNG, JPEG, GIF or WebP up to 5 MB.',
    'prefs.avatar.ldap': 'The photo comes from the directory. An uploaded photo replaces it.',
    'prefs.avatar.gravatar': 'Until you upload a photo, Gravatar provides one by your e-mail.',
    'prefs.password.current': 'Current password',
    'prefs.password.new': 'New password',
    'prefs.password.confirm': 'Repeat the new password',
    'prefs.password.change': 'Change password',
    'prefs.password.changed': 'Password changed. Other sessions are signed out.',
    'field.timezone': 'Time zone',
    'prefs.default': 'Default',
    'prefs.tz.hint': 'Dates and times in Umbrella are shown in this zone.',
    'defaults.edit': 'Change',
    'defaults.text': 'Users see these settings until they choose their own.',
    save: 'Save',
    cancel: 'Cancel',
    'signin.username': 'Username',
    'signin.password': 'Password',
    'signin.submit': 'Sign in',
    'signin.ldap': 'Use your corporate (LDAP / AD) account or a local Umbrella account.',
    'signin.entra': 'Sign in with Microsoft',
    'signin.or': 'or',
    signout: 'Sign out',
    'crash.title': 'This page failed to open',
    'crash.text': 'The rest of Umbrella keeps working: pick another section or reload the page. If it happens again, send the message below to the administrator.',
    'crash.reload': 'Reload page',
    'role.admin': 'Administrator',
    'role.user': 'User',
    'source.local': 'Local account',
    'source.ldap': 'LDAP / AD',
    'source.entra': 'Microsoft Entra ID',
    'state.ok': 'Connected',
    'state.error': 'Problem',
    'state.off': 'Off',
    'status.title': 'System status',
    'status.subtitle': 'Connections configured by the setup wizard',
    'status.refresh': 'Refresh',
    'settings.title': 'Defaults',
    'ldap.off': 'Directory sign-in is not configured. Only local accounts can sign in.',
    'field.address': 'Address',
    'field.version': 'Version',
    'field.mount': 'KV mount',
    'field.auth': 'Sign-in method',
    'field.auth.token': 'Token',
    'field.policies': 'Policies',
    'field.tokenExpires': 'Token expires',
    'field.database': 'Database',
    'field.savedAt': 'Last saved',
    'field.directory': 'Directory',
    'field.tls': 'Encryption',
    'field.tls.none': 'None',
    'field.baseDN': 'Search base',
    'field.adminGroup': 'Administrators group',
    'field.theme': 'Theme',
    'field.locale': 'Language',
    'field.setupAt': 'Set up at',
    'field.setupBy': 'Set up by',
    'field.users': 'Users',
    'field.users.value': '{total} (local {local}, LDAP / AD {ldap}, Entra ID {entra})',
    'field.appVersion': 'Umbrella version',
    'field.email': 'E-mail',
    'field.source': 'Account type',
    'field.role': 'Role',
    'field.lastLogin': 'Last sign-in',
    'profile.subtitle': 'Your Umbrella account',
    'profile.noAccess.title': 'No access yet',
    'profile.noAccess.text': 'Your account exists, but its role gives no access to pages. Ask an administrator to give you a role or add you to a directory group.',
    'profile.noAccess.admins': 'Administrators:',
    'profile.noAccess.none': 'No active administrator is known. Ask the person who installed Umbrella.',
    'expired.title': 'Set a new password',
    'expired.text': 'The password of {user} has expired under the password policy. Choose a new one to continue.',
    'expiry.title': 'Your password expires in {n} days ({date})',
    'expiry.text': 'Change it in advance to keep signing in without interruption.',
    'expiry.change': 'Change password',
    'err.password_expired': 'Your password has expired. Set a new one to continue.',
    'err.ldap_bind_password_required': 'Enter the service account password.',
    'err.no_local_admin': 'There is no active local administrator, so directory sign-in cannot be turned off.',
  },
  ru: {
    'nav.label': 'Разделы',
    'nav.profile': 'Профиль',
    'nav.settings': 'Настройки',
    'menu.open': 'Меню пользователя',
    'menu.language': 'Язык',
    'menu.theme': 'Тема',
    'profile.personal': 'Личные данные',
    'profile.password': 'Пароль',
    'profile.account': 'Учётная запись',
    'prefs.tz.saved': 'Часовой пояс сохранён.',
    'prefs.tg.title': 'Telegram',
    'prefs.tg.field': 'ID чата в Telegram',
    'prefs.tg.hint': 'Сюда приходит резервное оповещение об инцидентах вашей команды, если PagerDuty их не принял. Нажмите «Привязать Telegram», чтобы привязать через бота Umbrella, или введите свой числовой ID вручную.',
    'prefs.tg.saved': 'Чат Telegram сохранён.',
    'prefs.tg.link': 'Привязать Telegram',
    'prefs.tg.link.opened': 'В Telegram открылся чат с ботом: нажмите там «Запустить». Ссылка действует 15 минут.',
    'prefs.tg.link.manual': 'Если Telegram не открылся:',
    'err.bot_off': 'Telegram-бот выключен: администратор включает его в Настройки → Оповещения.',
    'err.invalid_telegram': 'ID чата — число (отрицательное для групп) или @имя_канала.',
    'signin.title': 'Вход',
    'field.last_name': 'Фамилия',
    'field.first_name': 'Имя',
    'field.middle_name': 'Отчество',
    'field.title': 'Должность',
    'field.department': 'Отдел',
    'field.manager': 'Руководитель',
    'field.passwordPolicy': 'Парольная политика',
    optional: 'необязательно',
    'prefs.saved': 'Профиль сохранён.',
    'prefs.directory': 'Данные профиля приходят из каталога (LDAP / AD) и обновляются при каждом входе.',
    'prefs.avatar.upload': 'Загрузить фото',
    'prefs.avatar.remove': 'Удалить',
    'prefs.avatar.saved': 'Фото обновлено.',
    'prefs.avatar.own': 'Ваше фото. PNG, JPEG, GIF или WebP до 5 МБ.',
    'prefs.avatar.ldap': 'Фото взято из каталога. Загруженное фото его заменит.',
    'prefs.avatar.gravatar': 'Пока фото не загружено, его подбирает Gravatar по вашей почте.',
    'prefs.password.current': 'Текущий пароль',
    'prefs.password.new': 'Новый пароль',
    'prefs.password.confirm': 'Повторите новый пароль',
    'prefs.password.change': 'Сменить пароль',
    'prefs.password.changed': 'Пароль изменён. Остальные сеансы завершены.',
    'field.timezone': 'Часовой пояс',
    'prefs.default': 'По умолчанию',
    'prefs.tz.hint': 'Даты и время в Umbrella показываются в этом поясе.',
    'defaults.edit': 'Изменить',
    'defaults.text': 'Пользователи видят эти настройки, пока не выберут свои.',
    save: 'Сохранить',
    cancel: 'Отмена',
    'signin.username': 'Логин',
    'signin.password': 'Пароль',
    'signin.submit': 'Войти',
    'signin.ldap': 'Используйте корпоративную учётную запись (LDAP / AD) или локальную учётную запись Umbrella.',
    'signin.entra': 'Войти через Microsoft',
    'signin.or': 'или',
    signout: 'Выйти',
    'crash.title': 'Не удалось открыть страницу',
    'crash.text': 'Остальные разделы Umbrella работают: выберите другой раздел или перезагрузите страницу. Если ошибка повторяется, передайте сообщение ниже администратору.',
    'crash.reload': 'Перезагрузить страницу',
    'role.admin': 'Администратор',
    'role.user': 'Пользователь',
    'source.local': 'Локальная учётная запись',
    'source.ldap': 'LDAP / AD',
    'source.entra': 'Microsoft Entra ID',
    'state.ok': 'Подключено',
    'state.error': 'Проблема',
    'state.off': 'Отключено',
    'status.title': 'Состояние системы',
    'status.subtitle': 'Подключения, настроенные мастером',
    'status.refresh': 'Обновить',
    'settings.title': 'Настройки по умолчанию',
    'ldap.off': 'Вход через каталог не настроен. Войти можно только локальными учётными записями.',
    'field.address': 'Адрес',
    'field.version': 'Версия',
    'field.mount': 'Хранилище KV',
    'field.auth': 'Способ входа',
    'field.auth.token': 'Токен',
    'field.policies': 'Политики',
    'field.tokenExpires': 'Токен действует до',
    'field.database': 'База данных',
    'field.savedAt': 'Последнее сохранение',
    'field.directory': 'Каталог',
    'field.tls': 'Шифрование',
    'field.tls.none': 'Нет',
    'field.baseDN': 'База поиска',
    'field.adminGroup': 'Группа администраторов',
    'field.theme': 'Тема',
    'field.locale': 'Язык',
    'field.setupAt': 'Настроено',
    'field.setupBy': 'Кем настроено',
    'field.users': 'Пользователи',
    'field.users.value': '{total} (локальных {local}, LDAP / AD {ldap}, Entra ID {entra})',
    'field.appVersion': 'Версия Umbrella',
    'field.email': 'Почта',
    'field.source': 'Тип учётной записи',
    'field.role': 'Роль',
    'field.lastLogin': 'Последний вход',
    'profile.subtitle': 'Ваша учётная запись Umbrella',
    'profile.noAccess.title': 'Доступа пока нет',
    'profile.noAccess.text': 'Учётная запись создана, но её роль не открывает ни одной страницы. Попросите администратора выдать роль или добавить вас в группу каталога.',
    'profile.noAccess.admins': 'Администраторы:',
    'profile.noAccess.none': 'Активных администраторов нет. Обратитесь к тому, кто устанавливал Umbrella.',
    'expired.title': 'Задайте новый пароль',
    'expired.text': 'Срок действия пароля {user} истёк по парольной политике. Чтобы продолжить, задайте новый.',
    'expiry.title': 'Пароль истекает через {n} дн. ({date})',
    'expiry.text': 'Смените его заранее, чтобы входить без перерыва.',
    'expiry.change': 'Сменить пароль',
    'err.password_expired': 'Срок действия пароля истёк. Задайте новый, чтобы продолжить.',
    'err.ldap_bind_password_required': 'Введите пароль служебной учётной записи.',
    'err.no_local_admin': 'Нет активного локального администратора, поэтому вход через каталог отключить нельзя.',
  },
}

export const strings: Dict = { en: { ...base.en, ...policyStrings.en }, ru: { ...base.ru, ...policyStrings.ru } }
