import type { Dict } from '../i18n'

export const topbarStrings: Dict = {
  en: {
    'nc.open': 'Notifications',
    'nc.unread': '{n} unread',
    'nc.title': 'Notifications',
    'nc.close': 'Close',
    'nc.empty': 'No notifications yet. Results of actions and new incidents appear here.',
    'nc.clear': 'Clear',
    'nc.clear.confirm': 'Delete all notifications from the history?',
    'nc.kept': 'The last {n} notifications are kept in this browser.',
    'nc.today': 'Today',
    'nc.earlier': 'Earlier',
    'nc.open.link': 'Open',
    'lights.label': 'Open incidents by priority',
    'lights.item': '{priority}: {n} open',
    'lights.offline': 'Incident counters are not available',
    'inc.new': 'New incident {priority}',
    'inc.new.ci': 'CI: {ci}',
    'inc.new.many': '{n} new incidents',
    'inc.new.many.text': 'The most severe: {priority} · {title}',
  },
  ru: {
    'nc.open': 'Уведомления',
    'nc.unread': 'Непрочитанных: {n}',
    'nc.title': 'Уведомления',
    'nc.close': 'Закрыть',
    'nc.empty': 'Уведомлений пока нет. Здесь появятся результаты действий и новые инциденты.',
    'nc.clear': 'Очистить',
    'nc.clear.confirm': 'Удалить все уведомления из истории?',
    'nc.kept': 'В этом браузере хранятся последние {n} уведомлений.',
    'nc.today': 'Сегодня',
    'nc.earlier': 'Ранее',
    'nc.open.link': 'Открыть',
    'lights.label': 'Открытые инциденты по приоритетам',
    'lights.item': '{priority}: открыто {n}',
    'lights.offline': 'Счётчики инцидентов недоступны',
    'inc.new': 'Новый инцидент {priority}',
    'inc.new.ci': 'КЕ: {ci}',
    'inc.new.many': 'Новых инцидентов: {n}',
    'inc.new.many.text': 'Самый важный: {priority} · {title}',
  },
}
