import type { Dict } from '../../../i18n'

export const groupStrings: Dict = {
  en: {
    'gm.title': 'Groups → roles and teams',
    'gm.text':
      'Members of a directory group get the role and the team of its row, including members of nested groups. The table is applied at every sign-in and on the schedule below. For the role the first matching row from the top wins; every matching row adds its team (a person can be in several teams). The administrators group of the connection wins over the table. Users the table gives no role get the role for new users.',
    'gm.manual':
      'A value given by the table replaces one set by hand. When a user no longer matches any row, what the table gave is taken back (the role becomes User, the team is cleared), but a value an administrator changed by hand since then is kept.',
    'gm.empty': 'No rows yet. Without rows, roles and teams of directory users are set by hand.',
    'gm.off': 'Turn on LDAP / AD or Entra ID sign-in above to map their groups.',
    'gm.source': 'Directory',
    'gm.source.ldap': 'LDAP / AD',
    'gm.source.entra': 'Entra ID',
    'gm.group': 'Group',
    'gm.group.ldap': 'cn=ops,ou=groups,dc=example,dc=org',
    'gm.group.entra': 'Group object ID',
    'gm.group.invalid.ldap': 'Enter the group DN.',
    'gm.group.invalid.entra': 'Enter the group object ID (GUID).',
    'gm.label': 'Note',
    'gm.label.placeholder': 'For example, Duty engineers',
    'gm.role': 'Role',
    'gm.team': 'Team',
    'gm.scope': 'Visibility scope',
    'gm.scope.all': 'All services',
    'gm.scope.teams': 'Services of my teams',
    'gm.keep': '— do not change —',
    'gm.missing': 'deleted',
    'gm.need': 'Choose a role, a team, a scope or several.',
    'gm.duplicate': 'This group is already in the table.',
    'gm.add': 'Add row',
    'gm.up': 'Move up',
    'gm.down': 'Move down',
    'gm.remove': 'Remove row',
    'gm.sync': 'Re-apply on a schedule',
    'gm.sync.hint':
      'Reads the groups of all known directory users with the service account (LDAP / AD) or the application (Entra ID), so changes reach users who do not sign in.',
    'gm.sync.every': 'Every',
    'gm.sync.minutes': 'min',
    'gm.entra.permission':
      'For Entra ID the schedule needs the Microsoft Graph application permission GroupMember.Read.All with admin consent. Sign-in itself needs only User.Read.',
    'gm.save': 'Save table',
    'gm.saved': 'Group mapping saved. It applies at the next sign-in or synchronization.',
    'gm.syncNow': 'Synchronize now',
    'gm.syncing': 'Synchronizing…',
    'gm.synced': 'Synchronization finished.',
    'gm.syncSave': 'Save the table first.',
    'gm.state.last': 'Last synchronization',
    'gm.state.never': 'Not yet',
    'gm.state.result': 'Result',
    'gm.state.result.value': '{users} users checked, {changed} changed, {missing} not found in the directory',
    'gm.state.failed': 'Failed: {error}',
    'gm.state.mapped': 'Given by the table now',
    'gm.state.mapped.value': 'roles: {roles}, teams: {teams}, scopes: {scopes}',
    'gm.state.by': 'by {actor}',
    'gm.state.schedule': 'schedule',
    'err.group_mapping_invalid': 'The group mapping table has an invalid row.',
    'err.group_sync_running': 'A synchronization is already running.',
  },
  ru: {
    'gm.title': 'Группы → роли и команды',
    'gm.text':
      'Участники группы каталога получают роль и команду из её строки, в том числе участники вложенных групп. Таблица применяется при каждом входе и по расписанию ниже. Для роли побеждает первая подходящая строка сверху; каждая подходящая строка добавляет свою команду (человек может быть в нескольких командах). Группа администраторов из настроек подключения важнее таблицы. Кому таблица не выдала роль, получает роль для новых пользователей.',
    'gm.manual':
      'Значение из таблицы заменяет заданное вручную. Когда пользователь перестаёт подходить под строки, выданное таблицей забирается (роль становится «Пользователь», команда очищается), но значение, которое администратор с тех пор изменил вручную, сохраняется.',
    'gm.empty': 'Строк пока нет. Без них роли и команды пользователей каталога задаются вручную.',
    'gm.off': 'Включите выше вход через LDAP / AD или Entra ID, чтобы сопоставлять их группы.',
    'gm.source': 'Каталог',
    'gm.source.ldap': 'LDAP / AD',
    'gm.source.entra': 'Entra ID',
    'gm.group': 'Группа',
    'gm.group.ldap': 'cn=ops,ou=groups,dc=example,dc=org',
    'gm.group.entra': 'ID объекта группы',
    'gm.group.invalid.ldap': 'Введите DN группы.',
    'gm.group.invalid.entra': 'Введите ID объекта группы (GUID).',
    'gm.label': 'Пометка',
    'gm.label.placeholder': 'Например, дежурные инженеры',
    'gm.role': 'Роль',
    'gm.team': 'Команда',
    'gm.scope': 'Область видимости',
    'gm.scope.all': 'Все сервисы',
    'gm.scope.teams': 'Сервисы моих команд',
    'gm.keep': '— не менять —',
    'gm.missing': 'удалена',
    'gm.need': 'Выберите роль, команду, область или несколько.',
    'gm.duplicate': 'Эта группа уже есть в таблице.',
    'gm.add': 'Добавить строку',
    'gm.up': 'Выше',
    'gm.down': 'Ниже',
    'gm.remove': 'Удалить строку',
    'gm.sync': 'Применять по расписанию',
    'gm.sync.hint':
      'Читает группы всех известных пользователей каталога служебной учётной записью (LDAP / AD) или приложением (Entra ID), чтобы изменения доходили и до тех, кто не входит в систему.',
    'gm.sync.every': 'Каждые',
    'gm.sync.minutes': 'мин',
    'gm.entra.permission':
      'Для Entra ID расписанию нужно разрешение приложения Microsoft Graph GroupMember.Read.All с согласием администратора. Самому входу достаточно User.Read.',
    'gm.save': 'Сохранить таблицу',
    'gm.saved': 'Сопоставление групп сохранено. Оно применится при следующем входе или синхронизации.',
    'gm.syncNow': 'Синхронизировать сейчас',
    'gm.syncing': 'Синхронизируем…',
    'gm.synced': 'Синхронизация завершена.',
    'gm.syncSave': 'Сначала сохраните таблицу.',
    'gm.state.last': 'Последняя синхронизация',
    'gm.state.never': 'Ещё не было',
    'gm.state.result': 'Итог',
    'gm.state.result.value': 'проверено пользователей: {users}, изменено: {changed}, не найдено в каталоге: {missing}',
    'gm.state.failed': 'Ошибка: {error}',
    'gm.state.mapped': 'Сейчас выдано таблицей',
    'gm.state.mapped.value': 'ролей: {roles}, команд: {teams}, областей: {scopes}',
    'gm.state.by': '— {actor}',
    'gm.state.schedule': 'по расписанию',
    'err.group_mapping_invalid': 'В таблице сопоставления групп есть неверная строка.',
    'err.group_sync_running': 'Синхронизация уже идёт.',
  },
}
