import type { Dict } from '../../../i18n'
import { ldapStrings } from '../../../connections/ldapStrings'
import { groupStrings } from './groupStrings'

const page: Dict = {
  en: {
    'dir.title': 'LDAP / Active Directory',
    'dir.text': 'Directory users sign in with their corporate accounts; members of the administrators group become Umbrella administrators.',
    'dir.state': 'Directory sign-in',
    'dir.state.on': 'On',
    'dir.state.off': 'Off',
    'dir.server': 'Server',
    'dir.tls': 'Encryption',
    'dir.tls.none': 'None',
    'dir.password': 'Service account password',
    'dir.password.set': 'Saved in OpenBao',
    'dir.password.unset': 'Not saved',
    'dir.users': 'Known directory users',
    'dir.users.value': '{total} (administrators {admins}, blocked {disabled})',
    'dir.lastSignIn': 'Last directory sign-in',
    'dir.lastSignIn.hint': 'Profiles and roles of directory users are synchronized at every sign-in.',
    'dir.localAdmins': 'Active local administrators',
    'dir.settings': 'Connection settings',
    'dir.enable': 'Allow sign-in with directory accounts',
    'dir.enable.hint': 'When off, only local Umbrella accounts can sign in. The connection settings are kept.',
    'dir.password.keep': 'Leave empty to keep the saved password.',
    'dir.password.again': 'The server or the service account changed: enter the password again.',
    'dir.off': 'Directory sign-in is off. Only local accounts can sign in.',
    'dir.off.sessions': 'Saving signs out directory users who are signed in now.',
    'dir.off.noAdmin': 'There is no active local administrator. Directory sign-in cannot be turned off, otherwise nobody could administer Umbrella.',
    'dir.check': 'Check connection',
    'dir.checking': 'Checking…',
    'dir.save': 'Save',
    'dir.saved': 'Directory settings saved.',
    'dir.save.hint': 'Umbrella checks the connection before saving.',
    'en.title': 'Microsoft Entra ID (Azure AD)',
    'en.text':
      'Users sign in with their Microsoft 365 / Entra ID accounts through the Microsoft sign-in page; members of the administrators group become Umbrella administrators.',
    'en.state': 'Sign-in with Microsoft',
    'en.tenant': 'Directory (tenant) ID',
    'en.tenant.hint': 'GUID or primary domain, for example contoso.onmicrosoft.com',
    'en.client': 'Application (client) ID',
    'en.client.hint': 'From the app registration overview.',
    'en.secret': 'Client secret',
    'en.secret.hint': 'The secret value (not its ID) from Certificates & secrets. Saved in OpenBao.',
    'en.secret.keep': 'Leave empty to keep the saved secret.',
    'en.secret.again': 'The tenant or the application changed: enter the client secret again.',
    'en.adminGroup': 'Administrators group (object ID)',
    'en.adminGroup.hint': 'Members, including through nested groups, get administrator rights.',
    'en.userGroup': 'Allowed users group (object ID)',
    'en.userGroup.hint': 'When set, only members of this group or the administrators group can sign in.',
    'en.userGroup.any': 'Any user of the tenant',
    'en.users': 'Known Entra ID users',
    'en.lastSignIn': 'Last Entra ID sign-in',
    'en.settings': 'Entra ID application',
    'en.enable': 'Allow sign-in with Microsoft Entra ID',
    'en.enable.hint': 'Adds a "Sign in with Microsoft" button to the sign-in page. The settings are kept when off.',
    'en.register':
      'Register an application in Entra ID (App registrations → New registration, single tenant), add the redirect URI below as a Web platform URI, create a client secret, and grant the delegated Microsoft Graph permission User.Read.',
    'en.redirect': 'Redirect URI',
    'en.redirect.hint': 'Copy it to the app registration exactly. It must be the address users open Umbrella with.',
    'en.cloud': 'Microsoft cloud',
    'en.cloud.global': 'Global (login.microsoftonline.com)',
    'en.cloud.usgov': 'US Government',
    'en.cloud.china': 'China (21Vianet)',
    'en.ok': 'Entra ID is reachable',
    'en.ok.text': 'Tenant found, application ID and client secret accepted.',
    'en.issuer': 'Issuer',
    'en.fail': 'Entra ID check failed',
    'en.saved': 'Entra ID settings saved.',
    'en.save.hint': 'Umbrella checks the tenant and the client secret before saving.',
    'en.off': 'Sign-in with Microsoft Entra ID is off.',
    'en.off.sessions': 'Saving signs out Entra ID users who are signed in now.',
    'en.off.noAdmin': 'There is no active local administrator. Entra ID sign-in cannot be turned off, otherwise nobody could administer Umbrella.',
    'err.ldap_bind_password_required': 'Enter the service account password.',
    'err.no_local_admin': 'There is no active local administrator, so sign-in through the directory or Microsoft Entra ID cannot be turned off.',
  },
  ru: {
    'dir.title': 'LDAP / Active Directory',
    'dir.text': 'Пользователи каталога входят корпоративными учётными записями; участники группы администраторов становятся администраторами Umbrella.',
    'dir.state': 'Вход через каталог',
    'dir.state.on': 'Включён',
    'dir.state.off': 'Выключен',
    'dir.server': 'Сервер',
    'dir.tls': 'Шифрование',
    'dir.tls.none': 'Нет',
    'dir.password': 'Пароль служебной учётной записи',
    'dir.password.set': 'Сохранён в OpenBao',
    'dir.password.unset': 'Не сохранён',
    'dir.users': 'Известные пользователи каталога',
    'dir.users.value': '{total} (администраторов {admins}, заблокировано {disabled})',
    'dir.lastSignIn': 'Последний вход через каталог',
    'dir.lastSignIn.hint': 'Профили и роли пользователей каталога синхронизируются при каждом входе.',
    'dir.localAdmins': 'Активные локальные администраторы',
    'dir.settings': 'Параметры подключения',
    'dir.enable': 'Разрешить вход учётными записями каталога',
    'dir.enable.hint': 'Если выключено, войти можно только локальными учётными записями Umbrella. Параметры подключения сохраняются.',
    'dir.password.keep': 'Оставьте пустым, чтобы сохранить текущий пароль.',
    'dir.password.again': 'Изменился сервер или служебная учётная запись: введите пароль ещё раз.',
    'dir.off': 'Вход через каталог выключен. Войти можно только локальными учётными записями.',
    'dir.off.sessions': 'При сохранении пользователи каталога, которые сейчас в системе, будут из неё выведены.',
    'dir.off.noAdmin': 'Нет активного локального администратора. Вход через каталог нельзя выключить, иначе администрировать Umbrella будет некому.',
    'dir.check': 'Проверить подключение',
    'dir.checking': 'Проверяем…',
    'dir.save': 'Сохранить',
    'dir.saved': 'Настройки каталога сохранены.',
    'dir.save.hint': 'Перед сохранением Umbrella проверяет подключение.',
    'en.title': 'Microsoft Entra ID (Azure AD)',
    'en.text':
      'Пользователи входят учётными записями Microsoft 365 / Entra ID через страницу входа Microsoft; участники группы администраторов становятся администраторами Umbrella.',
    'en.state': 'Вход через Microsoft',
    'en.tenant': 'ID каталога (клиента)',
    'en.tenant.hint': 'GUID или основной домен, например contoso.onmicrosoft.com',
    'en.client': 'ID приложения (клиента)',
    'en.client.hint': 'Со страницы обзора регистрации приложения.',
    'en.secret': 'Секрет клиента',
    'en.secret.hint': 'Значение секрета (не его ID) из раздела «Сертификаты и секреты». Сохраняется в OpenBao.',
    'en.secret.keep': 'Оставьте пустым, чтобы сохранить текущий секрет.',
    'en.secret.again': 'Изменился клиент или приложение: введите секрет клиента ещё раз.',
    'en.adminGroup': 'Группа администраторов (ID объекта)',
    'en.adminGroup.hint': 'Участники, в том числе через вложенные группы, получают права администратора.',
    'en.userGroup': 'Группа допущенных пользователей (ID объекта)',
    'en.userGroup.hint': 'Если задана, войти могут только участники этой группы или группы администраторов.',
    'en.userGroup.any': 'Любой пользователь клиента',
    'en.users': 'Известные пользователи Entra ID',
    'en.lastSignIn': 'Последний вход через Entra ID',
    'en.settings': 'Приложение Entra ID',
    'en.enable': 'Разрешить вход через Microsoft Entra ID',
    'en.enable.hint': 'На странице входа появится кнопка «Войти через Microsoft». При выключении настройки сохраняются.',
    'en.register':
      'Зарегистрируйте приложение в Entra ID (Регистрация приложений → Новая регистрация, один клиент), добавьте URI перенаправления ниже как URI платформы «Веб», создайте секрет клиента и выдайте делегированное разрешение Microsoft Graph User.Read.',
    'en.redirect': 'URI перенаправления',
    'en.redirect.hint': 'Скопируйте его в регистрацию приложения без изменений. Это должен быть адрес, по которому пользователи открывают Umbrella.',
    'en.cloud': 'Облако Microsoft',
    'en.cloud.global': 'Глобальное (login.microsoftonline.com)',
    'en.cloud.usgov': 'US Government',
    'en.cloud.china': 'Китай (21Vianet)',
    'en.ok': 'Entra ID доступен',
    'en.ok.text': 'Клиент найден, ID приложения и секрет клиента приняты.',
    'en.issuer': 'Издатель',
    'en.fail': 'Проверка Entra ID не прошла',
    'en.saved': 'Настройки Entra ID сохранены.',
    'en.save.hint': 'Перед сохранением Umbrella проверяет клиент и секрет.',
    'en.off': 'Вход через Microsoft Entra ID выключен.',
    'en.off.sessions': 'При сохранении пользователи Entra ID, которые сейчас в системе, будут из неё выведены.',
    'en.off.noAdmin': 'Нет активного локального администратора. Вход через Entra ID нельзя выключить, иначе администрировать Umbrella будет некому.',
    'err.ldap_bind_password_required': 'Введите пароль служебной учётной записи.',
    'err.no_local_admin': 'Нет активного локального администратора, поэтому вход через каталог или Microsoft Entra ID отключить нельзя.',
  },
}

export const strings: Dict = { en: { ...ldapStrings.en, ...groupStrings.en, ...page.en }, ru: { ...ldapStrings.ru, ...groupStrings.ru, ...page.ru } }
