import type { Dict } from '../../../i18n'
import { ldapStrings } from '../../../connections/ldapStrings'

const page: Dict = {
  en: {
    'dir.title': 'LDAP / Active Directory',
    'dir.text': 'Directory users sign in with their corporate accounts; members of the administrators group become Umbrella administrators.',
    'dir.state': 'Directory sign-in',
    'dir.state.on': 'On',
    'dir.state.off': 'Off',
    'dir.server': 'Server',
    'dir.tls': 'Encryption',
    'dir.tls.none': 'None',
    'dir.password': 'Service account password',
    'dir.password.set': 'Saved in OpenBao',
    'dir.password.unset': 'Not saved',
    'dir.users': 'Known directory users',
    'dir.users.value': '{total} (administrators {admins}, blocked {disabled})',
    'dir.lastSignIn': 'Last directory sign-in',
    'dir.lastSignIn.hint': 'Profiles and roles of directory users are synchronized at every sign-in.',
    'dir.localAdmins': 'Active local administrators',
    'dir.settings': 'Connection settings',
    'dir.enable': 'Allow sign-in with directory accounts',
    'dir.enable.hint': 'When off, only local Umbrella accounts can sign in. The connection settings are kept.',
    'dir.password.keep': 'Leave empty to keep the saved password.',
    'dir.password.again': 'The server or the service account changed: enter the password again.',
    'dir.off': 'Directory sign-in is off. Only local accounts can sign in.',
    'dir.off.sessions': 'Saving signs out directory users who are signed in now.',
    'dir.off.noAdmin': 'There is no active local administrator. Directory sign-in cannot be turned off, otherwise nobody could administer Umbrella.',
    'dir.check': 'Check connection',
    'dir.checking': 'Checking…',
    'dir.save': 'Save',
    'dir.saved': 'Directory settings saved.',
    'dir.save.hint': 'Umbrella checks the connection before saving.',
  },
  ru: {
    'dir.title': 'LDAP / Active Directory',
    'dir.text': 'Пользователи каталога входят корпоративными учётными записями; участники группы администраторов становятся администраторами Umbrella.',
    'dir.state': 'Вход через каталог',
    'dir.state.on': 'Включён',
    'dir.state.off': 'Выключен',
    'dir.server': 'Сервер',
    'dir.tls': 'Шифрование',
    'dir.tls.none': 'Нет',
    'dir.password': 'Пароль служебной учётной записи',
    'dir.password.set': 'Сохранён в OpenBao',
    'dir.password.unset': 'Не сохранён',
    'dir.users': 'Известные пользователи каталога',
    'dir.users.value': '{total} (администраторов {admins}, заблокировано {disabled})',
    'dir.lastSignIn': 'Последний вход через каталог',
    'dir.lastSignIn.hint': 'Профили и роли пользователей каталога синхронизируются при каждом входе.',
    'dir.localAdmins': 'Активные локальные администраторы',
    'dir.settings': 'Параметры подключения',
    'dir.enable': 'Разрешить вход учётными записями каталога',
    'dir.enable.hint': 'Если выключено, войти можно только локальными учётными записями Umbrella. Параметры подключения сохраняются.',
    'dir.password.keep': 'Оставьте пустым, чтобы сохранить текущий пароль.',
    'dir.password.again': 'Изменился сервер или служебная учётная запись: введите пароль ещё раз.',
    'dir.off': 'Вход через каталог выключен. Войти можно только локальными учётными записями.',
    'dir.off.sessions': 'При сохранении пользователи каталога, которые сейчас в системе, будут из неё выведены.',
    'dir.off.noAdmin': 'Нет активного локального администратора. Вход через каталог нельзя выключить, иначе администрировать Umbrella будет некому.',
    'dir.check': 'Проверить подключение',
    'dir.checking': 'Проверяем…',
    'dir.save': 'Сохранить',
    'dir.saved': 'Настройки каталога сохранены.',
    'dir.save.hint': 'Перед сохранением Umbrella проверяет подключение.',
  },
}

export const strings: Dict = { en: { ...ldapStrings.en, ...page.en }, ru: { ...ldapStrings.ru, ...page.ru } }
