export type TvLocale = 'en' | 'ru'

export const tvStrings: Record<TvLocale, Record<string, string>> = {
  en: {
    loading: 'Connecting…',
    'sev.critical': 'Critical',
    'sev.error': 'Error',
    'sev.warning': 'Warning',
    'sev.info': 'Info',
    'count.critical': 'Critical',
    'count.error': 'Errors',
    'count.warning': 'Warnings',
    'count.info': 'Info',
    total: 'Active',
    clear: 'All clear',
    'clear.sub': 'No active incidents on this board.',
    acked: 'Acknowledged',
    maintenance: 'Maintenance',
    updated: 'Updated {time}',
    live: 'Live',
    'offline.short': 'Offline',
    offline: 'No connection since {time}. Showing the last data received.',
    unavailable: 'Incident data is not available yet. Retrying…',
    more: 'Only the first {n} incidents are shown.',
    since: 'since {time}',
    events: '{n} events',
    'ago.s': 'just now',
    'ago.m': '{n} min',
    'ago.h': '{h} h {m} min',
    'ago.d': '{n} d',
    'err.title': 'This board cannot be shown',
    'err.board_not_found': 'The board does not exist, is turned off, or its address has changed. Ask an administrator for the current link.',
    'err.address_not_allowed': 'This screen ({ip}) is not in the networks allowed for the board. Ask an administrator to add it.',
    'err.retry': 'Retrying every {n} seconds.',
  },
  ru: {
    loading: 'Подключение…',
    'sev.critical': 'Критично',
    'sev.error': 'Ошибка',
    'sev.warning': 'Внимание',
    'sev.info': 'Инфо',
    'count.critical': 'Критичные',
    'count.error': 'Ошибки',
    'count.warning': 'Предупреждения',
    'count.info': 'Информационные',
    total: 'Активные',
    clear: 'Всё в порядке',
    'clear.sub': 'На этой панели нет активных инцидентов.',
    acked: 'Подтверждён',
    maintenance: 'Сервисное окно',
    updated: 'Обновлено в {time}',
    live: 'На связи',
    'offline.short': 'Нет связи',
    offline: 'Нет связи с {time}. Показаны последние полученные данные.',
    unavailable: 'Данные инцидентов пока недоступны. Повторяем попытку…',
    more: 'Показаны только первые {n} инцидентов.',
    since: 'с {time}',
    events: 'событий: {n}',
    'ago.s': 'только что',
    'ago.m': '{n} мин',
    'ago.h': '{h} ч {m} мин',
    'ago.d': '{n} д',
    'err.title': 'Панель недоступна',
    'err.board_not_found': 'Панель не существует, выключена или её адрес изменился. Запросите у администратора актуальную ссылку.',
    'err.address_not_allowed': 'Этот экран ({ip}) не входит в разрешённые для панели сети. Попросите администратора добавить его.',
    'err.retry': 'Повторная попытка каждые {n} с.',
  },
}
