apiVersion: 1

datasources:
  - name: PostgreSQL logs
    uid: opensearch-pg-logs
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    editable: false
    jsonData:
      database: "pg-logs-*"
      timeField: "@timestamp"
      flavor: opensearch
      version: 2.19.3
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5

  - name: Container logs
    uid: opensearch-container-logs
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    editable: false
    jsonData:
      database: "container-logs-*"
      timeField: "@timestamp"
      flavor: opensearch
      version: 2.19.3
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5
