import type { Dict } from '../../i18n'

// Texts of the page setup guides: sg.<page>.intro, and for each step sg.<page>.<step> (the name),
// .text (what to do and where) and .go (the button).
export const strings: Dict = {
  en: {
    'sg.title': 'Setup guide',
    'sg.progress': '{done} of {total} done',
    'sg.done': 'Done',
    'sg.optional': 'optional',
    'sg.ask': 'Ask an administrator',
    'sg.ask.hint': 'You do not have the permissions for this step.',
    'sg.collapse': 'Fold',
    'sg.expand': 'Unfold',

    'sg.monitoring.intro': 'A monitoring system gives Umbrella its hosts and alerts: hosts become configuration items, alerts become incidents, Prometheus metrics feed the RED/USE rules.',
    'sg.monitoring.source': 'Add a monitoring system',
    'sg.monitoring.source.text': 'Press «Add a system», pick Zabbix, Prometheus, Grafana or Graylog, enter its address and the credentials to sign in with, then «Check».',
    'sg.monitoring.source.go': 'Add a system',
    'sg.monitoring.alerts': 'Receive its alerts',
    'sg.monitoring.alerts.text': 'Turn on alert polling in the system card, or let the system push alerts to a connector with «Connect a source».',
    'sg.monitoring.hosts': 'Match hosts with configuration items',
    'sg.monitoring.hosts.text': 'Open the system and its host list: link a host to an item by hand or create an item from it where the names did not match on their own.',
    'sg.monitoring.rules': 'Add RED/USE rules on its metrics',
    'sg.monitoring.rules.text': 'For Prometheus: rules turn metrics such as error rate or CPU load into incidents.',
    'sg.monitoring.rules.go': 'Open rules',

    'sg.connectors.intro': 'A connector receives events from a monitoring system by webhook, parses them and turns them into incidents.',
    'sg.connectors.connect': 'Connect a source',
    'sg.connectors.connect.text': '«Connect a source» makes the token and a ready connector for Zabbix, Alertmanager, Grafana, Graylog or a plain webhook in one dialog.',
    'sg.connectors.connect.go': 'Connect a source',
    'sg.connectors.event': 'Receive the first event',
    'sg.connectors.event.text': 'Point the monitoring system at the connector address with its token, or send a test event from the connector page.',
    'sg.connectors.event.go': 'Open the connector',
    'sg.connectors.custom': 'Build your own connector',
    'sg.connectors.custom.text': 'For a system without a preset: press «Create connector», assemble the parsing from blocks in the editor, check it on a sample and publish.',
    'sg.connectors.custom.go': 'Create',

    'sg.cis.intro': 'Configuration items are the hosts, VMs and applications incidents are tied to. Their owners and services decide who is called.',
    'sg.cis.ci': 'Add configuration items',
    'sg.cis.ci.text': 'Press «New configuration item» or let them come by themselves: from monitoring system hosts, from NetBox or from incoming events.',
    'sg.cis.ci.go': 'New item',
    'sg.cis.owners': 'Name the people responsible',
    'sg.cis.owners.text': 'Open an item and add its owners: they get its incidents when no service team does.',
    'sg.cis.service': 'Bind items to a business service',
    'sg.cis.service.text': 'Then incidents of the item reach the team that owns the service and show the impact on the business.',
    'sg.cis.service.go': 'Open services',
    'sg.cis.netbox': 'Import items from NetBox',
    'sg.cis.netbox.text': 'Devices, VMs and their contacts come over and stay in sync.',
    'sg.cis.netbox.go': 'Open NetBox',

    'sg.services.intro': 'A business service ties configuration items to the team that owns them. It routes incidents and sets their priority by the criticality of the service.',
    'sg.services.team': 'Create a team',
    'sg.services.team.text': 'A service needs an owning team: create one on the teams page first.',
    'sg.services.team.go': 'Open teams',
    'sg.services.service': 'Create a service',
    'sg.services.service.text': 'Press «Create service», give it a name, an owning team and a criticality.',
    'sg.services.service.go': 'Create service',
    'sg.services.catalog': 'Bind configuration items',
    'sg.services.catalog.text': 'Open the service and pick the items it runs on, with an owning team: their incidents go to that team.',
    'sg.services.depends': 'Add dependencies between services',
    'sg.services.depends.text': 'In the service card, name the services it depends on: an incident of one shows its impact on the others.',

    'sg.cmdb.intro': 'The map is drawn from business services, their dependencies and configuration items. It fills in as the catalog does.',
    'sg.cmdb.ci': 'Add configuration items',
    'sg.cmdb.ci.text': 'By hand, from monitoring system hosts or from NetBox.',
    'sg.cmdb.ci.go': 'Open items',
    'sg.cmdb.service': 'Create business services',
    'sg.cmdb.service.text': 'Services are the top level of the map.',
    'sg.cmdb.service.go': 'Open services',
    'sg.cmdb.catalog': 'Bind items to services',
    'sg.cmdb.catalog.text': 'Each bound item hangs under its service on the map with its health.',
    'sg.cmdb.catalog.go': 'Open services',
    'sg.cmdb.depends': 'Link dependent services',
    'sg.cmdb.depends.text': 'Dependencies draw the arrows between services.',
    'sg.cmdb.depends.go': 'Open services',

    'sg.teams.intro': 'Teams own services and receive their incidents. Escalation goes to the team lead and on to the lead of the parent team.',
    'sg.teams.team': 'Create a team',
    'sg.teams.team.text': 'Press «New team». A team can be nested in another one to make a hierarchy.',
    'sg.teams.team.go': 'New team',
    'sg.teams.members': 'Add members',
    'sg.teams.members.text': 'Select the team and add the people on call: they get its incidents.',
    'sg.teams.lead': 'Name a team lead',
    'sg.teams.lead.text': 'The lead is the next step of escalation when nobody acknowledges.',
    'sg.teams.channel': 'Set a team channel',
    'sg.teams.channel.text': 'A team mailbox, Telegram chat, Teams or Zoom webhook gets every incident of the team.',

    'sg.users.intro': 'People sign in with a local account or from the directory. The role decides what they may do, the team what they receive.',
    'sg.users.user': 'Add users',
    'sg.users.user.text': 'Press «Create user» for a local account, or connect LDAP / AD so people sign in with their own.',
    'sg.users.user.go': 'Create user',
    'sg.users.roles': 'Give them roles',
    'sg.users.roles.text': 'Open a user and pick a role: on-call engineer, service owner, viewer… Not everyone needs to be an administrator.',
    'sg.users.teams': 'Put them into teams',
    'sg.users.teams.text': 'Only team members get incidents.',
    'sg.users.teams.go': 'Open teams',
    'sg.users.directory': 'Connect LDAP / AD',
    'sg.users.directory.text': 'Accounts, roles and teams then follow directory groups.',
    'sg.users.directory.go': 'Open LDAP / AD',

    'sg.rules.intro': 'RED/USE rules watch metrics in Prometheus and open incidents by rate, errors and duration (RED) or utilization, saturation and errors (USE).',
    'sg.rules.source': 'Add a metric source',
    'sg.rules.source.text': 'A Prometheus address on the «Metric sources» tab. A Prometheus added as a monitoring system counts too.',
    'sg.rules.source.go': 'New source',
    'sg.rules.rule': 'Create a rule',
    'sg.rules.rule.text': 'Pick the method and the signal, write the query, the threshold and the label that names the configuration item, then preview it.',
    'sg.rules.rule.go': 'New rule',
    'sg.rules.both': 'Cover both RED and USE',
    'sg.rules.both.text': 'RED for services (requests, errors, latency), USE for resources (CPU, memory, disks).',
    'sg.rules.both.go': 'New rule',

    'sg.maintenance.intro': 'During planned works incidents of the covered items and services are kept, but nobody is called.',
    'sg.maintenance.target': 'Have something to cover',
    'sg.maintenance.target.text': 'A window covers configuration items or business services: add them first.',
    'sg.maintenance.target.go': 'Open items',
    'sg.maintenance.window': 'Plan a maintenance window',
    'sg.maintenance.window.text': 'Press «New window», pick the items or services, the start and the end.',
    'sg.maintenance.window.go': 'New window',

    'sg.wallboards.intro': 'A wallboard shows incidents full-screen on a NOC TV, without signing in.',
    'sg.wallboards.wallboard': 'Create a wallboard',
    'sg.wallboards.wallboard.text': 'Pick which incidents it shows: by services, items, teams, severity.',
    'sg.wallboards.wallboard.go': 'New wallboard',
    'sg.wallboards.networks': 'Allow the TV networks',
    'sg.wallboards.networks.text': 'Open the wallboard and list the addresses or subnets of the TVs: it opens only from there.',

    'sg.response.intro': 'Response decides the priority of an incident from its impact on business services and calls people by the policy of that priority.',
    'sg.response.catalog': 'Bind items to owned services',
    'sg.response.catalog.text': 'Impact and priority come from the services an incident affects and their criticality.',
    'sg.response.catalog.go': 'Open services',
    'sg.response.integrations': 'Connect Teams, Zoom and Jira',
    'sg.response.integrations.text': 'For war rooms, bridge calls, voice calls and Jira tasks. Without them policies only send messages.',
    'sg.response.integrations.go': 'Integrations',
    'sg.response.dry_run': 'Try it in dry run',
    'sg.response.dry_run.text': 'Switch «Incident response» below to «Dry run» and save: each incident shows on its timeline what would be done, nothing is sent.',
    'sg.response.live': 'Turn it on',
    'sg.response.live.text': 'When the policies look right, switch to «On» and save.',

    'sg.settings.alerting.intro': 'Here incidents leave Umbrella: to PagerDuty or by backup notification to mail, Telegram, Teams and Zoom.',
    'sg.settings.alerting.public_url': 'Set the Umbrella address',
    'sg.settings.alerting.public_url.text': 'In the «Umbrella address» card below: links in messages and PagerDuty buttons lead to it.',
    'sg.settings.alerting.delivery': 'Set up a delivery channel',
    'sg.settings.alerting.delivery.text': 'PagerDuty with an integration key, or backup notification with someone to write to.',
    'sg.settings.alerting.backup': 'Add backup notification',
    'sg.settings.alerting.backup.text': 'If PagerDuty is down or nobody acknowledges, incidents also go by mail, Telegram, Teams or Zoom.',
    'sg.settings.alerting.grafana': 'Link a Grafana dashboard',
    'sg.settings.alerting.grafana.text': 'The incident card then opens the dashboard for the host and the time of the incident.',

    'sg.netbox.intro': 'NetBox is the source of configuration items and the people responsible for them.',
    'sg.netbox.connect': 'Connect NetBox',
    'sg.netbox.connect.text': 'Enter the address and the API token below, check the connection, choose what to import and save.',
    'sg.netbox.sync': 'Run the first synchronization',
    'sg.netbox.sync.text': 'Press «Synchronize now»: items and contacts come over, then they stay in sync on schedule.',
  },
  ru: {
    'sg.title': 'Мастер настройки',
    'sg.progress': 'Готово {done} из {total}',
    'sg.done': 'Готово',
    'sg.optional': 'по желанию',
    'sg.ask': 'Попросите администратора',
    'sg.ask.hint': 'Для этого шага у вас нет прав.',
    'sg.collapse': 'Свернуть',
    'sg.expand': 'Развернуть',

    'sg.monitoring.intro': 'Система мониторинга даёт Umbrella хосты и алерты: хосты становятся КЕ, алерты — инцидентами, метрики Prometheus питают правила RED/USE.',
    'sg.monitoring.source': 'Добавьте систему мониторинга',
    'sg.monitoring.source.text': 'Нажмите «Добавить систему», выберите Zabbix, Prometheus, Grafana или Graylog, укажите адрес и учётные данные для входа, затем «Проверить».',
    'sg.monitoring.source.go': 'Добавить систему',
    'sg.monitoring.alerts': 'Получайте её алерты',
    'sg.monitoring.alerts.text': 'Включите опрос алертов в карточке системы или настройте отправку алертов в коннектор через «Подключить источник».',
    'sg.monitoring.hosts': 'Сопоставьте хосты с КЕ',
    'sg.monitoring.hosts.text': 'Откройте систему и список её хостов: привяжите хост к КЕ вручную или создайте КЕ из хоста, если имена не совпали сами.',
    'sg.monitoring.rules': 'Добавьте правила RED/USE на её метриках',
    'sg.monitoring.rules.text': 'Для Prometheus: правила превращают метрики, например долю ошибок или загрузку CPU, в инциденты.',
    'sg.monitoring.rules.go': 'Открыть правила',

    'sg.connectors.intro': 'Коннектор принимает события от системы мониторинга по вебхуку, разбирает их и превращает в инциденты.',
    'sg.connectors.connect': 'Подключите источник',
    'sg.connectors.connect.text': '«Подключить источник» в одном диалоге создаёт токен и готовый коннектор для Zabbix, Alertmanager, Grafana, Graylog или простого вебхука.',
    'sg.connectors.connect.go': 'Подключить источник',
    'sg.connectors.event': 'Получите первое событие',
    'sg.connectors.event.text': 'Направьте систему мониторинга на адрес коннектора с его токеном или отправьте тестовое событие со страницы коннектора.',
    'sg.connectors.event.go': 'Открыть коннектор',
    'sg.connectors.custom': 'Соберите свой коннектор',
    'sg.connectors.custom.text': 'Для системы без готового шаблона: нажмите «Создать коннектор», соберите разбор из блоков в редакторе, проверьте на образце и опубликуйте.',
    'sg.connectors.custom.go': 'Создать',

    'sg.cis.intro': 'КЕ — это хосты, ВМ и приложения, к которым привязываются инциденты. Ответственные и сервисы КЕ решают, кого поднимать.',
    'sg.cis.ci': 'Добавьте КЕ',
    'sg.cis.ci.text': 'Нажмите «Новая КЕ» или дождитесь, пока они появятся сами: из хостов систем мониторинга, из NetBox или из входящих событий.',
    'sg.cis.ci.go': 'Новая КЕ',
    'sg.cis.owners': 'Назначьте ответственных',
    'sg.cis.owners.text': 'Откройте КЕ и добавьте ответственных: они получают её инциденты, если нет команды сервиса.',
    'sg.cis.service': 'Привяжите КЕ к бизнес-сервису',
    'sg.cis.service.text': 'Тогда инциденты КЕ уходят команде-владельцу сервиса и показывают влияние на бизнес.',
    'sg.cis.service.go': 'Открыть сервисы',
    'sg.cis.netbox': 'Загрузите КЕ из NetBox',
    'sg.cis.netbox.text': 'Устройства, ВМ и их контакты переносятся и дальше синхронизируются.',
    'sg.cis.netbox.go': 'Открыть NetBox',

    'sg.services.intro': 'Бизнес-сервис связывает КЕ с командой-владельцем. Он направляет инциденты и задаёт их приоритет по критичности сервиса.',
    'sg.services.team': 'Создайте команду',
    'sg.services.team.text': 'Сервису нужна команда-владелец: сначала создайте её на странице команд.',
    'sg.services.team.go': 'Открыть команды',
    'sg.services.service': 'Создайте сервис',
    'sg.services.service.text': 'Нажмите «Создать сервис», укажите название, команду-владельца и критичность.',
    'sg.services.service.go': 'Создать сервис',
    'sg.services.catalog': 'Привяжите КЕ',
    'sg.services.catalog.text': 'Откройте сервис и выберите КЕ, на которых он работает, и команду-владельца: инциденты этих КЕ уйдут ей.',
    'sg.services.depends': 'Укажите зависимости сервисов',
    'sg.services.depends.text': 'В карточке сервиса укажите, от каких сервисов он зависит: инцидент одного покажет влияние на другие.',

    'sg.cmdb.intro': 'Карта строится из бизнес-сервисов, их зависимостей и КЕ. Она заполняется вместе с каталогом.',
    'sg.cmdb.ci': 'Добавьте КЕ',
    'sg.cmdb.ci.text': 'Вручную, из хостов систем мониторинга или из NetBox.',
    'sg.cmdb.ci.go': 'Открыть КЕ',
    'sg.cmdb.service': 'Создайте бизнес-сервисы',
    'sg.cmdb.service.text': 'Сервисы — верхний уровень карты.',
    'sg.cmdb.service.go': 'Открыть сервисы',
    'sg.cmdb.catalog': 'Привяжите КЕ к сервисам',
    'sg.cmdb.catalog.text': 'Каждая привязанная КЕ появится на карте под своим сервисом с её состоянием.',
    'sg.cmdb.catalog.go': 'Открыть сервисы',
    'sg.cmdb.depends': 'Свяжите зависимые сервисы',
    'sg.cmdb.depends.text': 'Зависимости рисуют стрелки между сервисами.',
    'sg.cmdb.depends.go': 'Открыть сервисы',

    'sg.teams.intro': 'Команды владеют сервисами и получают их инциденты. Эскалация идёт к руководителю команды и дальше к руководителю родительской команды.',
    'sg.teams.team': 'Создайте команду',
    'sg.teams.team.text': 'Нажмите «Новая команда». Команду можно вложить в другую, чтобы получилась иерархия.',
    'sg.teams.team.go': 'Новая команда',
    'sg.teams.members': 'Добавьте участников',
    'sg.teams.members.text': 'Выберите команду и добавьте дежурных: они будут получать её инциденты.',
    'sg.teams.lead': 'Назначьте руководителя',
    'sg.teams.lead.text': 'Руководитель — следующий шаг эскалации, если никто не принял инцидент.',
    'sg.teams.channel': 'Укажите канал команды',
    'sg.teams.channel.text': 'Почтовый ящик команды, чат Telegram, вебхук Teams или Zoom получает все инциденты команды.',

    'sg.users.intro': 'Люди входят по локальной учётной записи или из каталога. Роль решает, что им можно, команда — что они получают.',
    'sg.users.user': 'Добавьте пользователей',
    'sg.users.user.text': 'Нажмите «Создать пользователя» для локальной учётной записи или подключите LDAP / AD, чтобы входили по своей.',
    'sg.users.user.go': 'Создать пользователя',
    'sg.users.roles': 'Назначьте роли',
    'sg.users.roles.text': 'Откройте пользователя и выберите роль: дежурный, владелец сервиса, наблюдатель… Не всем нужны права администратора.',
    'sg.users.teams': 'Распределите по командам',
    'sg.users.teams.text': 'Инциденты получают только участники команд.',
    'sg.users.teams.go': 'Открыть команды',
    'sg.users.directory': 'Подключите LDAP / AD',
    'sg.users.directory.text': 'Тогда учётные записи, роли и команды следуют группам каталога.',
    'sg.users.directory.go': 'Открыть LDAP / AD',

    'sg.rules.intro': 'Правила RED/USE следят за метриками в Prometheus и открывают инциденты по частоте, ошибкам и длительности (RED) или загрузке, насыщению и ошибкам (USE).',
    'sg.rules.source': 'Добавьте источник метрик',
    'sg.rules.source.text': 'Адрес Prometheus на вкладке «Источники метрик». Prometheus, добавленный как система мониторинга, тоже подходит.',
    'sg.rules.source.go': 'Новый источник',
    'sg.rules.rule': 'Создайте правило',
    'sg.rules.rule.text': 'Выберите метод и сигнал, напишите запрос, порог и метку, которая называет КЕ, затем проверьте предпросмотром.',
    'sg.rules.rule.go': 'Новое правило',
    'sg.rules.both': 'Покройте и RED, и USE',
    'sg.rules.both.text': 'RED — для сервисов (запросы, ошибки, задержка), USE — для ресурсов (CPU, память, диски).',
    'sg.rules.both.go': 'Новое правило',

    'sg.maintenance.intro': 'Во время плановых работ инциденты затронутых КЕ и сервисов сохраняются, но никого не поднимают.',
    'sg.maintenance.target': 'Заведите то, что окно будет покрывать',
    'sg.maintenance.target.text': 'Окно покрывает КЕ или бизнес-сервисы: сначала добавьте их.',
    'sg.maintenance.target.go': 'Открыть КЕ',
    'sg.maintenance.window': 'Запланируйте сервисное окно',
    'sg.maintenance.window.text': 'Нажмите «Новое окно», выберите КЕ или сервисы, начало и конец.',
    'sg.maintenance.window.go': 'Новое окно',

    'sg.wallboards.intro': 'ТВ-панель показывает инциденты на весь экран телевизора дежурной смены, без входа в систему.',
    'sg.wallboards.wallboard': 'Создайте панель',
    'sg.wallboards.wallboard.text': 'Выберите, какие инциденты она показывает: по сервисам, КЕ, командам, критичности.',
    'sg.wallboards.wallboard.go': 'Новая ТВ-панель',
    'sg.wallboards.networks': 'Разрешите сети телевизоров',
    'sg.wallboards.networks.text': 'Откройте панель и перечислите адреса или подсети телевизоров: открыть её можно будет только оттуда.',

    'sg.response.intro': 'Реагирование определяет приоритет инцидента по влиянию на бизнес-сервисы и поднимает людей по политике этого приоритета.',
    'sg.response.catalog': 'Привяжите КЕ к сервисам с владельцами',
    'sg.response.catalog.text': 'Влияние и приоритет считаются по сервисам, которые затронул инцидент, и их критичности.',
    'sg.response.catalog.go': 'Открыть сервисы',
    'sg.response.integrations': 'Подключите Teams, Zoom и Jira',
    'sg.response.integrations.text': 'Для war room, звонков-бриджей, голосовых вызовов и задач в Jira. Без них политики только отправляют сообщения.',
    'sg.response.integrations.go': 'Интеграции',
    'sg.response.dry_run': 'Проверьте в пробном режиме',
    'sg.response.dry_run.text': 'Переключите «Реагирование на инциденты» ниже в «Пробный режим» и сохраните: на ленте каждого инцидента видно, что было бы сделано, но ничего не отправляется.',
    'sg.response.live': 'Включите реагирование',
    'sg.response.live.text': 'Когда политики устраивают, переключите в «Включено» и сохраните.',

    'sg.settings.alerting.intro': 'Здесь инциденты выходят из Umbrella: в PagerDuty или резервным оповещением в почту, Telegram, Teams и Zoom.',
    'sg.settings.alerting.public_url': 'Укажите адрес Umbrella',
    'sg.settings.alerting.public_url.text': 'В карточке «Адрес Umbrella» ниже: на него ведут ссылки из сообщений и кнопки PagerDuty.',
    'sg.settings.alerting.delivery': 'Настройте канал доставки',
    'sg.settings.alerting.delivery.text': 'PagerDuty с ключом интеграции или резервное оповещение с получателями.',
    'sg.settings.alerting.backup': 'Добавьте резервное оповещение',
    'sg.settings.alerting.backup.text': 'Если PagerDuty недоступен или никто не принял инцидент, он уйдёт ещё и в почту, Telegram, Teams или Zoom.',
    'sg.settings.alerting.grafana': 'Привяжите дашборд Grafana',
    'sg.settings.alerting.grafana.text': 'Тогда из карточки инцидента открывается дашборд по хосту и времени инцидента.',

    'sg.netbox.intro': 'NetBox — источник КЕ и ответственных за них.',
    'sg.netbox.connect': 'Подключите NetBox',
    'sg.netbox.connect.text': 'Укажите ниже адрес и API-токен, проверьте подключение, выберите, что загружать, и сохраните.',
    'sg.netbox.sync': 'Запустите первую синхронизацию',
    'sg.netbox.sync.text': 'Нажмите «Синхронизировать»: КЕ и контакты перенесутся, дальше синхронизация идёт по расписанию.',
  },
}
