import type { Dict } from '../../i18n'
import { withOrg } from '../org/strings'
import { strings as app } from '../strings'

const page: Dict = {
  en: {
    'roles.list': 'Roles',
    'roles.new': 'New role',
    'roles.system': 'System',
    'roles.unsaved': 'Unsaved changes',
    'roles.members.count': 'Members',
    'roles.name': 'Name',
    'roles.name.system': 'System roles cannot be renamed.',
    'roles.description': 'Description',
    'roles.system.admin': 'Full access to every page and function.',
    'roles.system.user': 'Default role: own profile only until permissions are granted.',
    'roles.optional': 'optional',
    'roles.tabs': 'Role sections',
    'roles.tab.permissions': 'Permissions ({n})',
    'roles.tab.members': 'Members ({n})',
    'roles.admin.all': 'Administrators have every permission, including those of pages added later. Their permissions cannot be changed.',
    'roles.readOnly': 'You can view roles but not change them.',
    'roles.matrix.all': 'All',
    'roles.matrix.count': '{n} of {total}',
    'roles.diff.title': 'Unsaved changes',
    'roles.diff.name': 'Name: “{from}” → “{to}”',
    'roles.diff.description': 'Description changed',
    'roles.discard': 'Discard',
    'roles.save': 'Save',
    'roles.saved': 'Role saved.',
    'roles.duplicate': 'Duplicate',
    'roles.delete': 'Delete',
    'roles.create': 'Create',
    'roles.create.title': 'New role',
    'roles.duplicate.title': 'Duplicate role',
    'roles.copyName': '{name} (copy)',
    'roles.copyFrom': 'Copy permissions from',
    'roles.copyFrom.none': 'Do not copy: no permissions',
    'roles.copyFrom.hint': 'Permissions can be changed after the role is created.',
    'roles.delete.title': 'Delete role',
    'roles.delete.text': 'The role “{name}” will be deleted. This cannot be undone.',
    'roles.delete.empty': 'The role has no members.',
    'roles.delete.reassign': 'Move its {n} member(s) to',
    'roles.delete.reassign.hint': 'Every user has exactly one role, so the members need a new one.',
    'roles.members.text': 'Every user has exactly one role. Adding a user here moves them from their current role.',
    'roles.members.admin':
      'Administrators have full access. Directory (LDAP / AD) users get or lose this role at sign-in by their membership in the administrators group.',
    'roles.members.add': 'Add members',
    'roles.members.addTo': 'Add members to “{role}”',
    'roles.members.confirm': 'Move to this role',
    'roles.members.from': 'now: {role}',
    'roles.members.empty': 'The role has no members.',
    'roles.members.move': 'Role of {name}',
    'roles.members.moveTo': 'Move to “{role}”',
    'err.role_name_taken': 'A role with this name already exists.',
    'err.role_system': 'System roles cannot be renamed or deleted, and the administrator permissions cannot be changed.',
    'err.role_in_use': 'The role still has members. Choose a role to move them to.',
    'err.invalid_role_name': 'Role name: 1–80 characters.',
    'err.invalid_reassign': 'Choose another existing role for the members.',
  },
  ru: {
    'roles.list': 'Роли',
    'roles.new': 'Новая роль',
    'roles.system': 'Системная',
    'roles.unsaved': 'Есть несохранённые изменения',
    'roles.members.count': 'Участники',
    'roles.name': 'Название',
    'roles.name.system': 'Системные роли нельзя переименовать.',
    'roles.description': 'Описание',
    'roles.system.admin': 'Полный доступ ко всем страницам и функциям.',
    'roles.system.user': 'Роль по умолчанию: только собственный профиль, пока не выданы права.',
    'roles.optional': 'необязательно',
    'roles.tabs': 'Разделы роли',
    'roles.tab.permissions': 'Права ({n})',
    'roles.tab.members': 'Участники ({n})',
    'roles.admin.all': 'У администраторов есть все права, включая права страниц, которые появятся позже. Их права изменить нельзя.',
    'roles.readOnly': 'Вы можете просматривать роли, но не изменять их.',
    'roles.matrix.all': 'Все',
    'roles.matrix.count': '{n} из {total}',
    'roles.diff.title': 'Несохранённые изменения',
    'roles.diff.name': 'Название: «{from}» → «{to}»',
    'roles.diff.description': 'Изменено описание',
    'roles.discard': 'Отменить',
    'roles.save': 'Сохранить',
    'roles.saved': 'Роль сохранена.',
    'roles.duplicate': 'Дублировать',
    'roles.delete': 'Удалить',
    'roles.create': 'Создать',
    'roles.create.title': 'Новая роль',
    'roles.duplicate.title': 'Копия роли',
    'roles.copyName': '{name} (копия)',
    'roles.copyFrom': 'Скопировать права из роли',
    'roles.copyFrom.none': 'Не копировать: без прав',
    'roles.copyFrom.hint': 'Права можно изменить после создания роли.',
    'roles.delete.title': 'Удаление роли',
    'roles.delete.text': 'Роль «{name}» будет удалена. Отменить это нельзя.',
    'roles.delete.empty': 'В роли нет участников.',
    'roles.delete.reassign': 'Перевести её участников ({n}) в роль',
    'roles.delete.reassign.hint': 'У каждого пользователя ровно одна роль, поэтому участникам нужна новая.',
    'roles.members.text': 'У каждого пользователя ровно одна роль. Добавление сюда переводит пользователя из его текущей роли.',
    'roles.members.admin':
      'У администраторов полный доступ. Пользователи каталога (LDAP / AD) получают или теряют эту роль при входе — по членству в группе администраторов.',
    'roles.members.add': 'Добавить участников',
    'roles.members.addTo': 'Добавить участников в «{role}»',
    'roles.members.confirm': 'Перевести в эту роль',
    'roles.members.from': 'сейчас: {role}',
    'roles.members.empty': 'В роли нет участников.',
    'roles.members.move': 'Роль пользователя {name}',
    'roles.members.moveTo': 'Перевести в «{role}»',
    'err.role_name_taken': 'Роль с таким названием уже есть.',
    'err.role_system': 'Системные роли нельзя переименовать или удалить, а права администратора — изменить.',
    'err.role_in_use': 'В роли ещё есть участники. Выберите роль, в которую их перевести.',
    'err.invalid_role_name': 'Название роли: от 1 до 80 символов.',
    'err.invalid_reassign': 'Выберите для участников другую существующую роль.',
  },
}

export const strings: Dict = withOrg({ en: { ...app.en, ...page.en }, ru: { ...app.ru, ...page.ru } })
