import type { Dict } from '../../i18n'
import { strings as app } from '../strings'

const own: Dict = {
  en: {
    'usr.search': 'Search by name, login, e-mail or department',
    'usr.filter.source': 'Account type',
    'usr.filter.role': 'Role',
    'usr.filter.team': 'Team',
    'usr.filter.status': 'Status',
    'usr.filter.any': 'All',
    'usr.filter.reset': 'Reset filters',
    'usr.create': 'Create user',
    'usr.count': '{n} of {total}',
    'usr.empty': 'No users match the filters.',
    'usr.col.user': 'User',
    'usr.col.role': 'Role',
    'usr.col.team': 'Team',
    'usr.col.source': 'Type',
    'usr.col.status': 'Status',
    'usr.col.lastLogin': 'Last sign-in',
    'usr.never': 'Never',
    'usr.noTeam': 'No team',
    'usr.you': 'you',
    'usr.source.local': 'Local',
    'usr.source.ldap': 'LDAP / AD',
    'usr.source.entra': 'Entra ID',
    'usr.source.netbox': 'NetBox',
    'usr.status.active': 'Active',
    'usr.status.locked': 'Locked',
    'usr.status.expired': 'Password expired',
    'usr.status.must_change': 'Must change password',
    'usr.field.username': 'Login',
    'usr.field.username.hint': 'Up to 64 characters without spaces. Cannot be changed later.',
    'usr.field.password': 'Password',
    'usr.field.role': 'Role',
    'usr.field.team': 'Team',
    'usr.field.teams': 'Teams',
    'usr.field.teams.hint': 'A person can be in several teams and gets the incidents of each team’s services.',
    'usr.teams.add': 'Add a team',
    'usr.team.missing': '{id} (deleted)',
    'usr.field.created': 'Created',
    'usr.field.passwordChanged': 'Password changed',
    'usr.field.passwordExpires': 'Password expires',
    'usr.mustChange': 'Change the password at the next sign-in',
    'usr.mustChange.hint': 'The user signs in with this password once and then has to choose their own.',
    'usr.generate': 'Generate',
    'usr.copy': 'Copy',
    'usr.copied': 'Copied',
    'usr.section.profile': 'Profile',
    'usr.section.access': 'Role, team and visibility',
    'usr.field.scope': 'Visibility scope: business services',
    'usr.scope.hint': 'Empty — all incidents',
    'usr.scope.admin': 'Administrators see all incidents whatever is chosen here.',
    'usr.scope.add': 'Add a business service…',
    'usr.scope.missing': '{name} (deleted)',
    'usr.scope.short': 'Incidents of: {names}',
    'usr.section.actions': 'Account',
    'usr.ldap.profile': 'Profile data of directory accounts comes from LDAP / AD and updates at every sign-in.',
    'usr.ldap.admin': 'Members of the directory administrators group get the Administrator role back at their next sign-in.',
    'usr.self.role': 'You cannot change your own role.',
    'usr.adminOnly': 'Only administrators can change administrator accounts.',
    'usr.save': 'Save changes',
    'usr.saved': 'Changes saved.',
    'usr.created': 'User {name} created.',
    'usr.deleted': 'User {name} deleted.',
    'usr.lock': 'Lock',
    'usr.lock.hint': 'A locked user cannot sign in. Their open sessions end at once.',
    'usr.locked': 'User locked. Their sessions are closed.',
    'usr.unlock': 'Unlock',
    'usr.unlock.hint': 'The account is locked: the user cannot sign in.',
    'usr.unlocked': 'User unlocked.',
    'usr.password': 'Set password',
    'usr.password.hint': 'Replaces the password and closes the user’s sessions.',
    'usr.password.title': 'New password for {name}',
    'usr.password.set': 'Password set. The user’s sessions are closed.',
    'usr.delete': 'Delete',
    'usr.delete.hint': 'Removes the account and its stored password. This cannot be undone.',
    'usr.delete.title': 'Delete {name}?',
    'usr.delete.text': 'The account {login} and its password are removed permanently and its sessions end.',
    'usr.delete.ldap': 'A directory account is created again if the person signs in with LDAP / AD.',
    'usr.delete.netbox':
      'This account was made for a NetBox contact. The next NetBox synchronization creates it again while the contact is responsible for items and «Create accounts for contacts» is on (NetBox settings). Turn that off or remove the contact in NetBox.',
    'usr.delete.netbox.off': 'This account was made for a NetBox contact. NetBox does not create accounts now, so it will not come back.',
    'usr.delete.entra': 'An Entra ID account is created again if the person signs in with Microsoft.',
    'usr.delete.confirm': 'Delete user',
    'usr.back': 'Back',
    'usr.create.title': 'New local user',
    'usr.create.submit': 'Create',
    'err.invalid_username': 'Login: 1–64 characters without spaces or control characters.',
    'err.weak_password': 'The password does not meet the password policy.',
    'err.username_taken': 'A user with this login already exists.',
    'err.self_action': 'You cannot lock, delete or change the role of your own account.',
    'err.admin_only': 'Only administrators can manage administrator accounts.',
    'err.last_admin': 'The Administrator role must keep at least one active member.',
    'err.no_local_admin': 'At least one active local administrator must remain.',
    'err.unknown_role': 'The role no longer exists. Reload the page.',
    'err.unknown_team': 'The team no longer exists. Reload the page.',
    'err.service_not_found': 'A chosen business service no longer exists. Reload the page.',
    'err.too_many_services': 'Too many business services in the scope.',
    'err.not_found': 'The user no longer exists.',
  },
  ru: {
    'usr.search': 'Поиск по имени, логину, почте или отделу',
    'usr.filter.source': 'Тип учётной записи',
    'usr.filter.role': 'Роль',
    'usr.filter.team': 'Команда',
    'usr.filter.status': 'Статус',
    'usr.filter.any': 'Все',
    'usr.filter.reset': 'Сбросить фильтры',
    'usr.create': 'Создать пользователя',
    'usr.count': '{n} из {total}',
    'usr.empty': 'Нет пользователей, подходящих под фильтры.',
    'usr.col.user': 'Пользователь',
    'usr.col.role': 'Роль',
    'usr.col.team': 'Команда',
    'usr.col.source': 'Тип',
    'usr.col.status': 'Статус',
    'usr.col.lastLogin': 'Последний вход',
    'usr.never': 'Не входил',
    'usr.noTeam': 'Без команды',
    'usr.you': 'вы',
    'usr.source.local': 'Локальная',
    'usr.source.ldap': 'LDAP / AD',
    'usr.source.entra': 'Entra ID',
    'usr.source.netbox': 'NetBox',
    'usr.status.active': 'Активен',
    'usr.status.locked': 'Заблокирован',
    'usr.status.expired': 'Пароль истёк',
    'usr.status.must_change': 'Должен сменить пароль',
    'usr.field.username': 'Логин',
    'usr.field.username.hint': 'До 64 символов без пробелов. Изменить потом нельзя.',
    'usr.field.password': 'Пароль',
    'usr.field.role': 'Роль',
    'usr.field.team': 'Команда',
    'usr.field.teams': 'Команды',
    'usr.field.teams.hint': 'Человек может состоять в нескольких командах и получает инциденты сервисов каждой из них.',
    'usr.teams.add': 'Добавить команду',
    'usr.team.missing': '{id} (удалена)',
    'usr.field.created': 'Создан',
    'usr.field.passwordChanged': 'Пароль изменён',
    'usr.field.passwordExpires': 'Пароль истекает',
    'usr.mustChange': 'Сменить пароль при следующем входе',
    'usr.mustChange.hint': 'Пользователь войдёт с этим паролем один раз, после чего задаст свой.',
    'usr.generate': 'Сгенерировать',
    'usr.copy': 'Копировать',
    'usr.copied': 'Скопировано',
    'usr.section.profile': 'Профиль',
    'usr.section.access': 'Роль, команда и видимость',
    'usr.field.scope': 'Область видимости: бизнес-сервисы',
    'usr.scope.hint': 'Пусто — все инциденты',
    'usr.scope.admin': 'Администраторы видят все инциденты независимо от выбора.',
    'usr.scope.add': 'Добавить бизнес-сервис…',
    'usr.scope.missing': '{name} (удалён)',
    'usr.scope.short': 'Инциденты: {names}',
    'usr.section.actions': 'Учётная запись',
    'usr.ldap.profile': 'Данные профиля учётных записей каталога приходят из LDAP / AD и обновляются при каждом входе.',
    'usr.ldap.admin': 'Участники группы администраторов каталога снова получат роль администратора при следующем входе.',
    'usr.self.role': 'Свою роль изменить нельзя.',
    'usr.adminOnly': 'Изменять учётные записи администраторов могут только администраторы.',
    'usr.save': 'Сохранить изменения',
    'usr.saved': 'Изменения сохранены.',
    'usr.created': 'Пользователь {name} создан.',
    'usr.deleted': 'Пользователь {name} удалён.',
    'usr.lock': 'Заблокировать',
    'usr.lock.hint': 'Заблокированный пользователь не сможет войти. Его открытые сеансы сразу завершатся.',
    'usr.locked': 'Пользователь заблокирован, его сеансы завершены.',
    'usr.unlock': 'Разблокировать',
    'usr.unlock.hint': 'Учётная запись заблокирована: пользователь не может войти.',
    'usr.unlocked': 'Пользователь разблокирован.',
    'usr.password': 'Задать пароль',
    'usr.password.hint': 'Заменяет пароль и завершает сеансы пользователя.',
    'usr.password.title': 'Новый пароль для {name}',
    'usr.password.set': 'Пароль задан, сеансы пользователя завершены.',
    'usr.delete': 'Удалить',
    'usr.delete.hint': 'Удаляет учётную запись и сохранённый пароль. Отменить нельзя.',
    'usr.delete.title': 'Удалить {name}?',
    'usr.delete.text': 'Учётная запись {login} и её пароль будут удалены навсегда, сеансы завершатся.',
    'usr.delete.ldap': 'Учётная запись каталога появится снова, если человек войдёт через LDAP / AD.',
    'usr.delete.netbox':
      'Эта учётная запись создана для контакта NetBox. Следующая синхронизация NetBox создаст её снова, пока контакт отвечает за объекты и включено «Создавать учётные записи для контактов» (настройки NetBox). Выключите это или уберите контакт в NetBox.',
    'usr.delete.netbox.off': 'Эта учётная запись создана для контакта NetBox. Сейчас NetBox не создаёт учётные записи, поэтому она не вернётся.',
    'usr.delete.entra': 'Учётная запись Entra ID появится снова, если человек войдёт через Microsoft.',
    'usr.delete.confirm': 'Удалить пользователя',
    'usr.back': 'Назад',
    'usr.create.title': 'Новый локальный пользователь',
    'usr.create.submit': 'Создать',
    'err.invalid_username': 'Логин: 1–64 символа без пробелов и управляющих символов.',
    'err.weak_password': 'Пароль не соответствует парольной политике.',
    'err.username_taken': 'Пользователь с таким логином уже есть.',
    'err.self_action': 'Свою учётную запись нельзя заблокировать, удалить или сменить ей роль.',
    'err.admin_only': 'Управлять учётными записями администраторов могут только администраторы.',
    'err.last_admin': 'В роли администратора должен остаться хотя бы один активный участник.',
    'err.no_local_admin': 'Должен остаться хотя бы один активный локальный администратор.',
    'err.unknown_role': 'Роль больше не существует. Обновите страницу.',
    'err.unknown_team': 'Команда больше не существует. Обновите страницу.',
    'err.service_not_found': 'Выбранный бизнес-сервис больше не существует. Обновите страницу.',
    'err.too_many_services': 'Слишком много бизнес-сервисов в области видимости.',
    'err.not_found': 'Пользователь больше не существует.',
  },
}

export const strings: Dict = { en: { ...app.en, ...own.en }, ru: { ...app.ru, ...own.ru } }
