import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'ob.title': 'First steps',
    'ob.lead': 'An incident reaches a person when Umbrella has a source of events, people to send them to and a channel to deliver them. Each step opens the page that does it.',
    'ob.progress': '{done} of {total} done',
    'ob.done': 'Done',
    'ob.optional': 'optional',
    'ob.ask': 'Ask an administrator',
    'ob.ask.hint': 'You do not have the permissions for this step.',
    'ob.empty': 'No incidents yet. They appear here as soon as the first event arrives.',
    'ob.step.source': 'Connect a source of events',
    'ob.step.source.text': 'Zabbix, Alertmanager, Grafana or a webhook: the token and the connector are made in one dialog.',
    'ob.step.source.go': 'Connect',
    'ob.step.event': 'Receive the first event',
    'ob.step.event.text': 'Point the monitoring system at the connector address with its token, or send a test event from the connector.',
    'ob.step.event.go': 'Open the connector',
    'ob.step.team': 'Put together an on-call team',
    'ob.step.team.text': 'At least one team with members: they get the incidents of the services the team owns.',
    'ob.step.team.go': 'Open teams',
    'ob.step.catalog': 'Bind a configuration item to a service',
    'ob.step.catalog.text': 'Then incidents of the item go to the team that owns the service. Until then they take the default route.',
    'ob.step.catalog.go': 'Open services',
    'ob.step.delivery': 'Set up a delivery channel',
    'ob.step.delivery.text': 'PagerDuty with an integration key, or e-mail / Telegram / Teams / Zoom with someone to write to.',
    'ob.step.delivery.go': 'Set up',
    'ob.step.public_url': 'Set the Umbrella address',
    'ob.step.public_url.text': 'Links in e-mail, Telegram and PagerDuty (such as «Acknowledge») lead to it.',
    'ob.step.public_url.go': 'Set',
  },
  ru: {
    'ob.title': 'Первые шаги',
    'ob.lead': 'Инцидент доходит до человека, когда в Umbrella есть источник событий, люди, которым их отправлять, и канал доставки. Каждый шаг открывает страницу, где он делается.',
    'ob.progress': 'Готово {done} из {total}',
    'ob.done': 'Готово',
    'ob.optional': 'по желанию',
    'ob.ask': 'Попросите администратора',
    'ob.ask.hint': 'Для этого шага у вас нет прав.',
    'ob.empty': 'Инцидентов пока нет. Они появятся здесь, как только придёт первое событие.',
    'ob.step.source': 'Подключите источник событий',
    'ob.step.source.text': 'Zabbix, Alertmanager, Grafana или вебхук: токен и коннектор создаются в одном диалоге.',
    'ob.step.source.go': 'Подключить',
    'ob.step.event': 'Получите первое событие',
    'ob.step.event.text': 'Направьте систему мониторинга на адрес коннектора с его токеном или отправьте тестовое событие из коннектора.',
    'ob.step.event.go': 'Открыть коннектор',
    'ob.step.team': 'Соберите команду дежурных',
    'ob.step.team.text': 'Хотя бы одна команда с участниками: они получают инциденты сервисов, которыми владеет команда.',
    'ob.step.team.go': 'Открыть команды',
    'ob.step.catalog': 'Привяжите КЕ к сервису',
    'ob.step.catalog.text': 'Тогда инциденты этой КЕ уйдут команде-владельцу сервиса. До этого они идут по маршруту по умолчанию.',
    'ob.step.catalog.go': 'Открыть сервисы',
    'ob.step.delivery': 'Настройте канал доставки',
    'ob.step.delivery.text': 'PagerDuty с ключом интеграции или почта / Telegram / Teams / Zoom с получателями.',
    'ob.step.delivery.go': 'Настроить',
    'ob.step.public_url': 'Укажите адрес Umbrella',
    'ob.step.public_url.text': 'На него ведут ссылки из писем, Telegram и PagerDuty (например, «Принять»).',
    'ob.step.public_url.go': 'Указать',
  },
}
