import type { Dict } from '../../i18n'

// Strings of the page «Severity and impact» and of the priority block of the incident card.
export const strings: Dict = {
  en: {
    loading: 'Loading…',
    'err.invalid_impact_policy': 'The policy is not valid.',
    'err.invalid_severity': 'Choose the severity of the event.',
    'im.policy': 'Priority policy',
    'im.policy.text':
      'The priority of an incident (P1…P5) follows from the severity of its events and the business impact: the most critical business service the configuration item runs, or one that depends on it. Then the classification rules apply.',
    'im.enabled': 'Find the priority from the impact',
    'im.enabled.hint': 'Off: the priority is the event severity; the impact is still shown on the incident card.',
    'im.depth': 'Upstream depth',
    'im.depth.hint': 'How many depends_on steps count from the services of the item to the services that depend on them. 0: only the services of the item.',
    'im.template': 'The built-in template applies: it has not been changed yet.',
    'im.save': 'Save',
    'im.revert': 'Discard changes',
    'im.reset': 'Reset to template',
    'im.reset.confirm': 'Replace the matrix, the depth and the rules with the built-in template?',
    'im.saved': 'Saved. Open incidents got their priority again.',
    'im.reset.done': 'The template is restored.',
    'im.matrix': 'Impact matrix',
    'im.matrix.text': 'Rows: severity of the event. Columns: business impact. A cell is the priority of the incident.',
    'im.matrix.event': 'Event ↓ · impact →',
    'im.matrix.changed': 'Differs from the event severity',
    'im.matrix.template': 'Template: {sev}',
    'im.level.critical': 'Critical',
    'im.level.high': 'High',
    'im.level.medium': 'Medium',
    'im.level.low': 'Low',
    'im.level.none': 'No impact',
    'im.level.unknown': 'Unknown',
    'im.rules': 'Classification rules',
    'im.rules.text': 'Applied in order after the matrix. A rule whose condition holds changes the priority; «stop» skips the rules below it.',
    'im.rules.empty': 'No rules: the matrix alone decides.',
    'im.rule.add': 'Add rule',
    'im.rule.new': 'New rule',
    'im.rule.edit': 'Rule',
    'im.rule.name': 'Name',
    'im.rule.id': 'ID',
    'im.rule.id.hint': 'Letters, digits, dots, dashes, underscores; unique.',
    'im.rule.when': 'Condition (CEL)',
    'im.rule.when.hint': 'An expression that returns true or false.',
    'im.rule.action': 'Action',
    'im.rule.severity': 'Priority',
    'im.rule.n': 'Levels',
    'im.rule.level': 'Impact level',
    'im.rule.stop': 'Stop after this rule',
    'im.rule.stop.hint': 'The rules below are not looked at when this one matches.',
    'im.rule.enabled': 'Rule is on',
    'im.rule.up': 'Move up',
    'im.rule.down': 'Move down',
    'im.rule.delete': 'Delete',
    'im.rule.done': 'Apply',
    'im.rule.cancel': 'Cancel',
    'im.rule.off': 'Off',
    'im.rule.stopped': 'stop',
    'im.rule.error.name': 'Enter a name.',
    'im.rule.error.id': 'The ID is empty, has other characters or is used by another rule.',
    'im.rule.error.when': 'Enter a condition.',
    'im.action.set': 'Set priority',
    'im.action.raise': 'Raise by N levels',
    'im.action.lower': 'Lower by N levels',
    'im.action.impact': 'Set impact level',
    'im.action.set.text': 'priority {sev}',
    'im.action.raise.text': 'raise by {n}',
    'im.action.lower.text': 'lower by {n}',
    'im.action.impact.text': 'impact {level}',
    'im.vars': 'Variables',
    'im.var.event_severity': 'severity of the event: critical, error, warning, low, info',
    'im.var.severity': 'priority so far (after the matrix and the rules above)',
    'im.var.impact': 'impact level: critical, high, medium, low, none, unknown',
    'im.var.title': 'incident title',
    'im.var.ci': 'name of the configuration item',
    'im.var.ci_kind': 'kind of the item: device, vm, service, other',
    'im.var.signal': 'signal',
    'im.var.method': 'red, use or other',
    'im.var.labels': "event labels (map): 'env' in labels && labels['env'] == 'prod'",
    'im.var.services': "affected services (names), e.g. 'Payments' in services",
    'im.var.service_criticalities': 'their criticalities, most critical first',
    'im.var.direct_services': 'services the item itself runs',
    'im.var.team': 'owning team',
    'im.vars.example': "Example: 'Payments' in direct_services && event_severity == 'warning'",
    'im.test': 'Test',
    'im.test.text': 'Enter a sample event: the priority is found with the policy on this page (also unsaved) and the current catalog.',
    'im.test.title': 'Title',
    'im.test.ci': 'Configuration item',
    'im.test.ci.hint': 'As the event names it: host name, IP address, alias.',
    'im.test.signal': 'Signal',
    'im.test.severity': 'Event severity',
    'im.test.method': 'Method',
    'im.test.labels': 'Labels',
    'im.test.labels.hint': 'One per line: key=value.',
    'im.test.run': 'Check',
    'im.test.ci.found': 'Item: {name}',
    'im.test.ci.missing': 'The item is not in the catalog.',
    'im.test.team': 'Team: {name}',
    'im.priority': 'Priority',
    'im.event': 'event',
    'im.impact': 'impact',
    'im.upstream': 'upstream',
    'im.rule': 'rule',
    'im.how': 'How it was found',
    'im.step.event_severity': 'Event severity: {severity}',
    'im.step.impact_level': 'Business impact: {level}',
    'im.step.impact_level.services': 'Business impact: {level} — {services}',
    'im.step.impact_level.upstream': 'Business impact: {level} — {services}; upstream: {upstream}',
    'im.step.impact_level.only_upstream': 'Business impact: {level} — upstream: {upstream}',
    'im.step.impact_unknown.ci_unknown': 'Impact unknown: the item is not in the catalog, the matrix does not apply',
    'im.step.impact_unknown.no_services': 'Impact unknown: the catalog has no business services, the matrix does not apply',
    'im.step.policy_disabled': 'The policy is off: the priority is the event severity {severity}',
    'im.step.matrix': 'Matrix: {event} × {level} → {severity}',
    'im.step.rule_set': 'Rule «{rule}»: {from} → {severity}',
    'im.step.rule_raise': 'Rule «{rule}» raises by {n}: {from} → {severity}',
    'im.step.rule_lower': 'Rule «{rule}» lowers by {n}: {from} → {severity}',
    'im.step.rule_impact': 'Rule «{rule}» sets the impact {level}: {from} → {severity}',
    'im.step.rule_error': 'Rule «{rule}» failed and was skipped: {error}',
  },
  ru: {
    loading: 'Загрузка…',
    'err.invalid_impact_policy': 'Политика заполнена неверно.',
    'err.invalid_severity': 'Выберите важность события.',
    'im.policy': 'Политика приоритета',
    'im.policy.text':
      'Приоритет инцидента (P1…P5) следует из важности его событий и влияния на бизнес: самого критичного бизнес-сервиса, на котором работает КЕ, или сервиса, который от него зависит. Затем применяются правила классификации.',
    'im.enabled': 'Определять приоритет по влиянию',
    'im.enabled.hint': 'Выключено: приоритет равен важности события; влияние всё равно показывается в карточке инцидента.',
    'im.depth': 'Глубина зависимостей',
    'im.depth.hint': 'Сколько шагов depends_on учитывается от сервисов КЕ к сервисам, которые от них зависят. 0 — только сервисы самой КЕ.',
    'im.template': 'Действует встроенный шаблон: настройки ещё не менялись.',
    'im.save': 'Сохранить',
    'im.revert': 'Отменить изменения',
    'im.reset': 'Вернуть шаблон',
    'im.reset.confirm': 'Заменить матрицу, глубину и правила встроенным шаблоном?',
    'im.saved': 'Сохранено. Приоритет открытых инцидентов пересчитан.',
    'im.reset.done': 'Шаблон восстановлен.',
    'im.matrix': 'Матрица влияния',
    'im.matrix.text': 'Строки — важность события, столбцы — влияние на бизнес. В клетке — приоритет инцидента.',
    'im.matrix.event': 'Событие ↓ · влияние →',
    'im.matrix.changed': 'Отличается от важности события',
    'im.matrix.template': 'В шаблоне: {sev}',
    'im.level.critical': 'Критичное',
    'im.level.high': 'Высокое',
    'im.level.medium': 'Среднее',
    'im.level.low': 'Низкое',
    'im.level.none': 'Нет влияния',
    'im.level.unknown': 'Неизвестно',
    'im.rules': 'Правила классификации',
    'im.rules.text': 'Применяются по порядку после матрицы. Правило, условие которого выполнено, меняет приоритет; «стоп» пропускает правила ниже.',
    'im.rules.empty': 'Правил нет: решает только матрица.',
    'im.rule.add': 'Добавить правило',
    'im.rule.new': 'Новое правило',
    'im.rule.edit': 'Правило',
    'im.rule.name': 'Название',
    'im.rule.id': 'Идентификатор',
    'im.rule.id.hint': 'Латинские буквы, цифры, точка, дефис, подчёркивание; уникальный.',
    'im.rule.when': 'Условие (CEL)',
    'im.rule.when.hint': 'Выражение, которое возвращает true или false.',
    'im.rule.action': 'Действие',
    'im.rule.severity': 'Приоритет',
    'im.rule.n': 'Уровней',
    'im.rule.level': 'Уровень влияния',
    'im.rule.stop': 'Остановиться после этого правила',
    'im.rule.stop.hint': 'Если правило сработало, правила ниже не проверяются.',
    'im.rule.enabled': 'Правило включено',
    'im.rule.up': 'Выше',
    'im.rule.down': 'Ниже',
    'im.rule.delete': 'Удалить',
    'im.rule.done': 'Применить',
    'im.rule.cancel': 'Отмена',
    'im.rule.off': 'Выкл.',
    'im.rule.stopped': 'стоп',
    'im.rule.error.name': 'Введите название.',
    'im.rule.error.id': 'Идентификатор пуст, содержит другие символы или занят другим правилом.',
    'im.rule.error.when': 'Введите условие.',
    'im.action.set': 'Задать приоритет',
    'im.action.raise': 'Повысить на N уровней',
    'im.action.lower': 'Понизить на N уровней',
    'im.action.impact': 'Задать уровень влияния',
    'im.action.set.text': 'приоритет {sev}',
    'im.action.raise.text': 'повысить на {n}',
    'im.action.lower.text': 'понизить на {n}',
    'im.action.impact.text': 'влияние {level}',
    'im.vars': 'Переменные',
    'im.var.event_severity': 'важность события: critical, error, warning, low, info',
    'im.var.severity': 'приоритет на этот момент (после матрицы и правил выше)',
    'im.var.impact': 'уровень влияния: critical, high, medium, low, none, unknown',
    'im.var.title': 'заголовок инцидента',
    'im.var.ci': 'имя КЕ',
    'im.var.ci_kind': 'тип КЕ: device, vm, service, other',
    'im.var.signal': 'сигнал',
    'im.var.method': 'red, use или other',
    'im.var.labels': "метки события (map): 'env' in labels && labels['env'] == 'prod'",
    'im.var.services': "затронутые сервисы (имена), например 'Payments' in services",
    'im.var.service_criticalities': 'их критичность, самые критичные первыми',
    'im.var.direct_services': 'сервисы, на которых работает сама КЕ',
    'im.var.team': 'команда-владелец',
    'im.vars.example': "Пример: 'Payments' in direct_services && event_severity == 'warning'",
    'im.test': 'Проверка',
    'im.test.text': 'Введите пример события: приоритет считается по политике на этой странице (в том числе несохранённой) и текущему каталогу.',
    'im.test.title': 'Заголовок',
    'im.test.ci': 'КЕ',
    'im.test.ci.hint': 'Как её называет событие: имя хоста, IP-адрес, псевдоним.',
    'im.test.signal': 'Сигнал',
    'im.test.severity': 'Важность события',
    'im.test.method': 'Метод',
    'im.test.labels': 'Метки',
    'im.test.labels.hint': 'По одной в строке: ключ=значение.',
    'im.test.run': 'Проверить',
    'im.test.ci.found': 'КЕ: {name}',
    'im.test.ci.missing': 'КЕ нет в каталоге.',
    'im.test.team': 'Команда: {name}',
    'im.priority': 'Приоритет',
    'im.event': 'событие',
    'im.impact': 'влияние',
    'im.upstream': 'зависящие',
    'im.rule': 'правило',
    'im.how': 'Как получен',
    'im.step.event_severity': 'Важность события: {severity}',
    'im.step.impact_level': 'Влияние на бизнес: {level}',
    'im.step.impact_level.services': 'Влияние на бизнес: {level} — {services}',
    'im.step.impact_level.upstream': 'Влияние на бизнес: {level} — {services}; зависящие: {upstream}',
    'im.step.impact_level.only_upstream': 'Влияние на бизнес: {level} — зависящие: {upstream}',
    'im.step.impact_unknown.ci_unknown': 'Влияние неизвестно: КЕ нет в каталоге, матрица не применяется',
    'im.step.impact_unknown.no_services': 'Влияние неизвестно: в каталоге нет бизнес-сервисов, матрица не применяется',
    'im.step.policy_disabled': 'Политика выключена: приоритет равен важности события {severity}',
    'im.step.matrix': 'Матрица: {event} × {level} → {severity}',
    'im.step.rule_set': 'Правило «{rule}»: {from} → {severity}',
    'im.step.rule_raise': 'Правило «{rule}» повышает на {n}: {from} → {severity}',
    'im.step.rule_lower': 'Правило «{rule}» понижает на {n}: {from} → {severity}',
    'im.step.rule_impact': 'Правило «{rule}» задаёт влияние {level}: {from} → {severity}',
    'im.step.rule_error': 'Правило «{rule}» не выполнилось и пропущено: {error}',
  },
}
