import type { Dict } from '../../i18n'

export const contextStrings: Dict = {
  en: {
    'panel.cpu': 'CPU',
    'panel.memory': 'Memory',
    'panel.load': 'Load average (1 min)',
    'panel.disk': 'Disk space used',
    'panel.net_in': 'Network in',
    'panel.net_out': 'Network out',
    loading: 'Loading…',
    'mon.tab.context': 'Graphs and logs',
    'ctx.explain':
      'The Machine tab of an incident shows its machine around the start: these graphs from the monitoring systems that know the machine, lines from the log sources below and the events Umbrella received about it.',
    'ctx.settings': 'Incident card',
    'ctx.window': 'Default window',
    'ctx.window.hint': 'Time before and after the start of an incident; anyone can choose another one on the card.',
    'ctx.loglimit': 'Log lines',
    'ctx.loglimit.hint': 'How many of the newest lines are shown at most.',
    'ctx.minutes': 'min',
    'ctx.lines': 'lines',
    'ctx.panels': 'Graphs',
    'ctx.panels.hint':
      'For Prometheus-compatible systems: a PromQL query where $selector selects the series of the machine (by the host label of the system) and $host is its name. For Zabbix: an item key, * stands for any text. A graph is drawn from the systems it has a query for.',
    'ctx.panel.title': 'Title',
    'ctx.panel.unit': 'Unit',
    'ctx.panel.unit.hint': '%, bps, B, s or any text',
    'ctx.panel.promql': 'PromQL',
    'ctx.panel.zabbix': 'Zabbix item key',
    'ctx.panel.add': 'Add a graph',
    'ctx.panel.remove': 'Remove the graph',
    'ctx.panel.up': 'Move up',
    'ctx.panels.defaults': 'Standard graphs',
    'ctx.panels.defaults.confirm': 'Replace the graphs with the standard ones?',
    'ctx.panels.none': 'No graphs: the card shows only events and logs.',
    'ctx.save': 'Save',
    'ctx.saved': 'Saved.',
    'ctx.logs': 'Log sources',
    'ctx.logs.hint': 'Lines are looked up by every name of the machine: the item name, its short name, aliases, IP addresses and the host names monitoring systems know it by.',
    'ctx.logs.new': 'Add a log source',
    'ctx.logs.empty': 'No log sources yet.',
    'ctx.logs.col.name': 'Source',
    'ctx.logs.col.url': 'Address',
    'ctx.logs.off': 'Off',
    'ctx.kind.loki': 'Loki',
    'ctx.kind.opensearch': 'OpenSearch / Elasticsearch',
    'ctx.dialog.new': 'New log source',
    'ctx.dialog.edit': 'Log source',
    'ctx.kind': 'Store',
    'ctx.name': 'Name',
    'ctx.url': 'Address',
    'ctx.url.loki.hint': 'The address the Loki HTTP API answers at, e.g. http://loki:3100.',
    'ctx.url.opensearch.hint': 'The address of the cluster, e.g. https://opensearch:9200.',
    'ctx.cred': 'Credential',
    'ctx.cred.hint': 'Bearer, basic or header credential when the store asks for one. Secrets are kept in OpenBao.',
    'ctx.cred.none': 'None',
    'ctx.cred.missing': 'Create a credential on the Credentials page first.',
    'ctx.query': 'LogQL',
    'ctx.query.hint': '$host is a regular expression matching every name of the machine, e.g. {host=~"$host"} or {job="syslog", hostname=~"$host"}.',
    'ctx.index': 'Index',
    'ctx.index.hint': 'An index, alias or pattern, e.g. logs-*',
    'ctx.hostfield': 'Machine field',
    'ctx.msgfield': 'Message field',
    'ctx.timefield': 'Time field',
    'ctx.levelfield': 'Level field',
    'ctx.skip': 'Do not verify the TLS certificate',
    'ctx.enabled': 'Turned on',
    'ctx.enabled.hint': 'Incident cards read lines from turned-on sources only.',
    'ctx.test.host': 'Machine to check',
    'ctx.test.host.hint': 'A machine name to read the lines of the last hour by.',
    'ctx.test': 'Check',
    'ctx.test.ok': '{n} lines found',
    'ctx.test.fail': 'The source could not be read',
    'ctx.cancel': 'Cancel',
    'ctx.delete': 'Delete',
    'ctx.delete.confirm': 'Delete the log source "{name}"?',
    'err.window_invalid': 'The window must be from 1 minute to 7 days.',
    'err.log_limit_invalid': 'Log lines: from 10 to 2000.',
    'err.too_many_panels': 'At most 20 graphs.',
    'err.panel_title': 'Every graph needs a title of up to 100 characters and a unit of up to 20.',
    'err.panel_query': 'Every graph needs a PromQL query or a Zabbix item key.',
    'err.log_kind': 'Choose the kind of log store.',
    'err.log_query': 'The query is too long.',
    'err.log_field': 'Field and index names cannot contain spaces, / ? or #.',
    'err.log_test_host': 'Enter the name of a machine to check.',
    'err.name_invalid': 'Enter a name of up to 200 characters.',
    'err.url_invalid': 'Enter an http or https address.',
    'err.credential_not_found': 'The credential does not exist any more.',
    'err.credential_type': 'This kind of credential cannot be used here: use bearer, basic or header.',
    'err.too_many_sources': 'At most 20 log sources.',
  },
  ru: {
    'panel.cpu': 'CPU',
    'panel.memory': 'Память',
    'panel.load': 'Средняя загрузка (1 мин)',
    'panel.disk': 'Занято на дисках',
    'panel.net_in': 'Сеть, вход',
    'panel.net_out': 'Сеть, выход',
    loading: 'Загрузка…',
    'mon.tab.context': 'Графики и логи',
    'ctx.explain':
      'Вкладка «Машина» в карточке инцидента показывает машину вокруг его начала: эти графики из систем мониторинга, которые знают машину, строки из источников логов ниже и события, которые Umbrella получала по ней.',
    'ctx.settings': 'Карточка инцидента',
    'ctx.window': 'Окно по умолчанию',
    'ctx.window.hint': 'Время до и после начала инцидента; в карточке его можно поменять.',
    'ctx.loglimit': 'Строк логов',
    'ctx.loglimit.hint': 'Сколько последних строк показывать не больше.',
    'ctx.minutes': 'мин',
    'ctx.lines': 'строк',
    'ctx.panels': 'Графики',
    'ctx.panels.hint':
      'Для Prometheus-совместимых систем — запрос PromQL, где $selector выбирает ряды машины (по метке хоста системы), а $host — её имя. Для Zabbix — ключ элемента данных, * — любой текст. График строится из тех систем, для которых у него есть запрос.',
    'ctx.panel.title': 'Название',
    'ctx.panel.unit': 'Единица',
    'ctx.panel.unit.hint': '%, bps, B, s или любой текст',
    'ctx.panel.promql': 'PromQL',
    'ctx.panel.zabbix': 'Ключ элемента Zabbix',
    'ctx.panel.add': 'Добавить график',
    'ctx.panel.remove': 'Убрать график',
    'ctx.panel.up': 'Выше',
    'ctx.panels.defaults': 'Стандартные графики',
    'ctx.panels.defaults.confirm': 'Заменить графики стандартными?',
    'ctx.panels.none': 'Графиков нет: в карточке будут только события и логи.',
    'ctx.save': 'Сохранить',
    'ctx.saved': 'Сохранено.',
    'ctx.logs': 'Источники логов',
    'ctx.logs.hint': 'Строки ищутся по всем именам машины: имени КЕ, короткому имени, псевдонимам, IP-адресам и именам хостов в системах мониторинга.',
    'ctx.logs.new': 'Добавить источник логов',
    'ctx.logs.empty': 'Источников логов пока нет.',
    'ctx.logs.col.name': 'Источник',
    'ctx.logs.col.url': 'Адрес',
    'ctx.logs.off': 'Выключен',
    'ctx.kind.loki': 'Loki',
    'ctx.kind.opensearch': 'OpenSearch / Elasticsearch',
    'ctx.dialog.new': 'Новый источник логов',
    'ctx.dialog.edit': 'Источник логов',
    'ctx.kind': 'Хранилище',
    'ctx.name': 'Название',
    'ctx.url': 'Адрес',
    'ctx.url.loki.hint': 'Адрес HTTP API Loki, например http://loki:3100.',
    'ctx.url.opensearch.hint': 'Адрес кластера, например https://opensearch:9200.',
    'ctx.cred': 'Учётные данные',
    'ctx.cred.hint': 'Bearer, basic или header, если хранилище их требует. Секреты хранятся в OpenBao.',
    'ctx.cred.none': 'Нет',
    'ctx.cred.missing': 'Сначала создайте учётные данные на странице «Учётные данные».',
    'ctx.query': 'LogQL',
    'ctx.query.hint': '$host — регулярное выражение, совпадающее с любым именем машины, например {host=~"$host"} или {job="syslog", hostname=~"$host"}.',
    'ctx.index': 'Индекс',
    'ctx.index.hint': 'Индекс, псевдоним или шаблон, например logs-*',
    'ctx.hostfield': 'Поле машины',
    'ctx.msgfield': 'Поле сообщения',
    'ctx.timefield': 'Поле времени',
    'ctx.levelfield': 'Поле уровня',
    'ctx.skip': 'Не проверять TLS-сертификат',
    'ctx.enabled': 'Включён',
    'ctx.enabled.hint': 'Карточки инцидентов читают строки только из включённых источников.',
    'ctx.test.host': 'Машина для проверки',
    'ctx.test.host.hint': 'Имя машины, по которому прочитать строки за последний час.',
    'ctx.test': 'Проверить',
    'ctx.test.ok': 'Найдено строк: {n}',
    'ctx.test.fail': 'Не удалось прочитать источник',
    'ctx.cancel': 'Отмена',
    'ctx.delete': 'Удалить',
    'ctx.delete.confirm': 'Удалить источник логов «{name}»?',
    'err.window_invalid': 'Окно — от 1 минуты до 7 суток.',
    'err.log_limit_invalid': 'Строк логов — от 10 до 2000.',
    'err.too_many_panels': 'Не больше 20 графиков.',
    'err.panel_title': 'У каждого графика нужно название до 100 символов и единица до 20.',
    'err.panel_query': 'У каждого графика нужен запрос PromQL или ключ элемента Zabbix.',
    'err.log_kind': 'Выберите вид хранилища логов.',
    'err.log_query': 'Слишком длинный запрос.',
    'err.log_field': 'Имена полей и индекса не могут содержать пробелы, / ? и #.',
    'err.log_test_host': 'Укажите имя машины для проверки.',
    'err.name_invalid': 'Укажите название до 200 символов.',
    'err.url_invalid': 'Укажите адрес http или https.',
    'err.credential_not_found': 'Этих учётных данных уже нет.',
    'err.credential_type': 'Такие учётные данные здесь не подходят: нужны bearer, basic или header.',
    'err.too_many_sources': 'Не больше 20 источников логов.',
  },
}
