import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    loading: 'Loading…',
    'mon.tab.hosts': 'Hosts',
    'mon.tab.sources': 'Systems',
    'mon.new': 'Add a system',
    'mon.kind.zabbix': 'Zabbix',
    'mon.kind.prometheus': 'Prometheus',
    'mon.kind.grafana': 'Grafana',
    'mon.empty.sources': 'No monitoring systems yet. Add Zabbix, a Prometheus-compatible server or Grafana to read its host list and see which configuration items it covers.',
    'mon.empty.hosts': 'No hosts yet: read the host list of a system on the Systems tab.',
    'mon.empty.filtered': 'No hosts match the filter.',
    'mon.col.name': 'System',
    'mon.col.url': 'Address',
    'mon.col.hosts': 'Hosts',
    'mon.col.matched': 'Matched',
    'mon.col.unmatched': 'Not matched',
    'mon.col.sync': 'Last reading',
    'mon.off': 'Off',
    'mon.sync.now': 'Read',
    'mon.sync.running': 'Reading…',
    'mon.sync.never': 'Not read yet',
    'mon.sync.failed': 'Failed',
    'mon.sync.done': '{n} hosts read from {name}.',
    'mon.sync.every': 'every {n} min',
    'mon.sync.manual': 'by the button',
    'mon.dialog.new': 'New monitoring system',
    'mon.dialog.edit': 'Monitoring system',
    'mon.kind': 'System',
    'mon.name': 'Name',
    'mon.url': 'Address',
    'mon.url.zabbix.hint': 'The address of the Zabbix web interface, for example https://zabbix.example.com; the API is at api_jsonrpc.php there.',
    'mon.url.prometheus.hint': 'The address of the Prometheus HTTP API: Prometheus, VictoriaMetrics, Thanos or Mimir.',
    'mon.url.grafana.hint': 'The address of the Grafana web interface, for example https://grafana.example.com. Alerts and hosts come from Grafana-managed alert rules.',
    'mon.cred': 'Credential',
    'mon.cred.zabbix.hint': 'An outgoing API token (bearer) or a user name and password (basic) from Credentials, for reading hosts: read access is enough. It is not the token Zabbix sends alerts with — that one is made on the Alert intake tab. Secrets are kept in OpenBao.',
    'mon.cred.prometheus.hint': 'Bearer, basic or header credential when the server asks for one; RED/USE rules use it too. Secrets are kept in OpenBao.',
    'mon.cred.grafana.hint': 'A service account token (bearer) with the Viewer role, or a user name and password (basic). It is not the token Grafana sends alerts with — that one is made on the Alert intake tab. Secrets are kept in OpenBao.',
    'mon.cred.none': 'None',
    'mon.cred.missing': 'Create a credential on the Credentials page first.',
    'mon.query': 'Query',
    'mon.query.hint': 'An instant query whose series are the scrape targets. Default: up.',
    'mon.label': 'Host label',
    'mon.label.hint': 'The label that names the host; the port is cut off. Default: instance.',
    'mon.glabel.hint': 'The label of alert instances that names the host; the port is cut off. Empty: the first of {labels} that is set.',
    'mon.poll': 'Read firing alerts through the Grafana Alerting API',
    'mon.poll.hint': 'Besides the contact point: Umbrella reads the alert rules on this interval and hands alerts that began or stopped firing to the connector of the system. Both ways can work together and fold into the same incidents.',
    'mon.poll.every': 'Poll every',
    'mon.seconds': 's',
    'mon.skip': 'Do not verify the TLS certificate',
    'mon.enabled': 'Turned on',
    'mon.enabled.hint': 'Hosts of turned-off systems do not count toward coverage of configuration items and are not read on schedule.',
    'mon.interval': 'Read every',
    'mon.interval.hint': '0 reads only with the button.',
    'mon.minutes': 'min',
    'mon.test': 'Check',
    'mon.test.ok': 'Answers: {hosts} hosts',
    'mon.test.version': 'Version {version}',
    'mon.test.fail': 'The system did not answer',
    'mon.save': 'Save',
    'mon.cancel': 'Cancel',
    'mon.delete': 'Delete',
    'mon.delete.confirm': 'Delete the system "{name}"? Its hosts and hand-made links are forgotten.',
    'mon.saved.read': 'Saved. Reading hosts…',
    'mon.tile.total': 'All hosts',
    'mon.tile.matched': 'Matched with CIs',
    'mon.tile.unmatched': 'Not matched',
    'mon.tile.ambiguous': 'Several candidates',
    'mon.tile.excluded': 'Not a CI',
    'mon.search': 'Host, address, group or CI',
    'mon.filter.source': 'System',
    'mon.filter.any': 'Any',
    'mon.count': 'Shown: {shown} of {total}',
    'mon.limited': 'Only the first {n} hosts are shown: narrow the search.',
    'mon.h.host': 'Host',
    'mon.h.system': 'System',
    'mon.h.addresses': 'Addresses',
    'mon.h.groups': 'Groups / jobs',
    'mon.h.state': 'State',
    'mon.h.ci': 'Configuration item',
    'mon.state.up': 'Up',
    'mon.state.partial': 'Partly down',
    'mon.state.down': 'Down',
    'mon.state.unknown': 'Unknown',
    'mon.state.disabled': 'Disabled',
    'mon.match.name': 'by name',
    'mon.match.short': 'by short name',
    'mon.match.dns': 'by DNS name',
    'mon.match.ip': 'by IP address',
    'mon.match.manual': 'linked by hand',
    'mon.match.excluded': 'Not a CI',
    'mon.match.ambiguous': 'Several candidates',
    'mon.match.none': 'Not matched',
    'mon.also': 'Same machine in: {list}',
    'mon.create.also': 'The same machine in {list} is linked to this item too, so there is one item for all systems.',
    'mon.open': 'Open in the system',
    'mon.act.link': 'Link',
    'mon.act.change': 'Change',
    'mon.act.create': 'Create CI',
    'mon.link.title': 'Link {host}',
    'mon.link.text': 'Pick the configuration item this host is. A link made by hand wins over the automatic match, also for the incidents of the host.',
    'mon.link.search': 'Name, IP address or ID of the CI',
    'mon.link.candidates': 'Candidates',
    'mon.link.results': 'Configuration items',
    'mon.link.nothing': 'Nothing found.',
    'mon.link.none': 'Not a configuration item',
    'mon.link.none.hint': 'For test hosts, templates and the like: the host is no longer counted as not matched, and its incidents are suppressed (not sent anywhere, marked “host excluded”).',
    'mon.link.auto': 'Match automatically',
    'mon.link.save': 'Link',
    'mon.create.title': 'Create a CI from {host}',
    'mon.create.text': 'A configuration item named {name} with the addresses of the host is created and linked to it.',
    'mon.create.kind': 'Kind',
    'mon.create.register': 'Also register in NetBox',
    'mon.create.save': 'Create',
    'mon.kind.device': 'Device',
    'mon.kind.vm': 'Virtual machine',
    'mon.kind.service': 'Service',
    'mon.kind.other': 'Other',
    'err.monitoring_kind': 'Choose Zabbix, Prometheus or Grafana.',
    'err.monitoring_credential_required': 'Zabbix needs a credential: an API token or a user name and password.',
    'err.monitoring_interval': 'The interval is from 0 to 10080 minutes.',
    'err.monitoring_query': 'The query or the label is too long.',
    'err.monitoring_running': 'The host list of this system is already being read.',
    'err.monitoring_poll_interval': 'The poll interval is from 15 to 3600 seconds.',
    'err.poll_running': 'The alerts of this system are already being read.',
    'err.poll_off': 'Polling needs a Grafana system with a connector for its alerts.',
    'err.host_not_found': 'The system no longer has this host: read its host list again.',
    'err.url_invalid': 'Enter an http or https address.',
    'err.name_invalid': 'Enter a name.',
    'err.credential_not_found': 'The credential no longer exists.',
    'err.credential_type': 'This kind of credential cannot be used with this system.',
    'err.too_many_sources': 'Too many monitoring systems.',
    'err.ci_not_found': 'The configuration item no longer exists.',
    'err.link_mode': 'Choose how to link the host.',
    'sys.tab.alerts': 'Alert intake',
    'sys.tab.hosts': 'Hosts',
    'sys.tab.metrics': 'RED/USE metrics',
    'sys.settings': 'Settings',
    'sys.alerts.none.zabbix': 'Alerts of this Zabbix do not reach Umbrella yet. Connect the intake: Umbrella creates a token and a connector and gives you a ready media type for Zabbix.',
    'sys.alerts.none.prometheus': 'Alerts of this Prometheus do not reach Umbrella yet. Connect the intake: Umbrella creates a token and a connector and gives you a ready Alertmanager receiver.',
    'sys.alerts.none.grafana': 'Alerts of this Grafana do not reach Umbrella yet. Connect the intake: Umbrella creates a token and a connector and gives you a ready webhook contact point. The same connector also takes the alerts read by polling.',
    'sys.poll.title': 'Polling the Alerting API',
    'sys.poll.off': 'Off: alerts come only through the contact point. It is turned on in the settings of the system.',
    'sys.poll.every': 'every {n} s',
    'sys.poll.last': 'Last poll',
    'sys.poll.never': 'not yet',
    'sys.poll.result': '{firing} firing, {sent} handed to the connector',
    'sys.poll.failed': 'Failed',
    'sys.poll.now': 'Poll now',
    'sys.poll.unpublished': 'The connector is a draft: polled alerts go to it only once it is published.',
    'sys.alerts.connect': 'Connect the alert intake',
    'sys.alerts.pick': 'or use an existing connector',
    'sys.alerts.pick.none': 'Choose a connector…',
    'sys.alerts.connector': 'Connector',
    'sys.alerts.url': 'Intake address',
    'sys.alerts.last': 'Last delivery',
    'sys.alerts.never': 'nothing in the last 24 hours',
    'sys.alerts.received': '{n} requests in 24 h',
    'sys.alerts.unlink': 'Unlink',
    'sys.alerts.tokens': 'The intake token (the system sends alerts to Umbrella) and the credential of the system (Umbrella reads hosts) are different secrets going opposite ways.',
    'sys.hosts.summary': '{hosts} hosts: {matched} matched with CIs, {unmatched} not matched.',
    'sys.hosts.open': 'Show the hosts',
    'sys.hosts.links': 'Hosts linked by hand to a CI, or marked “Not a CI”, decide which CI the incidents of the host go to; open incidents follow a changed link at once.',
    'sys.metrics.text': 'This Prometheus is a metric source for RED/USE rules with its own address and credential: no separate metric source is needed.',
    'sys.metrics.rules': 'Rules that query it: {n}.',
    'sys.metrics.open': 'Open the rules',
    'err.source_in_use': 'RED/USE rules query this system: move them to another source or delete them first.',
    'err.connector_not_found': 'The connector no longer exists.',
  },
  ru: {
    loading: 'Загрузка…',
    'mon.tab.hosts': 'Хосты',
    'mon.tab.sources': 'Системы',
    'mon.new': 'Добавить систему',
    'mon.kind.zabbix': 'Zabbix',
    'mon.kind.prometheus': 'Prometheus',
    'mon.kind.grafana': 'Grafana',
    'mon.empty.sources': 'Систем мониторинга пока нет. Добавьте Zabbix, Prometheus-совместимый сервер или Grafana, чтобы загрузить список хостов и увидеть, какие КЕ под мониторингом.',
    'mon.empty.hosts': 'Хостов пока нет: загрузите список хостов системы на вкладке «Системы».',
    'mon.empty.filtered': 'Нет хостов под этот фильтр.',
    'mon.col.name': 'Система',
    'mon.col.url': 'Адрес',
    'mon.col.hosts': 'Хосты',
    'mon.col.matched': 'Сопоставлено',
    'mon.col.unmatched': 'Не сопоставлено',
    'mon.col.sync': 'Последняя загрузка',
    'mon.off': 'Выключена',
    'mon.sync.now': 'Загрузить',
    'mon.sync.running': 'Загрузка…',
    'mon.sync.never': 'Ещё не загружались',
    'mon.sync.failed': 'Ошибка',
    'mon.sync.done': 'Из {name} загружено хостов: {n}.',
    'mon.sync.every': 'каждые {n} мин',
    'mon.sync.manual': 'по кнопке',
    'mon.dialog.new': 'Новая система мониторинга',
    'mon.dialog.edit': 'Система мониторинга',
    'mon.kind': 'Система',
    'mon.name': 'Название',
    'mon.url': 'Адрес',
    'mon.url.zabbix.hint': 'Адрес веб-интерфейса Zabbix, например https://zabbix.example.com; API находится там же, в api_jsonrpc.php.',
    'mon.url.prometheus.hint': 'Адрес HTTP API Prometheus, VictoriaMetrics, Thanos или Mimir.',
    'mon.url.grafana.hint': 'Адрес веб-интерфейса Grafana, например https://grafana.example.com. Алерты и хосты берутся из правил алертинга, которыми управляет Grafana.',
    'mon.cred': 'Учётные данные',
    'mon.cred.zabbix.hint': 'Исходящий API-токен (bearer) или имя пользователя и пароль (basic) со страницы «Учётные данные» — для чтения хостов, достаточно права чтения. Это не тот токен, с которым Zabbix отправляет алерты: он создаётся на вкладке «Приём алертов». Секреты хранятся в OpenBao.',
    'mon.cred.prometheus.hint': 'Учётные данные bearer, basic или header, если сервер их требует; ими же пользуются правила RED/USE. Секреты хранятся в OpenBao.',
    'mon.cred.grafana.hint': 'Токен сервисного аккаунта (bearer) с ролью Viewer или имя пользователя и пароль (basic). Это не тот токен, с которым Grafana отправляет алерты, — его создают на вкладке «Приём алертов». Секреты хранятся в OpenBao.',
    'mon.cred.none': 'Нет',
    'mon.cred.missing': 'Сначала создайте учётные данные на странице «Учётные данные».',
    'mon.query': 'Запрос',
    'mon.query.hint': 'Мгновенный запрос, серии которого — цели сбора. По умолчанию up.',
    'mon.label': 'Метка хоста',
    'mon.label.hint': 'Метка с именем хоста; порт отбрасывается. По умолчанию instance.',
    'mon.glabel.hint': 'Метка экземпляров алертов с именем хоста; порт отбрасывается. Пусто: первая заполненная из {labels}.',
    'mon.poll': 'Забирать активные алерты через Grafana Alerting API',
    'mon.poll.hint': 'В дополнение к точке контакта: Umbrella с этим интервалом читает правила алертинга и передаёт коннектору системы алерты, которые начали или перестали срабатывать. Оба способа могут работать вместе и попадают в одни и те же инциденты.',
    'mon.poll.every': 'Опрашивать каждые',
    'mon.seconds': 'с',
    'mon.skip': 'Не проверять сертификат TLS',
    'mon.enabled': 'Включена',
    'mon.enabled.hint': 'Хосты выключенной системы не учитываются в покрытии КЕ и не загружаются по расписанию.',
    'mon.interval': 'Загружать каждые',
    'mon.interval.hint': '0 — только по кнопке.',
    'mon.minutes': 'мин',
    'mon.test': 'Проверить',
    'mon.test.ok': 'Отвечает: хостов {hosts}',
    'mon.test.version': 'Версия {version}',
    'mon.test.fail': 'Система не ответила',
    'mon.save': 'Сохранить',
    'mon.cancel': 'Отмена',
    'mon.delete': 'Удалить',
    'mon.delete.confirm': 'Удалить систему «{name}»? Её хосты и ручные привязки будут забыты.',
    'mon.saved.read': 'Сохранено. Загружаем хосты…',
    'mon.tile.total': 'Всего хостов',
    'mon.tile.matched': 'Сопоставлены с КЕ',
    'mon.tile.unmatched': 'Не сопоставлены',
    'mon.tile.ambiguous': 'Несколько кандидатов',
    'mon.tile.excluded': 'Не КЕ',
    'mon.search': 'Хост, адрес, группа или КЕ',
    'mon.filter.source': 'Система',
    'mon.filter.any': 'Любая',
    'mon.count': 'Показано: {shown} из {total}',
    'mon.limited': 'Показаны первые {n} хостов: уточните поиск.',
    'mon.h.host': 'Хост',
    'mon.h.system': 'Система',
    'mon.h.addresses': 'Адреса',
    'mon.h.groups': 'Группы / задания',
    'mon.h.state': 'Состояние',
    'mon.h.ci': 'КЕ',
    'mon.state.up': 'Доступен',
    'mon.state.partial': 'Частично недоступен',
    'mon.state.down': 'Недоступен',
    'mon.state.unknown': 'Неизвестно',
    'mon.state.disabled': 'Отключён',
    'mon.match.name': 'по имени',
    'mon.match.short': 'по короткому имени',
    'mon.match.dns': 'по DNS-имени',
    'mon.match.ip': 'по IP-адресу',
    'mon.match.manual': 'привязан вручную',
    'mon.match.excluded': 'Не КЕ',
    'mon.match.ambiguous': 'Несколько кандидатов',
    'mon.match.none': 'Не сопоставлен',
    'mon.also': 'Та же машина в: {list}',
    'mon.create.also': 'Та же машина в {list} тоже будет привязана к этой КЕ: одна КЕ на все системы.',
    'mon.open': 'Открыть в системе',
    'mon.act.link': 'Привязать',
    'mon.act.change': 'Изменить',
    'mon.act.create': 'Создать КЕ',
    'mon.link.title': 'Привязка {host}',
    'mon.link.text': 'Выберите КЕ, которой соответствует хост. Ручная привязка важнее автоматического сопоставления — и для инцидентов этого хоста.',
    'mon.link.search': 'Название, IP-адрес или ID КЕ',
    'mon.link.candidates': 'Кандидаты',
    'mon.link.results': 'Конфигурационные единицы',
    'mon.link.nothing': 'Ничего не найдено.',
    'mon.link.none': 'Не является КЕ',
    'mon.link.none.hint': 'Для тестовых хостов, шаблонов Zabbix и подобного: хост больше не считается несопоставленным, а его инциденты подавляются (никуда не отправляются, помечены «хост исключён»).',
    'mon.link.auto': 'Сопоставлять автоматически',
    'mon.link.save': 'Привязать',
    'mon.create.title': 'КЕ из хоста {host}',
    'mon.create.text': 'Будет создана КЕ {name} с адресами хоста и привязана к нему.',
    'mon.create.kind': 'Тип',
    'mon.create.register': 'Зарегистрировать и в NetBox',
    'mon.create.save': 'Создать',
    'mon.kind.device': 'Устройство',
    'mon.kind.vm': 'Виртуальная машина',
    'mon.kind.service': 'Сервис',
    'mon.kind.other': 'Другое',
    'err.monitoring_kind': 'Выберите Zabbix, Prometheus или Grafana.',
    'err.monitoring_credential_required': 'Для Zabbix нужны учётные данные: API-токен или имя пользователя и пароль.',
    'err.monitoring_interval': 'Интервал — от 0 до 10080 минут.',
    'err.monitoring_query': 'Слишком длинный запрос или метка.',
    'err.monitoring_running': 'Список хостов этой системы уже загружается.',
    'err.monitoring_poll_interval': 'Интервал опроса — от 15 до 3600 секунд.',
    'err.poll_running': 'Алерты этой системы уже читаются.',
    'err.poll_off': 'Для опроса нужна система Grafana с коннектором для её алертов.',
    'err.host_not_found': 'В системе больше нет этого хоста: загрузите список хостов заново.',
    'err.url_invalid': 'Введите адрес http или https.',
    'err.name_invalid': 'Введите название.',
    'err.credential_not_found': 'Учётные данные больше не существуют.',
    'err.credential_type': 'Такие учётные данные нельзя использовать с этой системой.',
    'err.too_many_sources': 'Слишком много систем мониторинга.',
    'err.ci_not_found': 'КЕ больше не существует.',
    'err.link_mode': 'Выберите, как привязать хост.',
    'sys.tab.alerts': 'Приём алертов',
    'sys.tab.hosts': 'Хосты',
    'sys.tab.metrics': 'Метрики RED/USE',
    'sys.settings': 'Настройки',
    'sys.alerts.none.zabbix': 'Алерты этого Zabbix пока не попадают в Umbrella. Подключите приём: Umbrella создаст токен и коннектор и даст готовый способ оповещения для Zabbix.',
    'sys.alerts.none.prometheus': 'Алерты этого Prometheus пока не попадают в Umbrella. Подключите приём: Umbrella создаст токен и коннектор и даст готового получателя для Alertmanager.',
    'sys.alerts.none.grafana': 'Алерты этой Grafana пока не попадают в Umbrella. Подключите приём: Umbrella создаст токен и коннектор и даст готовую точку контакта webhook. Этот же коннектор принимает и алерты, полученные опросом.',
    'sys.poll.title': 'Опрос Alerting API',
    'sys.poll.off': 'Выключен: алерты приходят только через точку контакта. Включается в настройках системы.',
    'sys.poll.every': 'каждые {n} с',
    'sys.poll.last': 'Последний опрос',
    'sys.poll.never': 'ещё не было',
    'sys.poll.result': 'активных: {firing}, передано коннектору: {sent}',
    'sys.poll.failed': 'Ошибка',
    'sys.poll.now': 'Опросить сейчас',
    'sys.poll.unpublished': 'Коннектор — черновик: алерты из опроса пойдут в него только после публикации.',
    'sys.alerts.connect': 'Подключить приём алертов',
    'sys.alerts.pick': 'или выбрать существующий коннектор',
    'sys.alerts.pick.none': 'Выберите коннектор…',
    'sys.alerts.connector': 'Коннектор',
    'sys.alerts.url': 'Адрес приёма',
    'sys.alerts.last': 'Последнее событие',
    'sys.alerts.never': 'за 24 часа ничего',
    'sys.alerts.received': 'запросов за 24 ч: {n}',
    'sys.alerts.unlink': 'Отвязать',
    'sys.alerts.tokens': 'Токен приёма (система отправляет алерты в Umbrella) и учётные данные системы (Umbrella читает хосты) — разные секреты, работающие в противоположных направлениях.',
    'sys.hosts.summary': 'Хостов: {hosts}, сопоставлено с КЕ: {matched}, не сопоставлено: {unmatched}.',
    'sys.hosts.open': 'Показать хосты',
    'sys.hosts.links': 'Ручная привязка хоста к КЕ и пометка «Не является КЕ» определяют, к какой КЕ попадут инциденты этого хоста; открытые инциденты переходят сразу после изменения привязки.',
    'sys.metrics.text': 'Этот Prometheus — источник метрик для правил RED/USE со своим адресом и учётными данными: отдельный источник метрик не нужен.',
    'sys.metrics.rules': 'Правил, которые его опрашивают: {n}.',
    'sys.metrics.open': 'Открыть правила',
    'err.source_in_use': 'Эту систему опрашивают правила RED/USE: сначала перенесите их на другой источник или удалите.',
    'err.connector_not_found': 'Коннектора больше нет.',
  },
}
