import type { Dict } from '../../../i18n'

export const policyStrings: Dict = {
  en: {
    'ap.title': 'Incident lifecycle',
    'ap.text': 'How long incidents wait, retry and are kept. An empty field keeps the default shown in it.',
    'ap.window': 'Reopen window, minutes',
    'ap.window.hint': 'An incident resolved this recently opens again on a new event instead of a new incident; RED and USE incidents of one service opened within it are linked.',
    'ap.delay': 'Wait for PagerDuty, seconds',
    'ap.delay.hint': 'How long backup notification waits for PagerDuty to take an incident, unless backup notification sets its own delay.',
    'ap.retry': 'Backup notification retry, minutes',
    'ap.retry.hint': 'A backup notification or follow-up not reported as sent this long after it was handed over is handed over again.',
    'ap.retention': 'Keep resolved incidents, days',
    'ap.retention.hint': 'Older resolved incidents are deleted with their timelines.',
    'ap.test': 'Test incidents, minutes',
    'ap.test.hint': 'A test incident of a connector resolves itself after this long.',
    'ap.default': 'default {v}',
    'err.policy_window_invalid': 'The reopen window is from 0 to 7 days.',
    'err.policy_delay_invalid': 'The wait is from 0 to 24 hours.',
    'err.policy_retry_invalid': 'The retry is from 0 to 24 hours.',
    'err.policy_retention_invalid': 'Keep incidents from 0 to 3650 days.',
    'err.policy_test_invalid': 'Test incidents last from 0 to 24 hours.',
  },
  ru: {
    'ap.title': 'Жизненный цикл инцидентов',
    'ap.text': 'Сколько инциденты ждут, повторяются и хранятся. Пустое поле оставляет значение по умолчанию, показанное в нём.',
    'ap.window': 'Окно переоткрытия, минут',
    'ap.window.hint': 'Инцидент, решённый так недавно, открывается снова на новое событие вместо нового инцидента; инциденты RED и USE одного сервиса, открытые в нём, связываются.',
    'ap.delay': 'Ожидание PagerDuty, секунд',
    'ap.delay.hint': 'Сколько резервное оповещение ждёт, пока PagerDuty возьмёт инцидент, если у резервного оповещения нет своей задержки.',
    'ap.retry': 'Повтор резервного оповещения, минут',
    'ap.retry.hint': 'Резервное оповещение или уведомление о завершении, о котором не сообщили, что оно отправлено, передаётся снова через это время.',
    'ap.retention': 'Хранить решённые инциденты, дней',
    'ap.retention.hint': 'Более старые решённые инциденты удаляются вместе с хронологией.',
    'ap.test': 'Тестовые инциденты, минут',
    'ap.test.hint': 'Тестовый инцидент коннектора решается сам через это время.',
    'ap.default': 'по умолчанию {v}',
    'err.policy_window_invalid': 'Окно переоткрытия от 0 до 7 дней.',
    'err.policy_delay_invalid': 'Ожидание от 0 до 24 часов.',
    'err.policy_retry_invalid': 'Повтор от 0 до 24 часов.',
    'err.policy_retention_invalid': 'Хранить инциденты от 0 до 3650 дней.',
    'err.policy_test_invalid': 'Тестовые инциденты живут от 0 до 24 часов.',
  },
}
