import type { Dict } from '../../../i18n'

export const strings: Dict = {
  en: {
    loading: 'Loading…',
    save: 'Save',
    saved: 'Settings saved.',
    add: 'Add',
    remove: 'Remove',
    none: '—',
    keep: 'Saved; leave empty to keep it',
    'sev.info': 'Info',
    'sev.warning': 'Warning',
    'sev.error': 'Error',
    'sev.critical': 'Critical',

    'pd.title': 'PagerDuty',
    'pd.text':
      'Incidents go to PagerDuty with the Events API v2; acknowledgements and resolutions made there come back by a Webhooks v3 subscription. Keys and tokens are kept in OpenBao.',
    state: 'State',
    'pd.state': 'State',
    'pd.state.on': 'On',
    'pd.state.off': 'Off',
    'pd.state.breaker': 'Paused after failures',
    'pd.sent': 'Sent / failed',
    'pd.queue': 'In the queue',
    'pd.lastSuccess': 'Last delivery',
    'pd.lastError': 'Last error',
    'pd.lastWebhook': 'Last update from PagerDuty',
    'pd.enable': 'Send incidents to PagerDuty',
    'pd.enable.hint': 'Without PagerDuty, error and critical incidents go to backup notification.',
    'pd.public': 'Public address of Umbrella',
    'pd.public.hint': 'Links in PagerDuty, mail and Telegram lead here, and PagerDuty sends its webhooks here. For example https://umbrella.example.com',
    'pd.region': 'Region',
    'pd.region.us': 'US (api.pagerduty.com)',
    'pd.region.eu': 'EU (api.eu.pagerduty.com)',
    'pd.min': 'Lowest severity sent',
    'pd.min.hint': 'Incidents below it stay in Umbrella.',
    'pd.token': 'REST API token',
    'pd.token.hint': 'Optional: lists services, creates integrations and the webhook subscription. A read-write user or account token.',
    'pd.token.check': 'Check token',
    'pd.token.ok': 'The token works.',
    'pd.token.clear': 'Forget the token',
    'pd.default': 'Default integration',
    'pd.default.hint': 'Incidents no route matches go here.',
    'pd.service': 'PagerDuty service',
    'pd.service.pick': 'Pick a service…',
    'pd.service.manual': 'Integration key typed by hand',
    'pd.key': 'Events API v2 integration key',
    'pd.routes': 'Routes',
    'pd.routes.hint': 'The first route that matches a service of the incident, then its team, chooses the PagerDuty service.',
    'pd.route.name': 'Name',
    'pd.route.team': 'Team',
    'pd.route.service': 'Business service',
    'pd.route.any': 'Any',
    'pd.route.add': 'Add route',
    'pd.webhook': 'Status updates from PagerDuty',
    'pd.webhook.url': 'Webhook address',
    'pd.webhook.on': 'Subscribed',
    'pd.webhook.off': 'Not subscribed',
    'pd.webhook.subscribe': 'Subscribe',
    'pd.webhook.unsubscribe': 'Unsubscribe',
    'pd.webhook.secret': 'Signing secret',
    'pd.webhook.secret.hint': 'Only when the subscription was made by hand in PagerDuty.',
    'pd.webhook.nourl': 'Set the public address first.',
    'pd.test': 'Send a test incident',
    'pd.test.ok': 'A test incident was triggered and resolved in PagerDuty.',

    'pd.settings': 'PagerDuty settings',
    'pd.set': 'Integration key set',
    'pd.notset': 'Not set',
    'pd.off': 'PagerDuty is off. Its settings are kept and apply again when it is turned on.',
    'nt.settings': 'Channels',
    'nt.extra.n.emails': '{n} addresses',
    'nt.extra.n.chats': '{n} chats',
    'nt.title': 'Backup notification',
    'nt.text':
      'When PagerDuty has not taken an error or critical incident in two minutes, the team of its business service (or the people responsible for the CI) get it by mail and from the Telegram bot, with a link that acknowledges it.',
    'nt.links.off': 'Acknowledgement links are off until the public address is set in the PagerDuty settings.',
    'nt.email': 'E-mail',
    'nt.email.enable': 'Send by e-mail',
    'nt.host': 'SMTP server',
    'nt.port': 'Port',
    'nt.port.hint': 'Empty: 587 for STARTTLS, 465 for TLS, 25 without encryption.',
    'nt.security': 'Encryption',
    'nt.security.starttls': 'STARTTLS',
    'nt.security.tls': 'TLS',
    'nt.security.none': 'None (internal relay)',
    'nt.skip': 'Do not check the server certificate',
    'nt.user': 'User name',
    'nt.password': 'Password',
    'nt.from': 'Sender',
    'nt.from.hint': 'For example Umbrella <umbrella@example.com>',
    'nt.telegram': 'Telegram bot',
    'nt.telegram.enable': 'Send from the Telegram bot',
    'nt.token': 'Bot token',
    'nt.token.hint': 'From @BotFather. People write to the bot once and put their chat ID in their profile.',
    'nt.api': 'Bot API address',
    'nt.api.hint': 'Optional: a proxy instead of https://api.telegram.org',
    'nt.extra': 'Always also notify',
    'nt.extra.emails': 'Addresses',
    'nt.extra.emails.hint': 'One per line: a duty mailbox, a distribution list.',
    'nt.extra.chats': 'Telegram chats',
    'nt.extra.chats.hint': 'One per line: a group chat ID (negative) or @channel. Add the bot to the group first.',
    'nt.test': 'Send a test',
    'nt.test.to': 'Test recipient',
    'nt.test.to.email': 'Empty: your e-mail',
    'nt.test.to.chat': 'Empty: your Telegram chat',
    'nt.test.ok': 'Sent to {to}.',
    'nt.test.okBot': 'Sent to {to} by @{bot}.',
    'nt.test.saveFirst': 'Tests use the saved settings: save first.',

    'gf.title': 'Grafana context',
    'gf.text': 'The incident card, PagerDuty and backup notification link to a Grafana dashboard opened on the time of the incident with its CI, service and team as variables.',
    'gf.dashboard': 'Dashboard address',
    'gf.dashboard.hint': 'Its own query parameters (orgId, fixed variables) are kept. Empty: no Grafana links.',
    'gf.window': 'Minutes around the incident',
    'gf.window.hint': 'Shown before it opened and after it ended.',
    'gf.vars': 'Variables passed: var-ci, var-ci_id, var-service, var-team, var-signal, var-incident.',
    'err.window_invalid': 'From 1 to 1440 minutes.',
    'err.public_url_invalid': 'The public address must be an http or https URL without a query.',
    'err.routing_key_required': 'Set the default integration or add a route.',
    'err.route_name': 'Every route needs a name.',
    'err.route_match': 'A route must match a team or a business service.',
    'err.route_key': 'Every route needs an integration key or a PagerDuty service.',
    'err.pagerduty_failed': 'PagerDuty refused the request.',
    'err.public_url_required': 'Set the public address first.',
    'err.email_incomplete': 'Mail needs an SMTP server and a sender.',
    'err.email_invalid': 'An address is not valid.',
    'err.telegram_invalid': 'A chat ID is a number (negative for groups) or @channel_name.',
    'err.from_invalid': 'The sender is not a valid address.',
    'err.token_required': 'Enter the bot token.',
    'err.channel_disabled': 'Turn the channel on and save first.',
    'err.notify_failed': 'The message was not sent.',
    'err.secrets_unavailable': 'OpenBao is not available, so the secret was not saved.',
  },
  ru: {
    loading: 'Загрузка…',
    save: 'Сохранить',
    saved: 'Настройки сохранены.',
    add: 'Добавить',
    remove: 'Удалить',
    none: '—',
    keep: 'Сохранён; оставьте пустым, чтобы не менять',
    'sev.info': 'Инфо',
    'sev.warning': 'Предупреждение',
    'sev.error': 'Ошибка',
    'sev.critical': 'Критично',

    'pd.title': 'PagerDuty',
    'pd.text':
      'Инциденты уходят в PagerDuty через Events API v2; подтверждения и решения, сделанные там, возвращаются по подписке Webhooks v3. Ключи и токены хранятся в OpenBao.',
    state: 'Состояние',
    'pd.state': 'Состояние',
    'pd.state.on': 'Включено',
    'pd.state.off': 'Выключено',
    'pd.state.breaker': 'Пауза после сбоев',
    'pd.sent': 'Отправлено / ошибок',
    'pd.queue': 'В очереди',
    'pd.lastSuccess': 'Последняя доставка',
    'pd.lastError': 'Последняя ошибка',
    'pd.lastWebhook': 'Последнее обновление из PagerDuty',
    'pd.enable': 'Отправлять инциденты в PagerDuty',
    'pd.enable.hint': 'Без PagerDuty инциденты уровня «ошибка» и «критично» уходят в резервное оповещение.',
    'pd.public': 'Публичный адрес Umbrella',
    'pd.public.hint': 'Сюда ведут ссылки из PagerDuty, почты и Telegram, и сюда PagerDuty шлёт вебхуки. Например https://umbrella.example.com',
    'pd.region': 'Регион',
    'pd.region.us': 'США (api.pagerduty.com)',
    'pd.region.eu': 'ЕС (api.eu.pagerduty.com)',
    'pd.min': 'Минимальная важность',
    'pd.min.hint': 'Инциденты ниже остаются в Umbrella.',
    'pd.token': 'Токен REST API',
    'pd.token.hint': 'Необязательно: нужен для списка сервисов, создания интеграций и подписки на вебхуки. Токен пользователя или учётной записи с правом записи.',
    'pd.token.check': 'Проверить токен',
    'pd.token.ok': 'Токен работает.',
    'pd.token.clear': 'Забыть токен',
    'pd.default': 'Интеграция по умолчанию',
    'pd.default.hint': 'Сюда идут инциденты, которым не подошёл ни один маршрут.',
    'pd.service': 'Сервис PagerDuty',
    'pd.service.pick': 'Выберите сервис…',
    'pd.service.manual': 'Ключ интеграции введён вручную',
    'pd.key': 'Ключ интеграции Events API v2',
    'pd.routes': 'Маршруты',
    'pd.routes.hint': 'Сервис PagerDuty выбирает первый маршрут, подошедший бизнес-сервису инцидента, затем его команде.',
    'pd.route.name': 'Название',
    'pd.route.team': 'Команда',
    'pd.route.service': 'Бизнес-сервис',
    'pd.route.any': 'Любой',
    'pd.route.add': 'Добавить маршрут',
    'pd.webhook': 'Обновления статусов из PagerDuty',
    'pd.webhook.url': 'Адрес вебхука',
    'pd.webhook.on': 'Подписка есть',
    'pd.webhook.off': 'Подписки нет',
    'pd.webhook.subscribe': 'Подписаться',
    'pd.webhook.unsubscribe': 'Отписаться',
    'pd.webhook.secret': 'Секрет подписи',
    'pd.webhook.secret.hint': 'Только если подписка создана вручную в PagerDuty.',
    'pd.webhook.nourl': 'Сначала задайте публичный адрес.',
    'pd.test': 'Отправить тестовый инцидент',
    'pd.test.ok': 'Тестовый инцидент открыт и решён в PagerDuty.',

    'pd.settings': 'Настройки PagerDuty',
    'pd.set': 'Ключ интеграции задан',
    'pd.notset': 'Не задана',
    'pd.off': 'PagerDuty выключен. Настройки сохраняются и снова действуют после включения.',
    'nt.settings': 'Каналы',
    'nt.extra.n.emails': 'адресов: {n}',
    'nt.extra.n.chats': 'чатов: {n}',
    'nt.title': 'Резервное оповещение',
    'nt.text':
      'Если PagerDuty за две минуты не принял инцидент уровня «ошибка» или «критично», команда его бизнес-сервиса (или ответственные за КЕ) получают его по почте и от Telegram-бота со ссылкой для подтверждения.',
    'nt.links.off': 'Ссылки для подтверждения выключены, пока в настройках PagerDuty не задан публичный адрес.',
    'nt.email': 'Почта',
    'nt.email.enable': 'Отправлять по почте',
    'nt.host': 'SMTP-сервер',
    'nt.port': 'Порт',
    'nt.port.hint': 'Пусто: 587 для STARTTLS, 465 для TLS, 25 без шифрования.',
    'nt.security': 'Шифрование',
    'nt.security.starttls': 'STARTTLS',
    'nt.security.tls': 'TLS',
    'nt.security.none': 'Нет (внутренний релей)',
    'nt.skip': 'Не проверять сертификат сервера',
    'nt.user': 'Имя пользователя',
    'nt.password': 'Пароль',
    'nt.from': 'Отправитель',
    'nt.from.hint': 'Например Umbrella <umbrella@example.com>',
    'nt.telegram': 'Telegram-бот',
    'nt.telegram.enable': 'Отправлять от Telegram-бота',
    'nt.token': 'Токен бота',
    'nt.token.hint': 'Выдаёт @BotFather. Сотрудник один раз пишет боту и указывает ID чата в профиле.',
    'nt.api': 'Адрес Bot API',
    'nt.api.hint': 'Необязательно: прокси вместо https://api.telegram.org',
    'nt.extra': 'Всегда оповещать также',
    'nt.extra.emails': 'Адреса',
    'nt.extra.emails.hint': 'По одному в строке: дежурный ящик, рассылка.',
    'nt.extra.chats': 'Чаты Telegram',
    'nt.extra.chats.hint': 'По одному в строке: ID группы (отрицательный) или @канал. Сначала добавьте бота в группу.',
    'nt.test': 'Отправить проверку',
    'nt.test.to': 'Получатель проверки',
    'nt.test.to.email': 'Пусто: ваша почта',
    'nt.test.to.chat': 'Пусто: ваш чат Telegram',
    'nt.test.ok': 'Отправлено: {to}.',
    'nt.test.okBot': 'Отправлено: {to}, бот @{bot}.',
    'nt.test.saveFirst': 'Проверка идёт по сохранённым настройкам: сначала сохраните.',

    'gf.title': 'Контекст в Grafana',
    'gf.text': 'Карточка инцидента, PagerDuty и резервное оповещение ведут на дашборд Grafana, открытый на времени инцидента, с его КЕ, сервисом и командой в переменных.',
    'gf.dashboard': 'Адрес дашборда',
    'gf.dashboard.hint': 'Его собственные параметры (orgId, фиксированные переменные) сохраняются. Пусто: ссылок на Grafana нет.',
    'gf.window': 'Минут вокруг инцидента',
    'gf.window.hint': 'Показываются до открытия и после завершения.',
    'gf.vars': 'Передаются переменные: var-ci, var-ci_id, var-service, var-team, var-signal, var-incident.',
    'err.window_invalid': 'От 1 до 1440 минут.',
    'err.public_url_invalid': 'Публичный адрес должен быть URL http или https без параметров.',
    'err.routing_key_required': 'Задайте интеграцию по умолчанию или добавьте маршрут.',
    'err.route_name': 'У каждого маршрута должно быть название.',
    'err.route_match': 'Маршрут должен выбирать команду или бизнес-сервис.',
    'err.route_key': 'Каждому маршруту нужен ключ интеграции или сервис PagerDuty.',
    'err.pagerduty_failed': 'PagerDuty отклонил запрос.',
    'err.public_url_required': 'Сначала задайте публичный адрес.',
    'err.email_incomplete': 'Для почты нужны SMTP-сервер и отправитель.',
    'err.email_invalid': 'Адрес указан неверно.',
    'err.telegram_invalid': 'ID чата — число (отрицательное для групп) или @имя_канала.',
    'err.from_invalid': 'Отправитель указан неверно.',
    'err.token_required': 'Введите токен бота.',
    'err.channel_disabled': 'Сначала включите канал и сохраните.',
    'err.notify_failed': 'Сообщение не отправлено.',
    'err.secrets_unavailable': 'OpenBao недоступен, поэтому секрет не сохранён.',
  },
}
