import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'tv.new': 'New board',
    'tv.empty': 'No TV boards yet. A board is a page of incidents for a wall screen: it opens without signing in, only from the networks you allow.',
    'tv.on': 'On',
    'tv.off': 'Turned off',
    'tv.link': 'Address',
    'tv.copy': 'Copy link',
    'tv.copied': 'Copied',
    'tv.open': 'Open',
    'tv.edit': 'Edit',
    'tv.rotate': 'New address',
    'tv.rotate.confirm': 'Give “{name}” a new address? Screens on the old one stop getting data until they open the new link.',
    'tv.delete': 'Delete',
    'tv.delete.confirm': 'Delete the board “{name}”? Screens showing it stop getting data.',
    'tv.row.scope': 'Shows',
    'tv.row.scope.all': 'All incidents',
    'tv.row.severity': 'Severity',
    'tv.row.severity.all': 'Any',
    'tv.row.extra': 'Also shows',
    'tv.row.extra.none': 'Only open incidents outside maintenance',
    'tv.row.sources': 'Allowed networks',
    'tv.row.screen': 'Screen',
    'tv.row.seen': 'Last opened',
    'tv.row.seen.never': 'Not opened since the server started',
    'tv.screen': 'refresh every {n} s · language: {locale} · time zone: {zone} · theme: {theme}',
    'tv.default.short': 'system default',
    'tv.extra.acked': 'acknowledged',
    'tv.extra.mw': 'in maintenance',
    'tv.seen': '{time} from {ip}',
    'tv.services': '{n} services',
    'tv.cis': '{n} CIs',
    'tv.teams': '{n} teams',
    'tv.dialog.new': 'New TV board',
    'tv.dialog.edit': 'TV board',
    'tv.name': 'Name',
    'tv.name.ph': 'For example: NOC wall, 3rd floor',
    'tv.scope': 'Business services, CIs and teams',
    'tv.scope.hint': 'The board shows incidents of any chosen item: the chosen CIs, every CI of the chosen services, and incidents routed to the chosen teams. Choose nothing to show all incidents.',
    'tv.search': 'Find a service, CI or team',
    'tv.found.services': 'Services',
    'tv.found.cis': 'CIs',
    'tv.found.teams': 'Teams',
    'tv.nothing': 'Nothing found.',
    'tv.remove': 'Remove {name}',
    'tv.missing': 'deleted',
    'tv.severities': 'Severity',
    'tv.severities.hint': 'Choose none to show every severity.',
    'tv.show.acked': 'Show acknowledged incidents',
    'tv.show.acked.hint': 'They stay on the board, dimmed, until resolved.',
    'tv.show.mw': 'Show incidents in maintenance',
    'tv.show.mw.hint': 'Incidents covered by a maintenance window, marked as such.',
    'tv.sources': 'Allowed addresses and networks',
    'tv.sources.ph': '10.20.0.0/16\n192.168.5.40',
    'tv.sources.hint': 'One per line: an address such as 192.168.5.40 or a network such as 10.20.0.0/16. The board opens only from these.',
    'tv.sources.mine': 'Add my address ({ip})',
    'tv.screen.title': 'Screen',
    'tv.refresh': 'Refresh period',
    'tv.refresh.hint': 'How often the screen asks for new data.',
    'tv.refresh.s': '{n} s',
    'tv.refresh.m': '{n} min',
    'tv.locale': 'Language',
    'tv.locale.default': 'System default',
    'tv.timezone': 'Time zone of the clock',
    'tv.timezone.default': 'System default',
    'tv.theme': 'Theme',
    'tv.theme.dark': 'Dark',
    'tv.theme.light': 'Light',
    'tv.disabled': 'Turn the board off',
    'tv.disabled.hint': 'Screens show that the board is not available.',
    'tv.save': 'Save',
    'tv.cancel': 'Cancel',
    'tv.proxies.title': 'Trusted proxies',
    'tv.proxies.text':
      'If Umbrella stands behind a reverse proxy or load balancer, list it here. Only for these addresses is the X-Forwarded-For header believed when a screen address is checked; otherwise the address of the connection is used.',
    'tv.proxies.none': 'None: the address of the connection is checked',
    'tv.proxies.label': 'Proxy addresses and networks',
    'tv.proxies.save': 'Save proxies',
    'tv.proxies.saved': 'Saved',
    'tv.yourip': 'This browser reaches Umbrella from {ip}.',
    'err.name_invalid': 'Enter a name of up to 100 characters.',
    'err.sources_required': 'Add at least one address or network the board opens from.',
    'err.source_invalid': 'An allowed address or network is not valid.',
    'err.too_many_sources': 'Too many allowed networks; 100 at most.',
    'err.refresh_invalid': 'The refresh period must be between 5 seconds and 10 minutes.',
    'err.severity_invalid': 'Unknown severity.',
    'err.too_many_targets': 'Too many services, CIs and teams on one board.',
    'err.too_many_boards': 'There are too many boards already.',
    'err.ci_not_found': 'A chosen CI no longer exists.',
    'err.service_not_found': 'A chosen service no longer exists.',
    'err.team_not_found': 'A chosen team no longer exists.',
    'err.proxy_invalid': 'A proxy address or network is not valid.',
    'err.too_many_proxies': 'Too many trusted proxies; 50 at most.',
  },
  ru: {
    'tv.new': 'Новая панель',
    'tv.empty': 'ТВ-панелей пока нет. Панель — это страница инцидентов для настенного экрана: она открывается без входа в систему и только из разрешённых сетей.',
    'tv.on': 'Включена',
    'tv.off': 'Выключена',
    'tv.link': 'Адрес',
    'tv.copy': 'Скопировать ссылку',
    'tv.copied': 'Скопировано',
    'tv.open': 'Открыть',
    'tv.edit': 'Изменить',
    'tv.rotate': 'Новый адрес',
    'tv.rotate.confirm': 'Выдать панели «{name}» новый адрес? Экраны со старым адресом перестанут получать данные, пока не откроют новую ссылку.',
    'tv.delete': 'Удалить',
    'tv.delete.confirm': 'Удалить панель «{name}»? Экраны с ней перестанут получать данные.',
    'tv.row.scope': 'Показывает',
    'tv.row.scope.all': 'Все инциденты',
    'tv.row.severity': 'Важность',
    'tv.row.severity.all': 'Любая',
    'tv.row.extra': 'Дополнительно',
    'tv.row.extra.none': 'Только открытые инциденты вне сервисных окон',
    'tv.row.sources': 'Разрешённые сети',
    'tv.row.screen': 'Экран',
    'tv.row.seen': 'Последнее открытие',
    'tv.row.seen.never': 'Не открывалась с запуска сервера',
    'tv.screen': 'обновление каждые {n} с · язык: {locale} · пояс: {zone} · тема: {theme}',
    'tv.default.short': 'системный',
    'tv.extra.acked': 'подтверждённые',
    'tv.extra.mw': 'в сервисных окнах',
    'tv.seen': '{time} с адреса {ip}',
    'tv.services': 'сервисов: {n}',
    'tv.cis': 'КЕ: {n}',
    'tv.teams': 'команд: {n}',
    'tv.dialog.new': 'Новая ТВ-панель',
    'tv.dialog.edit': 'ТВ-панель',
    'tv.name': 'Название',
    'tv.name.ph': 'Например: стена NOC, 3 этаж',
    'tv.scope': 'Бизнес-сервисы, КЕ и команды',
    'tv.scope.hint': 'Панель показывает инциденты любого выбранного объекта: выбранных КЕ, всех КЕ выбранных сервисов и инциденты, назначенные выбранным командам. Ничего не выбрано — показываются все инциденты.',
    'tv.search': 'Найти сервис, КЕ или команду',
    'tv.found.services': 'Сервисы',
    'tv.found.cis': 'КЕ',
    'tv.found.teams': 'Команды',
    'tv.nothing': 'Ничего не найдено.',
    'tv.remove': 'Убрать {name}',
    'tv.missing': 'удалён',
    'tv.severities': 'Важность',
    'tv.severities.hint': 'Ничего не выбрано — показывается любая важность.',
    'tv.show.acked': 'Показывать подтверждённые инциденты',
    'tv.show.acked.hint': 'Они остаются на панели, приглушёнными, до решения.',
    'tv.show.mw': 'Показывать инциденты в сервисных окнах',
    'tv.show.mw.hint': 'Инциденты, попавшие в сервисное окно, с соответствующей отметкой.',
    'tv.sources': 'Разрешённые адреса и сети',
    'tv.sources.ph': '10.20.0.0/16\n192.168.5.40',
    'tv.sources.hint': 'По одному в строке: адрес, например 192.168.5.40, или сеть, например 10.20.0.0/16. Панель открывается только с них.',
    'tv.sources.mine': 'Добавить мой адрес ({ip})',
    'tv.screen.title': 'Экран',
    'tv.refresh': 'Период обновления',
    'tv.refresh.hint': 'Как часто экран запрашивает новые данные.',
    'tv.refresh.s': '{n} с',
    'tv.refresh.m': '{n} мин',
    'tv.locale': 'Язык',
    'tv.locale.default': 'Системный по умолчанию',
    'tv.timezone': 'Часовой пояс часов',
    'tv.timezone.default': 'Системный по умолчанию',
    'tv.theme': 'Тема',
    'tv.theme.dark': 'Тёмная',
    'tv.theme.light': 'Светлая',
    'tv.disabled': 'Выключить панель',
    'tv.disabled.hint': 'Экраны покажут, что панель недоступна.',
    'tv.save': 'Сохранить',
    'tv.cancel': 'Отмена',
    'tv.proxies.title': 'Доверенные прокси',
    'tv.proxies.text':
      'Если Umbrella стоит за обратным прокси или балансировщиком, укажите его здесь. Заголовку X-Forwarded-For верим только от этих адресов; иначе проверяется адрес соединения.',
    'tv.proxies.none': 'Нет: проверяется адрес соединения',
    'tv.proxies.label': 'Адреса и сети прокси',
    'tv.proxies.save': 'Сохранить прокси',
    'tv.proxies.saved': 'Сохранено',
    'tv.yourip': 'Этот браузер обращается к Umbrella с адреса {ip}.',
    'err.name_invalid': 'Введите название длиной до 100 символов.',
    'err.sources_required': 'Добавьте хотя бы один адрес или сеть, с которых открывается панель.',
    'err.source_invalid': 'Разрешённый адрес или сеть указаны неверно.',
    'err.too_many_sources': 'Слишком много разрешённых сетей; не больше 100.',
    'err.refresh_invalid': 'Период обновления — от 5 секунд до 10 минут.',
    'err.severity_invalid': 'Неизвестная важность.',
    'err.too_many_targets': 'Слишком много сервисов, КЕ и команд на одной панели.',
    'err.too_many_boards': 'Панелей уже слишком много.',
    'err.ci_not_found': 'Выбранная КЕ больше не существует.',
    'err.service_not_found': 'Выбранный сервис больше не существует.',
    'err.team_not_found': 'Выбранная команда больше не существует.',
    'err.proxy_invalid': 'Адрес или сеть прокси указаны неверно.',
    'err.too_many_proxies': 'Слишком много доверенных прокси; не больше 50.',
  },
}
