import type { Dict } from '../../i18n'

export const mobileStrings: Dict = {
  en: {
    'm.tabs': 'Main sections',
    'm.tab.overview': 'Overview',
    'm.tab.incidents': 'Incidents',
    'm.tab.cmdb': 'Services',
    'm.tab.services': 'Services',
    'm.tab.maintenance': 'Windows',
    'm.tab.more': 'More',
    'm.more.title': 'All sections',
    'm.more.mobile': 'On the phone',
    'm.more.desktop': 'Better on a computer',
    'm.more.desktop.hint': 'Editors and settings with wide tables and canvases',
    'm.more.profile': 'Profile and preferences',
    'm.close': 'Close',
    'm.badge': '{n} active',
    'm.desktop.title': 'The «{page}» section is made for a computer',
    'm.desktop.text': 'The page has wide tables, a canvas or long forms that do not fit a phone screen. Open it on a computer, or open it here anyway.',
    'm.desktop.open': 'Open anyway',
    'm.desktop.home': 'Home',
    'm.ov.title': 'Overview',
    'm.ov.calm': 'All quiet',
    'm.ov.calm.text': 'No active incidents in your scope.',
    'm.ov.active': '{n} active incidents',
    'm.ov.active.one': '1 active incident',
    'm.ov.active.text': '{open} not acknowledged · {acked} acknowledged',
    'm.ov.top': 'Top priority now: {priority}',
    'm.ov.updated': 'Updated {time}',
    'm.ov.priorities': 'By priority',
    'm.ov.attention': 'Needs attention',
    'm.ov.attention.none': 'Every active incident is acknowledged.',
    'm.ov.all': 'All incidents',
    'm.ov.services': 'Services with problems',
    'm.ov.services.none': 'Every business service is healthy.',
    'm.ov.services.all': 'Service map',
    'm.ov.services.cis': '{n} CIs with problems',
    'm.ov.maintenance': 'Maintenance windows',
    'm.ov.maintenance.none': 'No current or planned windows.',
    'm.ov.maintenance.all': 'All windows',
    'm.ov.mw.active': 'now · until {end}',
    'm.ov.mw.planned': 'from {start}',
    'm.ov.flags': 'Delivery',
    'm.ov.flag.pd': 'Not taken by PagerDuty',
    'm.ov.flag.fallback': 'Backup notification',
    'm.ov.flag.suppressed': 'In maintenance',
    'm.ov.loading': 'Loading…',
    'm.ack': 'Acknowledge',
    'm.acked': 'Acknowledged',
    'm.acked.toast': '{id} is acknowledged',
    'm.filters': 'Filters',
    'm.filters.n': 'Filters · {n}',
    'm.select': 'Select',
    'm.select.done': 'Done',
    'm.health.critical': 'Critical',
    'm.health.warning': 'Degraded',
    'm.health.ok': 'Healthy',
    'm.health.unknown': 'Unknown',
    'm.map.services': 'Business services',
    'm.map.cis': 'Configuration items',
    'm.map.cis.n': '{n} CIs',
    'm.map.empty': 'Nothing matches the search.',
  },
  ru: {
    'm.tabs': 'Основные разделы',
    'm.tab.overview': 'Обзор',
    'm.tab.incidents': 'Инциденты',
    'm.tab.cmdb': 'Сервисы',
    'm.tab.services': 'Сервисы',
    'm.tab.maintenance': 'Окна',
    'm.tab.more': 'Ещё',
    'm.more.title': 'Все разделы',
    'm.more.mobile': 'На телефоне',
    'm.more.desktop': 'Удобнее на компьютере',
    'm.more.desktop.hint': 'Редакторы и настройки с широкими таблицами и холстами',
    'm.more.profile': 'Профиль и настройки',
    'm.close': 'Закрыть',
    'm.badge': 'Активных: {n}',
    'm.desktop.title': 'Раздел «{page}» рассчитан на компьютер',
    'm.desktop.text': 'На странице широкие таблицы, холст или длинные формы, которые не помещаются на экране телефона. Откройте её на компьютере или всё равно здесь.',
    'm.desktop.open': 'Открыть всё равно',
    'm.desktop.home': 'На главную',
    'm.ov.title': 'Обзор',
    'm.ov.calm': 'Всё спокойно',
    'm.ov.calm.text': 'В вашей зоне нет активных инцидентов.',
    'm.ov.active': 'Активных инцидентов: {n}',
    'm.ov.active.one': 'Один активный инцидент',
    'm.ov.active.text': 'Не подтверждено: {open} · подтверждено: {acked}',
    'm.ov.top': 'Наивысший приоритет сейчас: {priority}',
    'm.ov.updated': 'Обновлено {time}',
    'm.ov.priorities': 'По приоритетам',
    'm.ov.attention': 'Требуют внимания',
    'm.ov.attention.none': 'Все активные инциденты подтверждены.',
    'm.ov.all': 'Все инциденты',
    'm.ov.services': 'Сервисы с проблемами',
    'm.ov.services.none': 'Все бизнес-сервисы в норме.',
    'm.ov.services.all': 'Карта сервисов',
    'm.ov.services.cis': 'КЕ с проблемами: {n}',
    'm.ov.maintenance': 'Сервисные окна',
    'm.ov.maintenance.none': 'Текущих и запланированных окон нет.',
    'm.ov.maintenance.all': 'Все окна',
    'm.ov.mw.active': 'идёт · до {end}',
    'm.ov.mw.planned': 'с {start}',
    'm.ov.flags': 'Доставка',
    'm.ov.flag.pd': 'Не принято PagerDuty',
    'm.ov.flag.fallback': 'Резервное оповещение',
    'm.ov.flag.suppressed': 'На обслуживании',
    'm.ov.loading': 'Загрузка…',
    'm.ack': 'Подтвердить',
    'm.acked': 'Подтверждён',
    'm.acked.toast': '{id} подтверждён',
    'm.filters': 'Фильтры',
    'm.filters.n': 'Фильтры · {n}',
    'm.select': 'Выбрать',
    'm.select.done': 'Готово',
    'm.health.critical': 'Авария',
    'm.health.warning': 'Деградация',
    'm.health.ok': 'В норме',
    'm.health.unknown': 'Неизвестно',
    'm.map.services': 'Бизнес-сервисы',
    'm.map.cis': 'Конфигурационные единицы',
    'm.map.cis.n': 'КЕ: {n}',
    'm.map.empty': 'По запросу ничего не найдено.',
  },
}
