import type { Dict } from '../i18n'

export const ldapStrings: Dict = {
  en: {
    'ld.hint.tls': 'The directory accepts passwords only over an encrypted connection: use ldaps://…:636 or turn on StartTLS.',
    'ld.hint.cert':
      'Paste the CA certificate that issued the directory certificate, or (test environments only) turn off certificate verification. The address must match a name in the certificate.',
    'ld.hint.loopback':
      'Umbrella runs in a container, so localhost is the Umbrella container itself. Use the directory host name, for example ldaps://dc1.corp.umbrella.lab:636 in the shared Docker network.',
    'ld.attrs.hint': 'LDAP attributes Umbrella reads at every sign-in. Leave a field empty to skip it.',
    'ld.attr.username_attr': 'Login',
    'ld.attr.name_attr': 'Display name',
    'ld.attr.last_name_attr': 'Last name',
    'ld.attr.first_name_attr': 'First name',
    'ld.attr.middle_name_attr': 'Middle name',
    'ld.attr.title_attr': 'Job title',
    'ld.attr.department_attr': 'Department',
    'ld.attr.manager_attr': 'Manager (DN)',
    'ld.attr.email_attr': 'E-mail',
    'ld.attr.photo_attr': 'Photo',
    'ld.photo': 'Photo',
    'ld.kind': 'Directory type',
    'ld.kind.ad': 'Active Directory',
    'ld.kind.openldap': 'OpenLDAP and compatible',
    'ld.url': 'Server address',
    'ld.url.hint': 'ldaps://dc1.corp.example:636 or ldap://dc1.corp.example:389',
    'ld.starttls': 'Use StartTLS',
    'ld.starttls.hint': 'Upgrades an ldap:// connection to TLS.',
    'ld.bindDn': 'Service account',
    'ld.bindDn.hint.ad': 'DN or user@domain, for example svc-umbrella@corp.example',
    'ld.bindDn.hint.openldap': 'DN, for example cn=umbrella,ou=services,dc=example,dc=org',
    'ld.bindPassword': 'Service account password',
    'ld.baseDn': 'Search base (DN)',
    'ld.baseDn.hint': 'For example DC=corp,DC=example',
    'ld.filter': 'User filter',
    'ld.filter.hint': '{username} is replaced with the escaped login.',
    'ld.attrs': 'Attributes',
    'ld.adminGroup': 'Administrators group (DN)',
    'ld.adminGroup.hint': 'Members get administrator rights. Nested groups count in Active Directory.',
    'ld.testUser': 'Test user',
    'ld.testUser.hint': 'Optional: check that a user is found and, with a password, can sign in.',
    'ld.testUsername': 'Login',
    'ld.testPassword': 'Password',
    'ld.ok': 'Directory is reachable',
    'ld.ok.text': 'Service account signed in, search base found.',
    'ld.ok.group': 'Administrators group found.',
    'ld.user': 'User {name} found ({dn}).',
    'ld.user.auth': 'Password accepted.',
    'ld.user.admin': 'Member of the administrators group.',
    'ld.user.notAdmin': 'Not a member of the administrators group.',
    'ld.fail': 'Directory check failed',
    'ld.optional': 'optional',
    'ld.tls': 'TLS',
    'ld.ca': 'CA certificate (PEM)',
    'ld.ca.hint': 'Needed when the directory uses a certificate from an internal CA.',
    'ld.skip': 'Do not verify the certificate',
    'ld.skip.hint': 'Only for test environments: the connection can be intercepted.',
    'ld.row.title': 'Job title',
    'ld.row.department': 'Department',
    'ld.row.manager': 'Manager',
    'ld.row.email': 'E-mail',
  },
  ru: {
    'ld.hint.tls': 'Каталог принимает пароли только по зашифрованному соединению: укажите ldaps://…:636 или включите StartTLS.',
    'ld.hint.cert':
      'Вставьте сертификат CA, выпустивший сертификат каталога, или (только в тестовой среде) отключите проверку сертификата. Адрес должен совпадать с именем в сертификате.',
    'ld.hint.loopback':
      'Umbrella работает в контейнере, и localhost — это сам контейнер Umbrella. Укажите имя хоста каталога, например ldaps://dc1.corp.umbrella.lab:636 в общей сети Docker.',
    'ld.attrs.hint': 'Атрибуты LDAP, которые Umbrella читает при каждом входе. Оставьте поле пустым, чтобы не использовать атрибут.',
    'ld.attr.username_attr': 'Логин',
    'ld.attr.name_attr': 'Отображаемое имя',
    'ld.attr.last_name_attr': 'Фамилия',
    'ld.attr.first_name_attr': 'Имя',
    'ld.attr.middle_name_attr': 'Отчество',
    'ld.attr.title_attr': 'Должность',
    'ld.attr.department_attr': 'Отдел',
    'ld.attr.manager_attr': 'Руководитель (DN)',
    'ld.attr.email_attr': 'Почта',
    'ld.attr.photo_attr': 'Фото',
    'ld.photo': 'Фото',
    'ld.kind': 'Тип каталога',
    'ld.kind.ad': 'Active Directory',
    'ld.kind.openldap': 'OpenLDAP и совместимые',
    'ld.url': 'Адрес сервера',
    'ld.url.hint': 'ldaps://dc1.corp.example:636 или ldap://dc1.corp.example:389',
    'ld.starttls': 'Использовать StartTLS',
    'ld.starttls.hint': 'Переводит соединение ldap:// на TLS.',
    'ld.bindDn': 'Служебная учётная запись',
    'ld.bindDn.hint.ad': 'DN или user@domain, например svc-umbrella@corp.example',
    'ld.bindDn.hint.openldap': 'DN, например cn=umbrella,ou=services,dc=example,dc=org',
    'ld.bindPassword': 'Пароль служебной учётной записи',
    'ld.baseDn': 'База поиска (DN)',
    'ld.baseDn.hint': 'Например, DC=corp,DC=example',
    'ld.filter': 'Фильтр пользователей',
    'ld.filter.hint': 'Вместо {username} подставляется экранированный логин.',
    'ld.attrs': 'Атрибуты',
    'ld.adminGroup': 'Группа администраторов (DN)',
    'ld.adminGroup.hint': 'Участники получают права администратора. В Active Directory учитываются вложенные группы.',
    'ld.testUser': 'Проверочный пользователь',
    'ld.testUser.hint': 'Необязательно: проверить, что пользователь находится и, если указан пароль, может войти.',
    'ld.testUsername': 'Логин',
    'ld.testPassword': 'Пароль',
    'ld.ok': 'Каталог доступен',
    'ld.ok.text': 'Служебная учётная запись вошла, база поиска найдена.',
    'ld.ok.group': 'Группа администраторов найдена.',
    'ld.user': 'Пользователь {name} найден ({dn}).',
    'ld.user.auth': 'Пароль принят.',
    'ld.user.admin': 'Входит в группу администраторов.',
    'ld.user.notAdmin': 'Не входит в группу администраторов.',
    'ld.fail': 'Проверка каталога не прошла',
    'ld.optional': 'необязательно',
    'ld.tls': 'TLS',
    'ld.ca': 'Сертификат CA (PEM)',
    'ld.ca.hint': 'Нужен, если сертификат каталога выпущен внутренним удостоверяющим центром.',
    'ld.skip': 'Не проверять сертификат',
    'ld.skip.hint': 'Только для тестовых сред: соединение можно перехватить.',
    'ld.row.title': 'Должность',
    'ld.row.department': 'Отдел',
    'ld.row.manager': 'Руководитель',
    'ld.row.email': 'Почта',
  },
}
