import type { Dict } from '../i18n'

export const openBaoStrings: Dict = {
  en: {
    'ob.addr': 'Address',
    'ob.addr.hint': 'For example https://openbao.example.com:8200',
    'ob.mount': 'KV v2 mount',
    'ob.mount.hint': 'The secrets engine must be enabled as KV version 2.',
    'ob.namespace': 'Namespace',
    'ob.optional': 'optional',
    'ob.auth': 'Sign-in method',
    'ob.auth.approle': 'AppRole (recommended)',
    'ob.auth.token': 'Token',
    'ob.token': 'Token',
    'ob.roleId': 'Role ID',
    'ob.secretId': 'Secret ID',
    'ob.approlePath': 'AppRole auth path',
    'ob.tls': 'TLS',
    'ob.ca': 'CA certificate (PEM)',
    'ob.ca.hint': 'Needed when OpenBao uses a certificate from an internal CA.',
    'ob.skip': 'Do not verify the certificate',
    'ob.skip.hint': 'Only for test environments: the connection can be intercepted.',
    'ob.ok': 'OpenBao is ready',
    'ob.ok.text': 'Version {version}. Signed in, the {mount} store is readable and writable; the test secret was deleted.',
    'ob.fail': 'OpenBao check failed',
    'ob.loopback':
      'Umbrella runs in a container, so localhost is the Umbrella container itself. Use the OpenBao service name in the shared Docker network, for example http://openbao:8200, or http://host.docker.internal:8200 when OpenBao runs on the host.',
    'ob.policies': 'Policies',
    'ob.expires': 'Token expires',
    'ob.policy.hint': 'The Umbrella policy needs create, read, update and delete on {mount}/data/* and read, list and delete on {mount}/metadata/*.',
  },
  ru: {
    'ob.addr': 'Адрес',
    'ob.addr.hint': 'Например, https://openbao.example.com:8200',
    'ob.mount': 'Хранилище KV v2',
    'ob.mount.hint': 'Движок секретов должен быть включён как KV версии 2.',
    'ob.namespace': 'Пространство имён',
    'ob.optional': 'необязательно',
    'ob.auth': 'Способ входа',
    'ob.auth.approle': 'AppRole (рекомендуется)',
    'ob.auth.token': 'Токен',
    'ob.token': 'Токен',
    'ob.roleId': 'Role ID',
    'ob.secretId': 'Secret ID',
    'ob.approlePath': 'Путь метода AppRole',
    'ob.tls': 'TLS',
    'ob.ca': 'Сертификат CA (PEM)',
    'ob.ca.hint': 'Нужен, если сертификат OpenBao выпущен внутренним удостоверяющим центром.',
    'ob.skip': 'Не проверять сертификат',
    'ob.skip.hint': 'Только для тестовых сред: соединение можно перехватить.',
    'ob.ok': 'OpenBao готов',
    'ob.ok.text': 'Версия {version}. Вход выполнен, хранилище {mount} доступно на чтение и запись; тестовый секрет удалён.',
    'ob.fail': 'Проверка OpenBao не прошла',
    'ob.loopback':
      'Umbrella работает в контейнере, и localhost — это сам контейнер Umbrella. Укажите имя сервиса OpenBao в общей сети Docker, например http://openbao:8200, или http://host.docker.internal:8200, если OpenBao запущен на хосте.',
    'ob.policies': 'Политики',
    'ob.expires': 'Токен действует до',
    'ob.policy.hint': 'Политике Umbrella нужны create, read, update и delete на {mount}/data/* и read, list и delete на {mount}/metadata/*.',
  },
}
