import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'svc.search': 'Search by name, description or tag',
    'svc.filter.owner': 'Owner team',
    'svc.filter.owner.any': 'Any team',
    'svc.filter.owner.hint': 'Sub-teams are included.',
    'svc.filter.criticality': 'Criticality',
    'svc.filter.status': 'Status',
    'svc.filter.tag': 'Tag',
    'svc.filter.any': 'Any',
    'svc.filter.reset': 'Reset filters',
    'svc.group': 'Group by',
    'svc.group.none': 'No grouping',
    'svc.group.owner': 'Owner team',
    'svc.group.criticality': 'Criticality',
    'svc.create': 'Create service',
    'svc.count': '{shown} of {total}',
    'svc.empty': 'No business services yet.',
    'svc.empty.edit': 'Create the first service and assign the team that owns it.',
    'svc.empty.filtered': 'No services match the filters.',
    'svc.col.name': 'Service',
    'svc.col.criticality': 'Criticality',
    'svc.col.status': 'Status',
    'svc.col.owner': 'Owner team',
    'svc.col.teams': 'Supporting teams',
    'svc.col.tags': 'Tags',
    'svc.col.updated': 'Updated',
    'svc.list': 'Business services',
    'svc.crit.critical': 'Critical',
    'svc.crit.high': 'High',
    'svc.crit.medium': 'Medium',
    'svc.crit.low': 'Low',
    'svc.status.active': 'Active',
    'svc.status.planned': 'Planned',
    'svc.status.retired': 'Retired',
    'svc.team.deleted': 'Deleted team',
    'svc.field.name': 'Name',
    'svc.field.description': 'Description',
    'svc.field.owner': 'Owner team',
    'svc.field.owner.pick': 'Choose a team',
    'svc.field.owner.hint': 'The team responsible for the service.',
    'svc.field.teams': 'Supporting teams',
    'svc.field.teams.add': 'Add a team…',
    'svc.field.criticality': 'Criticality',
    'svc.field.status': 'Status',
    'svc.field.tags': 'Tags',
    'svc.field.tags.placeholder': 'Type a tag and press Enter',
    'svc.field.tags.hint': 'Up to 20 tags without spaces.',
    'svc.field.links': 'Links',
    'svc.field.links.hint': 'Runbooks, dashboards, repositories: http:// or https:// addresses.',
    'svc.field.link.title': 'Title',
    'svc.field.link.url': 'Address',
    'svc.field.link.add': 'Add link',
    'svc.field.dependencies': 'Depends on',
    'svc.field.dependencies.add': 'Add a service…',
    'svc.field.dependencies.hint': 'Services that would create a cycle are not offered.',
    'svc.field.dependents': 'Used by',
    'svc.field.created': 'Created',
    'svc.field.updated': 'Updated',
    'svc.field.id': 'ID',
    'svc.none': 'None',
    'svc.remove': 'Remove {name}',
    'svc.new': 'New business service',
    'svc.edit': 'Edit',
    'svc.edit.title': 'Edit {name}',
    'svc.save': 'Save',
    'svc.cancel': 'Cancel',
    'svc.close': 'Close',
    'svc.delete': 'Delete',
    'svc.delete.title': 'Delete the service?',
    'svc.delete.text': '“{name}” will be deleted. This cannot be undone.',
    'svc.delete.dependents': 'It is removed from the dependencies of: {names}.',
    'svc.delete.confirm': 'Delete service',
    'svc.noTeams': 'There are no teams yet. Create a team first: every service needs an owner team.',
    'svc.readonly': 'You can view services but not change them.',
    'err.invalid_service_name': 'The name must be 1–120 characters long.',
    'err.service_name_taken': 'A service with this name already exists.',
    'err.invalid_service_description': 'The description is too long.',
    'err.owner_team_required': 'Choose the owner team.',
    'err.unknown_team': 'One of the teams no longer exists. Remove it and save again.',
    'err.duplicate_team': 'The owner team cannot also be a supporting team.',
    'err.too_many_teams': 'Too many supporting teams.',
    'err.invalid_criticality': 'Unknown criticality.',
    'err.invalid_service_status': 'Unknown status.',
    'err.invalid_tag': 'Tags must be up to 40 characters, without spaces or commas.',
    'err.too_many_tags': 'Too many tags: at most 20.',
    'err.invalid_link': 'Each link needs an http:// or https:// address; titles are up to 120 characters.',
    'err.too_many_links': 'Too many links: at most 20.',
    'err.unknown_service': 'One of the dependencies no longer exists.',
    'err.too_many_dependencies': 'Too many dependencies.',
    'err.dependency_self': 'A service cannot depend on itself.',
    'err.dependency_cycle': 'These dependencies would create a cycle.',
    'err.not_found': 'The service no longer exists.',
  },
  ru: {
    'svc.search': 'Поиск по названию, описанию или тегу',
    'svc.filter.owner': 'Команда-владелец',
    'svc.filter.owner.any': 'Любая команда',
    'svc.filter.owner.hint': 'Учитываются и вложенные команды.',
    'svc.filter.criticality': 'Критичность',
    'svc.filter.status': 'Статус',
    'svc.filter.tag': 'Тег',
    'svc.filter.any': 'Любой',
    'svc.filter.reset': 'Сбросить фильтры',
    'svc.group': 'Группировка',
    'svc.group.none': 'Без группировки',
    'svc.group.owner': 'По команде',
    'svc.group.criticality': 'По критичности',
    'svc.create': 'Создать сервис',
    'svc.count': '{shown} из {total}',
    'svc.empty': 'Бизнес-сервисов пока нет.',
    'svc.empty.edit': 'Создайте первый сервис и назначьте команду, которая за него отвечает.',
    'svc.empty.filtered': 'Нет сервисов, подходящих под фильтры.',
    'svc.col.name': 'Сервис',
    'svc.col.criticality': 'Критичность',
    'svc.col.status': 'Статус',
    'svc.col.owner': 'Команда-владелец',
    'svc.col.teams': 'Поддерживающие команды',
    'svc.col.tags': 'Теги',
    'svc.col.updated': 'Изменён',
    'svc.list': 'Бизнес-сервисы',
    'svc.crit.critical': 'Критическая',
    'svc.crit.high': 'Высокая',
    'svc.crit.medium': 'Средняя',
    'svc.crit.low': 'Низкая',
    'svc.status.active': 'Работает',
    'svc.status.planned': 'Планируется',
    'svc.status.retired': 'Выведен',
    'svc.team.deleted': 'Удалённая команда',
    'svc.field.name': 'Название',
    'svc.field.description': 'Описание',
    'svc.field.owner': 'Команда-владелец',
    'svc.field.owner.pick': 'Выберите команду',
    'svc.field.owner.hint': 'Команда, которая отвечает за сервис.',
    'svc.field.teams': 'Поддерживающие команды',
    'svc.field.teams.add': 'Добавить команду…',
    'svc.field.criticality': 'Критичность',
    'svc.field.status': 'Статус',
    'svc.field.tags': 'Теги',
    'svc.field.tags.placeholder': 'Введите тег и нажмите Enter',
    'svc.field.tags.hint': 'До 20 тегов без пробелов.',
    'svc.field.links': 'Ссылки',
    'svc.field.links.hint': 'Регламенты, дашборды, репозитории: адреса http:// или https://.',
    'svc.field.link.title': 'Название',
    'svc.field.link.url': 'Адрес',
    'svc.field.link.add': 'Добавить ссылку',
    'svc.field.dependencies': 'Зависит от',
    'svc.field.dependencies.add': 'Добавить сервис…',
    'svc.field.dependencies.hint': 'Сервисы, которые образуют цикл, не предлагаются.',
    'svc.field.dependents': 'Используется в',
    'svc.field.created': 'Создан',
    'svc.field.updated': 'Изменён',
    'svc.field.id': 'ID',
    'svc.none': 'Нет',
    'svc.remove': 'Убрать {name}',
    'svc.new': 'Новый бизнес-сервис',
    'svc.edit': 'Изменить',
    'svc.edit.title': 'Изменение: {name}',
    'svc.save': 'Сохранить',
    'svc.cancel': 'Отмена',
    'svc.close': 'Закрыть',
    'svc.delete': 'Удалить',
    'svc.delete.title': 'Удалить сервис?',
    'svc.delete.text': '«{name}» будет удалён. Отменить это нельзя.',
    'svc.delete.dependents': 'Он будет убран из зависимостей сервисов: {names}.',
    'svc.delete.confirm': 'Удалить сервис',
    'svc.noTeams': 'Команд пока нет. Сначала создайте команду: у каждого сервиса должна быть команда-владелец.',
    'svc.readonly': 'Вы можете просматривать сервисы, но не изменять их.',
    'err.invalid_service_name': 'Название: от 1 до 120 символов.',
    'err.service_name_taken': 'Сервис с таким названием уже есть.',
    'err.invalid_service_description': 'Слишком длинное описание.',
    'err.owner_team_required': 'Выберите команду-владельца.',
    'err.unknown_team': 'Одной из команд больше нет. Уберите её и сохраните снова.',
    'err.duplicate_team': 'Команда-владелец не может быть одновременно поддерживающей.',
    'err.too_many_teams': 'Слишком много поддерживающих команд.',
    'err.invalid_criticality': 'Неизвестная критичность.',
    'err.invalid_service_status': 'Неизвестный статус.',
    'err.invalid_tag': 'Тег: до 40 символов, без пробелов и запятых.',
    'err.too_many_tags': 'Слишком много тегов: не больше 20.',
    'err.invalid_link': 'У каждой ссылки должен быть адрес http:// или https://; название — до 120 символов.',
    'err.too_many_links': 'Слишком много ссылок: не больше 20.',
    'err.unknown_service': 'Одного из сервисов-зависимостей больше нет.',
    'err.too_many_dependencies': 'Слишком много зависимостей.',
    'err.dependency_self': 'Сервис не может зависеть от самого себя.',
    'err.dependency_cycle': 'Такие зависимости образуют цикл.',
    'err.not_found': 'Сервиса больше нет.',
  },
}
