import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    loading: 'Loading…',
    'wb.new': 'New wallboard',
    'wb.empty.title': 'No TV wallboards yet',
    'wb.empty.text':
      'A wallboard is a full-screen page for a NOC TV: it shows the active incidents of the chosen CIs, business services and teams, the most severe first, and refreshes itself.',
    'wb.empty.access': 'It opens without signing in, but only from the networks you allow — for example, the address of the computer behind the TV.',
    'wb.empty.readonly': 'Ask an administrator to create one.',
    'wb.on': 'On',
    'wb.off': 'Off',
    'wb.scope.all': 'All incidents',
    'wb.n.cis.one': '{n} CI',
    'wb.n.cis.many': '{n} CIs',
    'wb.n.services.one': '{n} service',
    'wb.n.services.many': '{n} services',
    'wb.n.teams.one': '{n} team',
    'wb.n.teams.many': '{n} teams',
    'wb.ack.hidden': 'without acknowledged',
    'wb.suppressed.shown': 'with suppressed',
    'wb.resolved.shown': 'resolved for {n} min',
    'wb.networks': 'Allowed networks',
    'wb.refresh.every': 'Refresh every {n} s',
    'wb.updated': 'Changed by {who}, {at}',
    'wb.updated.at': 'Changed {at}',
    'wb.updated.label': 'Last change',
    'wb.edit': 'Edit',
    'wb.view': 'Details',
    'wb.open': 'Open on screen',
    'wb.copy': 'Copy link',
    'wb.copied': 'Link copied',
    'wb.copy.failed': 'Could not copy. The link: {url}',
    'wb.preview': 'Preview',
    'wb.delete': 'Delete',
    'wb.delete.confirm': 'Delete the wallboard “{title}”? Screens showing it will stop updating.',
    'wb.theme.dark': 'Dark',
    'wb.theme.light': 'Light',

    'wb.dialog.new': 'New TV wallboard',
    'wb.dialog.edit': 'TV wallboard',
    'wb.dialog.view': 'TV wallboard (read only)',
    'wb.section.general': 'General',
    'wb.section.filters': 'What to show',
    'wb.section.display': 'Display',
    'wb.section.access': 'Access',
    'wb.title': 'Title',
    'wb.title.ph': 'For example: NOC — main screen',
    'wb.slug': 'Address',
    'wb.slug.hint': 'Leave it empty for a random address nobody can guess, or type your own: Latin letters, digits and dashes. The screen opens at {url}',
    'wb.slug.random': 'random, made when you save',
    'wb.rotate': 'New address',
    'wb.rotate.hint': 'Gives the board a new random address. Screens on the old link stop getting data until they open the new one.',
    'wb.rotate.confirm': 'Give “{title}” a new address? Screens on the old link stop getting data.',
    'wb.rotated': 'The board has a new address. Copy the link again for the screens.',
    'wb.timezone': 'Time zone of the clock',
    'wb.timezone.auto': 'As in settings',
    'wb.proxies.title': 'Trusted proxies',
    'wb.proxies.text': 'If Umbrella stands behind a reverse proxy or load balancer, list it here. Only for these addresses is X-Forwarded-For believed when the address of a screen is checked; the same addresses also count for sign-in limits and the audit.',
    'wb.proxies.set': 'Set here',
    'wb.proxies.env': 'From UMBRELLA_TRUSTED_PROXIES',
    'wb.proxies.none': 'None',
    'wb.proxies.you': 'Your address as Umbrella sees it',
    'wb.proxies.field': 'Proxy addresses and networks, one per line',
    'wb.proxies.save': 'Save proxies',
    'wb.proxies.saved': 'Trusted proxies saved.',
    'err.proxy_invalid': 'A proxy address or network is not valid.',
    'err.too_many_proxies': 'Too many trusted proxies; 50 at most.',
    'err.timezone_invalid': 'Unknown time zone.',
    'wb.description': 'Description',
    'wb.description.hint': 'Where the screen hangs and who watches it. Shown only here.',
    'wb.enabled': 'Wallboard is on',
    'wb.enabled.hint': 'A switched-off wallboard does not open even from allowed networks.',
    'wb.targets': 'CIs, business services and teams',
    'wb.targets.hint': 'An incident is shown when its CI or one of its services is chosen, or a team that owns or supports one of its services (or gets it). Choose nothing to show every incident.',
    'wb.search': 'Find a CI, service or team',
    'wb.found.cis': 'CIs',
    'wb.found.services': 'Business services',
    'wb.found.teams': 'Teams',
    'wb.nothing': 'Nothing found.',
    'wb.chosen.cis': 'CIs',
    'wb.chosen.services': 'Services',
    'wb.chosen.teams': 'Teams',
    'wb.remove': 'Remove {name}',
    'wb.missing': 'deleted',
    'wb.severities': 'Severities',
    'wb.severities.hint': 'Nothing chosen — every severity.',
    'wb.methods': 'Methods',
    'wb.methods.hint': 'Nothing chosen — every method.',
    'wb.method.red': 'RED',
    'wb.method.use': 'USE',
    'wb.method.other': 'Other',
    'wb.show_acknowledged': 'Show acknowledged incidents',
    'wb.show_acknowledged.hint': 'Someone already works on them; they are listed after the open ones.',
    'wb.show_suppressed': 'Show incidents in maintenance windows',
    'wb.resolved': 'Keep resolved incidents on screen',
    'wb.resolved.hint': 'Minutes after resolution, 0 — hide at once.',
    'wb.minutes': 'min',
    'wb.seconds': 's',
    'wb.sort': 'Order within a severity',
    'wb.sort.newest': 'Newest first',
    'wb.sort.oldest': 'Oldest first',
    'wb.refresh': 'Refresh interval',
    'wb.theme': 'Theme',
    'wb.locale': 'Language',
    'wb.locale.auto': 'As in settings',
    'wb.locale.ru': 'Русский',
    'wb.locale.en': 'English',
    'wb.allowed': 'Allowed networks',
    'wb.allowed.hint': 'One per line: a network such as 10.20.0.0/24 or a single address such as 10.20.0.15. Only these addresses open the screen without signing in.',
    'wb.allowed.add_me': 'Add my address ({ip})',
    'wb.allowed.bad': 'Not an IP address or network: {list}',
    'wb.allowed.everyone': '{net} opens the screen to everyone who can reach Umbrella, without signing in.',
    'wb.allowed.proxy': 'Umbrella sees your address as {ip}. If it is the address of a proxy, add the proxy to Trusted proxies on this page.',
    'wb.save': 'Save',
    'wb.cancel': 'Cancel',
    'wb.close': 'Close',

    'wb.preview.title': 'Preview: {title}',
    'wb.preview.hint': 'What the screen shows now. The preview works for switched-off wallboards and from any network.',
    'wb.preview.empty': 'No incidents match — the screen shows “No active incidents”.',
    'wb.preview.not_ready': 'The alert engine is starting: the screen will show incidents in a moment.',
    'wb.preview.more': 'And {n} more on the screen.',
    'wb.preview.total': 'Total: {n}',
    'wb.preview.open': 'Open: {n}',
    'wb.preview.acknowledged': 'Acknowledged: {n}',
    'wb.col.severity': 'Severity',
    'wb.col.incident': 'Incident',
    'wb.col.status': 'Status',
    'wb.col.opened': 'Opened',
    'wb.col.count': 'Alerts',
    'wb.status.open': 'Open',
    'wb.status.acknowledged': 'Acknowledged',
    'wb.status.resolved': 'Resolved',
    'wb.suppressed': 'maintenance',
    'wb.ago.s': 'just now',
    'wb.ago.m': '{n} min ago',
    'wb.ago.h': '{n} h ago',
    'wb.ago.d': '{n} d ago',

    'err.title_invalid': 'Enter a title of up to 200 characters.',
    'err.description_too_long': 'The description is longer than 2000 characters.',
    'err.slug_invalid': 'Address: 2–63 Latin letters, digits and dashes, starting with a letter or digit.',
    'err.slug_taken': 'Another wallboard already uses this address.',
    'err.network_invalid': 'An allowed network is not an IP address or network.',
    'err.networks_required': 'Add at least one allowed network.',
    'err.too_many_networks': 'A wallboard allows at most 200 networks.',
    'err.severity_invalid': 'Unknown severity.',
    'err.method_invalid': 'Unknown method.',
    'err.sort_invalid': 'Unknown order.',
    'err.refresh_invalid': 'The refresh interval is from 5 to 600 seconds.',
    'err.theme_invalid': 'Choose the dark or light theme.',
    'err.locale_invalid': 'Choose Russian, English or the language from settings.',
    'err.resolved_invalid': 'Resolved incidents stay on screen from 0 to 1440 minutes.',
    'err.too_many_targets': 'Too many CIs, services and teams in one wallboard (500 at most).',
    'err.out_of_scope': 'These CIs, services or teams are outside your visibility scope.',
    'err.scope_required': 'Your visibility scope is limited: choose CIs, services or teams within it; a wallboard of every incident is not allowed.',
    'err.ci_not_found': 'A chosen CI no longer exists.',
    'err.service_not_found': 'A chosen service no longer exists.',
    'err.team_not_found': 'A chosen team no longer exists.',
    'err.not_found': 'The wallboard no longer exists.',
  },
  ru: {
    loading: 'Загрузка…',
    'wb.new': 'Новая ТВ-панель',
    'wb.empty.title': 'ТВ-панелей пока нет',
    'wb.empty.text':
      'ТВ-панель — полноэкранная страница для телевизора в дежурной смене: она показывает активные инциденты выбранных КЕ, бизнес-сервисов и команд, самые серьёзные сверху, и обновляется сама.',
    'wb.empty.access': 'Панель открывается без входа в систему, но только из разрешённых сетей — например, с адреса компьютера, подключённого к телевизору.',
    'wb.empty.readonly': 'Попросите администратора её создать.',
    'wb.on': 'Включена',
    'wb.off': 'Выключена',
    'wb.scope.all': 'Все инциденты',
    'wb.n.cis.one': '{n} КЕ',
    'wb.n.cis.few': '{n} КЕ',
    'wb.n.cis.many': '{n} КЕ',
    'wb.n.services.one': '{n} сервис',
    'wb.n.services.few': '{n} сервиса',
    'wb.n.services.many': '{n} сервисов',
    'wb.n.teams.one': '{n} команда',
    'wb.n.teams.few': '{n} команды',
    'wb.n.teams.many': '{n} команд',
    'wb.ack.hidden': 'без подтверждённых',
    'wb.suppressed.shown': 'с подавленными',
    'wb.resolved.shown': 'решённые {n} мин',
    'wb.networks': 'Разрешённые сети',
    'wb.refresh.every': 'Обновление каждые {n} с',
    'wb.updated': 'Изменено: {who}, {at}',
    'wb.updated.at': 'Изменена {at}',
    'wb.updated.label': 'Последнее изменение',
    'wb.edit': 'Изменить',
    'wb.view': 'Подробнее',
    'wb.open': 'Открыть на экране',
    'wb.copy': 'Скопировать ссылку',
    'wb.copied': 'Ссылка скопирована',
    'wb.copy.failed': 'Не удалось скопировать. Ссылка: {url}',
    'wb.preview': 'Предпросмотр',
    'wb.delete': 'Удалить',
    'wb.delete.confirm': 'Удалить ТВ-панель «{title}»? Экраны, на которых она открыта, перестанут обновляться.',
    'wb.theme.dark': 'Тёмная',
    'wb.theme.light': 'Светлая',

    'wb.dialog.new': 'Новая ТВ-панель',
    'wb.dialog.edit': 'ТВ-панель',
    'wb.dialog.view': 'ТВ-панель (только просмотр)',
    'wb.section.general': 'Основное',
    'wb.section.filters': 'Что показывать',
    'wb.section.display': 'Отображение',
    'wb.section.access': 'Доступ',
    'wb.title': 'Название',
    'wb.title.ph': 'Например: Дежурная смена — главный экран',
    'wb.slug': 'Адрес',
    'wb.slug.hint': 'Оставьте пустым — будет случайный адрес, который невозможно угадать, или задайте свой: латинские буквы, цифры и дефисы. Экран откроется по адресу {url}',
    'wb.slug.random': 'случайный, создаётся при сохранении',
    'wb.rotate': 'Новый адрес',
    'wb.rotate.hint': 'Выдаёт панели новый случайный адрес. Экраны со старой ссылкой перестанут получать данные, пока не откроют новую.',
    'wb.rotate.confirm': 'Выдать панели «{title}» новый адрес? Экраны со старой ссылкой перестанут получать данные.',
    'wb.rotated': 'У панели новый адрес. Скопируйте ссылку для экранов заново.',
    'wb.timezone': 'Часовой пояс часов',
    'wb.timezone.auto': 'Как в настройках',
    'wb.proxies.title': 'Доверенные прокси',
    'wb.proxies.text': 'Если Umbrella стоит за обратным прокси или балансировщиком, укажите его здесь. Заголовку X-Forwarded-For верим только от этих адресов при проверке адреса экрана; они же учитываются в ограничениях входа и аудите.',
    'wb.proxies.set': 'Заданы здесь',
    'wb.proxies.env': 'Из UMBRELLA_TRUSTED_PROXIES',
    'wb.proxies.none': 'Нет',
    'wb.proxies.you': 'Ваш адрес глазами Umbrella',
    'wb.proxies.field': 'Адреса и сети прокси, по одному в строке',
    'wb.proxies.save': 'Сохранить прокси',
    'wb.proxies.saved': 'Доверенные прокси сохранены.',
    'err.proxy_invalid': 'Адрес или сеть прокси указаны неверно.',
    'err.too_many_proxies': 'Слишком много доверенных прокси; не больше 50.',
    'err.timezone_invalid': 'Неизвестный часовой пояс.',
    'wb.description': 'Описание',
    'wb.description.hint': 'Где висит экран и кто на него смотрит. Видно только здесь.',
    'wb.enabled': 'Панель включена',
    'wb.enabled.hint': 'Выключенная панель не открывается даже из разрешённых сетей.',
    'wb.targets': 'КЕ, бизнес-сервисы и команды',
    'wb.targets.hint': 'Инцидент попадает на экран, если выбрана его КЕ или один из его сервисов, либо команда, которая владеет одним из его сервисов, поддерживает его или получает инцидент. Ничего не выбрано — показываются все инциденты.',
    'wb.search': 'Найти КЕ, сервис или команду',
    'wb.found.cis': 'КЕ',
    'wb.found.services': 'Бизнес-сервисы',
    'wb.found.teams': 'Команды',
    'wb.nothing': 'Ничего не найдено.',
    'wb.chosen.cis': 'КЕ',
    'wb.chosen.services': 'Сервисы',
    'wb.chosen.teams': 'Команды',
    'wb.remove': 'Убрать {name}',
    'wb.missing': 'удалён',
    'wb.severities': 'Критичность',
    'wb.severities.hint': 'Ничего не выбрано — любая критичность.',
    'wb.methods': 'Методы',
    'wb.methods.hint': 'Ничего не выбрано — любой метод.',
    'wb.method.red': 'RED',
    'wb.method.use': 'USE',
    'wb.method.other': 'Другое',
    'wb.show_acknowledged': 'Показывать подтверждённые инциденты',
    'wb.show_acknowledged.hint': 'Ими уже занимаются; они идут после открытых.',
    'wb.show_suppressed': 'Показывать инциденты в сервисных окнах',
    'wb.resolved': 'Оставлять решённые инциденты на экране',
    'wb.resolved.hint': 'Минут после решения, 0 — убирать сразу.',
    'wb.minutes': 'мин',
    'wb.seconds': 'с',
    'wb.sort': 'Порядок внутри критичности',
    'wb.sort.newest': 'Сначала новые',
    'wb.sort.oldest': 'Сначала старые',
    'wb.refresh': 'Интервал обновления',
    'wb.theme': 'Тема',
    'wb.locale': 'Язык',
    'wb.locale.auto': 'Как в настройках',
    'wb.locale.ru': 'Русский',
    'wb.locale.en': 'English',
    'wb.allowed': 'Разрешённые сети',
    'wb.allowed.hint': 'По одной в строке: сеть, например 10.20.0.0/24, или отдельный адрес, например 10.20.0.15. Только с этих адресов экран открывается без входа.',
    'wb.allowed.add_me': 'Добавить мой адрес ({ip})',
    'wb.allowed.bad': 'Это не IP-адрес и не сеть: {list}',
    'wb.allowed.everyone': '{net} открывает экран всем, кто может достучаться до Umbrella, без входа в систему.',
    'wb.allowed.proxy': 'Umbrella видит ваш адрес как {ip}. Если это адрес прокси, добавьте его в «Доверенные прокси» на этой странице.',
    'wb.save': 'Сохранить',
    'wb.cancel': 'Отмена',
    'wb.close': 'Закрыть',

    'wb.preview.title': 'Предпросмотр: {title}',
    'wb.preview.hint': 'Что сейчас на экране. Предпросмотр работает и для выключенных панелей, и из любой сети.',
    'wb.preview.empty': 'Подходящих инцидентов нет — на экране надпись «Активных инцидентов нет».',
    'wb.preview.not_ready': 'Движок оповещений запускается: инциденты появятся на экране через несколько секунд.',
    'wb.preview.more': 'И ещё {n} на экране.',
    'wb.preview.total': 'Всего: {n}',
    'wb.preview.open': 'Открыто: {n}',
    'wb.preview.acknowledged': 'Подтверждено: {n}',
    'wb.col.severity': 'Критичность',
    'wb.col.incident': 'Инцидент',
    'wb.col.status': 'Статус',
    'wb.col.opened': 'Открыт',
    'wb.col.count': 'Тревог',
    'wb.status.open': 'Открыт',
    'wb.status.acknowledged': 'Подтверждён',
    'wb.status.resolved': 'Решён',
    'wb.suppressed': 'сервисное окно',
    'wb.ago.s': 'только что',
    'wb.ago.m': '{n} мин назад',
    'wb.ago.h': '{n} ч назад',
    'wb.ago.d': '{n} дн назад',

    'err.title_invalid': 'Введите название длиной до 200 символов.',
    'err.description_too_long': 'Описание длиннее 2000 символов.',
    'err.slug_invalid': 'Адрес: от 2 до 63 латинских букв, цифр и дефисов, начиная с буквы или цифры.',
    'err.slug_taken': 'Этот адрес уже занят другой панелью.',
    'err.network_invalid': 'Одна из разрешённых сетей не является IP-адресом или сетью.',
    'err.networks_required': 'Добавьте хотя бы одну разрешённую сеть.',
    'err.too_many_networks': 'У панели может быть не больше 200 сетей.',
    'err.severity_invalid': 'Неизвестная критичность.',
    'err.method_invalid': 'Неизвестный метод.',
    'err.sort_invalid': 'Неизвестный порядок.',
    'err.refresh_invalid': 'Интервал обновления — от 5 до 600 секунд.',
    'err.theme_invalid': 'Выберите тёмную или светлую тему.',
    'err.locale_invalid': 'Выберите русский, английский или язык из настроек.',
    'err.resolved_invalid': 'Решённые инциденты остаются на экране от 0 до 1440 минут.',
    'err.too_many_targets': 'Слишком много КЕ, сервисов и команд в одной панели (не больше 500).',
    'err.out_of_scope': 'Эти КЕ, сервисы или команды вне вашей области видимости.',
    'err.scope_required': 'Ваша область видимости ограничена: выберите КЕ, сервисы или команды из неё; панель со всеми инцидентами создать нельзя.',
    'err.ci_not_found': 'Выбранная КЕ больше не существует.',
    'err.service_not_found': 'Выбранный сервис больше не существует.',
    'err.team_not_found': 'Выбранная команда больше не существует.',
    'err.not_found': 'Панель больше не существует.',
  },
}

// plural picks the plural form suffix for n: Russian has one / few / many, English one / many.
export function plural(locale: string, n: number) {
  if (locale !== 'ru') return n === 1 ? 'one' : 'many'
  const d = n % 10
  const h = n % 100
  if (d === 1 && h !== 11) return 'one'
  if (d >= 2 && d <= 4 && (h < 12 || h > 14)) return 'few'
  return 'many'
}
