import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'bulk.selected': '{n} selected',
    'bulk.clear': 'Clear selection',
    'bulk.selectAll': 'Select all shown',
    'bulk.selectOne': 'Select {name}',
    'bulk.bind': 'Bind to services…',
    'bulk.unbind': 'Unbind from services…',
    'bulk.bind.title': 'Bind {n} items to services',
    'bulk.unbind.title': 'Unbind {n} items from services',
    'bulk.bind.text': 'Every selected item is bound to every chosen service. Items kept in NetBox also get the tag of a service linked to NetBox.',
    'bulk.unbind.text': 'Every selected item is unbound from every chosen service. Items kept in NetBox lose the tag of a service linked to NetBox.',
    'bulk.services': 'Services',
    'bulk.services.search': 'Find a service',
    'bulk.services.none': 'No services match.',
    'bulk.services.chosen': '{n} chosen',
    'bulk.run.bind': 'Bind',
    'bulk.run.unbind': 'Unbind',
    'bulk.cancel': 'Cancel',
    'bulk.close': 'Close',
    'bulk.result.ok': 'Done: nothing failed.',
    'bulk.result.failed': '{n} failed: the rest was done.',
    'bulk.onlyFailed': 'Show only problems',
    'bulk.r.bound': 'Bound',
    'bulk.r.unbound': 'Unbound',
    'bulk.r.already': 'Already bound',
    'bulk.r.not_bound': 'Was not bound',
    'bulk.r.created': 'Created',
    'bulk.r.linked': 'Linked to an item made in this batch',
    'bulk.r.matched': 'Already has an item',
    'bulk.r.failed': 'Failed',
    'bulk.r.skipped': 'Skipped',
    'bulk.col.item': 'Item',
    'bulk.col.service': 'Service',
    'bulk.col.host': 'Host',
    'bulk.col.system': 'System',
    'bulk.col.result': 'Result',
    'bulk.hosts.create': 'Create items…',
    'bulk.hosts.title': 'Create configuration items of {n} hosts',
    'bulk.hosts.text':
      'Each host becomes a configuration item named after its technical name, with its IP addresses. One machine seen by several systems becomes one item, linked to all of them; a host that already matches an item is left as is.',
    'bulk.hosts.register': 'Also register them in NetBox',
    'bulk.hosts.run': 'Create',
    'bulk.cis.bindSelected': 'Bind selected ({n})',
    'bulk.cis.unbindSelected': 'Unbind selected ({n})',
    'err.stopped': 'Not tried: the same error repeated',
    'err.excluded': 'The host is marked as not a configuration item',
    'err.no_services': 'Choose at least one service.',
    'err.no_cis': 'Choose at least one item.',
    'err.no_hosts': 'Choose at least one host.',
    'err.bulk_action': 'Unknown action.',
    'err.too_many_services': 'Too many services at once: at most 50.',
    'err.too_many_hosts': 'Too many hosts at once: at most 500.',
  },
  ru: {
    'bulk.selected': 'Выбрано: {n}',
    'bulk.clear': 'Снять выбор',
    'bulk.selectAll': 'Выбрать все показанные',
    'bulk.selectOne': 'Выбрать {name}',
    'bulk.bind': 'Привязать к сервисам…',
    'bulk.unbind': 'Отвязать от сервисов…',
    'bulk.bind.title': 'Привязать КЕ к сервисам: {n}',
    'bulk.unbind.title': 'Отвязать КЕ от сервисов: {n}',
    'bulk.bind.text': 'Каждая выбранная КЕ привязывается к каждому выбранному сервису. КЕ из NetBox также получают тег сервиса, если сервис связан с NetBox.',
    'bulk.unbind.text': 'Каждая выбранная КЕ отвязывается от каждого выбранного сервиса. С КЕ из NetBox снимается тег сервиса, если сервис связан с NetBox.',
    'bulk.services': 'Сервисы',
    'bulk.services.search': 'Найти сервис',
    'bulk.services.none': 'Нет подходящих сервисов.',
    'bulk.services.chosen': 'Выбрано: {n}',
    'bulk.run.bind': 'Привязать',
    'bulk.run.unbind': 'Отвязать',
    'bulk.cancel': 'Отмена',
    'bulk.close': 'Закрыть',
    'bulk.result.ok': 'Готово, ошибок нет.',
    'bulk.result.failed': 'Не удалось: {n}. Остальное выполнено.',
    'bulk.onlyFailed': 'Только проблемы',
    'bulk.r.bound': 'Привязана',
    'bulk.r.unbound': 'Отвязана',
    'bulk.r.already': 'Уже привязана',
    'bulk.r.not_bound': 'Не была привязана',
    'bulk.r.created': 'Создана',
    'bulk.r.linked': 'Связан с КЕ, созданной в этом пакете',
    'bulk.r.matched': 'Уже есть КЕ',
    'bulk.r.failed': 'Ошибка',
    'bulk.r.skipped': 'Пропущен',
    'bulk.col.item': 'КЕ',
    'bulk.col.service': 'Сервис',
    'bulk.col.host': 'Хост',
    'bulk.col.system': 'Система',
    'bulk.col.result': 'Результат',
    'bulk.hosts.create': 'Создать КЕ…',
    'bulk.hosts.title': 'Создать КЕ для хостов: {n}',
    'bulk.hosts.text':
      'Каждый хост становится КЕ с его техническим именем и IP-адресами. Одна машина из нескольких систем становится одной КЕ и связывается со всеми; хост, у которого уже есть КЕ, не меняется.',
    'bulk.hosts.register': 'Также зарегистрировать в NetBox',
    'bulk.hosts.run': 'Создать',
    'bulk.cis.bindSelected': 'Привязать выбранные ({n})',
    'bulk.cis.unbindSelected': 'Отвязать выбранные ({n})',
    'err.stopped': 'Не выполнялось: одна и та же ошибка повторилась',
    'err.excluded': 'Хост отмечен как «не КЕ»',
    'err.no_services': 'Выберите хотя бы один сервис.',
    'err.no_cis': 'Выберите хотя бы одну КЕ.',
    'err.no_hosts': 'Выберите хотя бы один хост.',
    'err.bulk_action': 'Неизвестное действие.',
    'err.too_many_services': 'Слишком много сервисов за раз: не больше 50.',
    'err.too_many_hosts': 'Слишком много хостов за раз: не больше 500.',
  },
}

// requestStrings explain why a whole bulk request was refused. They are kept apart from the
// per-item results, where the same codes mean a problem with one service.
export const requestStrings: Dict = {
  en: {
    'err.too_many_cis': 'Too many configuration items at once: at most 1000.',
    'err.unknown_ci': 'One of the configuration items no longer exists. Reload the page.',
    'err.unknown_service': 'One of the services no longer exists. Reload the page.',
  },
  ru: {
    'err.too_many_cis': 'Слишком много КЕ за раз: не больше 1000.',
    'err.unknown_ci': 'Одной из КЕ больше нет. Обновите страницу.',
    'err.unknown_service': 'Одного из сервисов больше нет. Обновите страницу.',
  },
}
