import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    loading: 'Loading…',
    'mw.new': 'New window',
    'mw.empty': 'No maintenance windows yet. Plan one before works so incidents of the affected items are not sent to PagerDuty or by backup notification.',
    'mw.col.state': 'State',
    'mw.col.title': 'Window',
    'mw.col.targets': 'Covers',
    'mw.col.period': 'Period',
    'mw.col.author': 'Author',
    'mw.state.active': 'In progress',
    'mw.state.planned': 'Planned',
    'mw.state.finished': 'Finished',
    'mw.tile.active': 'In progress',
    'mw.tile.planned': 'Planned',
    'mw.tile.finished': 'Finished',
    'mw.edit': 'Edit',
    'mw.finish': 'Finish now',
    'mw.delete': 'Delete',
    'mw.delete.confirm': 'Delete the window “{title}”?',
    'mw.services': '{n} services',
    'mw.cis': '{n} CIs',
    'mw.dialog.new': 'New maintenance window',
    'mw.dialog.edit': 'Maintenance window',
    'mw.title': 'Title',
    'mw.title.ph': 'For example: PostgreSQL upgrade on db-01',
    'mw.comment': 'Comment',
    'mw.start': 'Start',
    'mw.end': 'End',
    'mw.tz': 'Time of your browser ({zone}).',
    'mw.duration': 'Length',
    'mw.now': 'Start now',
    'mw.hours': '{n} h',
    'mw.targets': 'Business services and CIs',
    'mw.targets.hint': 'Incidents of the chosen CIs and of every CI of the chosen services are kept but not sent.',
    'mw.search': 'Find a service or CI',
    'mw.found.services': 'Services',
    'mw.found.cis': 'CIs',
    'mw.nothing': 'Nothing found.',
    'mw.remove': 'Remove {name}',
    'mw.missing': 'deleted',
    'mw.save': 'Save',
    'mw.cancel': 'Cancel',
    'mw.created': 'by {who}',
    'err.title_invalid': 'Enter a title of up to 200 characters.',
    'err.period_invalid': 'The end must be after the start.',
    'err.period_too_long': 'A window lasts 90 days at most.',
    'err.targets_required': 'Choose at least one service or CI.',
    'err.out_of_scope': 'These CIs or services are outside your visibility scope. A CI counts as yours when all its services are.',
    'err.scope_required': 'Choose CIs or services within your visibility scope.',
    'err.too_many_targets': 'Too many services and CIs in one window.',
    'err.ci_not_found': 'A chosen CI no longer exists.',
    'err.service_not_found': 'A chosen service no longer exists.',
    'err.not_active': 'Only a window in progress can be finished.',
    'err.comment_too_long': 'The comment is too long.',
  },
  ru: {
    loading: 'Загрузка…',
    'mw.new': 'Новое окно',
    'mw.empty': 'Сервисных окон пока нет. Запланируйте окно перед работами, чтобы инциденты затронутых КЕ не уходили в PagerDuty и резервное оповещение.',
    'mw.col.state': 'Состояние',
    'mw.col.title': 'Окно',
    'mw.col.targets': 'Охватывает',
    'mw.col.period': 'Период',
    'mw.col.author': 'Автор',
    'mw.state.active': 'Идёт',
    'mw.state.planned': 'Запланировано',
    'mw.state.finished': 'Завершено',
    'mw.tile.active': 'Идут',
    'mw.tile.planned': 'Запланированы',
    'mw.tile.finished': 'Завершены',
    'mw.edit': 'Изменить',
    'mw.finish': 'Завершить сейчас',
    'mw.delete': 'Удалить',
    'mw.delete.confirm': 'Удалить окно «{title}»?',
    'mw.services': 'сервисов: {n}',
    'mw.cis': 'КЕ: {n}',
    'mw.dialog.new': 'Новое сервисное окно',
    'mw.dialog.edit': 'Сервисное окно',
    'mw.title': 'Название',
    'mw.title.ph': 'Например: обновление PostgreSQL на db-01',
    'mw.comment': 'Комментарий',
    'mw.start': 'Начало',
    'mw.end': 'Конец',
    'mw.tz': 'Время вашего браузера ({zone}).',
    'mw.duration': 'Длительность',
    'mw.now': 'Начать сейчас',
    'mw.hours': '{n} ч',
    'mw.targets': 'Бизнес-сервисы и КЕ',
    'mw.targets.hint': 'Инциденты выбранных КЕ и всех КЕ выбранных сервисов сохраняются, но никуда не отправляются.',
    'mw.search': 'Найти сервис или КЕ',
    'mw.found.services': 'Сервисы',
    'mw.found.cis': 'КЕ',
    'mw.nothing': 'Ничего не найдено.',
    'mw.remove': 'Убрать {name}',
    'mw.missing': 'удалён',
    'mw.save': 'Сохранить',
    'mw.cancel': 'Отмена',
    'mw.created': 'автор {who}',
    'err.title_invalid': 'Введите название длиной до 200 символов.',
    'err.period_invalid': 'Конец должен быть позже начала.',
    'err.period_too_long': 'Окно длится не больше 90 дней.',
    'err.targets_required': 'Выберите хотя бы один сервис или КЕ.',
    'err.out_of_scope': 'Эти КЕ или сервисы вне вашей области видимости. КЕ считается вашей, если все её сервисы ваши.',
    'err.scope_required': 'Выберите КЕ или сервисы из вашей области видимости.',
    'err.too_many_targets': 'Слишком много сервисов и КЕ в одном окне.',
    'err.ci_not_found': 'Выбранная КЕ больше не существует.',
    'err.service_not_found': 'Выбранный сервис больше не существует.',
    'err.not_active': 'Завершить можно только идущее окно.',
    'err.comment_too_long': 'Комментарий слишком длинный.',
  },
}
