import type { Dict } from '../../i18n'

export const machineStrings: Dict = {
  en: {
    'panel.cpu': 'CPU',
    'panel.memory': 'Memory',
    'panel.load': 'Load average (1 min)',
    'panel.disk': 'Disk space used',
    'panel.net_in': 'Network in',
    'panel.net_out': 'Network out',
    loading: 'Loading…',
    'inc.tab.machine': 'Machine',
    'mc.window': 'Window around the start',
    'mc.window.15': '±15 min',
    'mc.window.60': '±1 h',
    'mc.window.360': '±6 h',
    'mc.window.1440': '±24 h',
    'mc.window.custom': 'Custom',
    'mc.window.minutes': 'min',
    'mc.span': 'Up to the end of the incident',
    'mc.span.hint': 'The window before the start and after the end (now while it lasts)',
    'mc.refresh': 'Refresh',
    'mc.range': '{from} — {to}',
    'mc.hosts': 'Watched by',
    'mc.hosts.none': 'No monitoring system knows this machine',
    'mc.hosts.none.ci': 'The incident has no configuration item yet, and no host of a monitoring system has the name {name}. Bind the incident to an item or read the host lists on the Monitoring page.',
    'mc.hosts.none.text': 'Graphs come from the monitoring systems whose hosts are matched with the item on the Monitoring page.',
    'mc.panels.none': 'No graphs are set up. They are set on the Monitoring page, Graphs and logs tab.',
    'mc.panel.empty': 'No data in this window',
    'mc.panel.error': '{source}: {error}',
    'mc.mark.open': 'Incident started {at}',
    'mc.mark.resolve': 'Incident resolved {at}',
    'mc.legend.open': 'start',
    'mc.legend.resolve': 'end',
    'mc.legend.event': 'events',
    'mc.events': 'Umbrella events about the machine',
    'mc.events.none': 'Umbrella received no events about the machine in this window.',
    'mc.events.error': 'Events could not be read: {error}',
    'mc.events.col.time': 'Time',
    'mc.events.col.source': 'Source',
    'mc.events.col.event': 'Event',
    'mc.events.col.status': 'Status',
    'mc.events.count': '×{n}',
    'mc.incidents': 'Incidents of the machine in this window',
    'mc.incidents.this': 'this one',
    'mc.logs': 'Logs',
    'mc.logs.search': 'Find in lines',
    'mc.logs.find': 'Find',
    'mc.logs.none': 'No lines in this window.',
    'mc.logs.nosources': 'No log sources are turned on. Add one on the Monitoring page, Graphs and logs tab.',
    'mc.logs.nonames': 'The machine has no name to look its lines up by.',
    'mc.logs.truncated': 'Showing the newest {n} lines. Narrow the window or search to see the rest.',
    'mc.logs.names': 'Lines of {names}',
    'mc.logs.error': '{source}: {error}',
    'mc.firing': 'firing',
    'mc.resolved': 'resolved',
    'err.window_invalid': 'The window must be from 1 minute to 7 days.',
    'err.log_text': 'The search text is too long.',
  },
  ru: {
    'panel.cpu': 'CPU',
    'panel.memory': 'Память',
    'panel.load': 'Средняя загрузка (1 мин)',
    'panel.disk': 'Занято на дисках',
    'panel.net_in': 'Сеть, вход',
    'panel.net_out': 'Сеть, выход',
    loading: 'Загрузка…',
    'inc.tab.machine': 'Машина',
    'mc.window': 'Окно вокруг начала',
    'mc.window.15': '±15 мин',
    'mc.window.60': '±1 ч',
    'mc.window.360': '±6 ч',
    'mc.window.1440': '±24 ч',
    'mc.window.custom': 'Своё',
    'mc.window.minutes': 'мин',
    'mc.span': 'До конца инцидента',
    'mc.span.hint': 'Окно до начала и после окончания (пока инцидент идёт — до текущего момента)',
    'mc.refresh': 'Обновить',
    'mc.range': '{from} — {to}',
    'mc.hosts': 'Наблюдают',
    'mc.hosts.none': 'Машину не знает ни одна система мониторинга',
    'mc.hosts.none.ci': 'У инцидента ещё нет КЕ, и ни у одной системы мониторинга нет хоста с именем {name}. Привяжите инцидент к КЕ или перечитайте хосты на странице «Мониторинг».',
    'mc.hosts.none.text': 'Графики берутся из систем мониторинга, хосты которых сопоставлены с КЕ на странице «Мониторинг».',
    'mc.panels.none': 'Графики не настроены. Они задаются на странице «Мониторинг», вкладка «Графики и логи».',
    'mc.panel.empty': 'Нет данных в этом окне',
    'mc.panel.error': '{source}: {error}',
    'mc.mark.open': 'Начало инцидента {at}',
    'mc.mark.resolve': 'Инцидент решён {at}',
    'mc.legend.open': 'начало',
    'mc.legend.resolve': 'конец',
    'mc.legend.event': 'события',
    'mc.events': 'События Umbrella по машине',
    'mc.events.none': 'В этом окне Umbrella не получала событий по машине.',
    'mc.events.error': 'Не удалось прочитать события: {error}',
    'mc.events.col.time': 'Время',
    'mc.events.col.source': 'Источник',
    'mc.events.col.event': 'Событие',
    'mc.events.col.status': 'Состояние',
    'mc.events.count': '×{n}',
    'mc.incidents': 'Инциденты машины в этом окне',
    'mc.incidents.this': 'этот',
    'mc.logs': 'Логи',
    'mc.logs.search': 'Найти в строках',
    'mc.logs.find': 'Найти',
    'mc.logs.none': 'В этом окне строк нет.',
    'mc.logs.nosources': 'Нет включённых источников логов. Добавьте источник на странице «Мониторинг», вкладка «Графики и логи».',
    'mc.logs.nonames': 'У машины нет имени, по которому можно искать строки.',
    'mc.logs.truncated': 'Показаны последние {n} строк. Сузьте окно или поиск, чтобы увидеть остальные.',
    'mc.logs.names': 'Строки {names}',
    'mc.logs.error': '{source}: {error}',
    'mc.firing': 'активно',
    'mc.resolved': 'решено',
    'err.window_invalid': 'Окно — от 1 минуты до 7 суток.',
    'err.log_text': 'Слишком длинный текст поиска.',
  },
}
