import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'inc.search': 'Search by ID, title, item, signal, service or team',
    'inc.refresh': 'Refresh',
    'inc.auto': 'Updates every 10 seconds',
    'inc.count': '{shown} shown',
    'inc.more': 'Showing the first {n}. Narrow the filters to see the rest.',
    'inc.empty': 'No incidents match.',
    'inc.scoped': 'Showing incidents of your business services only',
    'inc.empty.active': 'Nothing is firing right now.',
    'inc.unavailable': 'Incidents need PostgreSQL storage; they appear once the alert tables are ready.',
    'inc.filter.status': 'Status',
    'inc.filter.severity': 'Severity',
    'inc.filter.method': 'Method',
    'inc.filter.team': 'Team',
    'inc.filter.service': 'Service',
    'inc.filter.any': 'Any',
    'inc.filter.reset': 'Reset filters',
    'inc.status.active': 'Active',
    'inc.status.open': 'Open',
    'inc.status.acknowledged': 'Acknowledged',
    'inc.status.resolved': 'Resolved',
    'inc.status.all': 'All',
    'inc.sev.critical': 'Critical',
    'inc.sev.error': 'Error',
    'inc.sev.warning': 'Warning',
    'inc.sev.info': 'Info',
    'inc.method.red': 'RED',
    'inc.method.use': 'USE',
    'inc.method.other': 'Other',
    'inc.role.lead': 'team lead',
    'inc.role.member': 'team member',
    'inc.tile.active': 'Active',
    'inc.tile.acknowledged': '{n} acknowledged',
    'inc.tile.pd': 'Not taken by PagerDuty',
    'inc.tile.fallback': 'Backup notification',
    'inc.tile.suppressed': 'In maintenance',
    'inc.tile.unbound': '{n} without a CI',
    'inc.col.severity': 'Severity',
    'inc.col.incident': 'Incident',
    'inc.col.owner': 'Service · team',
    'inc.col.status': 'Status',
    'inc.col.pd': 'PagerDuty',
    'inc.col.seen': 'Last event',
    'inc.col.count': 'Events',
    'inc.select.all': 'Select all',
    'inc.select.one': 'Select {id}',
    'inc.selected': '{n} selected',
    'inc.ack': 'Acknowledge',
    'inc.resolve': 'Resolve',
    'inc.bulk.done': 'Done: {done}. Skipped: {failed}.',
    'inc.noci': 'not in the catalog',
    'inc.noroute': 'no owner',
    'inc.pd.pending': 'Pending',
    'inc.pd.accepted': 'Taken',
    'inc.pd.acked': 'Acknowledged',
    'inc.pd.failed': 'Not delivered',
    'inc.pd.skipped': 'Not sent',
    'inc.badge.fallback': 'Backup',
    'inc.badge.suppressed': 'Maintenance',
    'inc.ago.s': 'just now',
    'inc.ago.m': '{n} min ago',
    'inc.ago.h': '{n} h ago',
    'inc.ago.d': '{n} d ago',
    'inc.close': 'Close',
    'inc.grafana': 'Context in Grafana',
    'inc.pd.open': 'Open in PagerDuty',
    'inc.tab.main': 'Overview',
    'inc.tab.timeline': 'Timeline',
    'inc.tab.sources': 'Sources',
    'inc.field.status': 'Status',
    'inc.field.severity': 'Severity',
    'inc.field.ci': 'Configuration item',
    'inc.field.signal': 'Signal',
    'inc.field.method': 'Method',
    'inc.field.services': 'Business services',
    'inc.field.team': 'Team',
    'inc.field.people': 'People',
    'inc.field.owners': 'CI owners',
    'inc.field.route': 'Route',
    'inc.field.opened': 'Opened',
    'inc.field.first': 'First event',
    'inc.field.last': 'Last event',
    'inc.field.resolved': 'Resolved',
    'inc.field.acked': 'Acknowledged',
    'inc.field.pd': 'PagerDuty',
    'inc.field.pdroute': 'PagerDuty route',
    'inc.field.pderror': 'Delivery error',
    'inc.field.fallback': 'Backup notification',
    'inc.field.maintenance': 'Maintenance',
    'inc.field.related': 'Related incident',
    'inc.field.labels': 'Labels',
    'inc.field.key': 'Key',
    'inc.via.service': 'owning team of the service',
    'inc.via.ci_owners': 'CI owners from NetBox',
    'inc.via.none': 'nobody: bind the item to a business service with an owning team',
    'inc.by': 'by {who}',
    'inc.src.firing': 'firing',
    'inc.src.resolved': 'back to normal',
    'inc.comment': 'Comment',
    'inc.comment.add': 'Add',
    'inc.comment.placeholder': 'What was done, who is on it…',
    'inc.none': '—',
    'err.not_open': 'Only an open incident can be acknowledged.',
    'err.not_active': 'The incident is already resolved.',
    'err.empty_comment': 'The comment is empty.',
    'err.alerts_unavailable': 'Incidents need PostgreSQL storage; they appear once the alert tables are ready.',
    'err.bad_action': 'Unknown action: an incident can be acknowledged or resolved.',
    'err.too_many': 'Too many incidents at once: at most 1000.',
    'tl.opened': 'Incident opened',
    'tl.reopened': 'Opened again: a new event came within {window} of resolving',
    'tl.resolved': 'Resolved',
    'tl.resolved.sources_resolved': 'Resolved: every source is back to normal',
    'tl.resolved.manual': 'Resolved by hand',
    'tl.resolved.pagerduty': 'Resolved in PagerDuty',
    'tl.acknowledged': 'Acknowledged',
    'tl.severity_raised': 'Severity raised: {from} → {to}',
    'tl.event': '{connector}: {title} — {severity}, {status}',
    'tl.event.value': '{connector}: {title} — {severity}, {status} ({value})',
    'tl.routed': 'Routed to {team} (people: {people})',
    'tl.routed.services': 'Routed through {services} to {team} (people: {people})',
    'tl.routed.owners': 'No team: routed to the CI owners ({people})',
    'tl.routed.none': 'Nobody to route to',
    'tl.ci_unknown': '“{ci}” is not in the catalog: the incident waits for the item',
    'tl.ci_bound': 'Bound to the configuration item {ci}',
    'tl.probable_cause': 'Probable cause: USE incident {alert} on {ci}',
    'tl.affects_service': 'Affects the service: RED incident {alert} on {ci}',
    'tl.suppressed': 'Suppressed by the maintenance window “{window}”',
    'tl.maintenance_over': 'The maintenance window is over: the incident is active',
    'tl.fallback': 'PagerDuty did not take the incident in {after}: backup notification to {people} people',
    'tl.comment': '{text}',
    'tl.pd_skipped': 'Not sent to PagerDuty: {reason}',
    'tl.pd_failed': 'PagerDuty did not take {action}: {error}',
    'tl.pd_accepted': 'PagerDuty took {action} (route “{route}”)',
    'tl.pd_incident_triggered': 'PagerDuty opened an incident',
    'tl.pd_incident_acknowledged': 'Acknowledged in PagerDuty',
    'tl.pd_incident_reopened': 'Opened again in PagerDuty',
    'tl.pd_reassigned': 'Reassigned in PagerDuty: {detail}',
    'tl.pd_escalated': 'Escalated in PagerDuty: {detail}',
    'tl.pd_annotated': 'Note in PagerDuty: {detail}',
    'tl.pd_priority_updated': 'Priority changed in PagerDuty: {detail}',
    'tl.pd_other': 'PagerDuty: {event}',
    'tl.pd_stale': 'Ignored a late PagerDuty update about an earlier incident {incident}: {event}',
    'tl.notify_sent': 'Sent by {channel} to {to}',
    'tl.notify_failed': 'Not sent by {channel} to {to}: {error}',
    'tl.notify_none': 'Backup notification has nobody to send to: no channel is set up or the people have no contacts',
  },
  ru: {
    'inc.search': 'Поиск по ID, заголовку, КЕ, сигналу, сервису или команде',
    'inc.refresh': 'Обновить',
    'inc.auto': 'Обновляется каждые 10 секунд',
    'inc.count': 'Показано: {shown}',
    'inc.more': 'Показаны первые {n}. Уточните фильтры, чтобы увидеть остальные.',
    'inc.empty': 'Подходящих инцидентов нет.',
    'inc.scoped': 'Показаны инциденты только ваших бизнес-сервисов',
    'inc.empty.active': 'Сейчас ничего не горит.',
    'inc.unavailable': 'Для инцидентов нужно хранилище PostgreSQL; они появятся, когда таблицы тревог будут готовы.',
    'inc.filter.status': 'Статус',
    'inc.filter.severity': 'Важность',
    'inc.filter.method': 'Метод',
    'inc.filter.team': 'Команда',
    'inc.filter.service': 'Сервис',
    'inc.filter.any': 'Любой',
    'inc.filter.reset': 'Сбросить фильтры',
    'inc.status.active': 'Активные',
    'inc.status.open': 'Открыт',
    'inc.status.acknowledged': 'Подтверждён',
    'inc.status.resolved': 'Решён',
    'inc.status.all': 'Все',
    'inc.sev.critical': 'Критично',
    'inc.sev.error': 'Ошибка',
    'inc.sev.warning': 'Предупреждение',
    'inc.sev.info': 'Инфо',
    'inc.method.red': 'RED',
    'inc.method.use': 'USE',
    'inc.method.other': 'Другое',
    'inc.role.lead': 'руководитель команды',
    'inc.role.member': 'участник команды',
    'inc.tile.active': 'Активные',
    'inc.tile.acknowledged': 'подтверждено: {n}',
    'inc.tile.pd': 'Не приняты PagerDuty',
    'inc.tile.fallback': 'Резервное оповещение',
    'inc.tile.suppressed': 'На обслуживании',
    'inc.tile.unbound': 'без КЕ: {n}',
    'inc.col.severity': 'Важность',
    'inc.col.incident': 'Инцидент',
    'inc.col.owner': 'Сервис · команда',
    'inc.col.status': 'Статус',
    'inc.col.pd': 'PagerDuty',
    'inc.col.seen': 'Активность',
    'inc.col.count': 'События',
    'inc.select.all': 'Выбрать все',
    'inc.select.one': 'Выбрать {id}',
    'inc.selected': 'Выбрано: {n}',
    'inc.ack': 'Подтвердить',
    'inc.resolve': 'Решить',
    'inc.bulk.done': 'Готово: {done}. Пропущено: {failed}.',
    'inc.noci': 'нет в каталоге',
    'inc.noroute': 'нет владельца',
    'inc.pd.pending': 'Ожидает',
    'inc.pd.accepted': 'Принят',
    'inc.pd.acked': 'Подтверждён',
    'inc.pd.failed': 'Не доставлен',
    'inc.pd.skipped': 'Не отправлен',
    'inc.badge.fallback': 'Резерв',
    'inc.badge.suppressed': 'Обслуживание',
    'inc.ago.s': 'только что',
    'inc.ago.m': '{n} мин назад',
    'inc.ago.h': '{n} ч назад',
    'inc.ago.d': '{n} дн назад',
    'inc.close': 'Закрыть',
    'inc.grafana': 'Контекст в Grafana',
    'inc.pd.open': 'Открыть в PagerDuty',
    'inc.tab.main': 'Основное',
    'inc.tab.timeline': 'Хронология',
    'inc.tab.sources': 'Источники',
    'inc.field.status': 'Статус',
    'inc.field.severity': 'Важность',
    'inc.field.ci': 'КЕ',
    'inc.field.signal': 'Сигнал',
    'inc.field.method': 'Метод',
    'inc.field.services': 'Бизнес-сервисы',
    'inc.field.team': 'Команда',
    'inc.field.people': 'Люди',
    'inc.field.owners': 'Ответственные за КЕ',
    'inc.field.route': 'Маршрут',
    'inc.field.opened': 'Открыт',
    'inc.field.first': 'Первое событие',
    'inc.field.last': 'Последнее событие',
    'inc.field.resolved': 'Решён',
    'inc.field.acked': 'Подтверждён',
    'inc.field.pd': 'PagerDuty',
    'inc.field.pdroute': 'Маршрут PagerDuty',
    'inc.field.pderror': 'Ошибка доставки',
    'inc.field.fallback': 'Резервное оповещение',
    'inc.field.maintenance': 'Обслуживание',
    'inc.field.related': 'Связанный инцидент',
    'inc.field.labels': 'Метки',
    'inc.field.key': 'Ключ',
    'inc.via.service': 'команда-владелец сервиса',
    'inc.via.ci_owners': 'ответственные за КЕ из NetBox',
    'inc.via.none': 'никто: привяжите КЕ к бизнес-сервису с командой-владельцем',
    'inc.by': '{who}',
    'inc.src.firing': 'горит',
    'inc.src.resolved': 'в норме',
    'inc.comment': 'Комментарий',
    'inc.comment.add': 'Добавить',
    'inc.comment.placeholder': 'Что сделано, кто занимается…',
    'inc.none': '—',
    'err.not_open': 'Подтвердить можно только открытый инцидент.',
    'err.not_active': 'Инцидент уже решён.',
    'err.empty_comment': 'Комментарий пустой.',
    'err.alerts_unavailable': 'Для инцидентов нужно хранилище PostgreSQL; они появятся, когда таблицы тревог будут готовы.',
    'err.bad_action': 'Неизвестное действие: инцидент можно подтвердить или решить.',
    'err.too_many': 'Слишком много инцидентов за раз: не больше 1000.',
    'tl.opened': 'Инцидент открыт',
    'tl.reopened': 'Открыт повторно: новое событие пришло в течение {window} после решения',
    'tl.resolved': 'Решён',
    'tl.resolved.sources_resolved': 'Решён: все источники вернулись в норму',
    'tl.resolved.manual': 'Решён вручную',
    'tl.resolved.pagerduty': 'Решён в PagerDuty',
    'tl.acknowledged': 'Подтверждён',
    'tl.severity_raised': 'Важность повышена: {from} → {to}',
    'tl.event': '{connector}: {title} — {severity}, {status}',
    'tl.event.value': '{connector}: {title} — {severity}, {status} ({value})',
    'tl.routed': 'Направлен команде {team}: людей — {people}',
    'tl.routed.services': 'Направлен через {services} команде {team}: людей — {people}',
    'tl.routed.owners': 'Команды нет: направлен ответственным за КЕ ({people})',
    'tl.routed.none': 'Направить некому',
    'tl.ci_unknown': '«{ci}» нет в каталоге: инцидент ждёт КЕ',
    'tl.ci_bound': 'Привязан к КЕ {ci}',
    'tl.probable_cause': 'Вероятная причина: USE-инцидент {alert} на {ci}',
    'tl.affects_service': 'Влияет на сервис: RED-инцидент {alert} на {ci}',
    'tl.suppressed': 'Подавлен окном обслуживания «{window}»',
    'tl.maintenance_over': 'Окно обслуживания закончилось: инцидент активен',
    'tl.fallback': 'PagerDuty не принял инцидент за {after}: резервное оповещение, людей — {people}',
    'tl.comment': '{text}',
    'tl.pd_skipped': 'Не отправлен в PagerDuty: {reason}',
    'tl.pd_failed': 'PagerDuty не принял {action}: {error}',
    'tl.pd_accepted': 'PagerDuty принял {action} (маршрут «{route}»)',
    'tl.pd_incident_triggered': 'В PagerDuty открыт инцидент',
    'tl.pd_incident_acknowledged': 'Подтверждён в PagerDuty',
    'tl.pd_incident_reopened': 'Снова открыт в PagerDuty',
    'tl.pd_reassigned': 'Переназначен в PagerDuty: {detail}',
    'tl.pd_escalated': 'Эскалирован в PagerDuty: {detail}',
    'tl.pd_annotated': 'Заметка в PagerDuty: {detail}',
    'tl.pd_priority_updated': 'Приоритет изменён в PagerDuty: {detail}',
    'tl.pd_other': 'PagerDuty: {event}',
    'tl.pd_stale': 'Проигнорировано запоздавшее обновление PagerDuty о прежнем инциденте {incident}: {event}',
    'tl.notify_sent': 'Отправлено ({channel}): {to}',
    'tl.notify_failed': 'Не отправлено ({channel}) {to}: {error}',
    'tl.notify_none': 'Резервное оповещение некому отправить: каналы не настроены или у людей нет контактов',
  },
}
