import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'inc.search': 'Search by ID, title, item, signal, service or team',
    'inc.refresh': 'Refresh',
    'inc.auto': 'Updates every 10 seconds',
    'inc.count': '{shown} shown',
    'inc.more': 'Showing the first {n}. Narrow the filters to see the rest.',
    'inc.empty': 'No incidents match.',
    'inc.scoped': 'Showing incidents of your business services only (your visibility scope)',
    'inc.empty.active': 'Nothing is firing right now.',
    'inc.unavailable': 'Incidents need PostgreSQL storage; they appear once the alert tables are ready.',
    'inc.filter.status': 'Status',
    'inc.filter.severity': 'Severity',
    'inc.filter.method': 'Method',
    'inc.filter.team': 'Team',
    'inc.filter.service': 'Service',
    'inc.filter.any': 'Any',
    'inc.filter.reset': 'Reset filters',
    'inc.status.active': 'Active',
    'inc.status.open': 'Open',
    'inc.status.acknowledged': 'Acknowledged',
    'inc.status.resolved': 'Resolved',
    'inc.status.all': 'All',
    'inc.method.red': 'RED',
    'inc.method.use': 'USE',
    'inc.method.other': 'Other',
    'inc.role.lead': 'team lead',
    'inc.role.member': 'team member',
    'inc.tile.active': 'Active',
    'inc.tile.acknowledged': '{n} acknowledged',
    'inc.tile.pd': 'Not taken by PagerDuty',
    'inc.tile.fallback': 'Backup notification',
    'inc.tile.suppressed': 'In maintenance',
    'inc.tile.unbound': '{n} without a CI',
    'inc.col.severity': 'Severity',
    'inc.col.incident': 'Incident',
    'inc.col.owner': 'Service · team',
    'inc.col.status': 'Status',
    'inc.col.pd': 'PagerDuty',
    'inc.col.seen': 'Last event',
    'inc.col.count': 'Events',
    'inc.select.all': 'Select all',
    'inc.select.one': 'Select {id}',
    'inc.selected': '{n} selected',
    'inc.ack': 'Acknowledge',
    'inc.resolve': 'Resolve',
    'inc.bulk.done': 'Done: {done}. Skipped: {failed}.',
    'inc.noci': 'not in the catalog',
    'inc.noroute': 'no owner',
    'inc.pd.pending': 'Pending',
    'inc.pd.accepted': 'Taken',
    'inc.pd.acked': 'Acknowledged',
    'inc.pd.failed': 'Not delivered',
    'inc.pd.skipped': 'Not sent',
    'inc.pd.off': 'PagerDuty not used',
    'inc.dur.m': '{n} min',
    'inc.dur.s': '{n} s',
    'inc.badge.fallback': 'Backup',
    'inc.badge.suppressed': 'Maintenance',
    'inc.ago.s': 'just now',
    'inc.ago.m': '{n} min ago',
    'inc.ago.h': '{n} h ago',
    'inc.ago.d': '{n} d ago',
    'inc.close': 'Close',
    'inc.grafana': 'Context in Grafana',
    'inc.pd.open': 'Open in PagerDuty',
    'inc.tab.main': 'Overview',
    'inc.tab.timeline': 'Timeline',
    'inc.tab.sources': 'Sources',
    'inc.field.status': 'Status',
    'inc.field.severity': 'Severity',
    'inc.field.ci': 'Configuration item',
    'inc.field.signal': 'Signal',
    'inc.field.method': 'Method',
    'inc.field.services': 'Business services',
    'inc.field.team': 'Team',
    'inc.field.people': 'People',
    'inc.field.owners': 'Responsible for the CI',
    'inc.field.route': 'Route',
    'inc.field.opened': 'Opened',
    'inc.field.first': 'First event',
    'inc.field.last': 'Last event',
    'inc.field.resolved': 'Resolved',
    'inc.field.acked': 'Acknowledged',
    'inc.field.pd': 'PagerDuty',
    'inc.field.pdroute': 'PagerDuty route',
    'inc.field.pderror': 'Delivery error',
    'inc.field.fallback': 'Backup notification',
    'inc.field.maintenance': 'Maintenance',
    'inc.field.related': 'Related incident',
    'inc.field.labels': 'Labels',
    'inc.field.key': 'Key',
    'inc.via.service': 'owning team of the service',
    'inc.via.ci_owners': 'responsible for the CI (the item has no service with an owning team)',
    'inc.via.none': 'nobody: bind the item to a business service with an owning team',
    'inc.by': 'by {who}',
    'inc.src.firing': 'firing',
    'inc.src.resolved': 'back to normal',
    'inc.comment': 'Comment',
    'inc.comment.add': 'Add',
    'inc.comment.placeholder': 'What was done, who is on it…',
    'inc.none': '—',
    'err.not_open': 'Only an open incident can be acknowledged.',
    'err.not_active': 'The incident is already resolved.',
    'err.empty_comment': 'The comment is empty.',
    'err.alerts_unavailable': 'Incidents need PostgreSQL storage; they appear once the alert tables are ready.',
    'err.bad_action': 'Unknown action: an incident can be acknowledged or resolved.',
    'err.too_many': 'Too many incidents at once: at most 1000.',
    'err.alias_taken': 'Another configuration item is already known by this name (see below), so events with it would match neither.',
    'err.incident_bound': 'The incident is already bound to a configuration item.',
    'err.incident_unbound': 'The incident still matches no single item: another item is known by the same name.',
    'err.incident_no_ci_name': 'The events of this incident name no item.',
    'err.unknown_service': 'The business service no longer exists.',
    'tl.opened': 'Incident opened',
    'tl.reopened': 'Opened again: a new event came within {window} of resolving',
    'tl.resolved': 'Resolved',
    'tl.resolved.sources_resolved': 'Resolved: every source is back to normal',
    'tl.resolved.manual': 'Resolved by hand',
    'tl.resolved.pagerduty': 'Resolved in PagerDuty',
    'tl.acknowledged': 'Acknowledged',
    'tl.severity_raised': 'Severity raised: {from} → {to}',
    'tl.event': '{connector}: {title} — {severity}, {status}',
    'tl.event.value': '{connector}: {title} — {severity}, {status} ({value})',
    'tl.routed': 'Routed to {team} (people: {people})',
    'tl.routed.services': 'Routed through {services} to {team} (people: {people})',
    'tl.routed.owners': 'No team: routed to the people responsible for the CI ({people})',
    'tl.routed.none': 'Nobody to route to',
    'tl.ci_unknown': '“{ci}” is not in the catalog: the incident waits for the item',
    'tl.ci_bound': 'Bound to the configuration item {ci}',
    'tl.merged_from': 'Incident {alert} merged in: it turned out to be about {ci}',
    'tl.merged_into': 'Merged into {alert}: {ci} already had an incident of this signal',
    'tl.resolved.merged': 'Resolved: merged into another incident',
    'inc.optional': 'optional',
    'inc.cancel': 'Cancel',
    'inc.netbox': 'Open in NetBox',
    'inc.field.links': 'Service links',
    'inc.mw.ci': 'Maintenance window for this item…',
    'inc.mw.services': 'Maintenance window for these services…',
    'inc.mw.title': 'Work on {name}',
    'inc.mw.gone': 'the window no longer exists',
    'inc.ci.unknown': '“{name}” is not in the catalog, so the incident has no service or team',
    'inc.ci.unknown.text': 'Create the configuration item or say which existing one it is: the incident is routed at once, and later events with this name too.',
    'inc.ci.unknown.ask': 'Ask someone who edits the catalog to add the item or bind this name to an existing one.',
    'inc.ci.create': 'Create item',
    'inc.ci.create.title': 'New configuration item',
    'inc.ci.create.text': 'Filled in from the event “{name}”. The incident is bound to the item once it is created.',
    'inc.ci.name': 'Name',
    'inc.ci.name.alias': 'Events call it “{name}”: that name is kept as an alias of the item.',
    'inc.ci.kind': 'Type',
    'inc.ci.kind.device': 'Device',
    'inc.ci.kind.vm': 'Virtual machine',
    'inc.ci.kind.service': 'Service',
    'inc.ci.kind.other': 'Other',
    'inc.ci.ips': 'IP addresses',
    'inc.ci.service': 'Business service',
    'inc.ci.service.hint': 'The incident goes to the owner team of the service.',
    'inc.ci.service.none': 'Do not bind',
    'inc.ci.descr': 'Description',
    'inc.ci.description': 'Created from incident {id}',
    'inc.ci.bind.open': 'Bind to an existing item…',
    'inc.ci.bind': 'Bind',
    'inc.ci.bind.title': 'Bind to an existing configuration item',
    'inc.ci.bind.text': 'Pick the item the events call “{name}”.',
    'inc.ci.bind.search': 'Configuration item',
    'inc.ci.bind.ph': 'Name, IP address, tag…',
    'inc.ci.bind.nothing': 'Nothing found.',
    'inc.ci.bind.effect': '“{name}” becomes an alias of {ci}: this incident and later events with this name go to it.',
    'inc.ci.done': 'The item is in the catalog; incidents bound: {n}.',
    'inc.resolve.title': 'Resolve {id}?',
    'inc.resolve.firing': 'Sources still fire: {n}',
    'inc.resolve.firing.text': 'If their event repeats within 10 minutes, the incident opens again.',
    'inc.resolve.calm': 'Every source is back to normal.',
    'inc.resolve.comment.ph': 'What was done (goes to the timeline)',
    'inc.bulk.resolve.title': 'Resolve {n} incidents?',
    'inc.bulk.resolve.firing': 'Sources of {n} of them still fire: they open again if their events repeat within 10 minutes.',
    'inc.bulk.ack.title': 'Acknowledge {n} incidents?',
    'inc.bulk.confirm': 'Confirm',
    'tl.probable_cause': 'Probable cause: USE incident {alert} on {ci}',
    'tl.affects_service': 'Affects the service: RED incident {alert} on {ci}',
    'tl.suppressed': 'Suppressed by the maintenance window “{window}”',
    'tl.maintenance_over': 'The maintenance window is over: the incident is active',
    'tl.fallback': 'PagerDuty did not take the incident in {after}: backup notification to {people} people',
    'tl.fallback.pd_not_taken': 'PagerDuty did not take the incident in {after}: backup notification to {people} people',
    'tl.fallback.pd_not_taken.now': 'Backup notification right away, without waiting for PagerDuty: {people} people',
    'tl.fallback.pd_off': 'Backup notification (PagerDuty is not used): {people} people',
    'tl.fallback.pd_off.later': 'Not taken in {after}: backup notification (PagerDuty is not used) to {people} people',
    'tl.fallback.pd_skipped': 'Not sent to PagerDuty (below its threshold): backup notification to {people} people',
    'tl.fallback_cancelled': 'Backup notification cancelled: the incident is already {status}',
    'tl.notify_followup': 'Follow-up “{event}” sent by {channel} to {to}',
    'tl.notify_followup_failed': 'Follow-up “{event}” not sent by {channel} to {to}: {error}',
    'tl.pd_skipped.below_threshold': 'Not sent to PagerDuty: below its minimum severity ({min})',
    'tl.pd_skipped.test': 'Not sent to PagerDuty: a test event',
    'tl.pd_failed.code': 'PagerDuty did not take {action}: {reason}',
    'tl.pd_failed.detail': 'PagerDuty did not take {action}: {reason} ({detail})',
    'pd.action.trigger': 'the incident',
    'pd.action.acknowledge': 'the acknowledgement',
    'pd.action.resolve': 'the resolution',
    'pd.err.no_key': 'no integration key is set (Settings → Alerting → PagerDuty)',
    'pd.err.key_unavailable': 'the integration key cannot be read from the secret store',
    'pd.err.queue_full': 'the sending queue is full',
    'pd.err.breaker': 'sending is paused for a minute after a series of failures',
    'pd.err.unreachable': 'PagerDuty is not reachable from Umbrella (network or proxy)',
    'pd.err.unavailable': 'PagerDuty is not answering for now; it is retried',
    'pd.err.rejected': 'PagerDuty rejected the event',
    'pd.err.error': 'delivery error',
    'fu.acknowledged': 'acknowledged',
    'fu.resolved': 'resolved',
    'tl.comment': '{text}',
    'tl.pd_skipped': 'Not sent to PagerDuty: {reason}',
    'tl.pd_failed': 'PagerDuty did not take {action}: {error}',
    'tl.pd_accepted': 'PagerDuty took {action} (route “{route}”)',
    'tl.pd_incident_triggered': 'PagerDuty opened an incident',
    'tl.pd_incident_acknowledged': 'Acknowledged in PagerDuty',
    'tl.pd_incident_reopened': 'Opened again in PagerDuty',
    'tl.pd_reassigned': 'Reassigned in PagerDuty: {detail}',
    'tl.pd_escalated': 'Escalated in PagerDuty: {detail}',
    'tl.pd_annotated': 'Note in PagerDuty: {detail}',
    'tl.pd_priority_updated': 'Priority changed in PagerDuty: {detail}',
    'tl.pd_other': 'PagerDuty: {event}',
    'tl.pd_stale': 'Ignored a late PagerDuty update about an earlier incident {incident}: {event}',
    'tl.notify_sent': 'Sent by {channel} to {to}',
    'tl.notify_failed': 'Not sent by {channel} to {to}: {error}',
    'tl.notify_none': 'Backup notification has nobody to send to: no channel is set up or the people have no contacts',
    'inc.badge.excluded': 'Host excluded',
    'inc.badge.test': 'Test',
    'inc.field.excluded': 'Suppressed',
    'inc.excluded.text': 'The host is marked “Not a CI” on the Monitoring systems page: the incident is not sent anywhere.',
    'tl.host_excluded': 'The host “{ci}” is marked “Not a CI”: suppressed, not sent anywhere',
    'tl.host_included': 'The host is no longer excluded: the incident is sent as usual',
    'tl.ci_unbound': 'The link of “{ci}” changed: the incident is no longer bound to {was}',
    'tl.resolved.test_expired': 'Resolved: the test event is over',
  },
  ru: {
    'inc.search': 'Поиск по ID, заголовку, КЕ, сигналу, сервису или команде',
    'inc.refresh': 'Обновить',
    'inc.auto': 'Обновляется каждые 10 секунд',
    'inc.count': 'Показано: {shown}',
    'inc.more': 'Показаны первые {n}. Уточните фильтры, чтобы увидеть остальные.',
    'inc.empty': 'Подходящих инцидентов нет.',
    'inc.scoped': 'Показаны инциденты только ваших бизнес-сервисов (ваша область видимости)',
    'inc.empty.active': 'Сейчас ничего не горит.',
    'inc.unavailable': 'Для инцидентов нужно хранилище PostgreSQL; они появятся, когда таблицы тревог будут готовы.',
    'inc.filter.status': 'Статус',
    'inc.filter.severity': 'Важность',
    'inc.filter.method': 'Метод',
    'inc.filter.team': 'Команда',
    'inc.filter.service': 'Сервис',
    'inc.filter.any': 'Любой',
    'inc.filter.reset': 'Сбросить фильтры',
    'inc.status.active': 'Активные',
    'inc.status.open': 'Открыт',
    'inc.status.acknowledged': 'Подтверждён',
    'inc.status.resolved': 'Решён',
    'inc.status.all': 'Все',
    'inc.method.red': 'RED',
    'inc.method.use': 'USE',
    'inc.method.other': 'Другое',
    'inc.role.lead': 'руководитель команды',
    'inc.role.member': 'участник команды',
    'inc.tile.active': 'Активные',
    'inc.tile.acknowledged': 'подтверждено: {n}',
    'inc.tile.pd': 'Не приняты PagerDuty',
    'inc.tile.fallback': 'Резервное оповещение',
    'inc.tile.suppressed': 'На обслуживании',
    'inc.tile.unbound': 'без КЕ: {n}',
    'inc.col.severity': 'Важность',
    'inc.col.incident': 'Инцидент',
    'inc.col.owner': 'Сервис · команда',
    'inc.col.status': 'Статус',
    'inc.col.pd': 'PagerDuty',
    'inc.col.seen': 'Активность',
    'inc.col.count': 'События',
    'inc.select.all': 'Выбрать все',
    'inc.select.one': 'Выбрать {id}',
    'inc.selected': 'Выбрано: {n}',
    'inc.ack': 'Подтвердить',
    'inc.resolve': 'Решить',
    'inc.bulk.done': 'Готово: {done}. Пропущено: {failed}.',
    'inc.noci': 'нет в каталоге',
    'inc.noroute': 'нет владельца',
    'inc.pd.pending': 'Ожидает',
    'inc.pd.accepted': 'Принят',
    'inc.pd.acked': 'Подтверждён',
    'inc.pd.failed': 'Не доставлен',
    'inc.pd.skipped': 'Не отправлен',
    'inc.pd.off': 'PagerDuty не используется',
    'inc.dur.m': '{n} мин',
    'inc.dur.s': '{n} с',
    'inc.badge.fallback': 'Резерв',
    'inc.badge.suppressed': 'Обслуживание',
    'inc.ago.s': 'только что',
    'inc.ago.m': '{n} мин назад',
    'inc.ago.h': '{n} ч назад',
    'inc.ago.d': '{n} дн назад',
    'inc.close': 'Закрыть',
    'inc.grafana': 'Контекст в Grafana',
    'inc.pd.open': 'Открыть в PagerDuty',
    'inc.tab.main': 'Основное',
    'inc.tab.timeline': 'Хронология',
    'inc.tab.sources': 'Источники',
    'inc.field.status': 'Статус',
    'inc.field.severity': 'Важность',
    'inc.field.ci': 'КЕ',
    'inc.field.signal': 'Сигнал',
    'inc.field.method': 'Метод',
    'inc.field.services': 'Бизнес-сервисы',
    'inc.field.team': 'Команда',
    'inc.field.people': 'Люди',
    'inc.field.owners': 'Ответственные за КЕ',
    'inc.field.route': 'Маршрут',
    'inc.field.opened': 'Открыт',
    'inc.field.first': 'Первое событие',
    'inc.field.last': 'Последнее событие',
    'inc.field.resolved': 'Решён',
    'inc.field.acked': 'Подтверждён',
    'inc.field.pd': 'PagerDuty',
    'inc.field.pdroute': 'Маршрут PagerDuty',
    'inc.field.pderror': 'Ошибка доставки',
    'inc.field.fallback': 'Резервное оповещение',
    'inc.field.maintenance': 'Обслуживание',
    'inc.field.related': 'Связанный инцидент',
    'inc.field.labels': 'Метки',
    'inc.field.key': 'Ключ',
    'inc.via.service': 'команда-владелец сервиса',
    'inc.via.ci_owners': 'ответственные за КЕ (у КЕ нет сервиса с командой-владельцем)',
    'inc.via.none': 'никто: привяжите КЕ к бизнес-сервису с командой-владельцем',
    'inc.by': '{who}',
    'inc.src.firing': 'горит',
    'inc.src.resolved': 'в норме',
    'inc.comment': 'Комментарий',
    'inc.comment.add': 'Добавить',
    'inc.comment.placeholder': 'Что сделано, кто занимается…',
    'inc.none': '—',
    'err.not_open': 'Подтвердить можно только открытый инцидент.',
    'err.not_active': 'Инцидент уже решён.',
    'err.empty_comment': 'Комментарий пустой.',
    'err.alerts_unavailable': 'Для инцидентов нужно хранилище PostgreSQL; они появятся, когда таблицы тревог будут готовы.',
    'err.bad_action': 'Неизвестное действие: инцидент можно подтвердить или решить.',
    'err.too_many': 'Слишком много инцидентов за раз: не больше 1000.',
    'err.alias_taken': 'Этим именем уже называется другая КЕ (см. ниже), и события с ним не подойдут ни к одной.',
    'err.incident_bound': 'Инцидент уже привязан к КЕ.',
    'err.incident_unbound': 'Инцидент всё ещё не подходит ни к одной КЕ: этим же именем называется другая КЕ.',
    'err.incident_no_ci_name': 'В событиях этого инцидента не указана КЕ.',
    'err.unknown_service': 'Бизнес-сервиса уже нет.',
    'tl.opened': 'Инцидент открыт',
    'tl.reopened': 'Открыт повторно: новое событие пришло в течение {window} после решения',
    'tl.resolved': 'Решён',
    'tl.resolved.sources_resolved': 'Решён: все источники вернулись в норму',
    'tl.resolved.manual': 'Решён вручную',
    'tl.resolved.pagerduty': 'Решён в PagerDuty',
    'tl.acknowledged': 'Подтверждён',
    'tl.severity_raised': 'Важность повышена: {from} → {to}',
    'tl.event': '{connector}: {title} — {severity}, {status}',
    'tl.event.value': '{connector}: {title} — {severity}, {status} ({value})',
    'tl.routed': 'Направлен команде {team}: людей — {people}',
    'tl.routed.services': 'Направлен через {services} команде {team}: людей — {people}',
    'tl.routed.owners': 'Команды нет: направлен ответственным за КЕ ({people})',
    'tl.routed.none': 'Направить некому',
    'tl.ci_unknown': '«{ci}» нет в каталоге: инцидент ждёт КЕ',
    'tl.ci_bound': 'Привязан к КЕ {ci}',
    'tl.merged_from': 'Присоединён инцидент {alert}: он оказался про {ci}',
    'tl.merged_into': 'Присоединён к {alert}: у {ci} уже был инцидент по этому сигналу',
    'tl.resolved.merged': 'Решён: присоединён к другому инциденту',
    'inc.optional': 'необязательно',
    'inc.cancel': 'Отмена',
    'inc.netbox': 'Открыть в NetBox',
    'inc.field.links': 'Ссылки сервиса',
    'inc.mw.ci': 'Сервисное окно на эту КЕ…',
    'inc.mw.services': 'Сервисное окно на эти сервисы…',
    'inc.mw.title': 'Работы на {name}',
    'inc.mw.gone': 'окно уже удалено',
    'inc.ci.unknown': '«{name}» нет в каталоге, поэтому у инцидента нет сервиса и команды',
    'inc.ci.unknown.text': 'Создайте КЕ или укажите, какая это из существующих: инцидент сразу получит маршрут, как и следующие события с этим именем.',
    'inc.ci.unknown.ask': 'Попросите того, кто ведёт каталог, создать КЕ или привязать это имя к существующей.',
    'inc.ci.create': 'Создать КЕ',
    'inc.ci.create.title': 'Новая КЕ',
    'inc.ci.create.text': 'Заполнено по событию «{name}». После создания инцидент будет привязан к КЕ.',
    'inc.ci.name': 'Название',
    'inc.ci.name.alias': 'В событиях она называется «{name}»: это имя сохранится как дополнительное имя КЕ.',
    'inc.ci.kind': 'Тип',
    'inc.ci.kind.device': 'Устройство',
    'inc.ci.kind.vm': 'Виртуальная машина',
    'inc.ci.kind.service': 'Сервис',
    'inc.ci.kind.other': 'Другое',
    'inc.ci.ips': 'IP-адреса',
    'inc.ci.service': 'Бизнес-сервис',
    'inc.ci.service.hint': 'Инцидент пойдёт команде-владельцу сервиса.',
    'inc.ci.service.none': 'Не привязывать',
    'inc.ci.descr': 'Описание',
    'inc.ci.description': 'Создана из инцидента {id}',
    'inc.ci.bind.open': 'Привязать к существующей КЕ…',
    'inc.ci.bind': 'Привязать',
    'inc.ci.bind.title': 'Привязать к существующей КЕ',
    'inc.ci.bind.text': 'Выберите КЕ, которую события называют «{name}».',
    'inc.ci.bind.search': 'КЕ',
    'inc.ci.bind.ph': 'Название, IP-адрес, тег…',
    'inc.ci.bind.nothing': 'Ничего не найдено.',
    'inc.ci.bind.effect': '«{name}» станет дополнительным именем КЕ {ci}: этот инцидент и следующие события с этим именем пойдут к ней.',
    'inc.ci.done': 'КЕ в каталоге; привязано инцидентов: {n}.',
    'inc.resolve.title': 'Решить {id}?',
    'inc.resolve.firing': 'Источники ещё горят: {n}',
    'inc.resolve.firing.text': 'Если событие повторится в течение 10 минут, инцидент откроется снова.',
    'inc.resolve.calm': 'Все источники вернулись в норму.',
    'inc.resolve.comment.ph': 'Что сделано (попадёт в хронологию)',
    'inc.bulk.resolve.title': 'Решить инциденты: {n}?',
    'inc.bulk.resolve.firing': 'У {n} из них источники ещё горят: они откроются снова, если событие повторится в течение 10 минут.',
    'inc.bulk.ack.title': 'Подтвердить инциденты: {n}?',
    'inc.bulk.confirm': 'Подтвердить',
    'tl.probable_cause': 'Вероятная причина: USE-инцидент {alert} на {ci}',
    'tl.affects_service': 'Влияет на сервис: RED-инцидент {alert} на {ci}',
    'tl.suppressed': 'Подавлен окном обслуживания «{window}»',
    'tl.maintenance_over': 'Окно обслуживания закончилось: инцидент активен',
    'tl.fallback': 'PagerDuty не принял инцидент за {after}: резервное оповещение, людей — {people}',
    'tl.fallback.pd_not_taken': 'PagerDuty не принял инцидент за {after}: резервное оповещение, людей — {people}',
    'tl.fallback.pd_not_taken.now': 'Резервное оповещение сразу, без ожидания PagerDuty: людей — {people}',
    'tl.fallback.pd_off': 'Резервное оповещение (PagerDuty не используется): людей — {people}',
    'tl.fallback.pd_off.later': 'Никто не взял за {after}: резервное оповещение (PagerDuty не используется), людей — {people}',
    'tl.fallback.pd_skipped': 'В PagerDuty не отправлялся (ниже порога): резервное оповещение, людей — {people}',
    'tl.fallback_cancelled': 'Резервное оповещение отменено: инцидент уже {status}',
    'tl.notify_followup': 'Уведомление «{event}» отправлено ({channel}): {to}',
    'tl.notify_followup_failed': 'Уведомление «{event}» не отправлено ({channel}) {to}: {error}',
    'tl.pd_skipped.below_threshold': 'Не отправлен в PagerDuty: важность ниже порога ({min})',
    'tl.pd_skipped.test': 'Не отправлен в PagerDuty: тестовое событие',
    'tl.pd_failed.code': 'PagerDuty не принял {action}: {reason}',
    'tl.pd_failed.detail': 'PagerDuty не принял {action}: {reason} ({detail})',
    'pd.action.trigger': 'инцидент',
    'pd.action.acknowledge': 'подтверждение',
    'pd.action.resolve': 'решение',
    'pd.err.no_key': 'не задан ключ интеграции (Настройки → Оповещения → PagerDuty)',
    'pd.err.key_unavailable': 'ключ интеграции не читается из хранилища секретов',
    'pd.err.queue_full': 'очередь отправки переполнена',
    'pd.err.breaker': 'отправка приостановлена на минуту после серии ошибок',
    'pd.err.unreachable': 'PagerDuty недоступен из Umbrella (сеть или прокси)',
    'pd.err.unavailable': 'PagerDuty временно не отвечает; попытки продолжаются',
    'pd.err.rejected': 'PagerDuty отклонил событие',
    'pd.err.error': 'ошибка доставки',
    'fu.acknowledged': 'взят в работу',
    'fu.resolved': 'решён',
    'tl.comment': '{text}',
    'tl.pd_skipped': 'Не отправлен в PagerDuty: {reason}',
    'tl.pd_failed': 'PagerDuty не принял {action}: {error}',
    'tl.pd_accepted': 'PagerDuty принял {action} (маршрут «{route}»)',
    'tl.pd_incident_triggered': 'В PagerDuty открыт инцидент',
    'tl.pd_incident_acknowledged': 'Подтверждён в PagerDuty',
    'tl.pd_incident_reopened': 'Снова открыт в PagerDuty',
    'tl.pd_reassigned': 'Переназначен в PagerDuty: {detail}',
    'tl.pd_escalated': 'Эскалирован в PagerDuty: {detail}',
    'tl.pd_annotated': 'Заметка в PagerDuty: {detail}',
    'tl.pd_priority_updated': 'Приоритет изменён в PagerDuty: {detail}',
    'tl.pd_other': 'PagerDuty: {event}',
    'tl.pd_stale': 'Проигнорировано запоздавшее обновление PagerDuty о прежнем инциденте {incident}: {event}',
    'tl.notify_sent': 'Отправлено ({channel}): {to}',
    'tl.notify_failed': 'Не отправлено ({channel}) {to}: {error}',
    'tl.notify_none': 'Резервное оповещение некому отправить: каналы не настроены или у людей нет контактов',
    'inc.badge.excluded': 'Хост исключён',
    'inc.badge.test': 'Тест',
    'inc.field.excluded': 'Подавлен',
    'inc.excluded.text': 'Хост помечен «Не является КЕ» на странице «Системы мониторинга»: инцидент никуда не отправляется.',
    'tl.host_excluded': 'Хост «{ci}» помечен «Не является КЕ»: инцидент подавлен и никуда не отправляется',
    'tl.host_included': 'Хост больше не исключён: инцидент отправляется как обычно',
    'tl.ci_unbound': 'Привязка «{ci}» изменилась: инцидент больше не привязан к {was}',
    'tl.resolved.test_expired': 'Решён: тестовое событие завершено',
  },
}
