import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'nb.state.title': 'Connection',
    'nb.state.text':
      'Umbrella reads devices, virtual machines and services from NetBox as configuration items, creates user accounts for the contacts assigned to them and keeps both up to date.',
    'nb.state': 'State',
    'nb.state.on': 'Connected',
    'nb.state.off': 'Not connected',
    'nb.url': 'NetBox address',
    'nb.url.hint': 'The address of the NetBox web interface, for example https://netbox.example.com.',
    'nb.token': 'API token',
    'nb.token.hint': 'A NetBox API token with read access; write access is needed to register, change and delete objects. It is stored in OpenBao.',
    'nb.token.keep': 'Leave empty to keep the saved token.',
    'nb.token.again': 'The address changed: enter the token again.',
    'nb.token.set': 'Saved in OpenBao',
    'nb.token.unset': 'Not set',
    'nb.items': 'Configuration items from NetBox',
    'nb.users': 'Accounts made for NetBox contacts',
    'nb.settings': 'Connection settings',
    'nb.enable': 'Connect NetBox',
    'nb.enable.hint': 'When turned off, synchronization stops; configuration items stay as they are.',
    'nb.skipVerify': 'Do not verify the TLS certificate',
    'nb.skipVerify.hint': 'Only for test installations with a self-signed certificate.',
    'nb.interval': 'Synchronize every',
    'nb.interval.hint': '0 synchronizes only with the button.',
    'nb.minutes': 'min',
    'nb.import': 'What to import',
    'nb.import.devices': 'Devices',
    'nb.import.vms': 'Virtual machines',
    'nb.import.services': 'Services',
    'nb.contacts': 'Responsible people',
    'nb.contacts.hint':
      'Contacts assigned to objects become their responsible people. An account with the same e-mail is used; otherwise an account is created and updated when the contact changes in NetBox. Such a person keeps the account when signing in through LDAP / AD or Entra ID.',
    'nb.directory': 'Match with the domain controller',
    'nb.directory.hint': 'Devices and virtual machines are matched with computer objects of Active Directory by name: DNS name, operating system, last logon, disabled accounts.',
    'nb.directory.none': 'Connect LDAP / AD of the Active Directory type in the settings to use this.',
    'nb.check': 'Check connection',
    'nb.checking': 'Checking…',
    'nb.save': 'Save',
    'nb.saved': 'NetBox settings are saved.',
    'nb.save.hint': 'The connection is checked before saving.',
    'nb.ok': 'NetBox answers',
    'nb.ok.text': 'NetBox {version}: {devices} devices, {vms} virtual machines, {services} services, {contacts} contacts.',
    'nb.fail': 'Umbrella cannot work with NetBox using these settings',
    'nb.off': 'NetBox is not connected. Configuration items can still be created by hand.',
    'nb.defaults': 'New objects in NetBox',
    'nb.defaults.text': 'Configuration items created in Umbrella are registered in NetBox with these values.',
    'nb.defaults.save': 'Save defaults',
    'nb.site': 'Site',
    'nb.deviceRole': 'Device role',
    'nb.deviceType': 'Device type',
    'nb.cluster': 'Cluster for virtual machines',
    'nb.pick': 'Not chosen',
    'nb.sync': 'Synchronization',
    'nb.sync.now': 'Synchronize now',
    'nb.sync.running': 'Synchronizing…',
    'nb.sync.never': 'NetBox has not been synchronized yet.',
    'nb.sync.last': 'Last run',
    'nb.sync.next': 'Next run',
    'nb.sync.manual': 'Only with the button',
    'nb.sync.result': 'Result',
    'nb.sync.ok': 'Done',
    'nb.sync.failed': 'Failed',
    'nb.sync.objects': 'Objects',
    'nb.sync.objects.value': '{objects} read: {created} new, {updated} changed, {deleted} deleted, {unlinked} unlinked',
    'nb.sync.users': 'Responsible people',
    'nb.sync.users.value': '{contacts} contacts: {created} accounts created, {updated} updated, {linked} linked by e-mail',
    'nb.sync.directory': 'Domain controller',
    'nb.sync.directory.value': '{matched} found, {missing} not found',
    'nb.sync.directory.off': 'Not checked',
    'nb.sync.done': 'Synchronization finished.',
    'nb.sync.by': 'by {actor}',
    'nb.sync.held': 'Items missing from NetBox were kept: {count}',
    'nb.sync.held.empty':
      'NetBox returned no objects at all. This usually means the API token lost its permissions or a filter is wrong, so nothing was deleted or unlinked. Check NetBox and synchronize again.',
    'nb.sync.held.share':
      'More than half of the items linked to NetBox are missing from its answer. To keep the catalog safe from an incomplete answer they were not deleted or unlinked. If they were really removed in NetBox, confirm the removal.',
    'nb.sync.held.confirm': 'Remove {count} missing items',
    'err.netbox_token_required': 'Enter the NetBox API token.',
    'err.netbox_invalid': 'NetBox settings are incomplete.',
    'err.netbox_unavailable': 'Umbrella cannot work with NetBox using these settings.',
    'err.netbox_off': 'NetBox is not connected.',
    'err.netbox_failed': 'NetBox refused the request.',
    'err.netbox_sync_running': 'A synchronization is already running.',
  },
  ru: {
    'nb.state.title': 'Подключение',
    'nb.state.text':
      'Umbrella загружает из NetBox устройства, виртуальные машины и сервисы как конфигурационные единицы, заводит учётные записи для назначенных им контактов и поддерживает их в актуальном состоянии.',
    'nb.state': 'Состояние',
    'nb.state.on': 'Подключён',
    'nb.state.off': 'Не подключён',
    'nb.url': 'Адрес NetBox',
    'nb.url.hint': 'Адрес веб-интерфейса NetBox, например https://netbox.example.com.',
    'nb.token': 'API-токен',
    'nb.token.hint': 'API-токен NetBox с правом чтения; для регистрации, изменения и удаления объектов нужно право записи. Хранится в OpenBao.',
    'nb.token.keep': 'Оставьте пустым, чтобы сохранить текущий токен.',
    'nb.token.again': 'Адрес изменился: введите токен ещё раз.',
    'nb.token.set': 'Сохранён в OpenBao',
    'nb.token.unset': 'Не задан',
    'nb.items': 'КЕ из NetBox',
    'nb.users': 'Учётные записи контактов NetBox',
    'nb.settings': 'Настройки подключения',
    'nb.enable': 'Подключить NetBox',
    'nb.enable.hint': 'Если выключить, синхронизация остановится; КЕ останутся как есть.',
    'nb.skipVerify': 'Не проверять сертификат TLS',
    'nb.skipVerify.hint': 'Только для тестовых установок с самоподписанным сертификатом.',
    'nb.interval': 'Синхронизировать каждые',
    'nb.interval.hint': '0 — только по кнопке.',
    'nb.minutes': 'мин',
    'nb.import': 'Что загружать',
    'nb.import.devices': 'Устройства',
    'nb.import.vms': 'Виртуальные машины',
    'nb.import.services': 'Сервисы',
    'nb.contacts': 'Ответственные',
    'nb.contacts.hint':
      'Контакты, назначенные объектам, становятся ответственными за КЕ. Если есть учётная запись с той же почтой, используется она; иначе учётная запись создаётся и обновляется при изменении контакта в NetBox. При входе через LDAP / AD или Entra ID человек получает эту же учётную запись.',
    'nb.directory': 'Сверка с контроллером домена',
    'nb.directory.hint':
      'Устройства и виртуальные машины сопоставляются с объектами компьютеров Active Directory по имени: DNS-имя, операционная система, последний вход, отключённые учётные записи.',
    'nb.directory.none': 'Чтобы включить сверку, подключите в настройках LDAP / AD типа Active Directory.',
    'nb.check': 'Проверить подключение',
    'nb.checking': 'Проверка…',
    'nb.save': 'Сохранить',
    'nb.saved': 'Настройки NetBox сохранены.',
    'nb.save.hint': 'Перед сохранением подключение проверяется.',
    'nb.ok': 'NetBox отвечает',
    'nb.ok.text': 'NetBox {version}: устройств {devices}, виртуальных машин {vms}, сервисов {services}, контактов {contacts}.',
    'nb.fail': 'С этими настройками Umbrella не может работать с NetBox',
    'nb.off': 'NetBox не подключён. КЕ можно заводить вручную.',
    'nb.defaults': 'Новые объекты в NetBox',
    'nb.defaults.text': 'С этими значениями КЕ, созданные в Umbrella, регистрируются в NetBox.',
    'nb.defaults.save': 'Сохранить значения',
    'nb.site': 'Площадка',
    'nb.deviceRole': 'Роль устройства',
    'nb.deviceType': 'Тип устройства',
    'nb.cluster': 'Кластер для виртуальных машин',
    'nb.pick': 'Не выбрано',
    'nb.sync': 'Синхронизация',
    'nb.sync.now': 'Синхронизировать',
    'nb.sync.running': 'Синхронизация…',
    'nb.sync.never': 'Синхронизации с NetBox ещё не было.',
    'nb.sync.last': 'Последний запуск',
    'nb.sync.next': 'Следующий запуск',
    'nb.sync.manual': 'Только по кнопке',
    'nb.sync.result': 'Результат',
    'nb.sync.ok': 'Выполнена',
    'nb.sync.failed': 'Ошибка',
    'nb.sync.objects': 'Объекты',
    'nb.sync.objects.value': 'прочитано {objects}: новых {created}, изменено {updated}, удалено {deleted}, отвязано {unlinked}',
    'nb.sync.users': 'Ответственные',
    'nb.sync.users.value': 'контактов {contacts}: создано учётных записей {created}, обновлено {updated}, привязано по почте {linked}',
    'nb.sync.directory': 'Контроллер домена',
    'nb.sync.directory.value': 'найдено {matched}, не найдено {missing}',
    'nb.sync.directory.off': 'Не проверялся',
    'nb.sync.done': 'Синхронизация завершена.',
    'nb.sync.by': '{actor}',
    'nb.sync.held': 'Объекты, которых нет в ответе NetBox, сохранены: {count}',
    'nb.sync.held.empty':
      'NetBox не вернул ни одного объекта. Обычно это значит, что API-токен потерял права или фильтр задан неверно, поэтому ничего не удалено и не отвязано. Проверьте NetBox и запустите синхронизацию снова.',
    'nb.sync.held.share':
      'В ответе NetBox нет больше половины связанных с ним объектов. Чтобы неполный ответ не опустошил каталог, они не удалены и не отвязаны. Если они действительно удалены в NetBox, подтвердите удаление.',
    'nb.sync.held.confirm': 'Удалить отсутствующие объекты: {count}',
    'err.netbox_token_required': 'Введите API-токен NetBox.',
    'err.netbox_invalid': 'Настройки NetBox заполнены не полностью.',
    'err.netbox_unavailable': 'С этими настройками Umbrella не может работать с NetBox.',
    'err.netbox_off': 'NetBox не подключён.',
    'err.netbox_failed': 'NetBox отклонил запрос.',
    'err.netbox_sync_running': 'Синхронизация уже идёт.',
  },
}
