import type { Dict } from '../i18n'

export const strings: Dict = {
  en: {
    'step.policy': 'Password policy',
    'step.policy.sub': 'Local accounts',
    'pol.title': 'Password policy for local accounts',
    'pol.text':
      'Umbrella checks every local password against these rules, including the administrator you create next. Directory (LDAP / AD) passwords follow the directory policy.',
    'ad.last_name': 'Last name',
    'ad.first_name': 'First name',
    'ad.middle_name': 'Middle name',
    'ad.if_any': 'if any',
    'ad.title_field': 'Job title',
    'ad.department': 'Department',
    'ad.manager': 'Manager',
    'ad.email.hint': 'Also used to pick a Gravatar picture until an avatar is uploaded.',
    'ad.email.bad': 'The e-mail address looks invalid.',
    title: 'Initial setup',
    'step.code': 'Setup code',
    'step.code.sub': 'Confirm access',
    'step.prefs': 'Language, theme, time',
    'step.prefs.sub': 'Defaults for everyone',
    'step.openbao': 'OpenBao',
    'step.openbao.sub': 'Secret storage',
    'step.postgres': 'PostgreSQL',
    'step.postgres.sub': 'Database',
    'step.ldap': 'LDAP / AD',
    'step.ldap.sub': 'Optional',
    'step.admin': 'Administrator',
    'step.admin.sub': 'Local account',
    'step.review': 'Review',
    'step.review.sub': 'Finish setup',
    back: 'Back',
    next: 'Next',
    check: 'Check connection',
    checking: 'Checking…',
    optional: 'optional',

    'code.title': 'Enter the setup code',
    'code.text':
      'The setup code protects this wizard until the first administrator is created. Umbrella prints it to its log at startup and stores it in the data directory.',
    'code.where': 'Where to find it',
    'code.logs': 'Container log:',
    'code.file': 'File in the data volume:',
    'code.label': 'Setup code',
    'code.verify': 'Continue',

    'prefs.title': 'Default language, theme and time zone',
    'prefs.text': 'Users see these settings until they choose their own. The wizard switches to your choice right away.',
    'prefs.locale': 'Default language',
    'prefs.theme': 'Default theme',
    'prefs.timezone': 'Default time zone',
    'prefs.timezone.hint': 'Dates and times are shown in this zone unless a user picks their own. Your browser zone is preselected.',
    'prefs.light.desc': 'Light background, dark text',
    'prefs.dark.desc': 'Dark background, light text',

    'ob.title': 'Connect OpenBao',
    'ob.text':
      'Umbrella keeps every password and key in OpenBao (KV v2). The database password and the directory service account password set in the next steps are saved there, not on disk.',

    'pg.title': 'Connect PostgreSQL',
    'pg.text': 'Umbrella stores users and settings in PostgreSQL. The password goes to OpenBao.',
    'pg.state.text': 'It may be a previous installation. Users and settings stay; the wizard updates the defaults and the administrator.',
    'pg.reuse': 'Use the existing Umbrella data',

    'ld.title': 'Sign-in with LDAP / Active Directory',
    'ld.text':
      'Optional. Directory users sign in with their corporate accounts; members of the administrators group become Umbrella administrators. You can skip this step.',
    'ld.enable': 'Connect a directory',
    'ld.enable.hint': 'When off, only local Umbrella accounts can sign in.',
    'ld.off': 'Directory sign-in will not be configured.',

    'ad.title': 'Local administrator',
    'ad.text': 'This account always works, even when the directory is unavailable. Its password hash is stored in OpenBao.',
    'ad.username': 'Login',
    'ad.email': 'E-mail',
    'ad.password': 'Password',
    'ad.confirm': 'Repeat the password',
    'ad.username.bad': 'Latin letters, digits and . _ @ -, 2–64 characters.',

    'rv.title': 'Review and finish',
    'rv.text':
      'Umbrella saves the passwords to OpenBao, creates its table in PostgreSQL, creates the administrator and switches to normal operation. The wizard then turns off.',
    'rv.edit': 'Change',
    'rv.finish': 'Finish setup',
    'rv.finishing': 'Setting up…',
    'rv.locale': 'Language',
    'rv.theme': 'Theme',
    'rv.timezone': 'Time zone',
    'rv.address': 'Address',
    'rv.auth': 'Sign-in',
    'rv.database': 'Database',
    'rv.reuse': 'Existing data',
    'rv.ldap': 'Directory',
    'rv.ldap.off': 'Not used',
    'rv.adminGroup': 'Administrators group',
    'rv.login': 'Login',
    'rv.name': 'Name',
    'rv.failed': 'Setup was not completed',
    'rv.goto': 'Open the step',

    'done.title': 'Umbrella is ready',
    'done.text': 'Setup is complete and the wizard is turned off. Sign in as {user}.',
    'done.signin': 'Go to sign in',
  },
  ru: {
    'step.policy': 'Парольная политика',
    'step.policy.sub': 'Локальные учётные записи',
    'pol.title': 'Парольная политика локальных учётных записей',
    'pol.text':
      'Umbrella проверяет по этим правилам каждый локальный пароль, в том числе пароль администратора на следующем шаге. Пароли каталога (LDAP / AD) подчиняются политике каталога.',
    'ad.last_name': 'Фамилия',
    'ad.first_name': 'Имя',
    'ad.middle_name': 'Отчество',
    'ad.if_any': 'при наличии',
    'ad.title_field': 'Должность',
    'ad.department': 'Отдел',
    'ad.manager': 'Руководитель',
    'ad.email.hint': 'По ней же подбирается картинка Gravatar, пока не загружен аватар.',
    'ad.email.bad': 'Адрес почты выглядит некорректным.',
    title: 'Первичная настройка',
    'step.code': 'Код установки',
    'step.code.sub': 'Подтверждение доступа',
    'step.prefs': 'Язык, тема, время',
    'step.prefs.sub': 'По умолчанию для всех',
    'step.openbao': 'OpenBao',
    'step.openbao.sub': 'Хранилище секретов',
    'step.postgres': 'PostgreSQL',
    'step.postgres.sub': 'База данных',
    'step.ldap': 'LDAP / AD',
    'step.ldap.sub': 'По желанию',
    'step.admin': 'Администратор',
    'step.admin.sub': 'Локальная учётная запись',
    'step.review': 'Проверка',
    'step.review.sub': 'Завершение настройки',
    back: 'Назад',
    next: 'Далее',
    check: 'Проверить подключение',
    checking: 'Проверяем…',
    optional: 'необязательно',

    'code.title': 'Введите код установки',
    'code.text': 'Код установки защищает мастер, пока не создан первый администратор. Umbrella выводит его в журнал при запуске и сохраняет в каталоге данных.',
    'code.where': 'Где взять код',
    'code.logs': 'Журнал контейнера:',
    'code.file': 'Файл в томе данных:',
    'code.label': 'Код установки',
    'code.verify': 'Продолжить',

    'prefs.title': 'Язык, тема и часовой пояс по умолчанию',
    'prefs.text': 'Пользователи видят эти настройки, пока не выберут свои. Мастер сразу переключается на ваш выбор.',
    'prefs.locale': 'Язык по умолчанию',
    'prefs.theme': 'Тема по умолчанию',
    'prefs.timezone': 'Часовой пояс по умолчанию',
    'prefs.timezone.hint': 'Даты и время показываются в этом поясе, если пользователь не выбрал свой. Заранее выбран пояс вашего браузера.',
    'prefs.light.desc': 'Светлый фон, тёмный текст',
    'prefs.dark.desc': 'Тёмный фон, светлый текст',

    'ob.title': 'Подключение к OpenBao',
    'ob.text':
      'Umbrella хранит все пароли и ключи в OpenBao (KV v2). Пароль базы данных и пароль служебной учётной записи каталога из следующих шагов сохраняются туда, а не на диск.',

    'pg.title': 'Подключение к PostgreSQL',
    'pg.text': 'Umbrella хранит пользователей и настройки в PostgreSQL. Пароль сохраняется в OpenBao.',
    'pg.state.text': 'Возможно, это предыдущая установка. Пользователи и настройки сохранятся; мастер обновит настройки по умолчанию и администратора.',
    'pg.reuse': 'Использовать существующие данные Umbrella',

    'ld.title': 'Вход через LDAP / Active Directory',
    'ld.text':
      'Необязательно. Пользователи каталога входят корпоративными учётными записями; участники группы администраторов получают права администратора Umbrella. Шаг можно пропустить.',
    'ld.enable': 'Подключить каталог',
    'ld.enable.hint': 'Если выключено, войти можно только локальными учётными записями Umbrella.',
    'ld.off': 'Вход через каталог настраиваться не будет.',

    'ad.title': 'Локальный администратор',
    'ad.text': 'Эта учётная запись работает всегда, даже когда каталог недоступен. Хеш её пароля хранится в OpenBao.',
    'ad.username': 'Логин',
    'ad.email': 'Почта',
    'ad.password': 'Пароль',
    'ad.confirm': 'Повторите пароль',
    'ad.username.bad': 'Латиница, цифры и . _ @ -, от 2 до 64 символов.',

    'rv.title': 'Проверка и завершение',
    'rv.text':
      'Umbrella сохранит пароли в OpenBao, создаст свою таблицу в PostgreSQL, создаст администратора и перейдёт в рабочий режим. После этого мастер отключится.',
    'rv.edit': 'Изменить',
    'rv.finish': 'Завершить настройку',
    'rv.finishing': 'Настраиваем…',
    'rv.locale': 'Язык',
    'rv.theme': 'Тема',
    'rv.timezone': 'Часовой пояс',
    'rv.address': 'Адрес',
    'rv.auth': 'Вход',
    'rv.database': 'База данных',
    'rv.reuse': 'Существующие данные',
    'rv.ldap': 'Каталог',
    'rv.ldap.off': 'Не используется',
    'rv.adminGroup': 'Группа администраторов',
    'rv.login': 'Логин',
    'rv.name': 'Имя',
    'rv.failed': 'Настройка не завершена',
    'rv.goto': 'Открыть шаг',

    'done.title': 'Umbrella готова к работе',
    'done.text': 'Настройка завершена, мастер отключён. Войдите как {user}.',
    'done.signin': 'Перейти ко входу',
  },
}
