import type { Dict } from '../i18n'

export const strings: Dict = {
  en: {
    'ld.hint.tls': 'The directory accepts passwords only over an encrypted connection: use ldaps://…:636 or turn on StartTLS.',
    'ld.hint.cert':
      'Paste the CA certificate that issued the directory certificate, or (test environments only) turn off certificate verification. The address must match a name in the certificate.',
    'ld.hint.loopback':
      'Umbrella runs in a container, so localhost is the Umbrella container itself. Use the directory host name, for example ldaps://dc1.corp.umbrella.lab:636 in the shared Docker network.',
    'step.policy': 'Password policy',
    'step.policy.sub': 'Local accounts',
    'pol.title': 'Password policy for local accounts',
    'pol.text':
      'Umbrella checks every local password against these rules, including the administrator you create next. Directory (LDAP / AD) passwords follow the directory policy.',
    'pol.length': 'Minimum length',
    'pol.digits': 'Require digits',
    'pol.digits.hint': '0–9 and other decimal digits.',
    'pol.special': 'Require special characters',
    'pol.special.hint': 'Punctuation and symbols such as ! @ # $ % - _ .',
    'pol.count': 'At least',
    'pol.case': 'Require upper and lower case',
    'pol.case.hint': 'At least one capital and one small letter.',
    'pol.letters': 'Allowed letters',
    'pol.letters.hint': 'Letters of other alphabets are rejected.',
    'pol.letters.latin': 'Latin',
    'pol.letters.latin.ex': 'A–Z, a–z',
    'pol.letters.cyrillic': 'Cyrillic',
    'pol.letters.cyrillic.ex': 'А–Я, а–я, Ё',
    'pol.letters.latin_cyrillic': 'Latin and Cyrillic',
    'pol.letters.latin_cyrillic.ex': 'Both alphabets',
    'pol.letters.any': 'Any alphabet',
    'pol.letters.any.ex': 'No restriction',
    'pol.summary': 'A password must meet these rules:',
    'pol.err.length': 'Minimum length must be from 8 to 128.',
    'pol.err.digits': 'The number of digits must be from 1 to 16.',
    'pol.err.special': 'The number of special characters must be from 1 to 16.',
    'pol.err.fit': 'Required digits, special characters and letters do not fit into the minimum length.',
    'pol.row.length': 'Length',
    'pol.row.digits': 'Digits',
    'pol.row.special': 'Special characters',
    'pol.row.mixed_case': 'Case',
    'pol.row.letters': 'Letters',
    'ad.last_name': 'Last name',
    'ad.first_name': 'First name',
    'ad.middle_name': 'Middle name',
    'ad.if_any': 'if any',
    'ad.title_field': 'Job title',
    'ad.department': 'Department',
    'ad.manager': 'Manager',
    'ad.email.hint': 'Also used to pick a Gravatar picture until an avatar is uploaded.',
    'ad.email.bad': 'The e-mail address looks invalid.',
    'ld.attrs.hint': 'LDAP attributes Umbrella reads at every sign-in. Leave a field empty to skip it.',
    'ld.attr.username_attr': 'Login',
    'ld.attr.name_attr': 'Display name',
    'ld.attr.last_name_attr': 'Last name',
    'ld.attr.first_name_attr': 'First name',
    'ld.attr.middle_name_attr': 'Middle name',
    'ld.attr.title_attr': 'Job title',
    'ld.attr.department_attr': 'Department',
    'ld.attr.manager_attr': 'Manager (DN)',
    'ld.attr.email_attr': 'E-mail',
    'ld.attr.photo_attr': 'Photo',
    'ld.photo': 'Photo',
    title: 'Initial setup',
    'step.code': 'Setup code',
    'step.code.sub': 'Confirm access',
    'step.prefs': 'Language, theme, time',
    'step.prefs.sub': 'Defaults for everyone',
    'step.openbao': 'OpenBao',
    'step.openbao.sub': 'Secret storage',
    'step.postgres': 'PostgreSQL',
    'step.postgres.sub': 'Database',
    'step.ldap': 'LDAP / AD',
    'step.ldap.sub': 'Optional',
    'step.admin': 'Administrator',
    'step.admin.sub': 'Local account',
    'step.review': 'Review',
    'step.review.sub': 'Finish setup',
    back: 'Back',
    next: 'Next',
    check: 'Check connection',
    checking: 'Checking…',
    optional: 'optional',
    changed: 'Settings changed after the check. Check the connection again.',

    'code.title': 'Enter the setup code',
    'code.text':
      'The setup code protects this wizard until the first administrator is created. Umbrella prints it to its log at startup and stores it in the data directory.',
    'code.where': 'Where to find it',
    'code.logs': 'Container log:',
    'code.file': 'File in the data volume:',
    'code.label': 'Setup code',
    'code.verify': 'Continue',

    'prefs.title': 'Default language, theme and time zone',
    'prefs.text': 'Users see these settings until they choose their own. The wizard switches to your choice right away.',
    'prefs.locale': 'Default language',
    'prefs.theme': 'Default theme',
    'prefs.timezone': 'Default time zone',
    'prefs.timezone.hint': 'Dates and times are shown in this zone unless a user picks their own. Your browser zone is preselected.',
    'prefs.light.desc': 'Light background, dark text',
    'prefs.dark.desc': 'Dark background, light text',

    'ob.title': 'Connect OpenBao',
    'ob.text':
      'Umbrella keeps every password and key in OpenBao (KV v2). The database password and the directory service account password set in the next steps are saved there, not on disk.',
    'ob.addr': 'Address',
    'ob.addr.hint': 'For example https://openbao.example.com:8200',
    'ob.mount': 'KV v2 mount',
    'ob.mount.hint': 'The secrets engine must be enabled as KV version 2.',
    'ob.namespace': 'Namespace',
    'ob.auth': 'Sign-in method',
    'ob.auth.approle': 'AppRole (recommended)',
    'ob.auth.token': 'Token',
    'ob.token': 'Token',
    'ob.roleId': 'Role ID',
    'ob.secretId': 'Secret ID',
    'ob.approlePath': 'AppRole auth path',
    'ob.tls': 'TLS',
    'ob.ca': 'CA certificate (PEM)',
    'ob.ca.hint': 'Needed when OpenBao uses a certificate from an internal CA.',
    'ob.skip': 'Do not verify the certificate',
    'ob.skip.hint': 'Only for test environments: the connection can be intercepted.',
    'ob.ok': 'OpenBao is ready',
    'ob.ok.text': 'Version {version}. Signed in, the {mount} store is readable and writable; the test secret was deleted.',
    'ob.fail': 'OpenBao check failed',
    'ob.loopback':
      'Umbrella runs in a container, so localhost is the Umbrella container itself. Use the OpenBao service name in the shared Docker network, for example http://openbao:8200, or http://host.docker.internal:8200 when OpenBao runs on the host.',
    'ob.policies': 'Policies',
    'ob.expires': 'Token expires',
    'ob.policy.hint': 'The Umbrella policy needs create, read, update and delete on {mount}/data/* and delete on {mount}/metadata/*.',

    'pg.title': 'Connect PostgreSQL',
    'pg.text': 'Umbrella stores users and settings in PostgreSQL. The password goes to OpenBao.',
    'pg.host': 'Host',
    'pg.port': 'Port',
    'pg.database': 'Database',
    'pg.user': 'User',
    'pg.password': 'Password',
    'pg.sslmode': 'SSL mode',
    'pg.ok': 'PostgreSQL is reachable',
    'pg.ok.text': 'PostgreSQL {version}, database {database}, user {user}.',
    'pg.fail': 'PostgreSQL check failed',
    'pg.loopback':
      'Umbrella runs in a container, so localhost is the Umbrella container itself. Use the PostgreSQL service name in the shared Docker network, for example postgres, or host.docker.internal when PostgreSQL runs on the host.',
    'pg.nocreate': 'The user cannot create tables in this database. Grant CREATE on the schema or pick another user.',
    'pg.state': 'This database already holds Umbrella data (saved {at})',
    'pg.state.text': 'It may be a previous installation. Users and settings stay; the wizard updates the defaults and the administrator.',
    'pg.reuse': 'Use the existing Umbrella data',

    'ld.title': 'Sign-in with LDAP / Active Directory',
    'ld.text':
      'Optional. Directory users sign in with their corporate accounts; members of the administrators group become Umbrella administrators. You can skip this step.',
    'ld.enable': 'Connect a directory',
    'ld.enable.hint': 'When off, only local Umbrella accounts can sign in.',
    'ld.kind': 'Directory type',
    'ld.kind.ad': 'Active Directory',
    'ld.kind.openldap': 'OpenLDAP and compatible',
    'ld.url': 'Server address',
    'ld.url.hint': 'ldaps://dc1.corp.example:636 or ldap://dc1.corp.example:389',
    'ld.starttls': 'Use StartTLS',
    'ld.starttls.hint': 'Upgrades an ldap:// connection to TLS.',
    'ld.bindDn': 'Service account',
    'ld.bindDn.hint.ad': 'DN or user@domain, for example svc-umbrella@corp.example',
    'ld.bindDn.hint.openldap': 'DN, for example cn=umbrella,ou=services,dc=example,dc=org',
    'ld.bindPassword': 'Service account password',
    'ld.baseDn': 'Search base (DN)',
    'ld.baseDn.hint': 'For example DC=corp,DC=example',
    'ld.filter': 'User filter',
    'ld.filter.hint': '{username} is replaced with the escaped login.',
    'ld.attrs': 'Attributes',
    'ld.adminGroup': 'Administrators group (DN)',
    'ld.adminGroup.hint': 'Members get administrator rights. Nested groups count in Active Directory.',
    'ld.testUser': 'Test user',
    'ld.testUser.hint': 'Optional: check that a user is found and, with a password, can sign in.',
    'ld.testUsername': 'Login',
    'ld.testPassword': 'Password',
    'ld.ok': 'Directory is reachable',
    'ld.ok.text': 'Service account signed in, search base found.',
    'ld.ok.group': 'Administrators group found.',
    'ld.user': 'User {name} found ({dn}).',
    'ld.user.auth': 'Password accepted.',
    'ld.user.admin': 'Member of the administrators group.',
    'ld.user.notAdmin': 'Not a member of the administrators group.',
    'ld.fail': 'Directory check failed',
    'ld.off': 'Directory sign-in will not be configured.',

    'ad.title': 'Local administrator',
    'ad.text': 'This account always works, even when the directory is unavailable. Its password hash is stored in OpenBao.',
    'ad.username': 'Login',
    'ad.email': 'E-mail',
    'ad.password': 'Password',
    'ad.confirm': 'Repeat the password',
    'ad.username.bad': 'Latin letters, digits and . _ @ -, 2–64 characters.',

    'rv.title': 'Review and finish',
    'rv.text':
      'Umbrella saves the passwords to OpenBao, creates its table in PostgreSQL, creates the administrator and switches to normal operation. The wizard then turns off.',
    'rv.edit': 'Change',
    'rv.finish': 'Finish setup',
    'rv.finishing': 'Setting up…',
    'rv.locale': 'Language',
    'rv.theme': 'Theme',
    'rv.timezone': 'Time zone',
    'rv.address': 'Address',
    'rv.auth': 'Sign-in',
    'rv.database': 'Database',
    'rv.reuse': 'Existing data',
    'rv.ldap': 'Directory',
    'rv.ldap.off': 'Not used',
    'rv.adminGroup': 'Administrators group',
    'rv.login': 'Login',
    'rv.name': 'Name',
    'rv.failed': 'Setup was not completed',
    'rv.goto': 'Open the step',

    'done.title': 'Umbrella is ready',
    'done.text': 'Setup is complete and the wizard is turned off. Sign in as {user}.',
    'done.signin': 'Go to sign in',
  },
  ru: {
    'ld.hint.tls': 'Каталог принимает пароли только по зашифрованному соединению: укажите ldaps://…:636 или включите StartTLS.',
    'ld.hint.cert':
      'Вставьте сертификат CA, выпустивший сертификат каталога, или (только в тестовой среде) отключите проверку сертификата. Адрес должен совпадать с именем в сертификате.',
    'ld.hint.loopback':
      'Umbrella работает в контейнере, и localhost — это сам контейнер Umbrella. Укажите имя хоста каталога, например ldaps://dc1.corp.umbrella.lab:636 в общей сети Docker.',
    'step.policy': 'Парольная политика',
    'step.policy.sub': 'Локальные учётные записи',
    'pol.title': 'Парольная политика локальных учётных записей',
    'pol.text':
      'Umbrella проверяет по этим правилам каждый локальный пароль, в том числе пароль администратора на следующем шаге. Пароли каталога (LDAP / AD) подчиняются политике каталога.',
    'pol.length': 'Минимальная длина',
    'pol.digits': 'Требовать цифры',
    'pol.digits.hint': '0–9 и другие десятичные цифры.',
    'pol.special': 'Требовать спецсимволы',
    'pol.special.hint': 'Знаки препинания и символы: ! @ # $ % - _ .',
    'pol.count': 'Не меньше',
    'pol.case': 'Требовать разный регистр',
    'pol.case.hint': 'Хотя бы одна заглавная и одна строчная буква.',
    'pol.letters': 'Допустимые буквы',
    'pol.letters.hint': 'Буквы других алфавитов отклоняются.',
    'pol.letters.latin': 'Латиница',
    'pol.letters.latin.ex': 'A–Z, a–z',
    'pol.letters.cyrillic': 'Кириллица',
    'pol.letters.cyrillic.ex': 'А–Я, а–я, Ё',
    'pol.letters.latin_cyrillic': 'Латиница и кириллица',
    'pol.letters.latin_cyrillic.ex': 'Оба алфавита',
    'pol.letters.any': 'Любой алфавит',
    'pol.letters.any.ex': 'Без ограничений',
    'pol.summary': 'Пароль должен соответствовать правилам:',
    'pol.err.length': 'Минимальная длина — от 8 до 128.',
    'pol.err.digits': 'Количество цифр — от 1 до 16.',
    'pol.err.special': 'Количество спецсимволов — от 1 до 16.',
    'pol.err.fit': 'Обязательные цифры, спецсимволы и буквы не помещаются в минимальную длину.',
    'pol.row.length': 'Длина',
    'pol.row.digits': 'Цифры',
    'pol.row.special': 'Спецсимволы',
    'pol.row.mixed_case': 'Регистр',
    'pol.row.letters': 'Буквы',
    'ad.last_name': 'Фамилия',
    'ad.first_name': 'Имя',
    'ad.middle_name': 'Отчество',
    'ad.if_any': 'при наличии',
    'ad.title_field': 'Должность',
    'ad.department': 'Отдел',
    'ad.manager': 'Руководитель',
    'ad.email.hint': 'По ней же подбирается картинка Gravatar, пока не загружен аватар.',
    'ad.email.bad': 'Адрес почты выглядит некорректным.',
    'ld.attrs.hint': 'Атрибуты LDAP, которые Umbrella читает при каждом входе. Оставьте поле пустым, чтобы не использовать атрибут.',
    'ld.attr.username_attr': 'Логин',
    'ld.attr.name_attr': 'Отображаемое имя',
    'ld.attr.last_name_attr': 'Фамилия',
    'ld.attr.first_name_attr': 'Имя',
    'ld.attr.middle_name_attr': 'Отчество',
    'ld.attr.title_attr': 'Должность',
    'ld.attr.department_attr': 'Отдел',
    'ld.attr.manager_attr': 'Руководитель (DN)',
    'ld.attr.email_attr': 'Почта',
    'ld.attr.photo_attr': 'Фото',
    'ld.photo': 'Фото',
    title: 'Первичная настройка',
    'step.code': 'Код установки',
    'step.code.sub': 'Подтверждение доступа',
    'step.prefs': 'Язык, тема, время',
    'step.prefs.sub': 'По умолчанию для всех',
    'step.openbao': 'OpenBao',
    'step.openbao.sub': 'Хранилище секретов',
    'step.postgres': 'PostgreSQL',
    'step.postgres.sub': 'База данных',
    'step.ldap': 'LDAP / AD',
    'step.ldap.sub': 'По желанию',
    'step.admin': 'Администратор',
    'step.admin.sub': 'Локальная учётная запись',
    'step.review': 'Проверка',
    'step.review.sub': 'Завершение настройки',
    back: 'Назад',
    next: 'Далее',
    check: 'Проверить подключение',
    checking: 'Проверяем…',
    optional: 'необязательно',
    changed: 'Настройки изменились после проверки. Проверьте подключение ещё раз.',

    'code.title': 'Введите код установки',
    'code.text': 'Код установки защищает мастер, пока не создан первый администратор. Umbrella выводит его в журнал при запуске и сохраняет в каталоге данных.',
    'code.where': 'Где взять код',
    'code.logs': 'Журнал контейнера:',
    'code.file': 'Файл в томе данных:',
    'code.label': 'Код установки',
    'code.verify': 'Продолжить',

    'prefs.title': 'Язык, тема и часовой пояс по умолчанию',
    'prefs.text': 'Пользователи видят эти настройки, пока не выберут свои. Мастер сразу переключается на ваш выбор.',
    'prefs.locale': 'Язык по умолчанию',
    'prefs.theme': 'Тема по умолчанию',
    'prefs.timezone': 'Часовой пояс по умолчанию',
    'prefs.timezone.hint': 'Даты и время показываются в этом поясе, если пользователь не выбрал свой. Заранее выбран пояс вашего браузера.',
    'prefs.light.desc': 'Светлый фон, тёмный текст',
    'prefs.dark.desc': 'Тёмный фон, светлый текст',

    'ob.title': 'Подключение к OpenBao',
    'ob.text':
      'Umbrella хранит все пароли и ключи в OpenBao (KV v2). Пароль базы данных и пароль служебной учётной записи каталога из следующих шагов сохраняются туда, а не на диск.',
    'ob.addr': 'Адрес',
    'ob.addr.hint': 'Например, https://openbao.example.com:8200',
    'ob.mount': 'Хранилище KV v2',
    'ob.mount.hint': 'Движок секретов должен быть включён как KV версии 2.',
    'ob.namespace': 'Пространство имён',
    'ob.auth': 'Способ входа',
    'ob.auth.approle': 'AppRole (рекомендуется)',
    'ob.auth.token': 'Токен',
    'ob.token': 'Токен',
    'ob.roleId': 'Role ID',
    'ob.secretId': 'Secret ID',
    'ob.approlePath': 'Путь метода AppRole',
    'ob.tls': 'TLS',
    'ob.ca': 'Сертификат CA (PEM)',
    'ob.ca.hint': 'Нужен, если сертификат OpenBao выпущен внутренним удостоверяющим центром.',
    'ob.skip': 'Не проверять сертификат',
    'ob.skip.hint': 'Только для тестовых сред: соединение можно перехватить.',
    'ob.ok': 'OpenBao готов',
    'ob.ok.text': 'Версия {version}. Вход выполнен, хранилище {mount} доступно на чтение и запись; тестовый секрет удалён.',
    'ob.fail': 'Проверка OpenBao не прошла',
    'ob.loopback':
      'Umbrella работает в контейнере, и localhost — это сам контейнер Umbrella. Укажите имя сервиса OpenBao в общей сети Docker, например http://openbao:8200, или http://host.docker.internal:8200, если OpenBao запущен на хосте.',
    'ob.policies': 'Политики',
    'ob.expires': 'Токен действует до',
    'ob.policy.hint': 'Политике Umbrella нужны create, read, update и delete на {mount}/data/* и delete на {mount}/metadata/*.',

    'pg.title': 'Подключение к PostgreSQL',
    'pg.text': 'Umbrella хранит пользователей и настройки в PostgreSQL. Пароль сохраняется в OpenBao.',
    'pg.host': 'Хост',
    'pg.port': 'Порт',
    'pg.database': 'База данных',
    'pg.user': 'Пользователь',
    'pg.password': 'Пароль',
    'pg.sslmode': 'Режим SSL',
    'pg.ok': 'PostgreSQL доступен',
    'pg.ok.text': 'PostgreSQL {version}, база {database}, пользователь {user}.',
    'pg.fail': 'Проверка PostgreSQL не прошла',
    'pg.loopback':
      'Umbrella работает в контейнере, и localhost — это сам контейнер Umbrella. Укажите имя сервиса PostgreSQL в общей сети Docker, например postgres, или host.docker.internal, если PostgreSQL запущен на хосте.',
    'pg.nocreate': 'У пользователя нет права создавать таблицы в этой базе. Выдайте CREATE на схему или выберите другого пользователя.',
    'pg.state': 'В базе уже есть данные Umbrella (сохранены {at})',
    'pg.state.text': 'Возможно, это предыдущая установка. Пользователи и настройки сохранятся; мастер обновит настройки по умолчанию и администратора.',
    'pg.reuse': 'Использовать существующие данные Umbrella',

    'ld.title': 'Вход через LDAP / Active Directory',
    'ld.text':
      'Необязательно. Пользователи каталога входят корпоративными учётными записями; участники группы администраторов получают права администратора Umbrella. Шаг можно пропустить.',
    'ld.enable': 'Подключить каталог',
    'ld.enable.hint': 'Если выключено, войти можно только локальными учётными записями Umbrella.',
    'ld.kind': 'Тип каталога',
    'ld.kind.ad': 'Active Directory',
    'ld.kind.openldap': 'OpenLDAP и совместимые',
    'ld.url': 'Адрес сервера',
    'ld.url.hint': 'ldaps://dc1.corp.example:636 или ldap://dc1.corp.example:389',
    'ld.starttls': 'Использовать StartTLS',
    'ld.starttls.hint': 'Переводит соединение ldap:// на TLS.',
    'ld.bindDn': 'Служебная учётная запись',
    'ld.bindDn.hint.ad': 'DN или user@domain, например svc-umbrella@corp.example',
    'ld.bindDn.hint.openldap': 'DN, например cn=umbrella,ou=services,dc=example,dc=org',
    'ld.bindPassword': 'Пароль служебной учётной записи',
    'ld.baseDn': 'База поиска (DN)',
    'ld.baseDn.hint': 'Например, DC=corp,DC=example',
    'ld.filter': 'Фильтр пользователей',
    'ld.filter.hint': 'Вместо {username} подставляется экранированный логин.',
    'ld.attrs': 'Атрибуты',
    'ld.adminGroup': 'Группа администраторов (DN)',
    'ld.adminGroup.hint': 'Участники получают права администратора. В Active Directory учитываются вложенные группы.',
    'ld.testUser': 'Проверочный пользователь',
    'ld.testUser.hint': 'Необязательно: проверить, что пользователь находится и, если указан пароль, может войти.',
    'ld.testUsername': 'Логин',
    'ld.testPassword': 'Пароль',
    'ld.ok': 'Каталог доступен',
    'ld.ok.text': 'Служебная учётная запись вошла, база поиска найдена.',
    'ld.ok.group': 'Группа администраторов найдена.',
    'ld.user': 'Пользователь {name} найден ({dn}).',
    'ld.user.auth': 'Пароль принят.',
    'ld.user.admin': 'Входит в группу администраторов.',
    'ld.user.notAdmin': 'Не входит в группу администраторов.',
    'ld.fail': 'Проверка каталога не прошла',
    'ld.off': 'Вход через каталог настраиваться не будет.',

    'ad.title': 'Локальный администратор',
    'ad.text': 'Эта учётная запись работает всегда, даже когда каталог недоступен. Хеш её пароля хранится в OpenBao.',
    'ad.username': 'Логин',
    'ad.email': 'Почта',
    'ad.password': 'Пароль',
    'ad.confirm': 'Повторите пароль',
    'ad.username.bad': 'Латиница, цифры и . _ @ -, от 2 до 64 символов.',

    'rv.title': 'Проверка и завершение',
    'rv.text':
      'Umbrella сохранит пароли в OpenBao, создаст свою таблицу в PostgreSQL, создаст администратора и перейдёт в рабочий режим. После этого мастер отключится.',
    'rv.edit': 'Изменить',
    'rv.finish': 'Завершить настройку',
    'rv.finishing': 'Настраиваем…',
    'rv.locale': 'Язык',
    'rv.theme': 'Тема',
    'rv.timezone': 'Часовой пояс',
    'rv.address': 'Адрес',
    'rv.auth': 'Вход',
    'rv.database': 'База данных',
    'rv.reuse': 'Существующие данные',
    'rv.ldap': 'Каталог',
    'rv.ldap.off': 'Не используется',
    'rv.adminGroup': 'Группа администраторов',
    'rv.login': 'Логин',
    'rv.name': 'Имя',
    'rv.failed': 'Настройка не завершена',
    'rv.goto': 'Открыть шаг',

    'done.title': 'Umbrella готова к работе',
    'done.text': 'Настройка завершена, мастер отключён. Войдите как {user}.',
    'done.signin': 'Перейти ко входу',
  },
}
