import type { Dict } from '../i18n'

export const strings: Dict = {
  en: {
    'title': 'Initial setup',
    'step.code': 'Setup code',
    'step.code.sub': 'Confirm access',
    'step.prefs': 'Language and theme',
    'step.prefs.sub': 'Defaults for everyone',
    'step.openbao': 'OpenBao',
    'step.openbao.sub': 'Secret storage',
    'step.postgres': 'PostgreSQL',
    'step.postgres.sub': 'Database',
    'step.ldap': 'LDAP / AD',
    'step.ldap.sub': 'Optional',
    'step.admin': 'Administrator',
    'step.admin.sub': 'Local account',
    'step.review': 'Review',
    'step.review.sub': 'Finish setup',
    'back': 'Back',
    'next': 'Next',
    'check': 'Check connection',
    'checking': 'Checking…',
    'optional': 'optional',
    'changed': 'Settings changed after the check. Check the connection again.',

    'code.title': 'Enter the setup code',
    'code.text': 'The setup code protects this wizard until the first administrator is created. Umbrella prints it to its log at startup and stores it in the data directory.',
    'code.where': 'Where to find it',
    'code.logs': 'Container log:',
    'code.file': 'File in the data volume:',
    'code.label': 'Setup code',
    'code.verify': 'Continue',

    'prefs.title': 'Default language and theme',
    'prefs.text': 'Users see these settings until they choose their own. The wizard switches to your choice right away.',
    'prefs.locale': 'Default language',
    'prefs.theme': 'Default theme',
    'prefs.light.desc': 'Light background, dark text',
    'prefs.dark.desc': 'Dark background, light text',

    'ob.title': 'Connect OpenBao',
    'ob.text': 'Umbrella keeps every password and key in OpenBao (KV v2). The database password and the directory service account password set in the next steps are saved there, not on disk.',
    'ob.addr': 'Address',
    'ob.addr.hint': 'For example https://openbao.example.com:8200',
    'ob.mount': 'KV v2 mount',
    'ob.mount.hint': 'The secrets engine must be enabled as KV version 2.',
    'ob.namespace': 'Namespace',
    'ob.auth': 'Sign-in method',
    'ob.auth.approle': 'AppRole (recommended)',
    'ob.auth.token': 'Token',
    'ob.token': 'Token',
    'ob.roleId': 'Role ID',
    'ob.secretId': 'Secret ID',
    'ob.approlePath': 'AppRole auth path',
    'ob.tls': 'TLS',
    'ob.ca': 'CA certificate (PEM)',
    'ob.ca.hint': 'Needed when OpenBao uses a certificate from an internal CA.',
    'ob.skip': 'Do not verify the certificate',
    'ob.skip.hint': 'Only for test environments: the connection can be intercepted.',
    'ob.ok': 'OpenBao is ready',
    'ob.ok.text': 'Version {version}. Signed in, the {mount} store is readable and writable; the test secret was deleted.',
    'ob.fail': 'OpenBao check failed',
    'ob.policies': 'Policies',
    'ob.expires': 'Token expires',
    'ob.policy.hint': 'The Umbrella policy needs create, read, update and delete on {mount}/data/* and delete on {mount}/metadata/*.',

    'pg.title': 'Connect PostgreSQL',
    'pg.text': 'Umbrella stores users and settings in PostgreSQL. The password goes to OpenBao.',
    'pg.host': 'Host',
    'pg.port': 'Port',
    'pg.database': 'Database',
    'pg.user': 'User',
    'pg.password': 'Password',
    'pg.sslmode': 'SSL mode',
    'pg.ok': 'PostgreSQL is reachable',
    'pg.ok.text': 'PostgreSQL {version}, database {database}, user {user}.',
    'pg.fail': 'PostgreSQL check failed',
    'pg.nocreate': 'The user cannot create tables in this database. Grant CREATE on the schema or pick another user.',
    'pg.state': 'This database already holds Umbrella data (saved {at})',
    'pg.state.text': 'It may be a previous installation. Users and settings stay; the wizard updates the defaults and the administrator.',
    'pg.reuse': 'Use the existing Umbrella data',

    'ld.title': 'Sign-in with LDAP / Active Directory',
    'ld.text': 'Optional. Directory users sign in with their corporate accounts; members of the administrators group become Umbrella administrators. You can skip this step.',
    'ld.enable': 'Connect a directory',
    'ld.enable.hint': 'When off, only local Umbrella accounts can sign in.',
    'ld.kind': 'Directory type',
    'ld.kind.ad': 'Active Directory',
    'ld.kind.openldap': 'OpenLDAP and compatible',
    'ld.url': 'Server address',
    'ld.url.hint': 'ldaps://dc1.corp.example:636 or ldap://dc1.corp.example:389',
    'ld.starttls': 'Use StartTLS',
    'ld.starttls.hint': 'Upgrades an ldap:// connection to TLS.',
    'ld.bindDn': 'Service account',
    'ld.bindDn.hint.ad': 'DN or user@domain, for example svc-umbrella@corp.example',
    'ld.bindDn.hint.openldap': 'DN, for example cn=umbrella,ou=services,dc=example,dc=org',
    'ld.bindPassword': 'Service account password',
    'ld.baseDn': 'Search base (DN)',
    'ld.baseDn.hint': 'For example DC=corp,DC=example',
    'ld.filter': 'User filter',
    'ld.filter.hint': '{username} is replaced with the escaped login.',
    'ld.attrs': 'Attributes',
    'ld.attr.username': 'Login',
    'ld.attr.name': 'Display name',
    'ld.attr.email': 'E-mail',
    'ld.adminGroup': 'Administrators group (DN)',
    'ld.adminGroup.hint': 'Members get administrator rights. Nested groups count in Active Directory.',
    'ld.testUser': 'Test user',
    'ld.testUser.hint': 'Optional: check that a user is found and, with a password, can sign in.',
    'ld.testUsername': 'Login',
    'ld.testPassword': 'Password',
    'ld.ok': 'Directory is reachable',
    'ld.ok.text': 'Service account signed in, search base found.',
    'ld.ok.group': 'Administrators group found.',
    'ld.user': 'User {name} found ({dn}).',
    'ld.user.auth': 'Password accepted.',
    'ld.user.admin': 'Member of the administrators group.',
    'ld.user.notAdmin': 'Not a member of the administrators group.',
    'ld.fail': 'Directory check failed',
    'ld.off': 'Directory sign-in will not be configured.',

    'ad.title': 'Local administrator',
    'ad.text': 'This account always works, even when the directory is unavailable. Keep its password in a safe place.',
    'ad.username': 'Login',
    'ad.name': 'Display name',
    'ad.email': 'E-mail',
    'ad.password': 'Password',
    'ad.confirm': 'Repeat the password',
    'ad.rule.length': 'At least 10 characters',
    'ad.rule.mix': 'Letters and digits',
    'ad.rule.user': 'Differs from the login',
    'ad.rule.match': 'Passwords match',
    'ad.username.bad': 'Latin letters, digits and . _ @ -, 2–64 characters.',

    'rv.title': 'Review and finish',
    'rv.text': 'Umbrella saves the passwords to OpenBao, creates its table in PostgreSQL, creates the administrator and switches to normal operation. The wizard then turns off.',
    'rv.edit': 'Change',
    'rv.finish': 'Finish setup',
    'rv.finishing': 'Setting up…',
    'rv.locale': 'Language',
    'rv.theme': 'Theme',
    'rv.address': 'Address',
    'rv.auth': 'Sign-in',
    'rv.database': 'Database',
    'rv.reuse': 'Existing data',
    'rv.ldap': 'Directory',
    'rv.ldap.off': 'Not used',
    'rv.adminGroup': 'Administrators group',
    'rv.login': 'Login',
    'rv.name': 'Name',
    'rv.failed': 'Setup was not completed',
    'rv.goto': 'Open the step',

    'done.title': 'Umbrella is ready',
    'done.text': 'Setup is complete and the wizard is turned off. Sign in as {user}.',
    'done.signin': 'Go to sign in',
  },
  ru: {
    'title': 'Первичная настройка',
    'step.code': 'Код установки',
    'step.code.sub': 'Подтверждение доступа',
    'step.prefs': 'Язык и тема',
    'step.prefs.sub': 'По умолчанию для всех',
    'step.openbao': 'OpenBao',
    'step.openbao.sub': 'Хранилище секретов',
    'step.postgres': 'PostgreSQL',
    'step.postgres.sub': 'База данных',
    'step.ldap': 'LDAP / AD',
    'step.ldap.sub': 'По желанию',
    'step.admin': 'Администратор',
    'step.admin.sub': 'Локальная учётная запись',
    'step.review': 'Проверка',
    'step.review.sub': 'Завершение настройки',
    'back': 'Назад',
    'next': 'Далее',
    'check': 'Проверить подключение',
    'checking': 'Проверяем…',
    'optional': 'необязательно',
    'changed': 'Настройки изменились после проверки. Проверьте подключение ещё раз.',

    'code.title': 'Введите код установки',
    'code.text': 'Код установки защищает мастер, пока не создан первый администратор. Umbrella выводит его в журнал при запуске и сохраняет в каталоге данных.',
    'code.where': 'Где взять код',
    'code.logs': 'Журнал контейнера:',
    'code.file': 'Файл в томе данных:',
    'code.label': 'Код установки',
    'code.verify': 'Продолжить',

    'prefs.title': 'Язык и тема по умолчанию',
    'prefs.text': 'Пользователи видят эти настройки, пока не выберут свои. Мастер сразу переключается на ваш выбор.',
    'prefs.locale': 'Язык по умолчанию',
    'prefs.theme': 'Тема по умолчанию',
    'prefs.light.desc': 'Светлый фон, тёмный текст',
    'prefs.dark.desc': 'Тёмный фон, светлый текст',

    'ob.title': 'Подключение к OpenBao',
    'ob.text': 'Umbrella хранит все пароли и ключи в OpenBao (KV v2). Пароль базы данных и пароль служебной учётной записи каталога из следующих шагов сохраняются туда, а не на диск.',
    'ob.addr': 'Адрес',
    'ob.addr.hint': 'Например, https://openbao.example.com:8200',
    'ob.mount': 'Хранилище KV v2',
    'ob.mount.hint': 'Движок секретов должен быть включён как KV версии 2.',
    'ob.namespace': 'Пространство имён',
    'ob.auth': 'Способ входа',
    'ob.auth.approle': 'AppRole (рекомендуется)',
    'ob.auth.token': 'Токен',
    'ob.token': 'Токен',
    'ob.roleId': 'Role ID',
    'ob.secretId': 'Secret ID',
    'ob.approlePath': 'Путь метода AppRole',
    'ob.tls': 'TLS',
    'ob.ca': 'Сертификат CA (PEM)',
    'ob.ca.hint': 'Нужен, если сертификат OpenBao выпущен внутренним удостоверяющим центром.',
    'ob.skip': 'Не проверять сертификат',
    'ob.skip.hint': 'Только для тестовых сред: соединение можно перехватить.',
    'ob.ok': 'OpenBao готов',
    'ob.ok.text': 'Версия {version}. Вход выполнен, хранилище {mount} доступно на чтение и запись; тестовый секрет удалён.',
    'ob.fail': 'Проверка OpenBao не прошла',
    'ob.policies': 'Политики',
    'ob.expires': 'Токен действует до',
    'ob.policy.hint': 'Политике Umbrella нужны create, read, update и delete на {mount}/data/* и delete на {mount}/metadata/*.',

    'pg.title': 'Подключение к PostgreSQL',
    'pg.text': 'Umbrella хранит пользователей и настройки в PostgreSQL. Пароль сохраняется в OpenBao.',
    'pg.host': 'Хост',
    'pg.port': 'Порт',
    'pg.database': 'База данных',
    'pg.user': 'Пользователь',
    'pg.password': 'Пароль',
    'pg.sslmode': 'Режим SSL',
    'pg.ok': 'PostgreSQL доступен',
    'pg.ok.text': 'PostgreSQL {version}, база {database}, пользователь {user}.',
    'pg.fail': 'Проверка PostgreSQL не прошла',
    'pg.nocreate': 'У пользователя нет права создавать таблицы в этой базе. Выдайте CREATE на схему или выберите другого пользователя.',
    'pg.state': 'В базе уже есть данные Umbrella (сохранены {at})',
    'pg.state.text': 'Возможно, это предыдущая установка. Пользователи и настройки сохранятся; мастер обновит настройки по умолчанию и администратора.',
    'pg.reuse': 'Использовать существующие данные Umbrella',

    'ld.title': 'Вход через LDAP / Active Directory',
    'ld.text': 'Необязательно. Пользователи каталога входят корпоративными учётными записями; участники группы администраторов получают права администратора Umbrella. Шаг можно пропустить.',
    'ld.enable': 'Подключить каталог',
    'ld.enable.hint': 'Если выключено, войти можно только локальными учётными записями Umbrella.',
    'ld.kind': 'Тип каталога',
    'ld.kind.ad': 'Active Directory',
    'ld.kind.openldap': 'OpenLDAP и совместимые',
    'ld.url': 'Адрес сервера',
    'ld.url.hint': 'ldaps://dc1.corp.example:636 или ldap://dc1.corp.example:389',
    'ld.starttls': 'Использовать StartTLS',
    'ld.starttls.hint': 'Переводит соединение ldap:// на TLS.',
    'ld.bindDn': 'Служебная учётная запись',
    'ld.bindDn.hint.ad': 'DN или user@domain, например svc-umbrella@corp.example',
    'ld.bindDn.hint.openldap': 'DN, например cn=umbrella,ou=services,dc=example,dc=org',
    'ld.bindPassword': 'Пароль служебной учётной записи',
    'ld.baseDn': 'База поиска (DN)',
    'ld.baseDn.hint': 'Например, DC=corp,DC=example',
    'ld.filter': 'Фильтр пользователей',
    'ld.filter.hint': 'Вместо {username} подставляется экранированный логин.',
    'ld.attrs': 'Атрибуты',
    'ld.attr.username': 'Логин',
    'ld.attr.name': 'Отображаемое имя',
    'ld.attr.email': 'Почта',
    'ld.adminGroup': 'Группа администраторов (DN)',
    'ld.adminGroup.hint': 'Участники получают права администратора. В Active Directory учитываются вложенные группы.',
    'ld.testUser': 'Проверочный пользователь',
    'ld.testUser.hint': 'Необязательно: проверить, что пользователь находится и, если указан пароль, может войти.',
    'ld.testUsername': 'Логин',
    'ld.testPassword': 'Пароль',
    'ld.ok': 'Каталог доступен',
    'ld.ok.text': 'Служебная учётная запись вошла, база поиска найдена.',
    'ld.ok.group': 'Группа администраторов найдена.',
    'ld.user': 'Пользователь {name} найден ({dn}).',
    'ld.user.auth': 'Пароль принят.',
    'ld.user.admin': 'Входит в группу администраторов.',
    'ld.user.notAdmin': 'Не входит в группу администраторов.',
    'ld.fail': 'Проверка каталога не прошла',
    'ld.off': 'Вход через каталог настраиваться не будет.',

    'ad.title': 'Локальный администратор',
    'ad.text': 'Эта учётная запись работает всегда, даже когда каталог недоступен. Сохраните пароль в надёжном месте.',
    'ad.username': 'Логин',
    'ad.name': 'Отображаемое имя',
    'ad.email': 'Почта',
    'ad.password': 'Пароль',
    'ad.confirm': 'Повторите пароль',
    'ad.rule.length': 'Не короче 10 символов',
    'ad.rule.mix': 'Буквы и цифры',
    'ad.rule.user': 'Не совпадает с логином',
    'ad.rule.match': 'Пароли совпадают',
    'ad.username.bad': 'Латиница, цифры и . _ @ -, от 2 до 64 символов.',

    'rv.title': 'Проверка и завершение',
    'rv.text': 'Umbrella сохранит пароли в OpenBao, создаст свою таблицу в PostgreSQL, создаст администратора и перейдёт в рабочий режим. После этого мастер отключится.',
    'rv.edit': 'Изменить',
    'rv.finish': 'Завершить настройку',
    'rv.finishing': 'Настраиваем…',
    'rv.locale': 'Язык',
    'rv.theme': 'Тема',
    'rv.address': 'Адрес',
    'rv.auth': 'Вход',
    'rv.database': 'База данных',
    'rv.reuse': 'Существующие данные',
    'rv.ldap': 'Каталог',
    'rv.ldap.off': 'Не используется',
    'rv.adminGroup': 'Группа администраторов',
    'rv.login': 'Логин',
    'rv.name': 'Имя',
    'rv.failed': 'Настройка не завершена',
    'rv.goto': 'Открыть шаг',

    'done.title': 'Umbrella готова к работе',
    'done.text': 'Настройка завершена, мастер отключён. Войдите как {user}.',
    'done.signin': 'Перейти ко входу',
  },
}
