import type { Dict } from '../../i18n'
import { strings as base } from '../strings'

// Words shared by the response page and the response tab of an incident.
const en: Record<string, string> = {
  'rs.tab.policies': 'Priority policies',
  'rs.tab.impact': 'Impact and priority',
  'rs.tab.integrations': 'Integrations',
  'rs.tab.check': 'Check',
  'rs.mode': 'Incident response',
  'rs.mode.off': 'Off',
  'rs.mode.dry_run': 'Dry run',
  'rs.mode.live': 'On',
  'rs.mode.hint.off': 'Incidents go only to PagerDuty and backup notification, as before.',
  'rs.mode.hint.dry_run': 'Every incident is assessed and the policy is played out on its timeline, but nothing is sent: no messages, chats, calls or Jira issues. Use it to tune the policies.',
  'rs.mode.hint.live': 'Policies run for real. Incidents opened before response was turned on are left alone.',
  'rs.since': 'Handles incidents opened since {at}.',
  'rs.save': 'Save',
  'rs.saved': 'Saved.',
  'rs.reset': 'Back to defaults',
  'rs.updated': 'Changed {at} by {by}',
  'rs.channels.off': 'Backup notification channels that are off: {list}. Steps skip them; turn them on in Settings → Alerting.',
  'rs.policy.on': 'Policy is on',
  'rs.policy.off': 'Off: incidents of this priority are only sent to PagerDuty and backup notification.',
  'rs.policy.summary': '{steps} steps · {room} · {bridge} · {jira}',
  'rs.policy.room.on': 'war room',
  'rs.policy.room.off': 'no war room',
  'rs.policy.bridge.none': 'no call',
  'rs.policy.bridge.teams': 'Teams call',
  'rs.policy.bridge.zoom': 'Zoom call',
  'rs.policy.jira.none': 'no Jira',
  'rs.policy.jira.task': 'Jira task',
  'rs.policy.jira.both': 'Jira task and postmortem',
  'rs.policy.jira.pm': 'postmortem',
  'rs.steps': 'Notification and escalation',
  'rs.steps.hint': 'Each step reaches its people by its methods the given time after the incident opened. Step 1 at 0 minutes is the first notification.',
  'rs.step': 'Step {n}',
  'rs.step.after': 'After, minutes',
  'rs.step.targets': 'Who',
  'rs.step.methods': 'How',
  'rs.step.users': 'More people',
  'rs.step.teams': 'More teams',
  'rs.step.add': 'Add a step',
  'rs.step.remove': 'Remove the step',
  'rs.step.none': 'No steps: nobody is told by the policy.',
  'rs.stop_on_ack': 'Stop escalating once the incident is acknowledged',
  'rs.stop_on_ack.hint': 'Off: escalation goes on until the incident is resolved.',
  'rs.room': 'War room in Microsoft Teams',
  'rs.room.hint': 'A group chat named after the incident with everything known about it: impact, services, sources, links. The team restores the service there and finds how to keep it from recurring.',
  'rs.room.members': 'Who joins',
  'rs.room.users': 'More people',
  'rs.room.add_escalated': 'People of later steps join the chat',
  'rs.room.post_updates': 'Post acknowledgement, raised priority, resolution and the postmortem in the chat',
  'rs.bridge': 'Conference call',
  'rs.bridge.hint': 'An online meeting opened with the incident; its link is in every message and in the chat.',
  'rs.bridge.none': 'None',
  'rs.bridge.teams': 'Microsoft Teams',
  'rs.bridge.zoom': 'Zoom',
  'rs.jira': 'Jira Cloud',
  'rs.jira.task': 'Create a task to resolve the incident when it opens',
  'rs.jira.comment': 'Add acknowledgement, resolution and raised priority to the task as comments',
  'rs.jira.postmortem': 'Create a postmortem when the incident is resolved',
  'rs.jira.days': 'Postmortem due in, days',
  'rs.days': 'd',
  'target.route': 'Owning team (route)',
  'target.lead': 'Team lead',
  'target.parent_lead': 'Lead of the parent team',
  'target.ci_owners': 'People responsible for the CI',
  'target.service_owners': 'Owners of affected services',
  'method.email': 'E-mail',
  'method.telegram': 'Telegram',
  'method.teams': 'Teams channel',
  'method.zoom': 'Zoom chat',
  'method.war_room': 'War room',
  'method.call_teams': 'Teams call',
  'method.call_zoom': 'Zoom call',
  'impact.extensive': 'Extensive',
  'impact.significant': 'Significant',
  'impact.moderate': 'Moderate',
  'impact.minor': 'Minor',
  'crit.critical': 'Critical',
  'crit.high': 'High',
  'crit.medium': 'Medium',
  'crit.low': 'Low',
  'rs.impact.text':
    'Impact is how much of the business the incident touches: the most critical of its business services and of the services that depend on them. Impact crossed with the severity of the events gives the response priority. The priority only rises while the incident is active.',
  'rs.impact.crit': 'Impact by service criticality',
  'rs.impact.no_service': 'CI outside any business service',
  'rs.impact.raise': 'Widen impact by one level',
  'rs.impact.red': 'RED signal (rate, errors, duration): users see it',
  'rs.impact.dependents': 'When at least this many services depend on the affected ones (0: off)',
  'rs.impact.incidents': 'When at least this many active incidents hit the same services (0: off)',
  'rs.impact.matrix': 'Priority matrix',
  'rs.impact.matrix.hint': 'Rows: impact. Columns: severity of the events (urgency). Cell: response priority.',
  'rs.impact.never_lower': 'Priority is never lower than the severity of the events',
  'rs.int.text': 'Without credentials, use dry run: the integration plans everything and writes it on the timeline but sends nothing. Secrets are stored in OpenBao and never shown again.',
  'rs.int.mode': 'Mode',
  'rs.int.test': 'Check the connection',
  'rs.int.ok': 'Connected: {info}',
  'rs.int.secret.set': 'Stored. Leave empty to keep it.',
  'rs.jira.title': 'Jira Cloud',
  'rs.jira.site': 'Site',
  'rs.jira.email': 'Account e-mail',
  'rs.jira.token': 'API token',
  'rs.jira.token.hint': 'id.atlassian.com → Security → API tokens.',
  'rs.jira.project': 'Project key',
  'rs.jira.task_type': 'Task issue type',
  'rs.jira.pm_type': 'Postmortem issue type',
  'rs.jira.labels': 'Labels',
  'rs.jira.labels.hint': 'Separated by spaces; the postmortem also gets "postmortem".',
  'rs.jira.link': 'Link type between postmortem and task',
  'rs.jira.done': 'Transition when resolved',
  'rs.jira.done.hint': 'For example Done; empty leaves the task as it is.',
  'rs.jira.prio': 'Jira priority of {p}',
  'rs.graph.title': 'Microsoft Teams (Graph): war rooms and calls',
  'rs.graph.text': 'Umbrella acts as a service account: it creates the chat, adds people by their e-mail (UPN) and opens meetings. Delegated permissions: Chat.Create, ChatMessage.Send, ChatMember.ReadWrite, OnlineMeetings.ReadWrite, User.ReadBasic.All, offline_access.',
  'rs.graph.tenant': 'Tenant ID or domain',
  'rs.graph.client': 'Application (client) ID',
  'rs.graph.secret': 'Client secret',
  'rs.graph.refresh': 'Refresh token of the service account',
  'rs.graph.refresh.hint': 'Got once by the device code sign-in (see the documentation); Umbrella keeps the rotated token.',
  'rs.graph.account': 'Service account',
  'rs.zoom.title': 'Zoom: calls',
  'rs.zoom.text': 'A Server-to-Server OAuth app (scope meeting:write:meeting, user:read:user) opens an instant meeting anyone with the link joins.',
  'rs.zoom.account': 'Account ID',
  'rs.zoom.client': 'Client ID',
  'rs.zoom.secret': 'Client secret',
  'rs.zoom.user': 'Meeting host',
  'rs.zoom.user.hint': 'E-mail of the Zoom user, or me.',
  'rs.sim.text': 'What would happen to an incident of a service: its impact, the priority and who each step reaches. The owning team of the service stands for the route.',
  'rs.sim.service': 'Business service',
  'rs.sim.none': 'No service',
  'rs.sim.severity': 'Severity of the events',
  'rs.sim.method': 'Method',
  'rs.sim.incidents': 'Active incidents of the service',
  'rs.sim.run': 'Assess',
  'rs.sim.unsaved': 'The check uses the saved settings: save your changes first.',
  'rs.sim.no_policy': 'The policy of this priority is off.',
  'rs.sim.nobody': 'nobody',
  'rs.sim.room': 'War room: {people}',
  'rs.as.priority': 'Response priority',
  'rs.as.impact': 'Impact',
  'rs.as.urgency': 'Severity of the events',
  'rs.as.services': 'Affected services',
  'rs.as.why': 'Why',
  'rs.as.via': 'via {name}',
  'rs.as.direct': 'directly',
  'reason.no_service': 'The CI belongs to no business service: impact {impact}',
  'reason.criticality': 'Most critical affected service {service} ({criticality}): impact {impact}',
  'reason.red': 'RED signal is what users see: impact {from} → {to}',
  'reason.dependents': '{count} more services depend on the affected ones: impact {from} → {to}',
  'reason.mass': '{count} active incidents on the same services: impact {from} → {to}',
  'reason.matrix': 'Matrix: impact {impact} × severity {urgency} = {priority}',
  'reason.never_lower': 'Not lower than the severity of the events: {priority}',
  'ir.off': 'Incident response is off. It is turned on in Automation → Incident response.',
  'ir.none': 'Response has not handled this incident: it opened before response was turned on, is a test, or is in a maintenance window.',
  'ir.dry': 'Dry run: nothing was sent.',
  'ir.steps': 'Escalation',
  'ir.step': 'Level {n} · {at}',
  'ir.step.people': 'Called in: {people}',
  'ir.step.reached': 'Reached: {list}',
  'ir.step.failed': 'Failed: {list}',
  'ir.room': 'War room',
  'ir.bridge': 'Call',
  'ir.task': 'Jira task',
  'ir.pm': 'Postmortem',
  'ir.open': 'Open',
  'ir.dry_tag': 'dry run',
  'ir.do.room': 'Open a war room',
  'ir.do.bridge': 'Start a call',
  'ir.do.task': 'Create a Jira task',
  'ir.do.postmortem': 'Create a postmortem',
  'ir.do.assess': 'Assess again',
  'ir.do.transition': 'Moving the Jira task',
  'ir.failure': '{action}: {error} (attempt {n})',
  'ir.members': '{n} in the chat',
  'err.response_off': 'Incident response is off.',
  'err.response_unavailable': 'Incident response needs PostgreSQL.',
  'err.bad_action': 'Unknown action.',
  'err.policy_invalid': 'A policy is not valid.',
  'err.impact_invalid': 'The impact rules are not valid.',
  'err.mode_invalid': 'Unknown mode.',
  'err.jira_incomplete': 'For Jira to work, fill in the site, the account, the token and the project.',
  'err.graph_incomplete': 'For Microsoft Teams to work, fill in the tenant, the application, the secret and the refresh token.',
  'err.zoom_incomplete': 'For Zoom to work, fill in the account, the client ID and the secret.',
  'err.graph_id_invalid': 'The tenant or the application ID is not valid.',
  'err.zoom_id_invalid': 'An ID or the host is not valid.',
  'err.project_invalid': 'The project key is upper-case letters, digits and _.',
  'err.label_invalid': 'A label has spaces.',
  'err.url_invalid': 'The address must be https without a query.',
  'err.email_invalid': 'The e-mail is not valid.',
  'err.severity_invalid': 'Unknown severity.',
  'err.integration_failed': 'The service did not accept the request.',
}

const ru: Record<string, string> = {
  'rs.tab.policies': 'Политики приоритетов',
  'rs.tab.impact': 'Влияние и приоритет',
  'rs.tab.integrations': 'Интеграции',
  'rs.tab.check': 'Проверка',
  'rs.mode': 'Реагирование на инциденты',
  'rs.mode.off': 'Выключено',
  'rs.mode.dry_run': 'Пробный режим',
  'rs.mode.live': 'Включено',
  'rs.mode.hint.off': 'Инциденты уходят только в PagerDuty и резервное оповещение, как раньше.',
  'rs.mode.hint.dry_run': 'Каждый инцидент оценивается, а политика разыгрывается в его хронологии, но ничего не отправляется: ни сообщений, ни чатов, ни звонков, ни задач Jira. Режим для настройки политик.',
  'rs.mode.hint.live': 'Политики работают по-настоящему. Инциденты, открытые до включения, не затрагиваются.',
  'rs.since': 'Обрабатываются инциденты, открытые с {at}.',
  'rs.save': 'Сохранить',
  'rs.saved': 'Сохранено.',
  'rs.reset': 'Вернуть по умолчанию',
  'rs.updated': 'Изменено {at}, {by}',
  'rs.channels.off': 'Выключенные каналы резервного оповещения: {list}. Шаги их пропускают; включите их в «Настройки → Оповещения».',
  'rs.policy.on': 'Политика включена',
  'rs.policy.off': 'Выключена: инциденты этого приоритета уходят только в PagerDuty и резервное оповещение.',
  'rs.policy.summary': 'шагов: {steps} · {room} · {bridge} · {jira}',
  'rs.policy.room.on': 'чат инцидента',
  'rs.policy.room.off': 'без чата',
  'rs.policy.bridge.none': 'без звонка',
  'rs.policy.bridge.teams': 'звонок Teams',
  'rs.policy.bridge.zoom': 'звонок Zoom',
  'rs.policy.jira.none': 'без Jira',
  'rs.policy.jira.task': 'задача Jira',
  'rs.policy.jira.both': 'задача и постмортем Jira',
  'rs.policy.jira.pm': 'постмортем',
  'rs.steps': 'Оповещение и эскалация',
  'rs.steps.hint': 'Каждый шаг через заданное время после открытия инцидента оповещает своих людей своими способами. Шаг 1 на 0 минуте — первое оповещение.',
  'rs.step': 'Шаг {n}',
  'rs.step.after': 'Через, минут',
  'rs.step.targets': 'Кого',
  'rs.step.methods': 'Как',
  'rs.step.users': 'Ещё люди',
  'rs.step.teams': 'Ещё команды',
  'rs.step.add': 'Добавить шаг',
  'rs.step.remove': 'Удалить шаг',
  'rs.step.none': 'Шагов нет: политика никого не оповещает.',
  'rs.stop_on_ack': 'Остановить эскалацию, когда инцидент подтверждён',
  'rs.stop_on_ack.hint': 'Выключено: эскалация идёт до решения инцидента.',
  'rs.room': 'Чат инцидента в Microsoft Teams',
  'rs.room.hint': 'Групповой чат с названием инцидента и всей информацией о нём: влияние, сервисы, источники, ссылки. В нём команда восстанавливает сервис и решает, как не допустить повторения.',
  'rs.room.members': 'Кто входит',
  'rs.room.users': 'Ещё люди',
  'rs.room.add_escalated': 'Люди следующих шагов добавляются в чат',
  'rs.room.post_updates': 'Писать в чат о подтверждении, повышении приоритета, решении и постмортеме',
  'rs.bridge': 'Звонок',
  'rs.bridge.hint': 'Онлайн-встреча открывается вместе с инцидентом; ссылка на неё есть в каждом сообщении и в чате.',
  'rs.bridge.none': 'Нет',
  'rs.bridge.teams': 'Microsoft Teams',
  'rs.bridge.zoom': 'Zoom',
  'rs.jira': 'Jira Cloud',
  'rs.jira.task': 'Создать задачу на устранение, когда инцидент открылся',
  'rs.jira.comment': 'Добавлять в задачу комментарии о подтверждении, решении и повышении приоритета',
  'rs.jira.postmortem': 'Создать постмортем, когда инцидент решён',
  'rs.jira.days': 'Срок постмортема, дней',
  'rs.days': 'дн.',
  'target.route': 'Команда-владелец (маршрут)',
  'target.lead': 'Руководитель команды',
  'target.parent_lead': 'Руководитель вышестоящей команды',
  'target.ci_owners': 'Ответственные за КЕ',
  'target.service_owners': 'Владельцы затронутых сервисов',
  'method.email': 'Почта',
  'method.telegram': 'Telegram',
  'method.teams': 'Канал Teams',
  'method.zoom': 'Чат Zoom',
  'method.war_room': 'Чат инцидента',
  'method.call_teams': 'Звонок Teams',
  'method.call_zoom': 'Звонок Zoom',
  'impact.extensive': 'Широкое',
  'impact.significant': 'Значительное',
  'impact.moderate': 'Умеренное',
  'impact.minor': 'Незначительное',
  'crit.critical': 'Критичный',
  'crit.high': 'Высокий',
  'crit.medium': 'Средний',
  'crit.low': 'Низкий',
  'rs.impact.text':
    'Влияние — какую часть бизнеса задевает инцидент: самый критичный из его бизнес-сервисов и сервисов, которые от них зависят. Влияние, пересечённое с важностью событий, даёт приоритет реагирования. Пока инцидент активен, приоритет только растёт.',
  'rs.impact.crit': 'Влияние по критичности сервиса',
  'rs.impact.no_service': 'КЕ вне бизнес-сервисов',
  'rs.impact.raise': 'Расширить влияние на уровень',
  'rs.impact.red': 'Сигнал RED (запросы, ошибки, задержки): его видят пользователи',
  'rs.impact.dependents': 'Когда от затронутых сервисов зависят не меньше стольких сервисов (0 — выкл.)',
  'rs.impact.incidents': 'Когда по тем же сервисам активно не меньше стольких инцидентов (0 — выкл.)',
  'rs.impact.matrix': 'Матрица приоритетов',
  'rs.impact.matrix.hint': 'Строки — влияние. Столбцы — важность событий (срочность). Ячейка — приоритет реагирования.',
  'rs.impact.never_lower': 'Приоритет не ниже важности событий',
  'rs.int.text': 'Без учётных данных используйте пробный режим: интеграция всё планирует и пишет в хронологию, но ничего не отправляет. Секреты хранятся в OpenBao и больше не показываются.',
  'rs.int.mode': 'Режим',
  'rs.int.test': 'Проверить подключение',
  'rs.int.ok': 'Подключено: {info}',
  'rs.int.secret.set': 'Сохранён. Оставьте пустым, чтобы не менять.',
  'rs.jira.title': 'Jira Cloud',
  'rs.jira.site': 'Сайт',
  'rs.jira.email': 'E-mail учётной записи',
  'rs.jira.token': 'API-токен',
  'rs.jira.token.hint': 'id.atlassian.com → Security → API tokens.',
  'rs.jira.project': 'Ключ проекта',
  'rs.jira.task_type': 'Тип задачи',
  'rs.jira.pm_type': 'Тип задачи постмортема',
  'rs.jira.labels': 'Метки',
  'rs.jira.labels.hint': 'Через пробел; постмортем получает ещё «postmortem».',
  'rs.jira.link': 'Тип связи постмортема и задачи',
  'rs.jira.done': 'Переход при решении',
  'rs.jira.done.hint': 'Например Done; пусто — задача не меняется.',
  'rs.jira.prio': 'Приоритет Jira для {p}',
  'rs.graph.title': 'Microsoft Teams (Graph): чаты и звонки',
  'rs.graph.text': 'Umbrella действует от сервисной учётной записи: создаёт чат, добавляет людей по e-mail (UPN) и открывает встречи. Делегированные разрешения: Chat.Create, ChatMessage.Send, ChatMember.ReadWrite, OnlineMeetings.ReadWrite, User.ReadBasic.All, offline_access.',
  'rs.graph.tenant': 'ID или домен арендатора',
  'rs.graph.client': 'ID приложения (client ID)',
  'rs.graph.secret': 'Секрет клиента',
  'rs.graph.refresh': 'Refresh-токен сервисной учётной записи',
  'rs.graph.refresh.hint': 'Получается один раз входом по коду устройства (см. документацию); Umbrella сама хранит обновлённый токен.',
  'rs.graph.account': 'Сервисная учётная запись',
  'rs.zoom.title': 'Zoom: звонки',
  'rs.zoom.text': 'Приложение Server-to-Server OAuth (scope meeting:write:meeting, user:read:user) открывает мгновенную встречу, в которую входят по ссылке.',
  'rs.zoom.account': 'Account ID',
  'rs.zoom.client': 'Client ID',
  'rs.zoom.secret': 'Client secret',
  'rs.zoom.user': 'Организатор встречи',
  'rs.zoom.user.hint': 'E-mail пользователя Zoom или me.',
  'rs.sim.text': 'Что произойдёт с инцидентом сервиса: влияние, приоритет и кого достанет каждый шаг. Маршрут — команда-владелец сервиса.',
  'rs.sim.service': 'Бизнес-сервис',
  'rs.sim.none': 'Без сервиса',
  'rs.sim.severity': 'Важность событий',
  'rs.sim.method': 'Метод',
  'rs.sim.incidents': 'Активных инцидентов сервиса',
  'rs.sim.run': 'Оценить',
  'rs.sim.unsaved': 'Проверка идёт по сохранённым настройкам: сначала сохраните изменения.',
  'rs.sim.no_policy': 'Политика этого приоритета выключена.',
  'rs.sim.nobody': 'никого',
  'rs.sim.room': 'Чат инцидента: {people}',
  'rs.as.priority': 'Приоритет реагирования',
  'rs.as.impact': 'Влияние',
  'rs.as.urgency': 'Важность событий',
  'rs.as.services': 'Затронутые сервисы',
  'rs.as.why': 'Почему',
  'rs.as.via': 'через {name}',
  'rs.as.direct': 'напрямую',
  'reason.no_service': 'КЕ не входит ни в один бизнес-сервис: влияние {impact}',
  'reason.criticality': 'Самый критичный затронутый сервис {service} ({criticality}): влияние {impact}',
  'reason.red': 'Сигнал RED видят пользователи: влияние {from} → {to}',
  'reason.dependents': 'От затронутых сервисов зависят ещё {count}: влияние {from} → {to}',
  'reason.mass': 'Активных инцидентов по тем же сервисам: {count}: влияние {from} → {to}',
  'reason.matrix': 'Матрица: влияние {impact} × важность {urgency} = {priority}',
  'reason.never_lower': 'Не ниже важности событий: {priority}',
  'ir.off': 'Реагирование на инциденты выключено. Оно включается в «Автоматизация → Реагирование на инциденты».',
  'ir.none': 'Реагирование не обрабатывало этот инцидент: он открыт до включения, тестовый или в сервисном окне.',
  'ir.dry': 'Пробный режим: ничего не отправлялось.',
  'ir.steps': 'Эскалация',
  'ir.step': 'Уровень {n} · {at}',
  'ir.step.people': 'Подключены: {people}',
  'ir.step.reached': 'Доставлено: {list}',
  'ir.step.failed': 'Ошибки: {list}',
  'ir.room': 'Чат инцидента',
  'ir.bridge': 'Звонок',
  'ir.task': 'Задача Jira',
  'ir.pm': 'Постмортем',
  'ir.open': 'Открыть',
  'ir.dry_tag': 'пробный режим',
  'ir.do.room': 'Открыть чат инцидента',
  'ir.do.bridge': 'Начать звонок',
  'ir.do.task': 'Создать задачу Jira',
  'ir.do.postmortem': 'Создать постмортем',
  'ir.do.assess': 'Оценить заново',
  'ir.do.transition': 'Перевод задачи Jira',
  'ir.failure': '{action}: {error} (попытка {n})',
  'ir.members': 'в чате: {n}',
  'err.response_off': 'Реагирование на инциденты выключено.',
  'err.response_unavailable': 'Реагированию на инциденты нужен PostgreSQL.',
  'err.bad_action': 'Неизвестное действие.',
  'err.policy_invalid': 'Политика заполнена неверно.',
  'err.impact_invalid': 'Правила влияния заполнены неверно.',
  'err.mode_invalid': 'Неизвестный режим.',
  'err.jira_incomplete': 'Для работы Jira заполните сайт, учётную запись, токен и проект.',
  'err.graph_incomplete': 'Для работы Microsoft Teams заполните арендатора, приложение, секрет и refresh-токен.',
  'err.zoom_incomplete': 'Для работы Zoom заполните Account ID, Client ID и секрет.',
  'err.graph_id_invalid': 'ID арендатора или приложения указан неверно.',
  'err.zoom_id_invalid': 'ID или организатор указан неверно.',
  'err.project_invalid': 'Ключ проекта: заглавные латинские буквы, цифры и _.',
  'err.label_invalid': 'В метке есть пробелы.',
  'err.url_invalid': 'Адрес должен быть https без параметров.',
  'err.email_invalid': 'E-mail указан неверно.',
  'err.severity_invalid': 'Неизвестная важность.',
  'err.integration_failed': 'Сервис не принял запрос.',
}

export const responseStrings: Dict = { en: { ...base.en, ...en }, ru: { ...base.ru, ...ru } }
