import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'inv.state.text':
      'An optional connection to Inventory DB, the datacenter inventory app. Umbrella reads its devices as configuration items and sends it the state of the alerts on them, so the device card in Inventory DB shows what is on fire with a link back to the incident.',
    'inv.state': 'State',
    'inv.state.on': 'Connected',
    'inv.state.off': 'Not connected',
    'inv.url': 'Inventory DB address',
    'inv.url.hint': 'The address of Inventory DB, for example https://inventory.example.com.',
    'inv.integration': 'Integration ID',
    'inv.integration.hint': 'Create an Umbrella integration in Inventory DB (POST /api/v1/integrations) and paste its id, such as int_abc123.',
    'inv.token': 'API token',
    'inv.token.hint': 'An Inventory DB API token of a read-only user. It is stored in OpenBao.',
    'inv.token.keep': 'Leave empty to keep the saved token.',
    'inv.token.again': 'The address or integration changed: enter the token again.',
    'inv.token.set': 'Saved in OpenBao',
    'inv.token.unset': 'Not set',
    'inv.secret': 'Signing secret',
    'inv.secret.hint': 'The secret Inventory DB showed when the integration was created. Alert states are signed with it. It is stored in OpenBao.',
    'inv.secret.keep': 'Leave empty to keep the saved secret.',
    'inv.items': 'Configuration items linked to Inventory DB',
    'inv.pushed': 'Active alerts Inventory DB knows about',
    'inv.settings': 'Connection settings',
    'inv.enable': 'Connect Inventory DB',
    'inv.enable.hint': 'Off by default. When turned off, nothing is read or sent; configuration items stay as they are.',
    'inv.skipVerify': 'Do not verify the TLS certificate',
    'inv.skipVerify.hint': 'Only for test installations with a self-signed certificate.',
    'inv.interval': 'Read devices every',
    'inv.interval.hint': '0 reads only with the button.',
    'inv.minutes': 'min',
    'inv.import': 'Read devices as configuration items',
    'inv.import.hint':
      'A device whose name an item already has (made by hand or read from NetBox) is linked to that item instead of creating a second one.',
    'inv.push': 'Send alert states to Inventory DB',
    'inv.push.hint': 'Every 30 seconds Umbrella sends the alerts on linked devices whose state changed, and reports finished ones as resolved.',
    'inv.push.noPublicUrl': 'Set the public address of Umbrella in Settings → Alerting so the states carry a link to the incident.',
    'inv.check': 'Check connection',
    'inv.checking': 'Checking…',
    'inv.save': 'Save',
    'inv.saved': 'Inventory DB settings are saved.',
    'inv.save.hint': 'The connection is checked before saving.',
    'inv.ok': 'Inventory DB answers',
    'inv.ok.text': 'The integration exports {items} objects (sites, racks and devices).',
    'inv.fail': 'Umbrella cannot work with Inventory DB using these settings',
    'inv.off': 'Inventory DB is not connected. This integration is optional.',
    'inv.sync': 'Devices',
    'inv.sync.now': 'Read devices now',
    'inv.sync.running': 'Reading…',
    'inv.sync.done': 'Devices are read.',
    'inv.sync.never': 'Devices have not been read yet.',
    'inv.sync.next': 'Next read',
    'inv.sync.manual': 'Only with the button',
    'inv.sync.last': 'Last read',
    'inv.sync.by': 'by {actor}',
    'inv.sync.result': 'Result',
    'inv.sync.ok': 'Done',
    'inv.sync.failed': 'Failed',
    'inv.sync.objects': 'Devices',
    'inv.sync.objects.value': '{objects} read: {created} created, {updated} updated, {linked} linked, {deleted} deleted, {unlinked} unlinked',
    'inv.sync.held': 'Items missing from Inventory DB were kept: {count}',
    'inv.sync.held.empty': 'Inventory DB returned no devices at all. The token may have lost its permissions, so nothing was deleted or unlinked.',
    'inv.sync.held.share': 'More than half of the linked items are missing from the answer, so they were not deleted or unlinked. If the devices were really removed, confirm the removal.',
    'inv.sync.held.confirm': 'Remove {count} missing items',
    'err.inventory_db_token_required': 'Enter the Inventory DB API token.',
    'err.inventory_db_secret_required': 'Enter the signing secret, or turn off sending alert states.',
    'err.inventory_db_invalid': 'Inventory DB settings are incomplete.',
    'err.inventory_db_unavailable': 'Umbrella cannot work with Inventory DB using these settings.',
    'err.inventory_db_off': 'Inventory DB is not connected.',
    'err.inventory_db_failed': 'Inventory DB refused the request.',
    'err.inventory_db_sync_running': 'Devices are already being read.',
  },
  ru: {
    'inv.state.text':
      'Необязательное подключение к Inventory DB, учёту инвентаря ЦОД. Umbrella загружает её устройства как КЕ и отправляет ей статусы тревог по ним, поэтому в карточке устройства в Inventory DB видно, что горит, со ссылкой на инцидент.',
    'inv.state': 'Состояние',
    'inv.state.on': 'Подключена',
    'inv.state.off': 'Не подключена',
    'inv.url': 'Адрес Inventory DB',
    'inv.url.hint': 'Адрес Inventory DB, например https://inventory.example.com.',
    'inv.integration': 'ID интеграции',
    'inv.integration.hint': 'Создайте в Inventory DB интеграцию Umbrella (POST /api/v1/integrations) и вставьте её id, например int_abc123.',
    'inv.token': 'API-токен',
    'inv.token.hint': 'API-токен пользователя Inventory DB только на чтение. Хранится в OpenBao.',
    'inv.token.keep': 'Оставьте пустым, чтобы сохранить прежний токен.',
    'inv.token.again': 'Адрес или интеграция изменились: введите токен заново.',
    'inv.token.set': 'Сохранён в OpenBao',
    'inv.token.unset': 'Не задан',
    'inv.secret': 'Секрет подписи',
    'inv.secret.hint': 'Секрет, который Inventory DB показала при создании интеграции. Им подписываются статусы тревог. Хранится в OpenBao.',
    'inv.secret.keep': 'Оставьте пустым, чтобы сохранить прежний секрет.',
    'inv.items': 'КЕ, связанные с Inventory DB',
    'inv.pushed': 'Активные тревоги, известные Inventory DB',
    'inv.settings': 'Настройки подключения',
    'inv.enable': 'Подключить Inventory DB',
    'inv.enable.hint': 'По умолчанию выключено. Когда выключено, ничего не загружается и не отправляется; КЕ остаются как есть.',
    'inv.skipVerify': 'Не проверять сертификат TLS',
    'inv.skipVerify.hint': 'Только для тестовых установок с самоподписанным сертификатом.',
    'inv.interval': 'Загружать устройства каждые',
    'inv.interval.hint': '0 — только по кнопке.',
    'inv.minutes': 'мин',
    'inv.import': 'Загружать устройства как КЕ',
    'inv.import.hint': 'Устройство, имя которого уже есть у КЕ (созданной вручную или из NetBox), связывается с этой КЕ, а не создаёт вторую.',
    'inv.push': 'Отправлять статусы тревог в Inventory DB',
    'inv.push.hint': 'Каждые 30 секунд Umbrella отправляет тревоги по связанным устройствам, у которых изменилось состояние, а завершённые — как решённые.',
    'inv.push.noPublicUrl': 'Задайте публичный адрес Umbrella в разделе Настройки → Оповещения, чтобы статусы несли ссылку на инцидент.',
    'inv.check': 'Проверить подключение',
    'inv.checking': 'Проверка…',
    'inv.save': 'Сохранить',
    'inv.saved': 'Настройки Inventory DB сохранены.',
    'inv.save.hint': 'Перед сохранением подключение проверяется.',
    'inv.ok': 'Inventory DB отвечает',
    'inv.ok.text': 'Интеграция отдаёт {items} объектов (площадки, стойки и устройства).',
    'inv.fail': 'С этими настройками Umbrella не может работать с Inventory DB',
    'inv.off': 'Inventory DB не подключена. Эта интеграция необязательна.',
    'inv.sync': 'Устройства',
    'inv.sync.now': 'Загрузить устройства',
    'inv.sync.running': 'Загрузка…',
    'inv.sync.done': 'Устройства загружены.',
    'inv.sync.never': 'Устройства ещё не загружались.',
    'inv.sync.next': 'Следующая загрузка',
    'inv.sync.manual': 'Только по кнопке',
    'inv.sync.last': 'Последняя загрузка',
    'inv.sync.by': 'запустил {actor}',
    'inv.sync.result': 'Результат',
    'inv.sync.ok': 'Выполнена',
    'inv.sync.failed': 'Ошибка',
    'inv.sync.objects': 'Устройства',
    'inv.sync.objects.value': 'прочитано {objects}: создано {created}, изменено {updated}, связано {linked}, удалено {deleted}, отвязано {unlinked}',
    'inv.sync.held': 'КЕ, которых нет в Inventory DB, сохранены: {count}',
    'inv.sync.held.empty': 'Inventory DB не вернула ни одного устройства. Возможно, токен потерял права, поэтому ничего не удалено и не отвязано.',
    'inv.sync.held.share': 'В ответе нет больше половины связанных КЕ, поэтому они не удалены и не отвязаны. Если устройства действительно удалены, подтвердите удаление.',
    'inv.sync.held.confirm': 'Удалить {count} отсутствующих КЕ',
    'err.inventory_db_token_required': 'Введите API-токен Inventory DB.',
    'err.inventory_db_secret_required': 'Введите секрет подписи или выключите отправку статусов тревог.',
    'err.inventory_db_invalid': 'Настройки Inventory DB заполнены не полностью.',
    'err.inventory_db_unavailable': 'С этими настройками Umbrella не может работать с Inventory DB.',
    'err.inventory_db_off': 'Inventory DB не подключена.',
    'err.inventory_db_failed': 'Inventory DB отклонила запрос.',
    'err.inventory_db_sync_running': 'Устройства уже загружаются.',
  },
}
