import type { Dict } from '../../i18n'

// Strings of quick connect, the test event and the explanation that ties connectors, monitoring
// systems and metric sources together.
export const sourcesStrings: Dict = {
  en: {
    'src.explain':
      'Alert intake — Connectors; host lists and CI matching — Monitoring systems; metrics for RED/USE rules — Prometheus systems or Metric sources. One Zabbix, Prometheus or Grafana is one monitoring system.',
    'src.explain.connectors': 'Connectors',
    'src.explain.monitoring': 'Monitoring systems',
    'src.explain.rules': 'RED/USE rules',
    'src.connect': 'Connect a source',
    'src.connect.title': 'Connect a source',
    'src.connect.hint':
      'Umbrella creates an intake token, a connector from the template and publishes it. You only paste the address and the token into the source.',
    'src.connect.preset': 'Source',
    'src.preset.zabbix': 'Zabbix',
    'src.preset.alertmanager': 'Prometheus Alertmanager',
    'src.preset.grafana': 'Grafana Alerting',
    'src.preset.webhook': 'Any system (JSON webhook)',
    'src.preset.zabbix.hint': 'Zabbix sends problems and recoveries through the Umbrella media type.',
    'src.preset.alertmanager.hint': 'Alertmanager sends the alerts of Prometheus rules to a webhook receiver.',
    'src.preset.grafana.hint': 'A Grafana contact point of the Webhook type.',
    'src.preset.webhook.hint': 'Your script or system posts JSON with title, host, signal, severity and status.',
    'src.connect.name': 'Name',
    'src.connect.name.hint': 'The connector name and the start of its address. Default: the name of the source.',
    'src.connect.go': 'Connect',
    'src.connect.cancel': 'Cancel',
    'src.connect.done': 'The connector “{name}” is published and accepts deliveries.',
    'src.url': 'Intake address',
    'src.token': 'Token',
    'src.token.once': 'The token is shown only now. Copy it: Umbrella keeps it only in OpenBao.',
    'src.copy': 'Copy',
    'src.copied': 'Copied',
    'src.download': 'Download',
    'src.steps': 'What to do in the source',
    'src.steps.zabbix.1': 'Download the media type below (address and token are already filled in) and import it in Zabbix: Alerts → Media types → Import.',
    'src.steps.zabbix.2': 'Users → Users → your user → Media: add the “Umbrella” media type, any value in “Send to”.',
    'src.steps.zabbix.3': 'Alerts → Actions → Trigger actions: an action that sends a message through “Umbrella”, with the same recovery operation.',
    'src.steps.alertmanager.1': 'Add the receiver below to alertmanager.yml (or merge it into your route) and reload Alertmanager.',
    'src.steps.alertmanager.2': 'Incidents get the CI from the instance, pod, service or job label.',
    'src.steps.grafana.1': 'Alerting → Contact points → New: Webhook with the address and the Authorization header below.',
    'src.steps.grafana.2': 'Use the contact point in a notification policy.',
    'src.steps.webhook.1': 'Post JSON to the address with the Authorization header, for example:',
    'src.open': 'Open the connector',
    'src.close': 'Done',
    'src.test': 'Send a test event',
    'src.test.hint':
      'The event goes through the published connector like a real one. The incident is marked as a test, is never sent to PagerDuty or by backup notification and resolves itself after 5 minutes.',
    'src.test.ci': 'CI name in the event',
    'src.test.ci.hint': 'To see the route of a real item, give its name. Empty: umbrella-test (not in the catalog).',
    'src.test.sent': 'Incident {id} opened.',
    'src.test.queued': 'The event is queued; the incident will appear shortly.',
    'src.test.failed': 'The connector could not process the test event',
    'src.test.open': 'Open the incident',
    'src.test.route': 'Route',
    'src.test.route.ci': 'CI: {ci}',
    'src.test.route.unknown': '“{ci}” is not in the catalog: nobody would get this incident.',
    'src.test.route.team': 'Team: {team}',
    'src.test.route.services': 'Business services: {services}',
    'src.test.route.people': 'People: {people}',
    'src.test.route.nobody': 'Nobody to route to.',
    'err.unknown_preset': 'Unknown template.',
    'err.connector_not_published': 'Publish the connector first.',
    'err.ingest_unavailable': 'The intake is not ready (PostgreSQL).',
    'err.secrets_unavailable': 'OpenBao is unavailable: the token cannot be saved.',
    'err.connector_slug_taken': 'This address is taken.',
  },
  ru: {
    'src.explain':
      'Приём алертов — Коннекторы; списки хостов и сопоставление с КЕ — Системы мониторинга; метрики для правил RED/USE — системы Prometheus или Источники метрик. Один Zabbix, Prometheus или Grafana — одна система мониторинга.',
    'src.explain.connectors': 'Коннекторы',
    'src.explain.monitoring': 'Системы мониторинга',
    'src.explain.rules': 'Правила RED/USE',
    'src.connect': 'Подключить источник',
    'src.connect.title': 'Подключить источник',
    'src.connect.hint':
      'Umbrella создаст токен приёма, коннектор из шаблона и опубликует его. В источнике останется указать адрес и токен.',
    'src.connect.preset': 'Источник',
    'src.preset.zabbix': 'Zabbix',
    'src.preset.alertmanager': 'Prometheus Alertmanager',
    'src.preset.grafana': 'Grafana Alerting',
    'src.preset.webhook': 'Любая система (JSON webhook)',
    'src.preset.zabbix.hint': 'Zabbix отправляет проблемы и восстановления через способ оповещения Umbrella.',
    'src.preset.alertmanager.hint': 'Alertmanager отправляет алерты правил Prometheus в webhook-получатель.',
    'src.preset.grafana.hint': 'Точка контакта Grafana типа Webhook.',
    'src.preset.webhook.hint': 'Ваш скрипт или система отправляет JSON с title, host, signal, severity и status.',
    'src.connect.name': 'Название',
    'src.connect.name.hint': 'Название коннектора и начало его адреса. По умолчанию — название источника.',
    'src.connect.go': 'Подключить',
    'src.connect.cancel': 'Отмена',
    'src.connect.done': 'Коннектор «{name}» опубликован и принимает события.',
    'src.url': 'Адрес приёма',
    'src.token': 'Токен',
    'src.token.once': 'Токен показан только сейчас. Скопируйте его: Umbrella хранит его только в OpenBao.',
    'src.copy': 'Копировать',
    'src.copied': 'Скопировано',
    'src.download': 'Скачать',
    'src.steps': 'Что сделать в источнике',
    'src.steps.zabbix.1': 'Скачайте способ оповещения ниже (адрес и токен уже подставлены) и импортируйте его в Zabbix: Оповещения → Способы оповещения → Импорт.',
    'src.steps.zabbix.2': 'Пользователи → Пользователи → ваш пользователь → Оповещения: добавьте способ «Umbrella», в «Отправлять на» — любое значение.',
    'src.steps.zabbix.3': 'Оповещения → Действия → Действия триггеров: действие с отправкой сообщения через «Umbrella» и такой же операцией восстановления.',
    'src.steps.alertmanager.1': 'Добавьте получателя ниже в alertmanager.yml (или объедините с вашим route) и перезагрузите Alertmanager.',
    'src.steps.alertmanager.2': 'КЕ инцидента берётся из метки instance, pod, service или job.',
    'src.steps.grafana.1': 'Alerting → Contact points → New: Webhook с адресом и заголовком Authorization ниже.',
    'src.steps.grafana.2': 'Укажите точку контакта в политике уведомлений.',
    'src.steps.webhook.1': 'Отправляйте JSON на адрес с заголовком Authorization, например:',
    'src.open': 'Открыть коннектор',
    'src.close': 'Готово',
    'src.test': 'Отправить тестовое событие',
    'src.test.hint':
      'Событие пройдёт через опубликованный коннектор как настоящее. Инцидент помечается как тестовый, не отправляется в PagerDuty и резервным оповещением и решается сам через 5 минут.',
    'src.test.ci': 'Имя КЕ в событии',
    'src.test.ci.hint': 'Чтобы увидеть маршрут настоящей КЕ, укажите её имя. Пусто — umbrella-test (нет в каталоге).',
    'src.test.sent': 'Открыт инцидент {id}.',
    'src.test.queued': 'Событие в очереди, инцидент скоро появится.',
    'src.test.failed': 'Коннектор не смог обработать тестовое событие',
    'src.test.open': 'Открыть инцидент',
    'src.test.route': 'Маршрут',
    'src.test.route.ci': 'КЕ: {ci}',
    'src.test.route.unknown': '«{ci}» нет в каталоге: этот инцидент никому не придёт.',
    'src.test.route.team': 'Команда: {team}',
    'src.test.route.services': 'Бизнес-сервисы: {services}',
    'src.test.route.people': 'Люди: {people}',
    'src.test.route.nobody': 'Направить некому.',
    'err.unknown_preset': 'Неизвестный шаблон.',
    'err.connector_not_published': 'Сначала опубликуйте коннектор.',
    'err.ingest_unavailable': 'Приём не готов (PostgreSQL).',
    'err.secrets_unavailable': 'OpenBao недоступен: токен не сохранить.',
    'err.connector_slug_taken': 'Этот адрес уже занят.',
  },
}
