import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'cn.title': 'Connectors',
    'cn.subtitle': 'Webhook intake: each connector turns the requests of one source into events, step by step, on a visual graph.',
    'cn.create': 'Create connector',
    'cn.create.title': 'New connector',
    'cn.import': 'Import',
    'cn.import.title': 'Import a connector',
    'cn.import.file': 'Export file',
    'cn.import.file.hint': 'A JSON file exported from Umbrella. Secrets are never exported: map the credentials below.',
    'cn.import.notJSON': 'The file is not valid JSON.',
    'cn.import.summary': 'Nodes: {nodes}. Samples: {samples}.',
    'cn.ingestDown': 'Request intake is unavailable: the PostgreSQL tables for incoming requests are not ready. Drafts can still be edited and tested.',
    'cn.empty': 'No connectors yet.',
    'cn.empty.hint': 'Connect a source in one step, create one from a template (Alertmanager, Grafana, Zabbix, generic webhook) or import an export.',
    'cn.col.name': 'Name',
    'cn.col.status': 'Status',
    'cn.col.received': 'Requests',
    'cn.col.events': 'Events',
    'cn.col.failed': 'Failed',
    'cn.col.last': 'Last request',
    'cn.col.version': 'Version',
    'cn.statsHint': 'Counters for the last 24 hours.',
    'cn.open': '{n} open',
    'cn.never': 'Never',
    'cn.version': 'version {n}',
    'cn.lockedBy': 'Being edited by {name}',
    'cn.locked.hint': 'The editor is read-only until they close it.',
    'cn.status.draft': 'Draft',
    'cn.status.published': 'Published',
    'cn.status.changed': 'Unpublished changes',
    'cn.status.publish_failed': 'Broken',
    'cn.field.preset': 'Template',
    'cn.preset.blank': 'Empty connector',
    'cn.preset.blank.hint': 'A webhook trigger and an event output to build on.',
    'cn.field.name': 'Name',
    'cn.field.slug': 'Address',
    'cn.field.slug.hint': 'Lowercase Latin letters, digits and dashes. The source sends requests to {url}',
    'cn.field.slug.change': 'Changing the address breaks the sources that use the old one.',
    'cn.field.description': 'Description',
    'cn.field.tags': 'Tags',
    'cn.field.tags.hint': 'Separated by commas.',
    'cn.optional': 'optional',
    'cn.cancel': 'Cancel',
    'cn.save': 'Save',
    'cn.close': 'Close',
    'cn.refresh': 'Refresh',
    'cn.reload': 'Reload',
    'cn.back': 'Back to connectors',
    'cn.cred.none': 'Not selected',
    'cn.cred.missing': 'Deleted credential',
    'cn.slots.hint': 'Choose the credentials that check incoming requests. You can do it later in the editor.',
    'cn.slots.named': '{slot} (was “{name}”)',
    'cn.slots.noCreds': 'No credentials of a suitable type yet. Create them on the Credentials page.',
    'cn.copyURL': 'Copy the full address',
    'cn.readOnly': 'Read only',
    'cn.save.saved': 'All changes saved',
    'cn.save.pending': 'Unsaved changes',
    'cn.save.saving': 'Saving…',
    'cn.save.error': 'Not saved',
    'cn.save.conflict': 'Changed elsewhere',
    'cn.conflict': 'The draft was changed in another window. Reload it to continue; your last changes here are not saved.',
    'cn.publishBroken': 'The published version cannot run on this server',
    'cn.undo': 'Undo (Ctrl+Z)',
    'cn.redo': 'Redo (Ctrl+Shift+Z)',
    'cn.versions': 'Versions',
    'cn.versions.none': 'Nothing has been published yet.',
    'cn.versions.current': 'live',
    'cn.versions.restore': 'Restore',
    'cn.versions.restore.hint': 'Replaces the draft with this version. Publish it to roll back.',
    'cn.export': 'Export',
    'cn.export.download': 'Download',
    'cn.export.hint': 'The draft graph as a JSON file. Credentials become slots that are mapped on import; secrets never leave Umbrella.',
    'cn.export.samples': 'Include samples',
    'cn.export.samples.hint': 'Sample bodies may contain production data.',
    'cn.settings': 'Settings',
    'cn.delete': 'Delete',
    'cn.delete.hint': 'The connector, its versions, samples, archived requests and failures are deleted. Type {slug} to confirm.',
    'cn.delete.confirm': 'Address of the connector',
    'cn.publish': 'Publish',
    'cn.publish.title': 'Publish the draft',
    'cn.publish.hint': 'The draft becomes version {n} and starts processing new requests. Requests already received stay on the version they arrived for.',
    'cn.publish.same': 'The live version is the same as the draft.',
    'cn.publish.name': 'Version name',
    'cn.publish.comment': 'What changed',
    'cn.unpublish': 'Stop',
    'cn.unpublish.hint': 'Stop: the address answers 404 until the next publication. Versions are kept.',
    'cn.palette': 'Nodes',
    'cn.cat.trigger': 'Trigger',
    'cn.cat.parse': 'Parse',
    'cn.cat.transform': 'Transform',
    'cn.cat.route': 'Route',
    'cn.cat.output': 'Output',
    'cn.cat.config': 'Settings',
    'cn.node.pinned': 'Output is pinned',
    'cn.node.issues': '{n} problems',
    'cn.node.trace': 'in {in} → out {out}',
    'cn.node.traceIn': 'in {in}',
    'cn.node.failed': '{n} failed',
    'cn.node.filtered': '{n} dropped',
    'cn.node.stale': 'The node or something before it changed after the test run. Run the test again.',
    'cn.node.name': 'Name on the canvas',
    'cn.node.disabled': 'Disabled',
    'cn.node.disabled.hint': 'Records pass through unchanged.',
    'cn.node.remove': 'Delete node',
    'cn.unknownType': 'Unknown node type',
    'cn.inspector': 'Node',
    'cn.tab.settings': 'Settings',
    'cn.tab.data': 'Data',
    'cn.tab.test': 'Test',
    'cn.tab.issues': 'Problems',
    'cn.tab.samples': 'Samples',
    'cn.tab.requests': 'Requests',
    'cn.tab.failures': 'Failures',
    'cn.tab.events': 'Events',
    'cn.tab.stats': 'Statistics',
    'cn.panel.hide': 'Hide the panel',
    'cn.panel.show': 'Show the panel',
    'cn.hint.template': 'Text with ${path} placeholders, fallbacks ${a|$b|"text"} and filters: lower, upper, trim, json, date, firstline, lastline, errorline, oneline, nohtml, noansi, unescape, truncate:200, head:20, tail:20 (lines).',
    'cn.hint.cel': 'CEL expression over event, request and connector.',
    'cn.hint.path': 'Path in the record: alerts[0].labels.instance',
    'cn.list.placeholder': 'One value per line',
    'cn.row.add': 'Add row',
    'cn.row.remove': 'Remove row',
    'cn.onError': 'When a record fails',
    'cn.onError.fail_record': 'Send to failures',
    'cn.onError.skip': 'Skip the record',
    'cn.onError.route_error': 'Continue on the error output',
    'cn.onError.fail_record.hint': 'The record goes to the failures list and can be reprocessed later.',
    'cn.onError.skip.hint': 'The record is dropped and counted as skipped.',
    'cn.onError.route_error.hint': 'The record with the error text goes to the “error” output.',
    'cn.preview': 'Preview',
    'cn.preview.onInput': 'Evaluate on the first input record of the last test run',
    'cn.preview.empty': 'Run a test first to evaluate on real data',
    'cn.pin': 'Pin output',
    'cn.pin.hint': 'Later test runs reuse this output instead of running the node and everything before it.',
    'cn.unpin': 'Unpin',
    'cn.data.notRun': 'Run a test to see what goes in and out of this node.',
    'cn.data.summary': '{in} records in, {us} µs.',
    'cn.data.input': 'Input',
    'cn.data.output': 'Output “{name}” ({n})',
    'cn.data.errors': 'Errors',
    'cn.data.item': 'Item {n}',
    'cn.data.none': 'No records.',
    'cn.data.view': 'View',
    'cn.data.table': 'Table',
    'cn.level.error': 'Error',
    'cn.level.warning': 'Warning',
    'cn.issues.none': 'No problems found.',
    'cn.test.sample': 'Sample',
    'cn.test.noSamples': 'No samples',
    'cn.test.run': 'Run',
    'cn.test.toNode': 'Run to selected',
    'cn.test.toNode.hint': 'Runs only the selected node and the nodes before it. Nothing is written.',
    'cn.test.all': 'Run all samples',
    'cn.test.all.hint': 'A regression check of the draft against every sample.',
    'cn.test.cannotRun': 'The graph has errors and cannot run. See Problems.',
    'cn.test.summary': 'Events: {events}. Failures: {failures}. Dropped by filters: {filtered}. Skipped: {skipped}. Test runs never write events.',
    'cn.test.failures': 'Failures',
    'cn.test.filtered': 'Dropped',
    'cn.test.result': 'Result',
    'cn.test.ok': 'OK',
    'cn.ev.severity': 'Severity',
    'cn.ev.status': 'Status',
    'cn.ev.title': 'Title',
    'cn.ev.details': 'Description and fields',
    'cn.ev.ci': 'CI',
    'cn.ev.signal': 'Signal',
    'cn.ev.labels': 'Labels',
    'cn.ev.key': 'Key',
    'cn.events.none': 'No events.',
    'cn.events.hint': 'Latest events written by the published versions, one row per deduplication key.',
    'cn.capture.hint': 'Wait for real requests: save the next',
    'cn.capture.within': 'requests within',
    'cn.capture.unit': 'minutes',
    'cn.capture.count': 'Number of requests',
    'cn.capture.minutes': 'Minutes to wait',
    'cn.capture.start': 'Capture as samples',
    'cn.capture.on': 'Capturing: {n} more requests until {until}. Send them to:',
    'cn.capture.stop': 'Stop capturing',
    'cn.samples.add': 'Add sample',
    'cn.samples.none': 'No samples. Capture real requests, add one by hand or save one from the Requests tab.',
    'cn.samples.source': 'Source',
    'cn.samples.format': 'Format',
    'cn.samples.size': 'Bytes',
    'cn.samples.created': 'Added',
    'cn.samples.delete': 'Delete sample',
    'cn.samples.body.hint': 'The request body exactly as the source sends it.',
    'cn.source.manual': 'By hand',
    'cn.source.capture': 'Captured',
    'cn.source.request': 'From a request',
    'cn.source.import': 'Imported',
    'cn.headers': 'Headers',
    'cn.query': 'Query parameters',
    'cn.body': 'Body',
    'cn.req.status': 'Status',
    'cn.req.any': 'Any status',
    'cn.req.pending': 'Queued',
    'cn.req.done': 'Processed',
    'cn.req.failed': 'Failed',
    'cn.req.none': 'No requests in the archive.',
    'cn.req.received': 'Received',
    'cn.req.from': 'From',
    'cn.req.error': 'Error',
    'cn.req.title': 'Request {id}',
    'cn.req.toSample': 'Save as sample',
    'cn.fail.show': 'Show',
    'cn.fail.open': 'Open failures',
    'cn.fail.resolved': 'Resolved',
    'cn.fail.none': 'No failures.',
    'cn.fail.choose': 'Choose',
    'cn.fail.reprocessChosen': 'Reprocess chosen ({n})',
    'cn.fail.reprocessAll': 'Reprocess all',
    'cn.fail.hint': 'Reprocessing runs the original requests again on the live version {n}.',
    'cn.fail.requeued': 'Requests queued again: {n}. No longer in the archive: {missing}.',
    'cn.fail.meta': 'Request {request}, item {item}, version {version}, retries {retries}',
    'cn.fail.record': 'Record',
    'cn.stats.period': 'Period',
    'cn.stats.h1': 'Last hour',
    'cn.stats.h6': 'Last 6 hours',
    'cn.stats.h24': 'Last 24 hours',
    'cn.stats.h168': 'Last 7 days',
    'cn.stats.received': 'Received',
    'cn.stats.events': 'Events',
    'cn.stats.failed': 'Failed',
    'cn.stats.rejected': 'Rejected',
    'cn.stats.filtered': 'Dropped',
    'cn.stats.latency': 'Max latency',
    'cn.stats.none': 'No requests in this period.',
    'cn.stats.chart': 'Requests over time',
    'cred.create': 'Add credential',
    'cred.new': 'New credential',
    'cred.empty': 'No credentials yet. Incoming: connectors check the requests of sources with them (quick connect creates a token by itself). Outgoing: monitoring systems and metric sources sign in to Zabbix, Prometheus and Grafana with them.',
    'cred.type': 'Type',
    'cred.usedBy': 'Used by',
    'cred.updated': 'Updated',
    'cred.type.bearer': 'Bearer token',
    'cred.type.basic': 'Basic auth',
    'cred.type.header': 'Header with a secret',
    'cred.type.hmac': 'HMAC signature',
    'cred.type.bearer.hint': 'The source sends “Authorization: Bearer <token>” or the X-Umbrella-Token header.',
    'cred.type.basic.hint': 'The source sends a user name and password with HTTP Basic authentication.',
    'cred.type.header.hint': 'The source sends the secret in a header of your choice.',
    'cred.type.hmac.hint': 'The source signs the body with HMAC-SHA256; the trigger says which header holds the signature.',
    'cred.field.token': 'Token',
    'cred.field.username': 'User name',
    'cred.field.password': 'Password',
    'cred.field.header': 'Header name',
    'cred.field.value': 'Header value',
    'cred.field.secret': 'Signing secret',
    'cred.secret.set': 'Set. Leave empty to keep it, or type a new value to replace it.',
    'cred.secret.hint': 'Stored in OpenBao. It cannot be viewed after saving.',
    'cred.generate': 'Generate',
    'cred.inUse': 'To delete it, remove it first from:',
    'cred.use.connector': 'connector',
    'cred.use.monitoring': 'monitoring system',
    'cred.use.metric_source': 'metric source',
    'cred.use.log_source': 'log source',
    'err.not_found': 'Not found. It may have been deleted.',
    'err.connector_slug_taken': 'Another connector already uses this address.',
    'err.invalid_connector_name': 'The name is empty or too long.',
    'err.invalid_connector_slug': 'Address: 2–63 lowercase Latin letters, digits and dashes, starting with a letter or digit.',
    'err.invalid_connector_description': 'The description is too long.',
    'err.invalid_connector_tags': 'Too many tags, or a tag is too long.',
    'err.unknown_preset': 'Unknown template.',
    'err.invalid_credential_mapping': 'A credential does not fit its slot.',
    'err.import_invalid': 'The file is not a connector export.',
    'err.graph_too_large': 'The graph is too large.',
    'err.invalid_graph': 'The graph is malformed.',
    'err.invalid_pins': 'Pinned data is malformed.',
    'err.draft_conflict': 'The draft was changed in another window.',
    'err.locked': 'Someone else is editing this connector.',
    'err.publish_failed': 'The draft has errors. Fix the problems listed in the Problems tab and publish again.',
    'err.not_published': 'The connector is not published.',
    'err.invalid_version_name': 'The version name is too long.',
    'err.invalid_sample_name': 'The sample name is empty or too long.',
    'err.sample_too_large': 'The sample is too large.',
    'err.sample_required': 'Choose a sample.',
    'err.invalid_capture': 'Capture up to 20 requests for up to 60 minutes.',
    'err.unknown_node': 'The node is not in the graph.',
    'err.test_run_timeout': 'The test run took too long.',
    'err.ingest_unavailable': 'Request intake is unavailable: PostgreSQL tables are not ready.',
    'err.invalid_credential_name': 'The name is empty or too long.',
    'err.invalid_credential_description': 'The description is too long.',
    'err.invalid_credential_type': 'Unknown credential type.',
    'err.invalid_credential_field': 'Fill in all fields.',
    'err.invalid_credential_secret': 'The secret is required, too long or has line breaks.',
    'err.credential_type_fixed': 'The type of a credential cannot be changed.',
    'err.credential_in_use': 'The credential is still in use (connectors, monitoring systems or metric sources).',
  },
  ru: {
    'cn.title': 'Коннекторы',
    'cn.subtitle': 'Приём вебхуков: каждый коннектор пошагово превращает запросы одного источника в события на визуальном графе.',
    'cn.create': 'Создать коннектор',
    'cn.create.title': 'Новый коннектор',
    'cn.import': 'Импорт',
    'cn.import.title': 'Импорт коннектора',
    'cn.import.file': 'Файл экспорта',
    'cn.import.file.hint': 'JSON-файл, выгруженный из Umbrella. Секреты не экспортируются: сопоставьте учётные данные ниже.',
    'cn.import.notJSON': 'Файл не является корректным JSON.',
    'cn.import.summary': 'Узлов: {nodes}. Образцов: {samples}.',
    'cn.ingestDown': 'Приём запросов недоступен: таблицы PostgreSQL для входящих запросов не готовы. Черновики можно править и тестировать.',
    'cn.empty': 'Коннекторов пока нет.',
    'cn.empty.hint': 'Подключите источник одной кнопкой, создайте коннектор из шаблона (Alertmanager, Grafana, Zabbix, общий вебхук) или импортируйте выгрузку.',
    'cn.col.name': 'Название',
    'cn.col.status': 'Статус',
    'cn.col.received': 'Запросы',
    'cn.col.events': 'События',
    'cn.col.failed': 'Ошибки',
    'cn.col.last': 'Последний запрос',
    'cn.col.version': 'Версия',
    'cn.statsHint': 'Счётчики за последние 24 часа.',
    'cn.open': 'открыто: {n}',
    'cn.never': 'Не было',
    'cn.version': 'версия {n}',
    'cn.lockedBy': 'Редактирует {name}',
    'cn.locked.hint': 'Редактор доступен только для чтения, пока коллега его не закроет.',
    'cn.status.draft': 'Черновик',
    'cn.status.published': 'Опубликован',
    'cn.status.changed': 'Есть неопубликованные изменения',
    'cn.status.publish_failed': 'Сломан',
    'cn.field.preset': 'Шаблон',
    'cn.preset.blank': 'Пустой коннектор',
    'cn.preset.blank.hint': 'Триггер-вебхук и выход событий, остальное — на ваш выбор.',
    'cn.field.name': 'Название',
    'cn.field.slug': 'Адрес',
    'cn.field.slug.hint': 'Строчные латинские буквы, цифры и дефисы. Источник отправляет запросы на {url}',
    'cn.field.slug.change': 'После смены адреса источники со старым адресом перестанут доставлять запросы.',
    'cn.field.description': 'Описание',
    'cn.field.tags': 'Теги',
    'cn.field.tags.hint': 'Через запятую.',
    'cn.optional': 'необязательно',
    'cn.cancel': 'Отмена',
    'cn.save': 'Сохранить',
    'cn.close': 'Закрыть',
    'cn.refresh': 'Обновить',
    'cn.reload': 'Загрузить заново',
    'cn.back': 'К списку коннекторов',
    'cn.cred.none': 'Не выбрано',
    'cn.cred.missing': 'Удалённые учётные данные',
    'cn.slots.hint': 'Выберите учётные данные для проверки входящих запросов. Это можно сделать и позже, в редакторе.',
    'cn.slots.named': '{slot} (было «{name}»)',
    'cn.slots.noCreds': 'Подходящих учётных данных пока нет. Создайте их на странице «Учётные данные».',
    'cn.copyURL': 'Скопировать полный адрес',
    'cn.readOnly': 'Только чтение',
    'cn.save.saved': 'Все изменения сохранены',
    'cn.save.pending': 'Есть несохранённые изменения',
    'cn.save.saving': 'Сохранение…',
    'cn.save.error': 'Не сохранено',
    'cn.save.conflict': 'Изменено в другом окне',
    'cn.conflict': 'Черновик изменили в другом окне. Загрузите его заново; последние изменения здесь не сохранены.',
    'cn.publishBroken': 'Опубликованная версия не может работать на этом сервере',
    'cn.undo': 'Отменить (Ctrl+Z)',
    'cn.redo': 'Повторить (Ctrl+Shift+Z)',
    'cn.versions': 'Версии',
    'cn.versions.none': 'Публикаций ещё не было.',
    'cn.versions.current': 'в работе',
    'cn.versions.restore': 'Восстановить',
    'cn.versions.restore.hint': 'Заменяет черновик этой версией. Опубликуйте его, чтобы откатиться.',
    'cn.export': 'Экспорт',
    'cn.export.download': 'Скачать',
    'cn.export.hint': 'Граф черновика в JSON. Учётные данные превращаются в слоты, которые сопоставляются при импорте; секреты не покидают Umbrella.',
    'cn.export.samples': 'Включить образцы',
    'cn.export.samples.hint': 'Тела образцов могут содержать продуктивные данные.',
    'cn.settings': 'Параметры',
    'cn.delete': 'Удалить',
    'cn.delete.hint': 'Будут удалены коннектор, его версии, образцы, архив запросов и ошибки. Введите {slug} для подтверждения.',
    'cn.delete.confirm': 'Адрес коннектора',
    'cn.publish': 'Опубликовать',
    'cn.publish.title': 'Публикация черновика',
    'cn.publish.hint': 'Черновик станет версией {n} и начнёт обрабатывать новые запросы. Уже принятые запросы обрабатываются версией, на которую пришли.',
    'cn.publish.same': 'Работающая версия совпадает с черновиком.',
    'cn.publish.name': 'Название версии',
    'cn.publish.comment': 'Что изменилось',
    'cn.unpublish': 'Остановить',
    'cn.unpublish.hint': 'Остановка: адрес отвечает 404 до следующей публикации. Версии сохраняются.',
    'cn.palette': 'Узлы',
    'cn.cat.trigger': 'Триггер',
    'cn.cat.parse': 'Разбор',
    'cn.cat.transform': 'Преобразование',
    'cn.cat.route': 'Маршрутизация',
    'cn.cat.output': 'Выход',
    'cn.cat.config': 'Настройки',
    'cn.node.pinned': 'Выход закреплён',
    'cn.node.issues': 'Проблем: {n}',
    'cn.node.trace': 'вход {in} → выход {out}',
    'cn.node.traceIn': 'вход {in}',
    'cn.node.failed': 'ошибок: {n}',
    'cn.node.filtered': 'отброшено: {n}',
    'cn.node.stale': 'Узел или что-то до него изменилось после тестового прогона. Запустите тест снова.',
    'cn.node.name': 'Название на холсте',
    'cn.node.disabled': 'Отключён',
    'cn.node.disabled.hint': 'Записи проходят без изменений.',
    'cn.node.remove': 'Удалить узел',
    'cn.unknownType': 'Неизвестный тип узла',
    'cn.inspector': 'Узел',
    'cn.tab.settings': 'Параметры',
    'cn.tab.data': 'Данные',
    'cn.tab.test': 'Тест',
    'cn.tab.issues': 'Проблемы',
    'cn.tab.samples': 'Образцы',
    'cn.tab.requests': 'Запросы',
    'cn.tab.failures': 'Ошибки',
    'cn.tab.events': 'События',
    'cn.tab.stats': 'Статистика',
    'cn.panel.hide': 'Скрыть панель',
    'cn.panel.show': 'Показать панель',
    'cn.hint.template': 'Текст с подстановками ${путь}, запасными вариантами ${a|$b|"текст"} и фильтрами: lower, upper, trim, json, date, firstline (первая строка), lastline, errorline (строка с ошибкой), oneline (в одну строку), nohtml, noansi, unescape (\\n → перевод строки), truncate:200 (символов), head:20 и tail:20 (строк).',
    'cn.hint.cel': 'Выражение CEL над event, request и connector.',
    'cn.hint.path': 'Путь в записи: alerts[0].labels.instance',
    'cn.list.placeholder': 'По одному значению в строке',
    'cn.row.add': 'Добавить строку',
    'cn.row.remove': 'Удалить строку',
    'cn.onError': 'Если запись не обработана',
    'cn.onError.fail_record': 'В список ошибок',
    'cn.onError.skip': 'Пропустить запись',
    'cn.onError.route_error': 'Продолжить по выходу error',
    'cn.onError.fail_record.hint': 'Запись попадает в список ошибок, её можно обработать повторно.',
    'cn.onError.skip.hint': 'Запись отбрасывается и учитывается как пропущенная.',
    'cn.onError.route_error.hint': 'Запись с текстом ошибки уходит на выход «error».',
    'cn.preview': 'Проверить',
    'cn.preview.onInput': 'Вычислить на первой входной записи последнего прогона',
    'cn.preview.empty': 'Сначала запустите тест, чтобы вычислять на реальных данных',
    'cn.pin': 'Закрепить выход',
    'cn.pin.hint': 'Следующие прогоны используют этот выход вместо выполнения узла и всего, что до него.',
    'cn.unpin': 'Открепить',
    'cn.data.notRun': 'Запустите тест, чтобы увидеть вход и выход этого узла.',
    'cn.data.summary': 'На входе записей: {in}, {us} мкс.',
    'cn.data.input': 'Вход',
    'cn.data.output': 'Выход «{name}» ({n})',
    'cn.data.errors': 'Ошибки',
    'cn.data.item': 'Элемент {n}',
    'cn.data.none': 'Записей нет.',
    'cn.data.view': 'Вид',
    'cn.data.table': 'Таблица',
    'cn.level.error': 'Ошибка',
    'cn.level.warning': 'Предупреждение',
    'cn.issues.none': 'Проблем не найдено.',
    'cn.test.sample': 'Образец',
    'cn.test.noSamples': 'Нет образцов',
    'cn.test.run': 'Запустить',
    'cn.test.toNode': 'До выбранного',
    'cn.test.toNode.hint': 'Выполняет только выбранный узел и узлы перед ним. Ничего не записывается.',
    'cn.test.all': 'Все образцы',
    'cn.test.all.hint': 'Регрессионная проверка черновика на всех образцах.',
    'cn.test.cannotRun': 'В графе есть ошибки, запуск невозможен. См. «Проблемы».',
    'cn.test.summary': 'Событий: {events}. Ошибок: {failures}. Отброшено фильтрами: {filtered}. Пропущено: {skipped}. Тестовый прогон не записывает события.',
    'cn.test.failures': 'Ошибки',
    'cn.test.filtered': 'Отброшено',
    'cn.test.result': 'Результат',
    'cn.test.ok': 'ОК',
    'cn.ev.severity': 'Важность',
    'cn.ev.status': 'Статус',
    'cn.ev.title': 'Заголовок',
    'cn.ev.details': 'Описание и поля',
    'cn.ev.ci': 'КЕ',
    'cn.ev.signal': 'Сигнал',
    'cn.ev.labels': 'Метки',
    'cn.ev.key': 'Ключ',
    'cn.events.none': 'Событий нет.',
    'cn.events.hint': 'Последние события опубликованных версий, одна строка на ключ дедупликации.',
    'cn.capture.hint': 'Дождаться реальных запросов: сохранить следующие',
    'cn.capture.within': 'запросов в течение',
    'cn.capture.unit': 'минут',
    'cn.capture.count': 'Количество запросов',
    'cn.capture.minutes': 'Сколько минут ждать',
    'cn.capture.start': 'Сохранить как образцы',
    'cn.capture.on': 'Идёт захват: ещё {n} запросов до {until}. Отправьте их на:',
    'cn.capture.stop': 'Остановить захват',
    'cn.samples.add': 'Добавить образец',
    'cn.samples.none': 'Образцов нет. Захватите реальные запросы, добавьте образец вручную или сохраните из вкладки «Запросы».',
    'cn.samples.source': 'Источник',
    'cn.samples.format': 'Формат',
    'cn.samples.size': 'Байт',
    'cn.samples.created': 'Добавлен',
    'cn.samples.delete': 'Удалить образец',
    'cn.samples.body.hint': 'Тело запроса в точности как его отправляет источник.',
    'cn.source.manual': 'Вручную',
    'cn.source.capture': 'Захвачен',
    'cn.source.request': 'Из запроса',
    'cn.source.import': 'Импортирован',
    'cn.headers': 'Заголовки',
    'cn.query': 'Параметры запроса',
    'cn.body': 'Тело',
    'cn.req.status': 'Статус',
    'cn.req.any': 'Любой статус',
    'cn.req.pending': 'В очереди',
    'cn.req.done': 'Обработан',
    'cn.req.failed': 'Ошибка',
    'cn.req.none': 'В архиве нет запросов.',
    'cn.req.received': 'Получен',
    'cn.req.from': 'Откуда',
    'cn.req.error': 'Ошибка',
    'cn.req.title': 'Запрос {id}',
    'cn.req.toSample': 'Сохранить как образец',
    'cn.fail.show': 'Показать',
    'cn.fail.open': 'Открытые ошибки',
    'cn.fail.resolved': 'Решённые',
    'cn.fail.none': 'Ошибок нет.',
    'cn.fail.choose': 'Выбрать',
    'cn.fail.reprocessChosen': 'Обработать выбранные ({n})',
    'cn.fail.reprocessAll': 'Обработать все',
    'cn.fail.hint': 'Повторная обработка заново прогоняет исходные запросы через работающую версию {n}.',
    'cn.fail.requeued': 'Запросов поставлено в очередь: {n}. Уже нет в архиве: {missing}.',
    'cn.fail.meta': 'Запрос {request}, элемент {item}, версия {version}, повторов {retries}',
    'cn.fail.record': 'Запись',
    'cn.stats.period': 'Период',
    'cn.stats.h1': 'Последний час',
    'cn.stats.h6': 'Последние 6 часов',
    'cn.stats.h24': 'Последние 24 часа',
    'cn.stats.h168': 'Последние 7 дней',
    'cn.stats.received': 'Получено',
    'cn.stats.events': 'События',
    'cn.stats.failed': 'Ошибки',
    'cn.stats.rejected': 'Отклонено',
    'cn.stats.filtered': 'Отброшено',
    'cn.stats.latency': 'Макс. задержка',
    'cn.stats.none': 'За этот период запросов не было.',
    'cn.stats.chart': 'Запросы во времени',
    'cred.create': 'Добавить',
    'cred.new': 'Новые учётные данные',
    'cred.empty': 'Учётных данных пока нет. Входящие: ими коннекторы проверяют запросы источников (быстрое подключение создаёт токен само). Исходящие: с ними системы мониторинга и источники метрик входят в Zabbix, Prometheus и Grafana.',
    'cred.type': 'Тип',
    'cred.usedBy': 'Используется',
    'cred.updated': 'Изменено',
    'cred.type.bearer': 'Bearer-токен',
    'cred.type.basic': 'Basic-аутентификация',
    'cred.type.header': 'Заголовок с секретом',
    'cred.type.hmac': 'Подпись HMAC',
    'cred.type.bearer.hint': 'Источник отправляет «Authorization: Bearer <токен>» или заголовок X-Umbrella-Token.',
    'cred.type.basic.hint': 'Источник отправляет логин и пароль через HTTP Basic.',
    'cred.type.header.hint': 'Источник отправляет секрет в заголовке, который вы выберете.',
    'cred.type.hmac.hint': 'Источник подписывает тело HMAC-SHA256; в триггере указывается заголовок с подписью.',
    'cred.field.token': 'Токен',
    'cred.field.username': 'Логин',
    'cred.field.password': 'Пароль',
    'cred.field.header': 'Имя заголовка',
    'cred.field.value': 'Значение заголовка',
    'cred.field.secret': 'Секрет подписи',
    'cred.secret.set': 'Задан. Оставьте пустым, чтобы сохранить, или введите новое значение для замены.',
    'cred.secret.hint': 'Хранится в OpenBao. После сохранения посмотреть его нельзя.',
    'cred.generate': 'Сгенерировать',
    'cred.inUse': 'Чтобы удалить, сначала уберите их отсюда:',
    'cred.use.connector': 'коннектор',
    'cred.use.monitoring': 'система мониторинга',
    'cred.use.metric_source': 'источник метрик',
    'cred.use.log_source': 'источник логов',
    'err.not_found': 'Не найдено. Возможно, объект удалён.',
    'err.connector_slug_taken': 'Этот адрес уже занят другим коннектором.',
    'err.invalid_connector_name': 'Название пустое или слишком длинное.',
    'err.invalid_connector_slug': 'Адрес: 2–63 символа — строчные латинские буквы, цифры и дефисы, начинается с буквы или цифры.',
    'err.invalid_connector_description': 'Слишком длинное описание.',
    'err.invalid_connector_tags': 'Слишком много тегов или слишком длинный тег.',
    'err.unknown_preset': 'Неизвестный шаблон.',
    'err.invalid_credential_mapping': 'Учётные данные не подходят для слота.',
    'err.import_invalid': 'Файл не является выгрузкой коннектора.',
    'err.graph_too_large': 'Слишком большой граф.',
    'err.invalid_graph': 'Граф повреждён.',
    'err.invalid_pins': 'Закреплённые данные повреждены.',
    'err.draft_conflict': 'Черновик изменили в другом окне.',
    'err.locked': 'Этот коннектор сейчас редактирует другой пользователь.',
    'err.publish_failed': 'В черновике есть ошибки. Исправьте проблемы со вкладки «Проблемы» и опубликуйте снова.',
    'err.not_published': 'Коннектор не опубликован.',
    'err.invalid_version_name': 'Слишком длинное название версии.',
    'err.invalid_sample_name': 'Название образца пустое или слишком длинное.',
    'err.sample_too_large': 'Образец слишком большой.',
    'err.sample_required': 'Выберите образец.',
    'err.invalid_capture': 'Можно захватить до 20 запросов на срок до 60 минут.',
    'err.unknown_node': 'Такого узла нет в графе.',
    'err.test_run_timeout': 'Тестовый прогон длился слишком долго.',
    'err.ingest_unavailable': 'Приём запросов недоступен: таблицы PostgreSQL не готовы.',
    'err.invalid_credential_name': 'Название пустое или слишком длинное.',
    'err.invalid_credential_description': 'Слишком длинное описание.',
    'err.invalid_credential_type': 'Неизвестный тип учётных данных.',
    'err.invalid_credential_field': 'Заполните все поля.',
    'err.invalid_credential_secret': 'Секрет не задан, слишком длинный или содержит переводы строк.',
    'err.credential_type_fixed': 'Тип учётных данных изменить нельзя.',
    'err.credential_in_use': 'Учётные данные ещё используются (коннекторы, системы мониторинга или источники метрик).',
  },
}
