import type { Dict } from '../../../i18n'
import { connectionStrings, mergeDicts } from '../../../connections/connectionStrings'
import { openBaoStrings } from '../../../connections/openbaoStrings'

const page: Dict = {
  en: {
    'obs.current': 'Current connection',
    'obs.current.text': 'The OpenBao server where Umbrella keeps passwords, tokens and other secrets.',
    'obs.addr': 'Address',
    'obs.version': 'Server version',
    'obs.mount': 'KV v2 mount',
    'obs.namespace': 'Namespace',
    'obs.auth': 'Sign-in method',
    'obs.auth.token': 'Token',
    'obs.auth.approle': 'AppRole ({path})',
    'obs.tls': 'TLS',
    'obs.tls.ca': 'own CA certificate',
    'obs.tls.skip': 'certificate is not verified',
    'obs.tls.default': 'system CA certificates',
    'obs.expires': 'Token expires',
    'obs.never': 'never',
    'obs.renewable': 'Renewable token',
    'obs.policies': 'Policies',
    'obs.secrets': 'Secrets in the mount',
    'obs.lastError': 'Last error',
    'obs.test.ok': 'OpenBao works',
    'obs.test.okText': 'Signed in; a test secret was written to {mount} and deleted.',
    'obs.test.fail': 'OpenBao check failed',

    'obs.move': 'Move to another OpenBao',
    'obs.move.text':
      'Copy every secret of the current mount to another OpenBao server or mount and switch Umbrella to it. The current installation is not changed.',
    'obs.move.targetSecrets': 'Secrets already in the target mount',
    'obs.move.notEmpty': 'The target mount already holds {count} secrets',
    'obs.move.notEmptyText': 'Secrets with the same paths will be replaced with the copies; other secrets stay.',
    'obs.move.overwrite': 'Write into the non-empty mount',
    'obs.move.confirm': 'Move Umbrella to another OpenBao?',
    'obs.move.step1': 'All {count} secrets of {from} are copied to {to}.',
    'obs.move.step2': 'Password references of users, the directory and the database switch to the new mount.',
    'obs.move.step3': 'Umbrella saves the new OpenBao connection and switches to it; for a few seconds it does not answer requests. Sessions stay open.',
    'obs.move.step4': 'The current OpenBao installation is left as it is.',
    'obs.move.done': 'Umbrella now works with {addr} ({mount})',
    'obs.move.doneText': 'Secrets copied: {copied}. References updated: {refs}. The previous installation was not changed.',

    'err.openbao_same_store': 'Umbrella already uses this OpenBao mount.',
    'err.openbao_not_kv2': 'The target mount is missing, not accessible or not KV version 2.',
    'err.openbao_list_failed': 'Umbrella cannot list the secrets. The policy needs list on <mount>/metadata/*.',
    'err.openbao_target_not_empty': 'The target mount already holds secrets. Confirm writing into it.',
    'err.openbao_migration_failed': 'The secrets were not moved. Umbrella keeps working with the current OpenBao.',
  },
  ru: {
    'obs.current': 'Текущее подключение',
    'obs.current.text': 'Сервер OpenBao, в котором Umbrella хранит пароли, токены и другие секреты.',
    'obs.addr': 'Адрес',
    'obs.version': 'Версия сервера',
    'obs.mount': 'Хранилище KV v2',
    'obs.namespace': 'Пространство имён',
    'obs.auth': 'Способ входа',
    'obs.auth.token': 'Токен',
    'obs.auth.approle': 'AppRole ({path})',
    'obs.tls': 'TLS',
    'obs.tls.ca': 'собственный сертификат CA',
    'obs.tls.skip': 'сертификат не проверяется',
    'obs.tls.default': 'системные сертификаты CA',
    'obs.expires': 'Токен действует до',
    'obs.never': 'бессрочно',
    'obs.renewable': 'Продлеваемый токен',
    'obs.policies': 'Политики',
    'obs.secrets': 'Секретов в хранилище',
    'obs.lastError': 'Последняя ошибка',
    'obs.test.ok': 'OpenBao работает',
    'obs.test.okText': 'Вход выполнен; тестовый секрет записан в {mount} и удалён.',
    'obs.test.fail': 'Проверка OpenBao не прошла',

    'obs.move': 'Перенос в другой OpenBao',
    'obs.move.text':
      'Скопировать все секреты текущего хранилища на другой сервер или в другое хранилище OpenBao и переключить Umbrella на него. Текущая установка не изменяется.',
    'obs.move.targetSecrets': 'Секретов в целевом хранилище',
    'obs.move.notEmpty': 'В целевом хранилище уже есть секреты: {count}',
    'obs.move.notEmptyText': 'Секреты с совпадающими путями будут заменены копиями, остальные останутся.',
    'obs.move.overwrite': 'Записать в непустое хранилище',
    'obs.move.confirm': 'Перенести Umbrella в другой OpenBao?',
    'obs.move.step1': 'Все секреты ({count}) из {from} копируются в {to}.',
    'obs.move.step2': 'Ссылки на пароли пользователей, каталога и базы данных переключаются на новое хранилище.',
    'obs.move.step3': 'Umbrella сохраняет новое подключение к OpenBao и переключается на него, несколько секунд не отвечая на запросы. Сеансы сохраняются.',
    'obs.move.step4': 'Текущая установка OpenBao остаётся без изменений.',
    'obs.move.done': 'Umbrella работает с {addr} ({mount})',
    'obs.move.doneText': 'Скопировано секретов: {copied}. Обновлено ссылок: {refs}. Прежняя установка не изменена.',

    'err.openbao_same_store': 'Umbrella уже использует это хранилище OpenBao.',
    'err.openbao_not_kv2': 'Целевое хранилище отсутствует, недоступно или не является KV версии 2.',
    'err.openbao_list_failed': 'Umbrella не может получить список секретов. Политике нужно право list на <mount>/metadata/*.',
    'err.openbao_target_not_empty': 'В целевом хранилище уже есть секреты. Подтвердите запись в него.',
    'err.openbao_migration_failed': 'Секреты не перенесены. Umbrella продолжает работать с текущим OpenBao.',
  },
}

export const strings = mergeDicts(connectionStrings, openBaoStrings, page)
