import type { Dict } from './i18n'
import { policyStrings } from './policy'

const editor: Dict = {
  en: {
    'pol.length': 'Minimum length',
    'pol.digits': 'Require digits',
    'pol.digits.hint': '0–9 and other decimal digits.',
    'pol.special': 'Require special characters',
    'pol.special.hint': 'Punctuation and symbols such as ! @ # $ % - _ .',
    'pol.count': 'At least',
    'pol.case': 'Require upper and lower case',
    'pol.case.hint': 'At least one capital and one small letter.',
    'pol.letters': 'Allowed letters',
    'pol.letters.hint': 'Letters of other alphabets are rejected.',
    'pol.letters.latin': 'Latin',
    'pol.letters.latin.ex': 'A–Z, a–z',
    'pol.letters.cyrillic': 'Cyrillic',
    'pol.letters.cyrillic.ex': 'А–Я, а–я, Ё',
    'pol.letters.latin_cyrillic': 'Latin and Cyrillic',
    'pol.letters.latin_cyrillic.ex': 'Both alphabets',
    'pol.letters.any': 'Any alphabet',
    'pol.letters.any.ex': 'No restriction',
    'pol.summary': 'A password must meet these rules:',
    'pol.err.length': 'Minimum length must be from 8 to 128.',
    'pol.err.digits': 'The number of digits must be from 1 to 16.',
    'pol.err.special': 'The number of special characters must be from 1 to 16.',
    'pol.err.fit': 'Required digits, special characters and letters do not fit into the minimum length.',
    'pol.row.length': 'Length',
    'pol.row.digits': 'Digits',
    'pol.row.special': 'Special characters',
    'pol.row.mixed_case': 'Case',
    'pol.row.letters': 'Letters',
    'pol.expire': 'Require periodic password change',
    'pol.expire.hint': 'After the lifetime ends, a local user must set a new password at the next sign-in. Directory accounts follow the directory rules.',
    'pol.maxAge': 'Password lifetime, days',
    'pol.maxAge.hint': 'From 1 to 3650 days.',
    'pol.warn': 'Warn before expiry, days',
    'pol.warn.hint': 'Users see a reminder this many days before the password expires. 0 turns the reminder off.',
    'pol.err.max_age': 'Password lifetime must be from 1 to 3650 days.',
    'pol.err.warn': 'The warning must be from 0 to 90 days and shorter than the password lifetime.',
    'pol.row.max_age': 'Lifetime',
    'pol.maxAge.days': 'Change every {n} days',
    'pol.maxAge.warn': 'reminder {n} days before',
    'pol.maxAge.never': 'Never expires',
  },
  ru: {
    'pol.length': 'Минимальная длина',
    'pol.digits': 'Требовать цифры',
    'pol.digits.hint': '0–9 и другие десятичные цифры.',
    'pol.special': 'Требовать спецсимволы',
    'pol.special.hint': 'Знаки препинания и символы: ! @ # $ % - _ .',
    'pol.count': 'Не меньше',
    'pol.case': 'Требовать разный регистр',
    'pol.case.hint': 'Хотя бы одна заглавная и одна строчная буква.',
    'pol.letters': 'Допустимые буквы',
    'pol.letters.hint': 'Буквы других алфавитов отклоняются.',
    'pol.letters.latin': 'Латиница',
    'pol.letters.latin.ex': 'A–Z, a–z',
    'pol.letters.cyrillic': 'Кириллица',
    'pol.letters.cyrillic.ex': 'А–Я, а–я, Ё',
    'pol.letters.latin_cyrillic': 'Латиница и кириллица',
    'pol.letters.latin_cyrillic.ex': 'Оба алфавита',
    'pol.letters.any': 'Любой алфавит',
    'pol.letters.any.ex': 'Без ограничений',
    'pol.summary': 'Пароль должен соответствовать правилам:',
    'pol.err.length': 'Минимальная длина — от 8 до 128.',
    'pol.err.digits': 'Количество цифр — от 1 до 16.',
    'pol.err.special': 'Количество спецсимволов — от 1 до 16.',
    'pol.err.fit': 'Обязательные цифры, спецсимволы и буквы не помещаются в минимальную длину.',
    'pol.row.length': 'Длина',
    'pol.row.digits': 'Цифры',
    'pol.row.special': 'Спецсимволы',
    'pol.row.mixed_case': 'Регистр',
    'pol.row.letters': 'Буквы',
    'pol.expire': 'Требовать периодическую смену пароля',
    'pol.expire.hint':
      'Когда срок действия истечёт, локальный пользователь должен задать новый пароль при следующем входе. Учётные записи каталога подчиняются правилам каталога.',
    'pol.maxAge': 'Срок действия пароля, дней',
    'pol.maxAge.hint': 'От 1 до 3650 дней.',
    'pol.warn': 'Предупреждать заранее, дней',
    'pol.warn.hint': 'За столько дней до окончания срока пользователь видит напоминание. 0 — без напоминания.',
    'pol.err.max_age': 'Срок действия пароля — от 1 до 3650 дней.',
    'pol.err.warn': 'Предупреждение — от 0 до 90 дней и меньше срока действия пароля.',
    'pol.row.max_age': 'Срок действия',
    'pol.maxAge.days': 'Смена каждые {n} дн.',
    'pol.maxAge.warn': 'напоминание за {n} дн.',
    'pol.maxAge.never': 'Бессрочно',
  },
}

export const policyEditorStrings: Dict = { en: { ...editor.en, ...policyStrings.en }, ru: { ...editor.ru, ...policyStrings.ru } }
