import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    loading: 'Loading…',
    'rl.tab.rules': 'Rules',
    'rl.tab.sources': 'Metric sources',
    'rl.new': 'New rule',
    'rl.empty': 'No rules yet. Add a metric source, then a rule from a template.',
    'rl.empty.sources': 'Add a Prometheus monitoring system (Monitoring systems page) or a metric source: a Prometheus-compatible API (Prometheus, VictoriaMetrics, Thanos, Mimir).',
    'rl.col.method': 'Method',
    'rl.col.name': 'Rule',
    'rl.col.cond': 'Condition',
    'rl.col.state': 'State',
    'rl.col.source': 'Source',
    'rl.method.red': 'RED',
    'rl.method.use': 'USE',
    'rl.method.red.hint': 'Rate, errors, duration of a service',
    'rl.method.use.hint': 'Utilization, saturation, errors of a resource',
    'rl.off': 'Off',
    'rl.firing': 'Firing: {n}',
    'rl.pending': 'Pending: {n}',
    'rl.ok': 'OK · series: {n}',
    'rl.never': 'Not evaluated yet',
    'rl.error': 'Error',
    'rl.for': 'for {d}',
    'rl.dialog.new': 'New rule',
    'rl.dialog.edit': 'Rule',
    'rl.template': 'Template',
    'rl.template.none': 'Empty rule',
    'rl.name': 'Name',
    'rl.method': 'Method',
    'rl.source': 'Metric source',
    'rl.query': 'PromQL query',
    'rl.query.hint': 'An instant vector; every series is checked against the condition.',
    'rl.op': 'Condition',
    'rl.threshold': 'Threshold',
    'rl.forField': 'For',
    'rl.forField.hint': 'How long the condition must hold: 0s, 1m, 5m.',
    'rl.interval': 'Every',
    'rl.interval.hint': 'At least 10s.',
    'rl.severity': 'Severity',
    'rl.cilabel': 'CI label',
    'rl.cilabel.hint': 'The label that names the CI: instance (without the port), host, job, name…',
    'rl.signal': 'Signal',
    'rl.signal.hint': 'Empty: method and name. Incidents of one CI and signal fold into one.',
    'rl.title': 'Incident title',
    'rl.title.hint': 'Placeholders: ${ci}, ${value}, ${threshold}, ${labels.name}.',
    'rl.enabled': 'Evaluate the rule',
    'rl.preview': 'Check now',
    'rl.preview.result': 'Series: {total}, meet the condition: {matched}.',
    'rl.preview.more': 'Showing the first {n}.',
    'rl.evaluate': 'Evaluate now',
    'rl.save': 'Save',
    'rl.cancel': 'Cancel',
    'rl.delete': 'Delete',
    'rl.delete.confirm': 'Delete the rule “{name}”? What it fired is resolved.',
    'rl.lastEval': 'Last evaluated {at}',
    'ms.new': 'New source',
    'ms.name': 'Name',
    'ms.url': 'Address',
    'ms.url.hint': 'The base address of the Prometheus HTTP API, for example http://prometheus:9090',
    'ms.cred': 'Credential',
    'ms.cred.none': 'None',
    'ms.cred.hint': 'Bearer token, basic or header credential from the credential catalog.',
    'ms.skip': 'Do not check the server certificate',
    'ms.test': 'Check',
    'ms.test.ok': 'The source answers: {n} series of up.',
    'ms.rules': 'Rules',
    'ms.delete.confirm': 'Delete the source “{name}”?',
    'ms.dialog.new': 'New metric source',
    'ms.dialog.edit': 'Metric source',
    'sev.info': 'Info',
    'sev.warning': 'Warning',
    'sev.error': 'Error',
    'sev.critical': 'Critical',
    'err.rule_name': 'Enter a name of up to 200 characters.',
    'err.rule_method': 'Choose RED or USE.',
    'err.rule_source': 'Choose a metric source.',
    'err.rule_query': 'Enter a PromQL query.',
    'err.rule_op': 'Choose a condition.',
    'err.rule_threshold': 'The threshold must be a number.',
    'err.rule_severity': 'Choose a severity.',
    'err.rule_for': 'The duration is like 0s, 1m or 5m, at most 24h.',
    'err.rule_interval': 'The interval is from 10s to 1h.',
    'err.source_not_found': 'The metric source no longer exists.',
    'err.source_in_use': 'Rules use this source: move or delete them first.',
    'err.source_failed': 'The source did not answer.',
    'err.url_invalid': 'Enter an http or https address.',
    'err.name_invalid': 'Enter a name.',
    'err.credential_not_found': 'The credential no longer exists.',
    'err.credential_type': 'Only bearer, basic and header credentials can query metrics.',
    'err.too_many_rules': 'Too many rules.',
    'ms.kind.system': 'monitoring system',
    'ms.kind.source': 'metric source',
    'ms.systems.hint': 'A Prometheus monitoring system is a metric source by itself: its address and credential are set once on the Monitoring systems page. A separate metric source is only for a server that is not a monitoring system.',
    'ms.merge': 'Merge into the system',
    'ms.merge.new': 'Make a monitoring system',
    'ms.merge.hint': 'One object per Prometheus: the rules move to the monitoring system and the metric source is deleted.',
    'ms.merge.confirm': 'Merge “{name}” into the Prometheus monitoring system at the same address? Its rules ({n}) move to the system with their state, the metric source is deleted.',
    'ms.merge.confirm.new': 'Make “{name}” a Prometheus monitoring system? Its rules ({n}) move to the system with their state, the metric source is deleted; the system also reads the host list.',
  },
  ru: {
    loading: 'Загрузка…',
    'rl.tab.rules': 'Правила',
    'rl.tab.sources': 'Источники метрик',
    'rl.new': 'Новое правило',
    'rl.empty': 'Правил пока нет. Добавьте источник метрик, затем правило из шаблона.',
    'rl.empty.sources': 'Сначала добавьте систему мониторинга Prometheus (страница «Системы мониторинга») или источник метрик: API, совместимый с Prometheus (Prometheus, VictoriaMetrics, Thanos, Mimir).',
    'rl.col.method': 'Метод',
    'rl.col.name': 'Правило',
    'rl.col.cond': 'Условие',
    'rl.col.state': 'Состояние',
    'rl.col.source': 'Источник',
    'rl.method.red': 'RED',
    'rl.method.use': 'USE',
    'rl.method.red.hint': 'Поток, ошибки и время ответа сервиса',
    'rl.method.use.hint': 'Загрузка, насыщение и ошибки ресурса',
    'rl.off': 'Выключено',
    'rl.firing': 'Срабатывает: {n}',
    'rl.pending': 'Ожидание: {n}',
    'rl.ok': 'Норма · рядов: {n}',
    'rl.never': 'Ещё не вычислялось',
    'rl.error': 'Ошибка',
    'rl.for': 'в течение {d}',
    'rl.dialog.new': 'Новое правило',
    'rl.dialog.edit': 'Правило',
    'rl.template': 'Шаблон',
    'rl.template.none': 'Пустое правило',
    'rl.name': 'Название',
    'rl.method': 'Метод',
    'rl.source': 'Источник метрик',
    'rl.query': 'Запрос PromQL',
    'rl.query.hint': 'Мгновенный вектор; каждый ряд проверяется по условию.',
    'rl.op': 'Условие',
    'rl.threshold': 'Порог',
    'rl.forField': 'В течение',
    'rl.forField.hint': 'Сколько условие должно держаться: 0s, 1m, 5m.',
    'rl.interval': 'Каждые',
    'rl.interval.hint': 'Не меньше 10s.',
    'rl.severity': 'Важность',
    'rl.cilabel': 'Метка КЕ',
    'rl.cilabel.hint': 'Метка с именем КЕ: instance (без порта), host, job, name…',
    'rl.signal': 'Сигнал',
    'rl.signal.hint': 'Пусто: метод и название. Инциденты одной КЕ и сигнала схлопываются в один.',
    'rl.title': 'Заголовок инцидента',
    'rl.title.hint': 'Подстановки: ${ci}, ${value}, ${threshold}, ${labels.имя}.',
    'rl.enabled': 'Вычислять правило',
    'rl.preview': 'Проверить сейчас',
    'rl.preview.result': 'Рядов: {total}, подходят под условие: {matched}.',
    'rl.preview.more': 'Показаны первые {n}.',
    'rl.evaluate': 'Вычислить сейчас',
    'rl.save': 'Сохранить',
    'rl.cancel': 'Отмена',
    'rl.delete': 'Удалить',
    'rl.delete.confirm': 'Удалить правило «{name}»? Его сработавшие инциденты будут решены.',
    'rl.lastEval': 'Последнее вычисление {at}',
    'ms.new': 'Новый источник',
    'ms.name': 'Название',
    'ms.url': 'Адрес',
    'ms.url.hint': 'Базовый адрес Prometheus HTTP API, например http://prometheus:9090',
    'ms.cred': 'Учётные данные',
    'ms.cred.none': 'Нет',
    'ms.cred.hint': 'Bearer-токен, basic или заголовок из каталога учётных данных.',
    'ms.skip': 'Не проверять сертификат сервера',
    'ms.test': 'Проверить',
    'ms.test.ok': 'Источник отвечает: рядов up — {n}.',
    'ms.rules': 'Правил',
    'ms.delete.confirm': 'Удалить источник «{name}»?',
    'ms.dialog.new': 'Новый источник метрик',
    'ms.dialog.edit': 'Источник метрик',
    'sev.info': 'Инфо',
    'sev.warning': 'Предупреждение',
    'sev.error': 'Ошибка',
    'sev.critical': 'Критично',
    'err.rule_name': 'Введите название длиной до 200 символов.',
    'err.rule_method': 'Выберите RED или USE.',
    'err.rule_source': 'Выберите источник метрик.',
    'err.rule_query': 'Введите запрос PromQL.',
    'err.rule_op': 'Выберите условие.',
    'err.rule_threshold': 'Порог должен быть числом.',
    'err.rule_severity': 'Выберите важность.',
    'err.rule_for': 'Длительность вида 0s, 1m или 5m, не больше 24h.',
    'err.rule_interval': 'Интервал от 10s до 1h.',
    'err.source_not_found': 'Источник метрик больше не существует.',
    'err.source_in_use': 'Источник используют правила: сначала перенесите или удалите их.',
    'err.source_failed': 'Источник не ответил.',
    'err.url_invalid': 'Введите адрес http или https.',
    'err.name_invalid': 'Введите название.',
    'err.credential_not_found': 'Учётные данные больше не существуют.',
    'err.credential_type': 'Для метрик подходят только bearer, basic и заголовок.',
    'err.too_many_rules': 'Слишком много правил.',
    'ms.kind.system': 'система мониторинга',
    'ms.kind.source': 'источник метрик',
    'ms.systems.hint': 'Система мониторинга Prometheus сама служит источником метрик: её адрес и учётные данные задаются один раз на странице «Системы мониторинга». Отдельный источник метрик нужен только для сервера, который не заведён как система.',
    'ms.merge': 'Объединить с системой',
    'ms.merge.new': 'Сделать системой мониторинга',
    'ms.merge.hint': 'Один объект на один Prometheus: правила переходят в систему мониторинга, источник метрик удаляется.',
    'ms.merge.confirm': 'Объединить «{name}» с системой мониторинга Prometheus с тем же адресом? Правила ({n}) перейдут в систему с их состоянием, источник метрик будет удалён.',
    'ms.merge.confirm.new': 'Сделать «{name}» системой мониторинга Prometheus? Правила ({n}) перейдут в систему с их состоянием, источник метрик будет удалён; система также будет читать список хостов.',
  },
}
