import type { Dict } from '../../../i18n'
import { connectionStrings, mergeDicts } from '../../../connections/connectionStrings'
import { postgresStrings } from '../../../connections/postgresStrings'

const page: Dict = {
  en: {
    'pgs.current': 'Current connection',
    'pgs.current.text': 'The PostgreSQL database where Umbrella saves its state.',
    'pgs.host': 'Host',
    'pgs.port': 'Port',
    'pgs.database': 'Database',
    'pgs.user': 'User',
    'pgs.sslmode': 'SSL mode',
    'pgs.version': 'Server version',
    'pgs.size': 'Database size',
    'pgs.savedAt': 'Last saved',
    'pgs.pending': 'Unsaved changes',
    'pgs.test.ok': 'Connection works',
    'pgs.test.okText': 'PostgreSQL {version} answered in {latency} ms.',
    'pgs.test.fail': 'PostgreSQL does not answer',

    'pgs.stats': 'Statistics',
    'pgs.stats.text': 'Live counters of the Umbrella database from pg_stat_database, table sizes and the longest running operations.',
    'pgs.stats.auto': 'Refresh every 10 seconds',
    'pgs.stats.collected': 'Collected {at}',
    'pgs.tx': 'Transactions',
    'pgs.tx.since': 'Counters since {at}.',
    'pgs.tx.sinceStart': 'Counters since the statistics were last reset.',
    'pgs.tx.commits': 'Commits',
    'pgs.tx.rollbacks': 'Rollbacks',
    'pgs.tx.rate': 'Transactions per second',
    'pgs.tx.rateWait': 'after the next refresh',
    'pgs.tx.cache': 'Cache hit ratio',
    'pgs.tx.backends': 'Connections',
    'pgs.tx.deadlocks': 'Deadlocks',
    'pgs.tx.conflicts': 'Conflicts',
    'pgs.tx.temp': 'Temporary files',
    'pgs.tx.returned': 'Rows returned',
    'pgs.tx.fetched': 'Rows fetched',
    'pgs.tx.inserted': 'Rows inserted',
    'pgs.tx.updated': 'Rows updated',
    'pgs.tx.deleted': 'Rows deleted',
    'pgs.tables': 'Table sizes',
    'pgs.tables.top': 'The {shown} largest of {total} tables.',
    'pgs.tables.none': 'The database has no user tables.',
    'pgs.tables.name': 'Table',
    'pgs.tables.total': 'Total',
    'pgs.tables.data': 'Data',
    'pgs.tables.indexes': 'Indexes',
    'pgs.tables.rows': 'Rows',
    'pgs.tables.dead': 'Dead rows',
    'pgs.ops': 'Top 10 longest operations',
    'pgs.ops.none': 'No queries or open transactions are running right now.',
    'pgs.ops.limited': 'Only sessions of the database user are visible. Grant the pg_read_all_stats role to see all sessions.',
    'pgs.ops.pid': 'PID',
    'pgs.ops.who': 'User / application',
    'pgs.ops.state': 'State',
    'pgs.ops.wait': 'Waiting for',
    'pgs.ops.duration': 'Duration',
    'pgs.ops.query': 'Query',
    'pgs.stmts': 'Top 10 statements',
    'pgs.stmts.byTotal': 'By total time',
    'pgs.stmts.byMean': 'By mean time',
    'pgs.stmts.missing': 'The pg_stat_statements extension is not installed in this database.',
    'pgs.stmts.missingHint': 'Add pg_stat_statements to shared_preload_libraries, restart PostgreSQL and run CREATE EXTENSION pg_stat_statements.',
    'pgs.stmts.error': 'pg_stat_statements is not readable',
    'pgs.stmts.none': 'No statements recorded yet.',
    'pgs.stmts.calls': 'Calls',
    'pgs.stmts.total': 'Total',
    'pgs.stmts.mean': 'Mean',
    'pgs.stmts.rows': 'Rows',

    'pgs.move': 'Move to another database',
    'pgs.move.text':
      'Copy all Umbrella data to another PostgreSQL database and switch Umbrella to it. The current database is not changed. The new password is saved to OpenBao.',
    'pgs.move.overwrite': 'Replace the Umbrella data in that database',
    'pgs.move.overwriteText': 'The data saved there will be replaced with the current data of this installation.',
    'pgs.move.confirm': 'Move Umbrella to another database?',
    'pgs.move.step1': 'Users, settings, the audit log, incidents with their history and the queue of received requests are copied to {where}.',
    'pgs.move.step2': 'The password of the new database is saved to OpenBao.',
    'pgs.move.step3': 'Umbrella switches to the new database; for a few seconds it does not answer requests. Sessions stay open.',
    'pgs.move.step4': 'The current database {current} is left as it is.',
    'pgs.move.replace': 'The Umbrella data already stored in the new database will be replaced.',
    'pgs.move.done': 'Umbrella now works with {where}',
    'pgs.move.doneText': 'All data is copied. The previous database was not changed and can be removed when it is no longer needed.',

    'unit.b': 'B',
    'unit.kb': 'KiB',
    'unit.mb': 'MiB',
    'unit.gb': 'GiB',
    'unit.tb': 'TiB',
    'unit.ms': 'ms',
    'unit.s': 's',
    'unit.min': 'min',
    'unit.h': 'h',

    'err.postgres_same_database': 'This is the database Umbrella already uses.',
    'err.postgres_has_state': 'The database already holds Umbrella data. Confirm that it should be replaced.',
    'err.postgres_migration_failed': 'The data was not moved. Umbrella keeps working with the current database.',
    'err.postgres_stats_failed': 'PostgreSQL statistics could not be read.',
  },
  ru: {
    'pgs.current': 'Текущее подключение',
    'pgs.current.text': 'База PostgreSQL, в которой Umbrella сохраняет своё состояние.',
    'pgs.host': 'Хост',
    'pgs.port': 'Порт',
    'pgs.database': 'База данных',
    'pgs.user': 'Пользователь',
    'pgs.sslmode': 'Режим SSL',
    'pgs.version': 'Версия сервера',
    'pgs.size': 'Размер базы',
    'pgs.savedAt': 'Последнее сохранение',
    'pgs.pending': 'Несохранённые изменения',
    'pgs.test.ok': 'Подключение работает',
    'pgs.test.okText': 'PostgreSQL {version} ответил за {latency} мс.',
    'pgs.test.fail': 'PostgreSQL не отвечает',

    'pgs.stats': 'Статистика',
    'pgs.stats.text': 'Счётчики базы Umbrella из pg_stat_database, размеры таблиц и самые долгие операции.',
    'pgs.stats.auto': 'Обновлять каждые 10 секунд',
    'pgs.stats.collected': 'Собрано {at}',
    'pgs.tx': 'Транзакции',
    'pgs.tx.since': 'Счётчики с {at}.',
    'pgs.tx.sinceStart': 'Счётчики с последнего сброса статистики.',
    'pgs.tx.commits': 'Фиксации',
    'pgs.tx.rollbacks': 'Откаты',
    'pgs.tx.rate': 'Транзакций в секунду',
    'pgs.tx.rateWait': 'после следующего обновления',
    'pgs.tx.cache': 'Попадания в кэш',
    'pgs.tx.backends': 'Подключения',
    'pgs.tx.deadlocks': 'Взаимоблокировки',
    'pgs.tx.conflicts': 'Конфликты',
    'pgs.tx.temp': 'Временные файлы',
    'pgs.tx.returned': 'Строк возвращено',
    'pgs.tx.fetched': 'Строк выбрано',
    'pgs.tx.inserted': 'Строк вставлено',
    'pgs.tx.updated': 'Строк изменено',
    'pgs.tx.deleted': 'Строк удалено',
    'pgs.tables': 'Размеры таблиц',
    'pgs.tables.top': '{shown} самых больших из {total} таблиц.',
    'pgs.tables.none': 'В базе нет пользовательских таблиц.',
    'pgs.tables.name': 'Таблица',
    'pgs.tables.total': 'Всего',
    'pgs.tables.data': 'Данные',
    'pgs.tables.indexes': 'Индексы',
    'pgs.tables.rows': 'Строк',
    'pgs.tables.dead': 'Мёртвых строк',
    'pgs.ops': 'Топ-10 самых долгих операций',
    'pgs.ops.none': 'Сейчас нет выполняющихся запросов и открытых транзакций.',
    'pgs.ops.limited': 'Видны только сеансы пользователя базы. Выдайте роль pg_read_all_stats, чтобы видеть все сеансы.',
    'pgs.ops.pid': 'PID',
    'pgs.ops.who': 'Пользователь / приложение',
    'pgs.ops.state': 'Состояние',
    'pgs.ops.wait': 'Ожидание',
    'pgs.ops.duration': 'Длительность',
    'pgs.ops.query': 'Запрос',
    'pgs.stmts': 'Топ-10 запросов',
    'pgs.stmts.byTotal': 'По общему времени',
    'pgs.stmts.byMean': 'По среднему времени',
    'pgs.stmts.missing': 'Расширение pg_stat_statements в этой базе не установлено.',
    'pgs.stmts.missingHint':
      'Добавьте pg_stat_statements в shared_preload_libraries, перезапустите PostgreSQL и выполните CREATE EXTENSION pg_stat_statements.',
    'pgs.stmts.error': 'pg_stat_statements недоступно для чтения',
    'pgs.stmts.none': 'Запросы ещё не записаны.',
    'pgs.stmts.calls': 'Вызовов',
    'pgs.stmts.total': 'Всего',
    'pgs.stmts.mean': 'В среднем',
    'pgs.stmts.rows': 'Строк',

    'pgs.move': 'Перенос в другую базу',
    'pgs.move.text':
      'Скопировать все данные Umbrella в другую базу PostgreSQL и переключить Umbrella на неё. Текущая база не изменяется. Новый пароль сохраняется в OpenBao.',
    'pgs.move.overwrite': 'Заменить данные Umbrella в этой базе',
    'pgs.move.overwriteText': 'Сохранённые там данные будут заменены текущими данными этой установки.',
    'pgs.move.confirm': 'Перенести Umbrella в другую базу?',
    'pgs.move.step1': 'Пользователи, настройки, журнал аудита, инциденты с историей и очередь принятых запросов копируются в {where}.',
    'pgs.move.step2': 'Пароль новой базы сохраняется в OpenBao.',
    'pgs.move.step3': 'Umbrella переключается на новую базу и несколько секунд не отвечает на запросы. Сеансы сохраняются.',
    'pgs.move.step4': 'Текущая база {current} остаётся без изменений.',
    'pgs.move.replace': 'Данные Umbrella, уже сохранённые в новой базе, будут заменены.',
    'pgs.move.done': 'Umbrella работает с {where}',
    'pgs.move.doneText': 'Все данные скопированы. Прежняя база не изменена, её можно удалить, когда она станет не нужна.',

    'unit.b': 'Б',
    'unit.kb': 'КиБ',
    'unit.mb': 'МиБ',
    'unit.gb': 'ГиБ',
    'unit.tb': 'ТиБ',
    'unit.ms': 'мс',
    'unit.s': 'с',
    'unit.min': 'мин',
    'unit.h': 'ч',

    'err.postgres_same_database': 'Umbrella уже использует эту базу.',
    'err.postgres_has_state': 'В базе уже есть данные Umbrella. Подтвердите их замену.',
    'err.postgres_migration_failed': 'Данные не перенесены. Umbrella продолжает работать с текущей базой.',
    'err.postgres_stats_failed': 'Не удалось прочитать статистику PostgreSQL.',
  },
}

export const strings = mergeDicts(connectionStrings, postgresStrings, page)
