import type { Dict } from '../../i18n'

export const strings: Dict = {
  en: {
    'rt.title': 'Where an incident goes',
    'rt.rule':
      'Rule: the item → its most critical active service that has an owning team → that team (its lead and members; a team without people hands over to its parent) → otherwise the people responsible for the item.',
    'rt.service': 'Service',
    'rt.service.primary': 'decides the route',
    'rt.service.others': 'also in: {list}',
    'rt.service.none': 'none — bind the item to a business service',
    'rt.team': 'Team',
    'rt.team.none': 'no service with an owning team',
    'rt.people': 'Receives',
    'rt.people.n': '{n} person(s): {list}',
    'rt.people.owners': 'CI owners ({n}): {list}',
    'rt.people.none': 'nobody — only the «always notify» addresses get backup notification',
    'rt.channel': 'team channel {list}',
    'rt.pd': 'PagerDuty',
    'rt.pd.off': 'not used',
    'rt.pd.default': 'default integration',
    'rt.pd.nokey': 'default integration (no key: not sent)',
    'rt.pd.min': 'from severity {sev}',
    'rt.elsewhere': 'Items of this service routed by another, more critical service:',
    'rt.elsewhere.row': '{ci} → {service} ({team})',
    'rt.elsewhere.noteam': 'no team',
    'rt.loading': 'Calculating the route…',
    'rt.error': 'The route could not be calculated.',
    'rt.lead': 'lead',
  },
  ru: {
    'rt.title': 'Куда пойдёт инцидент',
    'rt.rule':
      'Правило: КЕ → самый критичный действующий сервис этой КЕ, у которого есть команда-владелец → эта команда (руководитель и участники; если людей нет — родительская команда) → иначе ответственные за КЕ.',
    'rt.service': 'Сервис',
    'rt.service.primary': 'определяет маршрут',
    'rt.service.others': 'также входит в: {list}',
    'rt.service.none': 'нет — привяжите КЕ к бизнес-сервису',
    'rt.team': 'Команда',
    'rt.team.none': 'нет сервиса с командой-владельцем',
    'rt.people': 'Получат',
    'rt.people.n': '{n} чел.: {list}',
    'rt.people.owners': 'ответственные за КЕ ({n}): {list}',
    'rt.people.none': 'никто — резервное оповещение получат только адреса «Всегда оповещать также»',
    'rt.channel': 'канал команды {list}',
    'rt.pd': 'PagerDuty',
    'rt.pd.off': 'не используется',
    'rt.pd.default': 'интеграция по умолчанию',
    'rt.pd.nokey': 'интеграция по умолчанию (ключа нет: не отправляется)',
    'rt.pd.min': 'от важности {sev}',
    'rt.elsewhere': 'КЕ этого сервиса, инциденты которых уходят по другому, более критичному сервису:',
    'rt.elsewhere.row': '{ci} → {service} ({team})',
    'rt.elsewhere.noteam': 'без команды',
    'rt.loading': 'Считаем маршрут…',
    'rt.error': 'Не удалось рассчитать маршрут.',
    'rt.lead': 'руководитель',
  },
}
